CREATE PROCEDURE [dbo].[DWH_INS_STOREDAILYPAYMENT_SP] @YearMonth INT AS
BEGIN      
  
  IF OBJECT_ID('tempdb.dbo.#SD', 'U') IS NOT NULL DROP TABLE #SD;

  WITH CANCELS AS (
    SELECT SALEID, SUM(PRICE) CANCELLED_AMT 
	  FROM SLS_CANCELLEDPRODUCTS_SYN (NOLOCK) 
	 WHERE OMITREASON = 0 
	 GROUP BY SALEID)
  SELECT S.TRANSACTION_DT
	   , S.STORE
	   , SUM(CASE WHEN S.TRANSACTIONTYPE != 5 AND S.CANCELLED_FL = 'N' THEN S.TOTAL_AMT ELSE 0 END)  [SALE_AMT]
	   , SUM(CASE WHEN S.TRANSACTIONTYPE != 5 AND S.CANCELLED_FL = 'N' THEN 1 ELSE 0 END) [SALE_QTY]       
	   , SUM(CASE WHEN S.TRANSACTIONTYPE = 5 AND S.CANCELLED_FL = 'N' THEN S.TOTAL_AMT ELSE 0 END)  [REFUND_AMT]
	   , SUM(CASE WHEN S.TRANSACTIONTYPE = 5 AND S.CANCELLED_FL = 'N' THEN 1 ELSE 0 END) [REFUND_QTY]
	   , SUM(CASE WHEN ISNULL(SP.CARD_AMT,0) = 0 AND S.CANCELLED_FL = 'N' THEN S.TOTAL_AMT ELSE 0 END) [CASH_AMT]
	   , SUM(CASE WHEN ISNULL(SP.CARD_AMT,0) = 0 AND S.CANCELLED_FL = 'N' THEN 1 ELSE 0 END) [CASH_QTY]
	   , SUM(CASE WHEN ISNULL(SP.CARD_AMT,0) > 0 AND S.CANCELLED_FL = 'N' THEN S.TOTAL_AMT ELSE 0 END) [CARD_AMT]
	   , SUM(CASE WHEN ISNULL(SP.CARD_AMT,0) > 0 AND S.CANCELLED_FL = 'N' THEN 1 ELSE 0 END) [CARD_QTY]
	   , SUM(CASE WHEN S.TRANSACTIONTYPE != 5 THEN ISNULL(CANCELLED_AMT,0) ELSE 0 END) CANCELLED_AMT
	   , SUM(CASE WHEN S.TRANSACTIONTYPE != 5 AND ISNULL(CANCELLED_AMT,0) > 0 THEN 1 ELSE 0 END) CANCELLED_QTY
	INTO #SD
	FROM SLS_SALE S (NOLOCK)
	JOIN RPT_DATE DT (NOLOCK) ON S.TRANSACTION_DT = DT.DATE_DT
    LEFT JOIN SLS_SALEPAYMENT SP (NOLOCK) ON S.SALEID = SP.SALE
	LEFT JOIN CANCELS C ON S.SALEID = C.SALEID
   WHERE DT.YEARMONTH_NO = @YearMonth
     AND S.DELETED_FL = 'N'
	 AND SP.DELETED_FL = 'N'
   GROUP BY S.TRANSACTION_DT, S.STORE
    
  INSERT INTO SLS_STOREDAILYPAYMENT_SYN
  SELECT A.*    
    FROM #SD A
    LEFT JOIN SLS_STOREDAILYPAYMENT_SYN B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE
   WHERE B.TRANSACTION_DT IS NULL
    
  DELETE B
    FROM #SD A
   RIGHT JOIN SLS_STOREDAILYPAYMENT_SYN B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE
   WHERE A.TRANSACTION_DT IS NULL
     AND B.TRANSACTION_DT IN (SELECT DATE_DT FROM RPT_DATE WHERE YEARMONTH_NO = @YearMonth)
      
  UPDATE B
     SET B.SALE_AMT = A.SALE_AMT
       , B.SALE_QTY = A.SALE_QTY  
       , B.REFUND_AMT = A.REFUND_AMT
       , B.REFUND_QTY = A.REFUND_QTY
       , B.CASH_AMT = A.CASH_AMT
       , B.CASH_QTY = A.CASH_QTY
       , B.CARD_AMT = A.CARD_AMT
       , B.CARD_QTY = A.CARD_QTY
       , B.CANCELLED_AMT = A.CANCELLED_AMT
       , B.CANCELLED_QTY = A.CANCELLED_QTY
    FROM #SD A
    JOIN SLS_STOREDAILYPAYMENT_SYN B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE
   WHERE B.SALE_AMT != A.SALE_AMT
      OR B.SALE_QTY != A.SALE_QTY
      OR B.REFUND_AMT != A.REFUND_AMT
      OR B.REFUND_QTY != A.REFUND_QTY
      OR B.CASH_AMT != A.CASH_AMT
      OR B.CASH_QTY != A.CASH_QTY
      OR B.CARD_AMT != A.CARD_AMT
      OR B.CARD_QTY != A.CARD_QTY
      OR B.CANCELLED_AMT != A.CANCELLED_AMT
      OR B.CANCELLED_QTY != A.CANCELLED_QTY
      
END; 