CREATE PROCEDURE DWH_INS_STOREDAILYPRODUCT_SP @YearMonth INT AS
BEGIN

	SELECT CAST(SD.TRANSACTION_DT AS DATE) TRANSACTION_DT, SD.STORE, SD.PRODUCT,     
		   SUM(SD.QUANTITY_QTY * CASE WHEN S.TRANSACTIONTYPE != 5 THEN 1.0 ELSE -1.0 END / (CASE WHEN P.UNIT = 1 THEN 1000.0 ELSE 1 END)) QUANTITY, 
		   SUM(PRICE) PRICE    
	  INTO #SD
	  FROM SLS_SALEDETAIL SD (NOLOCK)
	  JOIN RPT_DATE DT (NOLOCK) ON SD.TRANSACTION_DT = DT.DATE_DT
	  JOIN SLS_SALE S (NOLOCK) ON SD.SALE = S.SALEID
	  JOIN PRD_PRODUCT P (NOLOCK) ON SD.PRODUCT = P.PRODUCTID
	 WHERE DT.YEARMONTH_NO = @YearMonth
	   AND SD.CANCEL_FL = 'N'
	   AND SD.DELETED_FL = 'N'  
	   AND S.CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'  
	 GROUP BY SD.TRANSACTION_DT, SD.STORE, SD.PRODUCT;
	
	INSERT INTO MakTechDWH.dbo.SLS_STOREDAILYPRODUCT
	SELECT A.*
	  FROM #SD A
	  LEFT JOIN MakTechDWH.dbo.SLS_STOREDAILYPRODUCT B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE AND A.PRODUCT = B.PRODUCT
	 WHERE B.PRODUCT IS NULL

	DELETE B
	-- SELECT B.*
	  FROM #SD A
	  RIGHT JOIN MakTechDWH.dbo.SLS_STOREDAILYPRODUCT B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE AND A.PRODUCT = B.PRODUCT
	 WHERE A.PRODUCT IS NULL
	   AND B.TRANSACTION_DT IN (SELECT DATE_DT FROM RPT_DATE WHERE YEARMONTH_NO = @YearMonth);

	UPDATE B	
	   SET B.QUANTITY = A.QUANTITY, B.PRICE = A.PRICE
    -- SELECT *
	  FROM #SD A
	  JOIN MakTechDWH.dbo.SLS_STOREDAILYPRODUCT B ON A.TRANSACTION_DT = B.TRANSACTION_DT AND A.STORE = B.STORE AND A.PRODUCT = B.PRODUCT
	 WHERE A.QUANTITY != B.QUANTITY OR A.PRICE != B.PRICE;

END