CREATE PROCEDURE ACC_LST_LOOMIS_SP @StartDate DATE = NULL, @EndDate DATE = NULL AS
BEGIN

	WITH TOTALS AS (
	SELECT L.STORE, 
		   SUM(ACTUAL_AMT - RST.BANK_AMT) CUMULATIVEDIFF_AMT,
		   SUM(CASE WHEN ACTUAL_AMT < RST.BANK_AMT THEN ACTUAL_AMT - RST.BANK_AMT ELSE 0 END) CUMNEGATIVEDIFF_AMT,
		   SUM(CASE WHEN ABS(ACTUAL_AMT - RST.BANK_AMT) < 1 THEN 1 ELSE 0 END) CONSISTENTDAY_CNT,
		   COUNT(*) TOTALDAY_CNT
	  FROM ACC_LOOMIS L
	  JOIN RCL_STORE RST ON RST.RECONCILIATION_DT = L.SALE_DT AND L.STORE = RST.STORE
	  JOIN RPT_DATE DT ON DT.DATE_DT = @EndDate
	  JOIN RPT_DATE DT2 ON DT.YEAR_NO = DT2.YEAR_NO AND DT2.DATE_DT = L.SALE_DT
	 WHERE SALE_DT <= @EndDate
	 GROUP BY L.STORE)
    SELECT L.LOOMISID,
           L.EVENT,
           L.ORGANIZATION,
           L.DELETED_FL,
           L.CREATE_DT,
           L.UPDATE_DT,
           L.CREATEUSER,
           L.UPDATEUSER,
           L.CREATECHANNEL,
           L.CREATEBRANCH,
           L.CREATESCREEN,
           L.SALE_DT,
           L.STORE,
           L.SEAL_TXT,
           L.DECLARED_AMT,
           L.ACTUAL_AMT,
           L.FAKE_AMT,
		   L.ACTUAL_AMT - L.DECLARED_AMT ACTUALDIFF_AMT,
           L.EXPLANATION_TXT,
		   ISNULL(RST.BANK_AMT, 0) BANK_AMT,
		   L.ACTUAL_AMT - ISNULL(RST.BANK_AMT,0) RCLDIFF_AMT,
		   L.DECLARED_AMT - ISNULL(RST.BANK_AMT,0) RCLDECLAREDDIFF_AMT,
		   CASE WHEN ABS(L.DECLARED_AMT - L.ACTUAL_AMT) < 1 AND ABS(L.DECLARED_AMT - ISNULL(RST.BANK_AMT,0)) < 1 THEN 1 
				WHEN ABS(L.DECLARED_AMT - L.ACTUAL_AMT) < 1 THEN 2
				WHEN ABS(L.DECLARED_AMT - ISNULL(RST.BANK_AMT,0)) < 1 THEN 3
				WHEN ABS(L.ACTUAL_AMT - ISNULL(RST.BANK_AMT,0)) < 1 THEN 4
				ELSE 5 
		   END CONTROL_CD,
           L.MIKRO_TM,
           L.MIKROSTATUS_CD,
           L.MIKROTRANCODE_TXT,
		   L.LOOMIS_DT,
		   T.CUMULATIVEDIFF_AMT,
		   T.CUMNEGATIVEDIFF_AMT,
		   T.CONSISTENTDAY_CNT,
		   T.TOTALDAY_CNT DAY_CNT
      FROM ACC_LOOMIS L (NOLOCK)
	  LEFT JOIN RCL_STORE RST ON RST.RECONCILIATION_DT = L.SALE_DT AND L.STORE = RST.STORE
	  LEFT JOIN TOTALS T ON L.STORE = T.STORE
     WHERE SALE_DT BETWEEN ISNULL(@StartDate, CONVERT(DATE, '20180101', 112)) AND ISNULL(@EndDate, CONVERT(DATE, '20491231', 112))
	   AND L.DELETED_FL = 'N';

END;
