CREATE PROCEDURE ACC_RPT_EINVOICEMIKROTRANSFER_SP @StartDate DATE, @EndDate DATE AS
BEGIN
	SELECT S.TRANSACTION_DT, ST.STOREID, ST.STORE_NM, P.PRODUCTID, P.CODE_NM, P.NAME_NM, 
		   CASE WHEN S.TRANSACTIONTYPE = 5 THEN 'Maktech de yok' ELSE 'Mikro da yok' END GROUP_DSC,
		   SUM(CASE WHEN S.TRANSACTIONTYPE = 5 THEN -1 ELSE 1 END * PRICE) TOTAL_AMT, 
		   SUM(CASE WHEN S.TRANSACTIONTYPE = 5 THEN -1 ELSE 1 END * PRICE * 100.0 / (100.0 + VAT_RT)) TOTALNOVAT_AMT, 
		   SUM(CASE WHEN SD.UNIT = 1 THEN QUANTITY_QTY / 1000.0 ELSE QUANTITY_QTY END) TOTAL_QTY
	  FROM ACC_INVOICE I
	  JOIN SLS_SALE S ON I.SALE = S.SALEID AND S.CANCELLED_FL  = 'N' AND S.DELETED_FL = 'N'
	  JOIN STR_STORE ST ON S.STORE = ST.STOREID
	  JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE AND SD.CANCEL_FL = 'N' AND SD.DELETED_FL = 'N'
	  JOIN PRD_PRODUCT P ON SD.PRODUCT = P.PRODUCTID
	 WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND I.DELETED_FL = 'N'
	 GROUP BY S.TRANSACTION_DT, ST.STOREID, ST.STORE_NM, P.PRODUCTID, P.CODE_NM, P.NAME_NM, 
		   CASE WHEN S.TRANSACTIONTYPE = 5 THEN 'Maktech de yok' ELSE 'Mikro da yok' END
	 ORDER BY 1, 2
END