CREATE PROCEDURE ACC_LST_NEWINVOICES_SP AS
BEGIN
	WITH INVOICES AS (
	SELECT S.SALEID, S.STORE, S.TRANSACTION_DT, S.TOTAL_AMT
	  FROM ACC_INVOICE I
	  JOIN SLS_SALE S ON I.SALE = S.SALEID
	 WHERE I.DELETED_FL = 'N')
	SELECT SC.SALE, SC.EINVOICE_FL, SC.CUSTOMER_NM, SC.ADDRESS_TXT, SC.TAXCENTER_NM, SC.IDENTITYNO_TXT, SC.EMAIL_TXT, SC.PHONENUMBER_TXT, 
		   SC.EINVOICERECEIPT_NO, S.TOTAL_AMT SALE_AMT, I2.SALEID REFUNDSALEID, I2.TOTAL_AMT REFUND_AMT, S.STORE, S.TRANSACTION_DT
	  FROM SLS_SALECUSTOMER SC
	  JOIN SLS_SALE S ON SC.SALE = S.SALEID
	  LEFT JOIN INVOICES I1 ON S.SALEID = I1.SALEID
	  LEFT JOIN INVOICES I2 ON S.STORE = I2.STORE AND S.TRANSACTION_DT = I2.TRANSACTION_DT
	 WHERE S.TOTAL_AMT > 5
	   AND I1.SALEID IS NULL
	   AND ABS(S.TOTAL_AMT) != ABS(ISNULL(I2.TOTAL_AMT,0))
	   AND S.STORE IN (SELECT STORE FROM ACC_EINVOICESTORE)
	   AND S.TRANSACTION_DT >= CAST(GETDATE() AS date)
END