CREATE PROCEDURE ACC_LST_BANKPOSTRAN_SP @BlockDate DATE AS
BEGIN

  -- DECLARE @BlockDate DATE = '2019-09-17'

  IF OBJECT_ID('tempdb.dbo.#RCLCARD', 'U') IS NOT NULL  DROP TABLE #RCLCARD;
  IF OBJECT_ID('tempdb.dbo.#POSDATA', 'U') IS NOT NULL  DROP TABLE #POSDATA;
  IF OBJECT_ID('tempdb.dbo.#STOREDIFF', 'U') IS NOT NULL  DROP TABLE #STOREDIFF;

  SELECT ST.STORE, CD.CARDGROUP_CD, CD.CARDZET_AMT, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY CARDZET_AMT DESC) ROWNO
    INTO #RCLCARD
    FROM RCL_STORE ST
    JOIN RCL_CARDDIST CD ON ST.STORERECID = CD.STOREREC
   WHERE ST.RECONCILIATION_DT = @BlockDate
     AND CD.CARDZET_AMT > 0
  
  SELECT B.*, P.STORE, ST.STORE_NM, ROW_NUMBER() OVER (PARTITION BY P.STORE ORDER BY DEBIT_AMT DESC) ROWNO
    INTO #POSDATA
    FROM ACC_BANKPOSTRAN B (NOLOCK)
    LEFT JOIN STR_POS P (NOLOCK) ON B.POSREF_TXT = P.POSCODE_TXT
    LEFT JOIN STR_STORE ST ON P.STORE = ST.STOREID
   WHERE B.BLOCKED_DT = @BlockDate
     AND B.DELETED_FL = 'N'
  
  SELECT ISNULL(A.STORE, B.STORE) STORE, ISNULL(A.DEBIT_AMT,0) - ISNULL(B.CARDZET_AMT,0) STOREDIFF
    INTO #STOREDIFF
    FROM (SELECT STORE, SUM(DEBIT_AMT) DEBIT_AMT FROM #POSDATA GROUP BY STORE) A
    FULL OUTER JOIN (SELECT STORE, SUM(CARDZET_AMT) CARDZET_AMT FROM #RCLCARD GROUP BY STORE) B
      ON A.STORE = B.STORE
   WHERE ABS(ISNULL(A.DEBIT_AMT,0) - ISNULL(B.CARDZET_AMT,0)) >= 0.5
  
  SELECT PD.BANKPOSTRANID, PD.EVENT, PD.ORGANIZATION, PD.DELETED_FL, PD.CREATE_DT, PD.UPDATE_DT, PD.CREATEUSER, PD.UPDATEUSER, PD.CREATECHANNEL, PD.CREATEBRANCH, PD.CREATESCREEN
	   , PD.BANK, PD.STOREREF_TXT, PD.POSREF_TXT, PD.BLOCKED_DT, PD.VALUE_DT, PD.QUANTITY_QTY, PD.CREDIT_AMT, PD.DEBIT_AMT, PD.COMMISSION_AMT, PD.MIKRO_TM, PD.MIKROSTATUS_CD
	   , PD.MIKROTRANCODE_TXT, COALESCE(PD.STORE, RC.STORE) STORE, ST.STORE_NM, COALESCE(PD.ROWNO, RC.ROWNO) ROWNO
	   , RC.CARDZET_AMT
  	   , CASE WHEN PD.STORE IS NULL AND PD.BANKPOSTRANID IS NOT NULL THEN 2 WHEN SD.STORE IS NOT NULL THEN 3 ELSE 1 END CONTROL_CD
  	   , ISNULL(SD.STOREDIFF,0) STOREDIFF_AMT
    FROM #POSDATA PD
	FULL JOIN #RCLCARD RC ON PD.STORE = RC.STORE AND PD.ROWNO = RC.ROWNO
    LEFT JOIN #STOREDIFF SD ON COALESCE(PD.STORE, RC.STORE) = SD.STORE
	LEFT JOIN STR_STORE ST ON COALESCE(PD.STORE, RC.STORE) = ST.STOREID
--   WHERE COALESCE(PD.STORE, RC.STORE) = 72
   ORDER BY COALESCE(PD.STORE, RC.STORE) 

END;