CREATE PROCEDURE GAM_LST_GAMESCORE_SP AS
BEGIN
	DECLARE @today DATE = CAST(GETDATE() AS date)
	SELECT *, ROW_NUMBER() OVER (PARTITION BY DAYGROUP ORDER BY MAXSCORE DESC) ROWNO
	  FROM (
	SELECT PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM, 'Bugün' DAYGROUP, MAX(SCORE_NO) MAXSCORE, MAX(LASTLEVEL_CD) MAXLEVEL, SUM(QUESTION_CNT) QUESTION_CNT, AVG(SCORE_NO) AVGSCORE, COUNT(*) GAME_CNT
	  FROM GAM_PLAY P
	  JOIN GAM_PLAYER PL ON P.PLAYER = PL.PLAYERID
	  JOIN ORG_BRANCH B ON PL.BRANCH = B.BRANCHID
	  JOIN RPT_DATE D ON D.DATE_DT = @today 
	  JOIN RPT_DATE D1 ON D1.DATE_DT = CAST(P.CREATE_DT AS date) AND D.DATE_DT = D1.DATE_DT
	 GROUP BY PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM
	 UNION ALL
	SELECT PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM, 'Bu Hafta' DAYGROUP, MAX(SCORE_NO), MAX(LASTLEVEL_CD), SUM(QUESTION_CNT), AVG(SCORE_NO), COUNT(*)
	  FROM GAM_PLAY P
	  JOIN GAM_PLAYER PL ON P.PLAYER = PL.PLAYERID
	  JOIN ORG_BRANCH B ON PL.BRANCH = B.BRANCHID
	  JOIN RPT_DATE D ON D.DATE_DT = @today 
	  JOIN RPT_DATE D1 ON D1.DATE_DT = CAST(P.CREATE_DT AS date) AND D.YEARWEEK_NO = D1.YEARWEEK_NO
	 GROUP BY PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM
	 UNION ALL
	SELECT PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM, 'Bu Ay' DAYGROUP, MAX(SCORE_NO), MAX(LASTLEVEL_CD), SUM(QUESTION_CNT), AVG(SCORE_NO), COUNT(*)
	  FROM GAM_PLAY P
	  JOIN GAM_PLAYER PL ON P.PLAYER = PL.PLAYERID
	  JOIN ORG_BRANCH B ON PL.BRANCH = B.BRANCHID
	  JOIN RPT_DATE D ON D.DATE_DT = @today 
	  JOIN RPT_DATE D1 ON D1.DATE_DT = CAST(P.CREATE_DT AS date) AND D.YEARMONTH_NO = D1.YEARMONTH_NO
	 GROUP BY PL.PLAYERID, B.BRANCH_NM, PL.PLAYER_NM) A
	 ORDER BY DAYGROUP, MAXSCORE DESC
END