-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_REGIONMANAGERS]
(
    /*Section="Columns"*/
    [REGIONMANAGERSID]     INT NOT NULL IDENTITY,
    [MANAGER_NM]           VARCHAR(100) NOT NULL,
    [TELNO_TXT]            VARCHAR(100) NULL,
    [EMAIL_TXT]            VARCHAR(100) NULL,
    [USERID]               INT NULL,
    [EXPENSEACCCODE_TXT]   VARCHAR(100) NULL,
    [MIKROPROJECTCODE_TXT] VARCHAR(50) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_REGIONMANAGERS_PK] PRIMARY KEY ([REGIONMANAGERSID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_REGIONMANAGERS_F01] FOREIGN KEY ([USERID]) REFERENCES [SEC_USER]([USERID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [STR_REGIONMANAGERS_X01] ON [STR_REGIONMANAGERS] ([USERID])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Region Managers: Region Managers',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_REGIONMANAGERS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Region Managers Id: Identity column for STR_REGIONMANAGERS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'REGIONMANAGERSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Region Manager Name: Name of region managers.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'MANAGER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'TelNo: TelNo' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'TELNO_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Email: Email' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'EMAIL_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Region User: Region User' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'USERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Account Code: Expense Account Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSEACCCODE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Project Code: Mikro Project Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_REGIONMANAGERS',
    @level2type=N'COLUMN',
    @level2name=N'MIKROPROJECTCODE_TXT'
GO

/*Section="End"*/
