-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_TERMINAL]
(
    /*Section="Columns"*/
    [TERMINALID]   INT NOT NULL IDENTITY,
    [ORGANIZATION] INT NOT NULL,
    [DELETED_FL]   VARCHAR NOT NULL,
    [CREATE_DT]    DATETIME NOT NULL,
    [UPDATE_DT]    DATETIME NULL,
    [CREATEUSER]   INT NOT NULL,
    [UPDATEUSER]   INT NULL,
    [TERMINAL_NO]  INT NOT NULL,
    [STORE]        INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_TERMINAL_PK] PRIMARY KEY ([TERMINALID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_TERMINAL_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_TERMINAL_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_TERMINAL_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_TERMINAL_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [STR_TERMINAL_X01] ON [STR_TERMINAL] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Terminal: Terminal store relationships.',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_TERMINAL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Terminal Id: Identity column for STR_TERMINAL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'TERMINALID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Terminal: Terminal identifier from DST_TERMINAL table.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'TERMINAL_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store reference.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TERMINAL', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

/*Section="End"*/
