-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_CASHREGISTERMODEL]
(
    /*Section="Columns"*/
    [CASHREGISTERMODELID] INT NOT NULL IDENTITY,
    [BRAND]               INT NOT NULL,
    [MODEL_NM]            VARCHAR(100) NOT NULL,
    [COMMENT_DSC]         VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_CASHREGISTERMODEL_PK] PRIMARY KEY ([CASHREGISTERMODELID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_CASHREGISTERMODEL_F01] FOREIGN KEY ([BRAND]) REFERENCES [STR_CASHREGISTERBRAND]([CASHREGISTERBRANDID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [STR_CASHREGISTERMODEL_X01] ON [STR_CASHREGISTERMODEL] ([MODEL_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Cash Register Model: Cash Register Model Information',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_CASHREGISTERMODEL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Cash Register Model Id: Identity column for STR_CASHREGISTERMODEL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTERMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'CASHREGISTERMODELID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Brand: Brand reference' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTERMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'BRAND'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Name of cash register model.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTERMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'MODEL_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Description: Comment for cash register model.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTERMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
