-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_EMPLOYEE]
(
    /*Section="Columns"*/
    [EMPLOYEEID]      INT NOT NULL,
    [ORGANIZATION]    INT NOT NULL,
    [DELETED_FL]      VARCHAR NOT NULL,
    [CREATE_DT]       DATETIME NOT NULL,
    [UPDATE_DT]       DATETIME NULL,
    [CREATEUSER]      INT NOT NULL,
    [UPDATEUSER]      INT NULL,
    [EMPLOYEE_NM]     VARCHAR(100) NOT NULL,
    [DEPARTMENT_CD]   INT NULL,
    [DEPARTMENT_NM]   VARCHAR(100) NOT NULL,
    [INCENTIVEACT_CD] INT NULL,
    [START_DT]        DATETIME NULL,
    [QUIT_DT]         DATETIME NULL,
    [WORKINGTYPE_DSC] VARCHAR(100) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_EMPLOYEE_PK] PRIMARY KEY ([EMPLOYEEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_EMPLOYEE_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_EMPLOYEE_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_EMPLOYEE_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Employee: Employees',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_EMPLOYEE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Employee Id: Identity column for STR_EMPLOYEE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'EMPLOYEEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Employee Name: Name of employee.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'EMPLOYEE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Department Code: Department Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'DEPARTMENT_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Department Name: Department Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'DEPARTMENT_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Incentive Act Code: Incentive Act Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'INCENTIVEACT_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Start Date: Start Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'START_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Quit Date: Quit Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'QUIT_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Working Type: Working Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_EMPLOYEE',
    @level2type=N'COLUMN',
    @level2name=N'WORKINGTYPE_DSC'
GO

/*Section="End"*/
