-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_TOWN]
(
    /*Section="Columns"*/
    [TOWNID]  INT NOT NULL IDENTITY,
    [CITY]    INT NOT NULL,
    [TOWN_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_TOWN_PK] PRIMARY KEY ([TOWNID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_TOWN_F01] FOREIGN KEY ([CITY]) REFERENCES [STR_CITY]([CITYID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [STR_TOWN_X01] ON [STR_TOWN] ([TOWN_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Town: Town',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_TOWN',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Town Id: Identity column for CNT_TOWN' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TOWN', 
    @level2type=N'COLUMN',
    @level2name=N'TOWNID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'City: City' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TOWN', 
    @level2type=N'COLUMN',
    @level2name=N'CITY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Town Name: Name of town.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_TOWN', 
    @level2type=N'COLUMN',
    @level2name=N'TOWN_NM'
GO

/*Section="End"*/
