-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_ACCOUNTS]
(
    /*Section="Columns"*/
    [ACCOUNTSID]   INT NOT NULL IDENTITY,
    [ORGANIZATION] INT NOT NULL,
    [DELETED_FL]   VARCHAR NOT NULL,
    [CREATE_DT]    DATETIME NOT NULL,
    [UPDATE_DT]    DATETIME NULL,
    [CREATEUSER]   INT NOT NULL,
    [UPDATEUSER]   INT NULL,
    [STORE]        INT NOT NULL,
    [ACCOUNTTYPE]  INT NOT NULL,
    [BANK]         INT NOT NULL,
    [ACCOUNT_TXT]  VARCHAR(100) NOT NULL,
    [ACCOUNT_DSC]  VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_ACCOUNTS_PK] PRIMARY KEY ([ACCOUNTSID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_ACCOUNTS_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_ACCOUNTS_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_ACCOUNTS_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_ACCOUNTS_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [STR_ACCOUNTS_F05] FOREIGN KEY ([ACCOUNTTYPE]) REFERENCES [STR_ACCOUNTTYPE]([ACCOUNTTYPEID]),
    CONSTRAINT [STR_ACCOUNTS_F06] FOREIGN KEY ([BANK]) REFERENCES [STR_BANK]([BANKID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [STR_ACCOUNTS_X01] ON [STR_ACCOUNTS] ([STORE])
GO

CREATE INDEX [STR_ACCOUNTS_X02] ON [STR_ACCOUNTS] ([BANK])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Accounts: Store Accounts',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_ACCOUNTS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Accounts Id: Identity column for STR_ACCOUNTS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'ACCOUNTSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Account Type: Account Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'ACCOUNTTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Bank: Bank' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'BANK'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Account Text: Account Text' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'ACCOUNT_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Account Description: Comment for store accounts.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_ACCOUNTS', 
    @level2type=N'COLUMN',
    @level2name=N'ACCOUNT_DSC'
GO

/*Section="End"*/
