-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_PROHIBITEDHOURS]
(
    /*Section="Columns"*/
    [PROHIBITEDHOURSID] INT NOT NULL IDENTITY,
    [ACTION]            INT NOT NULL,
    [STORE_CD]          INT NULL,
    [STARTHOUR_NO]      INT NOT NULL,
    [ENDHOUR_NO]        INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_PROHIBITEDHOURS_PK] PRIMARY KEY ([PROHIBITEDHOURSID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_PROHIBITEDHOURS_F01] FOREIGN KEY ([ACTION]) REFERENCES [STR_ACTION]([ACTIONID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Prohibited Hours: Prohibited Hours',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_PROHIBITEDHOURS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Prohibited Hours Id: Identity column for STR_PROHIBITEDHOURS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_PROHIBITEDHOURS', 
    @level2type=N'COLUMN',
    @level2name=N'PROHIBITEDHOURSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Action: Action' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_PROHIBITEDHOURS', 
    @level2type=N'COLUMN',
    @level2name=N'ACTION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Code: Store Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_PROHIBITEDHOURS', 
    @level2type=N'COLUMN',
    @level2name=N'STORE_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Start Hour: Start Hour' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_PROHIBITEDHOURS', 
    @level2type=N'COLUMN',
    @level2name=N'STARTHOUR_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'End Hour: End Hour' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'STR_PROHIBITEDHOURS', 
    @level2type=N'COLUMN',
    @level2name=N'ENDHOUR_NO'
GO

/*Section="End"*/
