-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_SCALE]
(
    /*Section="Columns"*/
    [SCALEID]             INT NOT NULL IDENTITY,
    [ORGANIZATION]        INT NOT NULL,
    [DELETED_FL]          VARCHAR NOT NULL,
    [CREATE_DT]           DATETIME NOT NULL,
    [UPDATE_DT]           DATETIME NULL,
    [CREATEUSER]          INT NOT NULL,
    [UPDATEUSER]          INT NULL,
    [SCALE_NM]            VARCHAR(100) NOT NULL,
    [STORE]               INT NOT NULL,
    [SCALEMODEL]          INT NOT NULL,
    [PRICEFILEPATH_TXT]   VARCHAR(200) NULL,
    [CURRENTPRICEVERSION] INT NULL,
    [CURRENTPRICELOAD_TM] DATETIME NULL,
    [PRIVATEPRICEVERSION] INT NULL,
    [PRIVATEPRICELOAD_TM] DATETIME NULL,
    [CREATEPRICEFILE_FL]  VARCHAR(1) NULL,
    [IPADDRESS_TXT]       VARCHAR(20) NULL,
    [STATUS_FL]           VARCHAR(1) NULL,
    [STATUS_TXT]          VARCHAR(100) NULL,
    [SEALVALID_DT]        DATETIME NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_SCALE_PK] PRIMARY KEY ([SCALEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_SCALE_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_SCALE_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_SCALE_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_SCALE_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [STR_SCALE_F05] FOREIGN KEY ([SCALEMODEL]) REFERENCES [STR_SCALEMODEL]([SCALEMODELID]),
    CONSTRAINT [STR_SCALE_F06] FOREIGN KEY ([CURRENTPRICEVERSION]) REFERENCES [PRC_PACKAGEVERSION]([PACKAGEVERSIONID]),
    CONSTRAINT [STR_SCALE_F07] FOREIGN KEY ([PRIVATEPRICEVERSION]) REFERENCES [PRC_PACKAGEVERSION]([PACKAGEVERSIONID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [STR_SCALE_X01] ON [STR_SCALE] ([STORE])
GO

CREATE INDEX [STR_SCALE_X02] ON [STR_SCALE] ([CURRENTPRICEVERSION])
GO

CREATE INDEX [STR_SCALE_X03] ON [STR_SCALE] ([PRIVATEPRICEVERSION])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Scales: Definition of scales at stores.',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_SCALE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Scales Id: Identity column for STR_SCALE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'SCALEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Name of store scales.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'SCALE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Scale Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Scale Model: Store Scale Model' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'SCALEMODEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Price File Path: Price File Path' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'PRICEFILEPATH_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Current Price Version: Current Price Version' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'CURRENTPRICEVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Current Price Load Time: Current Price Version Load Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'CURRENTPRICELOAD_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Private Price Version: Private Price Version' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'PRIVATEPRICEVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Private Price Load Time: Private Price Version Load Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'PRIVATEPRICELOAD_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Price File Flag: It is used to create price file for scale for once. ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEPRICEFILE_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'IpAdress: IpAdress' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'IPADDRESS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status: Status' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Text: Status Text' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Seal Valid Date: Seal Valid Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_SCALE',
    @level2type=N'COLUMN',
    @level2name=N'SEALVALID_DT'
GO

/*Section="End"*/
