-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_CASHREGISTER]
(
    /*Section="Columns"*/
    [CASHREGISTERID]      INT NOT NULL,
    [ORGANIZATION]        INT NOT NULL,
    [DELETED_FL]          VARCHAR NOT NULL,
    [CREATE_DT]           DATETIME NOT NULL,
    [UPDATE_DT]           DATETIME NULL,
    [CREATEUSER]          INT NOT NULL,
    [UPDATEUSER]          INT NULL,
    [CASHREGISTER_NM]     VARCHAR(100) NOT NULL,
    [STORE]               INT NOT NULL,
    [CASHREGISTERMODEL]   INT NOT NULL,
    [PRICEFILEPATH_TXT]   VARCHAR(200) NULL,
    [SALEFILEPATH1_TXT]   VARCHAR(1000) NULL,
    [SALEFILEPATH2_TXT]   VARCHAR(1000) NULL,
    [SALEFILEPATH3_TXT]   VARCHAR(1000) NULL,
    [CURRENTPRICEVERSION] INT NULL,
    [CURRENTPRICELOAD_TM] DATETIME NULL,
    [PRIVATEPRICEVERSION] INT NULL,
    [PRIVATEPRICELOAD_TM] DATETIME NULL,
    [CREATEPRICEFILE_FL]  VARCHAR(1) NULL,
    [IPADDRESS_TXT]       VARCHAR(20) NULL,
    [STATUS_FL]           VARCHAR(1) NULL,
    [STATUS_TXT]          VARCHAR(100) NULL,
    [GIBDEVICENO_TXT]     VARCHAR(20) NULL,
    [SERIALNO_TXT]        VARCHAR(100) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_CASHREGISTER_PK] PRIMARY KEY ([CASHREGISTERID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_CASHREGISTER_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_CASHREGISTER_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_CASHREGISTER_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_CASHREGISTER_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [STR_CASHREGISTER_F05] FOREIGN KEY ([CASHREGISTERMODEL]) REFERENCES [STR_CASHREGISTERMODEL]([CASHREGISTERMODELID]),
    CONSTRAINT [STR_CASHREGISTER_F06] FOREIGN KEY ([CURRENTPRICEVERSION]) REFERENCES [PRC_PACKAGEVERSION]([PACKAGEVERSIONID]),
    CONSTRAINT [STR_CASHREGISTER_F07] FOREIGN KEY ([PRIVATEPRICEVERSION]) REFERENCES [PRC_PACKAGEVERSION]([PACKAGEVERSIONID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [STR_CASHREGISTER_X01] ON [STR_CASHREGISTER] ([STORE])
GO

CREATE INDEX [STR_CASHREGISTER_X02] ON [STR_CASHREGISTER] ([CURRENTPRICEVERSION])
GO

CREATE INDEX [STR_CASHREGISTER_X03] ON [STR_CASHREGISTER] ([PRIVATEPRICEVERSION])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Cash Register: Definitions of cash register machines at stores.',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_CASHREGISTER',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Cash Register Id: Identity column for STR_CASHREGISTER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CASHREGISTERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Name of store cash register.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CASHREGISTER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Cash Register Model: Cash Register Model' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CASHREGISTERMODEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Price File Path: Price File Path' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'PRICEFILEPATH_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale File Path 1: Sale File Path' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'SALEFILEPATH1_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale File Path 2: Sale File Path' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'SALEFILEPATH2_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale File Path 3: Sale File Path' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'SALEFILEPATH3_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Current Price Version: Current Price Version' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CURRENTPRICEVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Current Price Load Time: Current Price Version Load Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CURRENTPRICELOAD_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Private Price Version: Private Price Version' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'PRIVATEPRICEVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Private Price Load Time: Private Price Version Load Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'PRIVATEPRICELOAD_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Price File Flag: This column is used to create price file for the cash register once. ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'CREATEPRICEFILE_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'IpAddress: IpAddress' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'IPADDRESS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status: Status Text' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Text: Status Text' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gib Device No: Gelir İdaresi Başkanlığına bildirilen Odeme Kaydedici Cihaz (OKS) sicil no' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'GIBDEVICENO_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Serial No: Serial No' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_CASHREGISTER',
    @level2type=N'COLUMN',
    @level2name=N'SERIALNO_TXT'
GO

/*Section="End"*/
