-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [STR_WORKINGHOURS]
(
    /*Section="Columns"*/
    [WORKINGHOURSID] BIGINT NOT NULL IDENTITY,
    [EVENT]          INT NOT NULL,
    [ORGANIZATION]   INT NOT NULL,
    [DELETED_FL]     VARCHAR NOT NULL,
    [CREATE_DT]      DATETIME NOT NULL,
    [UPDATE_DT]      DATETIME NULL,
    [CREATEUSER]     INT NOT NULL,
    [UPDATEUSER]     INT NULL,
    [CREATECHANNEL]  INT NOT NULL,
    [CREATEBRANCH]   INT NOT NULL,
    [CREATESCREEN]   INT NOT NULL,
    [STORECODE_TXT]  VARCHAR(50) NULL,
    [STORE_NM]       VARCHAR(100) NULL,
    [OPENING_TM]     DATETIME NULL,
    [CLOSING_TM]     DATETIME NULL,
    [OPENGUSER_NM]   VARCHAR(100) NULL,
    [CLOSEUSER_NM]   VARCHAR(100) NULL,
    [STORE]          INT NULL,
    [OPENUSER]       INT NULL,
    [CLOSEUSER]      INT NULL,
    [NOTE_DSC]       VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [STR_WORKINGHOURS_PK] PRIMARY KEY ([WORKINGHOURSID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [STR_WORKINGHOURS_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [STR_WORKINGHOURS_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [STR_WORKINGHOURS_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_WORKINGHOURS_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_WORKINGHOURS_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [STR_WORKINGHOURS_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [STR_WORKINGHOURS_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [STR_WORKINGHOURS_F08] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [STR_WORKINGHOURS_F09] FOREIGN KEY ([OPENUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [STR_WORKINGHOURS_F10] FOREIGN KEY ([CLOSEUSER]) REFERENCES [SEC_USER]([USERID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [STR_WORKINGHOURS_X01] ON [STR_WORKINGHOURS] ([STORE])
GO

CREATE INDEX [STR_WORKINGHOURS_X02] ON [STR_WORKINGHOURS] ([OPENUSER])
GO

CREATE INDEX [STR_WORKINGHOURS_X03] ON [STR_WORKINGHOURS] ([CLOSEUSER])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Working Hours: Daily opening and closing times of the stores',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'STR_WORKINGHOURS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Working Hours Id: Identity column for STR_WORKINGHOURS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'WORKINGHOURSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Code: code from Pronet' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'STORECODE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Name: Name of location.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'STORE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Opening Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'OPENING_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Closing Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CLOSING_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Open User Name: Name of user openned the store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'OPENGUSER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Close User Name: Name of user closed the store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CLOSEUSER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: fk from STR_STORE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Open User: fk from SEC_USER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'OPENUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Close User: fk from SEC_USER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'CLOSEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Note: Comment for working hours.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'STR_WORKINGHOURS',
    @level2type=N'COLUMN',
    @level2name=N'NOTE_DSC'
GO

/*Section="End"*/
