-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_BANKPOSTRAN]
(
    /*Section="Columns"*/
    [BANKPOSTRANID]     BIGINT NOT NULL IDENTITY,
    [EVENT]             INT NOT NULL,
    [ORGANIZATION]      INT NOT NULL,
    [DELETED_FL]        VARCHAR NOT NULL,
    [CREATE_DT]         DATETIME NOT NULL,
    [UPDATE_DT]         DATETIME NULL,
    [CREATEUSER]        INT NOT NULL,
    [UPDATEUSER]        INT NULL,
    [CREATECHANNEL]     INT NOT NULL,
    [CREATEBRANCH]      INT NOT NULL,
    [CREATESCREEN]      INT NOT NULL,
    [BANK]              INT NOT NULL,
    [STOREREF_TXT]      VARCHAR(100) NULL,
    [POSREF_TXT]        VARCHAR(100) NULL,
    [BLOCKED_DT]        DATETIME NOT NULL,
    [VALUE_DT]          DATETIME NULL,
    [QUANTITY_QTY]      INT NULL,
    [CREDIT_AMT]        NUMERIC(22,6) NOT NULL,
    [DEBIT_AMT]         NUMERIC(22,6) NOT NULL,
    [COMMISSION_AMT]    NUMERIC(22,6) NOT NULL,
    [MIKRO_TM]          DATETIME NULL,
    [MIKROSTATUS_CD]    INT NOT NULL,
    [MIKROTRANCODE_TXT] VARCHAR(100) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_BANKPOSTRAN_PK] PRIMARY KEY ([BANKPOSTRANID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_BANKPOSTRAN_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [ACC_BANKPOSTRAN_F08] FOREIGN KEY ([BANK]) REFERENCES [STR_BANK]([BANKID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [ACC_BANKPOSTRAN_X01] ON [ACC_BANKPOSTRAN] ([BANK])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Bank Pos Transactions: Daily Bank Pos Transactions',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_BANKPOSTRAN',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Bank Pos Transactions Id: Identity column for ACC_BANKPOSTRAN' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'BANKPOSTRANID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Bank: Bank' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'BANK'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'StoreRef: Uye No' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'STOREREF_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'PosRef: Pos Id' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'POSREF_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Blocked Date: Blocked Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'BLOCKED_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Value Date: Value Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'VALUE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Quantity: Quantity' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'QUANTITY_QTY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Credit Amount: Credit Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'CREDIT_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Debit Amount: Debit Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'DEBIT_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Commission Amount: Commission Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'COMMISSION_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Transfer Time: Mikro Transfer Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'MIKRO_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Status Code: Mikro Status Code 0: Not Transferred 1: Transferred' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'MIKROSTATUS_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Transaction Code: Mikro Transaction Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_BANKPOSTRAN',
    @level2type=N'COLUMN',
    @level2name=N'MIKROTRANCODE_TXT'
GO

/*Section="End"*/
