-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_FIRMTYPE]
(
    /*Section="Columns"*/
    [FIRMTYPEID]  INT NOT NULL,
    [FIRMTYPE_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_FIRMTYPE_PK] PRIMARY KEY ([FIRMTYPEID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [ACC_FIRMTYPE_X01] ON [ACC_FIRMTYPE] ([FIRMTYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Firm Type: Types of firms (supplier, technical partner)',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_FIRMTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Firm Type Id: Identity column for ACC_FIRMTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMTYPE', 
    @level2type=N'COLUMN',
    @level2name=N'FIRMTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Name of firm type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMTYPE', 
    @level2type=N'COLUMN',
    @level2name=N'FIRMTYPE_NM'
GO

/*Section="End"*/
