-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_EXPENSECENTER]
(
    /*Section="Columns"*/
    [EXPENSECENTERID]       INT NOT NULL IDENTITY,
    [EXPENSECENTER_NM]      VARCHAR(100) NOT NULL,
    [EXPENSECENTERCODE_TXT] VARCHAR(50) NOT NULL,
    [CENTERGROUP_NO]        INT NOT NULL,
    [REGIONMANAGER]         INT NULL,
    [STORE]                 INT NULL,
    [ACTIVE_FL]             VARCHAR(1) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_EXPENSECENTER_PK] PRIMARY KEY ([EXPENSECENTERID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_EXPENSECENTER_F01] FOREIGN KEY ([REGIONMANAGER]) REFERENCES [STR_REGIONMANAGERS]([REGIONMANAGERSID]),
    CONSTRAINT [ACC_EXPENSECENTER_F02] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [ACC_EXPENSECENTER_X01] ON [ACC_EXPENSECENTER] ([STORE]) WHERE [STORE] IS NOT NULL;
GO
CREATE UNIQUE INDEX [ACC_EXPENSECENTER_X02] ON [ACC_EXPENSECENTER] ([REGIONMANAGER]) WHERE [REGIONMANAGER] IS NOT NULL;
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Expense Center: Expense Center',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_EXPENSECENTER',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Center Id: Identity column for ACC_EXPENSECENTER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSECENTERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Center Name: Name of expense center.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSECENTER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Center Code: Expense Center Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSECENTERCODE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Center Group: Expense Center Group 1: HQ, 2: REGION 3: STORE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'CENTERGROUP_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Region Manager: Region Manager' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'REGIONMANAGER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Active Flag: Active Flag' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_EXPENSECENTER', 
    @level2type=N'COLUMN',
    @level2name=N'ACTIVE_FL'
GO

/*Section="End"*/
