-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_IDENTITYINFO]
(
    /*Section="Columns"*/
    [IDENTITYINFOID]     INT NOT NULL IDENTITY,
    [ORGANIZATION]       INT NOT NULL,
    [DELETED_FL]         VARCHAR NOT NULL,
    [CREATE_DT]          DATETIME NOT NULL,
    [UPDATE_DT]          DATETIME NULL,
    [CREATEUSER]         INT NOT NULL,
    [UPDATEUSER]         INT NULL,
    [IDENTITYNO_TXT]     VARCHAR(30) NOT NULL,
    [IDENTITY_NM]        VARCHAR(100) NOT NULL,
    [TAXCENTERCODE_TXT]  VARCHAR(30) NOT NULL,
    [TAXCENTER_NM]       VARCHAR(100) NOT NULL,
    [ACTIVESTATUS_TXT]   VARCHAR(10) NULL,
    [COMPANYTYPE_TXT]    VARCHAR(30) NULL,
    [FATHER_NM]          VARCHAR(30) NULL,
    [IDENTITYTYPE_TXT]   VARCHAR(15) NULL,
    [PROFESSIONCODE_TXT] VARCHAR(15) NULL,
    [PROFESSION_DSC]     VARCHAR(1000) NULL,
    [ADDRESS_TXT]        VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_IDENTITYINFO_PK] PRIMARY KEY ([IDENTITYINFOID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_IDENTITYINFO_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [ACC_IDENTITYINFO_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ACC_IDENTITYINFO_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]) 
);
GO

/*Section="Indexes"*/
CREATE UNIQUE INDEX ACC_IDENTITYINFO_IX01 ON ACC_IDENTITYINFO (IDENTITYNO_TXT)
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Identity Info: Taxpayer Identification Numbers and National ID Numbers basic details',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_IDENTITYINFO',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Identity Info Id: Identity column for ACC_IDENTITYINFO' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'IDENTITYINFOID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Identity No: Identity No' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'IDENTITYNO_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Identity Name: Name of identity info.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'IDENTITY_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Tax Center Code: Tax Center Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'TAXCENTERCODE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Tax Center Name: Tax Center Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'TAXCENTER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Active Status: Active Status' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'ACTIVESTATUS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Company Type: Company Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'COMPANYTYPE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Father Name: Father Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'FATHER_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Identity Type: Identity Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'IDENTITYTYPE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Profession Code: Profession Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'PROFESSIONCODE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Profession: Profession' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'PROFESSION_DSC'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Address: Address' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_IDENTITYINFO', 
    @level2type=N'COLUMN',
    @level2name=N'ADDRESS_TXT'
GO

/*Section="End"*/
