-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_DEPARTMENT]
(
    /*Section="Columns"*/
    [DEPARTMENTID]      INT NOT NULL IDENTITY,
    [DEPARTMENT_NM]     VARCHAR(100) NOT NULL,
    [STORE]             INT NULL,
    [EXPENSECENTER_TXT] VARCHAR(50) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_DEPARTMENT_PK] PRIMARY KEY ([DEPARTMENTID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_DEPARTMENT_F01] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [ACC_DEPARTMENT_X01] ON [ACC_DEPARTMENT] ([DEPARTMENT_NM])
GO

CREATE INDEX [ACC_DEPARTMENT_X02] ON [ACC_DEPARTMENT] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Accounting Department: Accounting Department',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_DEPARTMENT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Accounting Department Id: Identity column for ACC_DEPARTMENT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_DEPARTMENT', 
    @level2type=N'COLUMN',
    @level2name=N'DEPARTMENTID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Department Name: Name of accounting department.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_DEPARTMENT', 
    @level2type=N'COLUMN',
    @level2name=N'DEPARTMENT_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_DEPARTMENT', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Center: Expense Center' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_DEPARTMENT', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSECENTER_TXT'
GO

/*Section="End"*/
