-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_FIRMCONTACT]
(
    /*Section="Columns"*/
    [FIRM]           INT NOT NULL,
    [CONTACT]        INT NOT NULL,
    [CREATE_DT]      DATETIME NOT NULL,
    [CREATEUSER]     INT NOT NULL,
    [CREATECHANNEL]  INT NOT NULL,
    [CREATEBRANCH]   INT NOT NULL,
    [CREATESCREEN]   INT NOT NULL,
    [ISDEFAULT_FL]   VARCHAR(1) NOT NULL,
    [ISACTIVE_FL]    VARCHAR(1) NOT NULL,
    [ISPREFERRED_FL] VARCHAR(1) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_FIRMCONTACT_PK] PRIMARY KEY ([FIRM],[CONTACT]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_FIRMCONTACT_F01] FOREIGN KEY ([FIRM]) REFERENCES [ACC_FIRM]([FIRMID]),
    CONSTRAINT [ACC_FIRMCONTACT_F02] FOREIGN KEY ([CONTACT]) REFERENCES [CNT_CONTACT]([CONTACTID]),
    CONSTRAINT [ACC_FIRMCONTACT_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ACC_FIRMCONTACT_F04] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [ACC_FIRMCONTACT_F05] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [ACC_FIRMCONTACT_F06] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Firm Contact: Firm Contact Relation',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_FIRMCONTACT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Firm: ACC_FIRM' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'FIRM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Contact: CNT_CONTACT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CONTACT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Creation date of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creation branch of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Creation screen of the user.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Is Default: Default contact ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'ISDEFAULT_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Is Active: Is ACtive' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'ISACTIVE_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Is Preferred: Is Preferred For Notification ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ACC_FIRMCONTACT', 
    @level2type=N'COLUMN',
    @level2name=N'ISPREFERRED_FL'
GO

/*Section="End"*/
