-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ACC_EXCELFILECOLUMNS]
(
    /*Section="Columns"*/
    [EXCELFILECOLUMNSID] INT NOT NULL IDENTITY,
    [EXCELFILE]          INT NOT NULL,
    [COLUMN_NM]          VARCHAR(100) NOT NULL,
    [COLUMNINDEX_NO]     INT NOT NULL,
    [COLUMNTYPE_CD]      INT NOT NULL,
    [FORMAT_TXT]         VARCHAR(50) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ACC_EXCELFILECOLUMNS_PK] PRIMARY KEY ([EXCELFILECOLUMNSID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ACC_EXCELFILECOLUMNS_F01] FOREIGN KEY ([EXCELFILE]) REFERENCES [ACC_EXCELFILE]([EXCELFILEID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Excel File Columns: Excel File Columns',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ACC_EXCELFILECOLUMNS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Excel File Columns Id: Identity column for ACC_EXCELFILECOLUMNS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'EXCELFILECOLUMNSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Excel File: Excel File' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'EXCELFILE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Column Name: Name of excel file columns.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'COLUMN_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Column Index: Column Index' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'COLUMNINDEX_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Column Type: Column Type 1: Text 2: Decimal 3: Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'COLUMNTYPE_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Column Format: Column Format, such as date format dd.MM.yyyy or dd/MM/yyyy or decimal format #.#' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ACC_EXCELFILECOLUMNS',
    @level2type=N'COLUMN',
    @level2name=N'FORMAT_TXT'
GO

/*Section="End"*/
