-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_REDIRECTIONGROUP]
(
    /*Section="Columns"*/
    [REDIRECTIONGROUPID] INT NOT NULL IDENTITY,
    [GROUP_NM]           VARCHAR(100) NOT NULL,
    [REQUESTDEFINITION]  INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_REDIRECTIONGROUP_PK] PRIMARY KEY ([REDIRECTIONGROUPID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [HDK_REDIRECTIONGROUP_F01] FOREIGN KEY ([REQUESTDEFINITION]) REFERENCES [HDK_REQUESTDEF]([REQUESTDEFID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Redirection Group: Redirection Group',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_REDIRECTIONGROUP',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Redirection Group Id: Identity column for HDK_REDIRECTIONGROUP' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REDIRECTIONGROUP', 
    @level2type=N'COLUMN',
    @level2name=N'REDIRECTIONGROUPID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Group Name: Name of redirection group.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REDIRECTIONGROUP', 
    @level2type=N'COLUMN',
    @level2name=N'GROUP_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request Definition: Request Definition' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REDIRECTIONGROUP', 
    @level2type=N'COLUMN',
    @level2name=N'REQUESTDEFINITION'
GO

/*Section="End"*/
