-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_ASSIGNUSER]
(
    /*Section="Columns"*/
    [ASSIGNUSERID]    INT NOT NULL IDENTITY,
    [GROUP_NM]        VARCHAR(100) NOT NULL,
    [RESPONSIBLEUSER] INT NOT NULL,
    [ADMIN_FL]        VARCHAR(1) NOT NULL,
    [SEEALL_FL]       VARCHAR(1) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_ASSIGNUSER_PK] PRIMARY KEY ([ASSIGNUSERID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [HDK_ASSIGNUSER_F01] FOREIGN KEY ([RESPONSIBLEUSER]) REFERENCES [SEC_USER]([USERID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [HDK_ASSIGNUSER_X01] ON [HDK_ASSIGNUSER] ([RESPONSIBLEUSER])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Assign User: Assign User List',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_ASSIGNUSER',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Assign User Id: Identity column for HDK_ASSIGNUSER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_ASSIGNUSER', 
    @level2type=N'COLUMN',
    @level2name=N'ASSIGNUSERID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Group Name: Name of assign user.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_ASSIGNUSER', 
    @level2type=N'COLUMN',
    @level2name=N'GROUP_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Responsible User: Responsible User' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_ASSIGNUSER', 
    @level2type=N'COLUMN',
    @level2name=N'RESPONSIBLEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Admin Flag: Admin Flag' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_ASSIGNUSER', 
    @level2type=N'COLUMN',
    @level2name=N'ADMIN_FL'
GO

/*Section="End"*/
