-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_ATTRIBUTECHOICE]
(
    /*Section="Columns"*/
    [ATTRIBUTECHOICEID] INT NOT NULL IDENTITY,
    [ATTRIBUTE]         INT NOT NULL,
    [CHOICE_NM]         VARCHAR(100) NOT NULL,
    [DISPLAYORDER_NO]   INT NULL,
    [PRIORITYPOINT_NO]  INT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_ATTRIBUTECHOICE_PK] PRIMARY KEY ([ATTRIBUTECHOICEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [HDK_ATTRIBUTECHOICE_F01] FOREIGN KEY ([ATTRIBUTE]) REFERENCES [HDK_ATTRIBUTE]([ATTRIBUTEID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Attribute Choice: Attribute Choice',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_ATTRIBUTECHOICE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Attribute Choice Id: Identity column for HDK_ATTRIBUTECHOICE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_ATTRIBUTECHOICE',
    @level2type=N'COLUMN',
    @level2name=N'ATTRIBUTECHOICEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Attribute: Attribute' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_ATTRIBUTECHOICE',
    @level2type=N'COLUMN',
    @level2name=N'ATTRIBUTE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Choice Name: Name of attribute choice.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_ATTRIBUTECHOICE',
    @level2type=N'COLUMN',
    @level2name=N'CHOICE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Display Order: Display Order' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_ATTRIBUTECHOICE',
    @level2type=N'COLUMN',
    @level2name=N'DISPLAYORDER_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Priority Point: Priority Point' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_ATTRIBUTECHOICE',
    @level2type=N'COLUMN',
    @level2name=N'PRIORITYPOINT_NO'
GO

/*Section="End"*/
