-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_REQUESTDETAIL]
(
    /*Section="Columns"*/
    [REQUESTDETAILID]    BIGINT NOT NULL IDENTITY,
    [EVENT]              INT NOT NULL,
    [ORGANIZATION]       INT NOT NULL,
    [DELETED_FL]         VARCHAR NOT NULL,
    [CREATE_DT]          DATETIME NOT NULL,
    [UPDATE_DT]          DATETIME NULL,
    [CREATEUSER]         INT NOT NULL,
    [UPDATEUSER]         INT NULL,
    [CREATECHANNEL]      INT NOT NULL,
    [CREATEBRANCH]       INT NOT NULL,
    [CREATESCREEN]       INT NOT NULL,
    [REQUEST]            BIGINT NOT NULL,
    [ATTRIBUTE]          INT NOT NULL,
    [ATTRIBUTEVALUE_TXT] VARCHAR(1000) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_REQUESTDETAIL_PK] PRIMARY KEY ([REQUESTDETAILID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [HDK_REQUESTDETAIL_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F08] FOREIGN KEY ([REQUEST]) REFERENCES [HDK_REQUEST]([REQUESTID]),
    CONSTRAINT [HDK_REQUESTDETAIL_F09] FOREIGN KEY ([ATTRIBUTE]) REFERENCES [HDK_ATTRIBUTE]([ATTRIBUTEID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [HDK_REQUESTDETAIL_X01] ON [HDK_REQUESTDETAIL] ([REQUEST])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Request Detail: Request Detail',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_REQUESTDETAIL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request Detail Id: Identity column for HDK_REQUESTDETAIL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'REQUESTDETAILID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request: Request' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'REQUEST'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Attribute: Attribute' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'ATTRIBUTE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Attribute Value: Attribute Value' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'ATTRIBUTEVALUE_TXT'
GO

/*Section="End"*/
