-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_REQUESTSTATUS]
(
    /*Section="Columns"*/
    [REQUESTSTATUSID] INT NOT NULL,
    [STATUS_NM]       VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_REQUESTSTATUS_PK] PRIMARY KEY ([REQUESTSTATUSID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Request Status: Request Status',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_REQUESTSTATUS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request Status Id: Identity column for HDK_REQUESTSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'REQUESTSTATUSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Name: Name of request status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'STATUS_NM'
GO

/*Section="End"*/
