-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [HDK_REQUESTGROUP]
(
    /*Section="Columns"*/
    [REQUESTGROUPID]  INT NOT NULL IDENTITY,
    [REQUESTGROUP_NM] VARCHAR(100) NOT NULL,
    [DISPLAYORDER_NO] INT NULL,
    [ACTIVE_FL]       VARCHAR(1) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [HDK_REQUESTGROUP_PK] PRIMARY KEY ([REQUESTGROUPID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Request Group: Talep Grupları',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'HDK_REQUESTGROUP',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request Group Id: Identity column for HDK_REQUESTGROUP' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTGROUP',
    @level2type=N'COLUMN',
    @level2name=N'REQUESTGROUPID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Request Group Name: Name of request group.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTGROUP',
    @level2type=N'COLUMN',
    @level2name=N'REQUESTGROUP_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Display Order: Display Order' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTGROUP',
    @level2type=N'COLUMN',
    @level2name=N'DISPLAYORDER_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Active Flag: Active Flag' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'HDK_REQUESTGROUP',
    @level2type=N'COLUMN',
    @level2name=N'ACTIVE_FL'
GO

/*Section="End"*/
