CREATE PROCEDURE [dbo].[PRD_LST_PRODUCTREPORT_SP]       
AS        
BEGIN        
SELECT P.PRODUCTID      
  , SEC.USER_NM CREATE_USER_NM      
  , SEC2.USER_NM UPDATE_USER_NM      
  , P.CODE_NM
  , CASE P.DELETED_FL WHEN 'N' THEN 'Hayır' ELSE 'Evet' END AS DELETED_FL
  , P.NAME_NM      
  , P.PURCHASEVAT_RT      
  , P.SALEVAT_RT      
  , P.OLDCODE_NM      
  , P.GTIPCODE_TXT      
  , P.SHORTNAME_NM      
  , C2.COUNTRY_NM      
  , P.CONTENT_TXT      
  , P.EXPIRESIN_CNT      
  , P.SHELFLIFE_CNT      
  , P.COMMENT_DSC      
  , U2.UNIT_NM WEIGHTUNIT      
  , P.LOADORDER_TXT      
  , P.PARENT      
  , P.INITIALPRICE_AMT      
  , B2.BARCODE_TXT BARCODE_TXT1      
  , B3.BARCODE_TXT BARCODE_TXT2      
  , CASE  WHEN  PS.[1] IS NOT NULL THEN PS.[1] ELSE '0' END KOKU  
  , CASE  WHEN  PS.[2] IS NOT NULL THEN PS.[2] ELSE '0' END ULUSLARARASI_KODU  
  , CASE  WHEN  PS.[3] IS NOT NULL THEN PS.[3] ELSE '0' END TOSHIBAID  
  , CASE  WHEN  PS.[4] IS NOT NULL THEN PS.[4] ELSE '0' END SIPARISE_KAPALI  
  , CASE  WHEN  PS.[5] IS NOT NULL THEN PS.[5] ELSE '0' END DELİST    
  , CASE  WHEN  PS.[6] IS NOT NULL THEN PS.[6] ELSE '0' END KONSIYE_URUN   
  , CA.CATEGORY_NM  
  , SG.SUBGROUP_NM  
  , SP1.SUPERGROUP1_NM      
  , SP2.SUPERGROUP2_NM      
  , SP3.SUPERGROUP3_NM      
  , U.UNIT_NM      
  , BT.BARCODETYPE_NM      
  , ST.SEASONTYPE_NM      
  , W.WARNING_TXT      
  , SC.CONDITION_TXT      
  , C.NAME_NM CAMPAIGN_NM       
  , SU.PACKAGE_QTY SHIPMENTUNIT_QTY       
  FROM PRD_PRODUCT P       
  LEFT JOIN (   
             SELECT PRODUCT,MAX( [1]) [1]  ,MAX([2])[2] ,MAX([3])[3] ,MAX([4])[4] ,MAX([5])[5] ,MAX([6])[6]  
             FROM (  
    SELECT * FROM  PRD_PROPERTY P4 LEFT JOIN PRD_PROPERTYTYPE P5 ON P4.PROPERTYTYPE=P5.PROPERTYTYPEID   )as a  
             PIVOT( MAX(VALUE_TXT) FOR PROPERTYTYPE IN ([1],[2],[3],[4],[5],[6]))as b GROUP BY PRODUCT  
         ) PS ON PS.PRODUCT=P.PRODUCTID   
  LEFT JOIN SEC_USER SEC ON SEC.USERID=P.CREATEUSER       
  LEFT JOIN SEC_USER SEC2 ON SEC2.USERID=P.UPDATEUSER       
  LEFT JOIN PRD_SUBGROUP SG ON P.SUBGROUP=SG.SUBGROUPID       
  LEFT JOIN PRD_CATEGORY CA ON CA.CATEGORYID=SG.CATEGORY       
  LEFT JOIN PRD_SUPERGROUP1 SP1 ON P.SUPERGROUP1=SP1.SUPERGROUP1ID       
  LEFT JOIN PRD_SUPERGROUP2 SP2 ON P.SUPERGROUP1=SP2.SUPERGROUP2ID       
  LEFT JOIN PRD_SUPERGROUP3 SP3 ON P.SUPERGROUP1=SP3.SUPERGROUP3ID       
  LEFT JOIN PRD_UNIT U ON P.UNIT=U.UNITID         
  LEFT JOIN PRD_UNIT U2 ON P.WEIGHTUNIT=U2.UNITID        
  LEFT JOIN PRD_BARCODETYPE BT ON P.BARCODETYPE=BT.BARCODETYPEID       
  LEFT JOIN PRD_SEASONTYPE ST ON P.SEASONTYPE=ST.SEASONTYPEID      
  LEFT JOIN PRD_WARNING W ON P.WARNING=W.WARNINGID       
  LEFT JOIN PRD_STORAGECONDITION SC ON P.STORAGECONDITION=SC.STORAGECONDITIONID       
  LEFT JOIN PRD_CAMPAIGN C ON P.CAMPAIGN=C.CAMPAIGNID       
  LEFT JOIN PRD_COUNTRY C2 ON P.COUNTRY=C2.COUNTRYID       
  LEFT JOIN WHS_PRODUCTSHIPMENTUNIT SU ON SU.PRODUCT = P.PRODUCTID       
  LEFT JOIN (SELECT PRODUCT, BARCODE_TXT, ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY BARCODEID DESC) ROWNO FROM PRD_BARCODE) B2 ON B2.PRODUCT=P.PRODUCTID AND B2.ROWNO = 1       
  LEFT JOIN (SELECT PRODUCT, BARCODE_TXT, ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY BARCODEID DESC) ROWNO FROM PRD_BARCODE) B3 ON B3.PRODUCT=P.PRODUCTID AND B3.ROWNO = 2;    
 END