CREATE PROCEDURE [dbo].[PRD_LST_HOTKEYS56_SP] AS
BEGIN
	SELECT CAST(P.VALUE_TXT AS INT) HOTKEY, CAST(RIGHT(B.BARCODE_TXT,4) AS INT) CODE, PP.NAME_NM PRODUCTNAME
	  FROM PRD_PROPERTY P
	  JOIN PRD_BARCODE B ON P.PRODUCT = B.PRODUCT AND DELETED_FL = 'N' AND B.BARCODE_TXT NOT IN ('2901038', '2901423')
	  JOIN PRD_PRODUCT PP ON P.PRODUCT = PP.PRODUCTID
	 WHERE PROPERTYTYPE = 9
	   AND B.BARCODE_TXT LIKE '290%'
	 ORDER BY CAST(P.VALUE_TXT AS INT) 
END
