CREATE PROCEDURE PRD_LST_PRDWITHSTOCKGRFILTER_SP AS
BEGIN
	SELECT -1 AS PRODUCTID, ' *TÜM ÜRÜNLER*' AS NAME_NM  
	 UNION ALL
	SELECT DISTINCT COALESCE(10000 + SG.STOCKGROUP, P.PRODUCTID) PRODUCTID, COALESCE(SG.STOCKGROUP_NM, P.NAME_NM) NAME_NM  
	  FROM PRD_PRODUCT P (NOLOCK)    
	  LEFT JOIN PRD_STOCKGROUP_VW SG (NOLOCK) ON P.PRODUCTID = SG.PRODUCTID AND USAGETYPE_CD = 1
	 WHERE P.DELETED_FL = 'N'    
	 ORDER BY 2 
END