ALTER PROCEDURE [dbo].[PRD_LST_COMPAREPERFORMANCE_SP]
	@Product INT,
	@StartDate DATE,
	@EndDate DATE,
	@StartCompDate DATE,
	@EndCompDate DATE
AS
BEGIN
	SELECT  S3.STORE_NM STORE,
	        S.PRODUCT,		  
	        P.NAME_NM,		
	        SUM(S.QUANTITY) QUANTITY,		
	        SUM(S.PRICE) PRICE,	
	        SUM(S2.QUANTITY) COMP_QUANTITY,		
	        SUM(S2.PRICE) COMP_PRICE		
    FROM  SLS_STOREDAILYPRODUCT S JOIN SLS_STOREDAILYPRODUCT S2 ON S.STORE=S2.STORE AND S.PRODUCT=S2.PRODUCT
	      LEFT JOIN PRD_PRODUCT P ON S.PRODUCT=P.PRODUCTID
		  LEFT JOIN STR_STORE S3 ON S.STORE=S3.STOREID
    WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate 
	      AND S2.TRANSACTION_DT BETWEEN @StartCompDate AND @EndCompDate
		  AND S.PRODUCT=@Product
    GROUP BY S.STORE,S.PRODUCT,S2.STORE,S2.PRODUCT,P.NAME_NM,S3.STORE_NM
END