CREATE PROCEDURE IBM_SEL_IDENTITYINFO_SP @IdentityNo VARCHAR(100) AS
BEGIN
	SELECT COALESCE(CL.TITLE_DSC COLLATE Turkish_CI_AS, C.NAME) CUSTOMER_NM
		 , TRIM(L.ADDRESS_1+' '+L.ADDRESS_2+' '+L.ADDRESS_3) ADDRESS_TXT
		 , L.PHONE_1 TEL_NO
		 , E.TAX_OFFICE
		 , CL.ALIAS_DSC 
	  FROM IBM_CUSTOMER_SYN C
	  LEFT JOIN IBM_CUSTOMEREXT_SYN E ON C.ID = E.FK_CUSTOMER
	  LEFT JOIN IBM_LOCATION L ON E.FK_LOCATION_WORK = L.ID
	  LEFT JOIN ACC_EINVOICECLIENT CL ON C.CODE COLLATE Turkish_100_CI_AS = CL.IDENTIFIER_NO 
	 WHERE C.CODE = @IdentityNo
END