CREATE PROCEDURE [dbo].[SLS_LST_STORESALEZET_SP] @TransactionDate DATE, @StoreId INT AS
BEGIN
  SELECT *
    FROM SLS_SALEZET
   WHERE STORE = @StoreId
     AND TRANSACTION_DT = @TransactionDate
     AND DELETED_FL = 'N'
   ORDER BY CASHREGISTER;
END