CREATE PROCEDURE SLS_DEL_SALEROW_SP @TransactionTxt VARCHAR(100) AS  
BEGIN  
  DELETE SP  
    FROM SLS_SALEPAYMENT SP  
    JOIN SLS_SALE S ON SP.SALE = S.SALEID   
   WHERE S.TRANSACTION_TXT = @TransactionTxt
  
  DELETE SD  
    FROM SLS_SALEDETAIL SD  
    JOIN SLS_SALE S ON SD.SALE = S.SALEID   
   WHERE S.TRANSACTION_TXT = @TransactionTxt
  
  DELETE SR  
    FROM SLS_SALERAW SR  
    JOIN SLS_SALE S ON SR.SALE = S.SALEID   
   WHERE S.TRANSACTION_TXT = @TransactionTxt
  
  DELETE S  
    FROM SLS_SALE S   
   WHERE S.TRANSACTION_TXT = @TransactionTxt
END