CREATE PROCEDURE SLS_LST_STORECANCELDETAIL_SP @StartDate DATE, @EndDate DATE, @StoreId INT AS            
BEGIN            
  
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;      
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();      
  
  WITH CANCELS AS (            
  SELECT DISTINCT S.SALEID            
    FROM SLS_CANCELLEDPRODUCTS_SYN S            
   WHERE S.OMITREASON = 0            
     AND S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate             
     AND S.STORE = @StoreId)            
  SELECT *      
    FROM (      
  SELECT S.CASHIER_NM, S.SALEID, S.TOTAL_AMT, S.TRANSACTION_DT, DATEPART(HOUR, TRANSACTION_TM) HOUR, P.CODE_NM, P.NAME_NM,       
		 CASE WHEN S.CANCELLED_FL = 'Y' THEN 'Y' ELSE SD.CANCEL_FL END CANCEL_FL, SD.PRICE,     
		 CASE WHEN P.UNIT = 1 THEN SD.QUANTITY_QTY/1000.0 ELSE SD.QUANTITY_QTY END QUANTITY_QTY, TRANSACTION_TM,      
		 SUM(CASE WHEN S.CANCELLED_FL = 'Y' OR SD.CANCEL_FL = 'Y' THEN SD.PRICE ELSE 0 END) OVER (PARTITION BY S.SALEID) CANCELTOTAL_AMT      
    FROM CANCELS C            
    JOIN #stores ST ON ST.STOREID = @StoreId             
    JOIN SLS_SALE S ON C.SALEID = S.SALEID            
    JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE            
    JOIN PRD_PRODUCT P ON SD.PRODUCT = P.PRODUCTID) A      
   ORDER BY A.CANCELTOTAL_AMT DESC      

END