CREATE PROCEDURE SLS_SEL_REFUND_SP @SaleDetailId BIGINT AS
BEGIN

  SELECT SD.SALEDETAILID, S.TRANSACTION_DT, S.TRANSACTION_TM, S.TRANSACTION_TXT, SD.UNIT, SD.QUANTITY_QTY, SD.PRICE, 
  	     'Tarih : '+CONVERT(VARCHAR(20), TRANSACTION_TM, 120) + ' Miktar : '+ CAST(QUANTITY_QTY AS varchar(20)) + ' Tutar : '+CAST(ABS(PRICE) AS varchar(20)) TRAN_DSC
    FROM SLS_SALE S (NOLOCK)
    JOIN SLS_SALEDETAIL SD (NOLOCK) ON S.SALEID = SD.SALE AND S.STORE = SD.STORE AND S.TRANSACTION_DT = SD.TRANSACTION_DT
   WHERE SD.SALEDETAILID = @SaleDetailId

END