CREATE PROCEDURE SLS_LST_CANCELREASONBYDATE_SP @ReconciliationDate DATE, @StoreId INT = -1 WITH RECOMPILE AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;

	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();
	-- SELECT * INTO #STORES FROM STR_STORE WHERE STOREID = 21;

	SELECT C.CANCELREASONID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           NULL STOREREC,
           SD.SALEDETAILID SALEDETAIL,
           C.REASON_TXT,
           C.CASHIER_NM,
		   S.TRANSACTION_TM SALETRANSACTION_TM,
		   S.CASHREGISTER SALECASHREGISTER,
		   P.CODE_NM PRODUCTCODE_NM,
		   P.NAME_NM PRODUCT_NM,
		   SD.PRICE,
		   S.STORE
	  FROM SLS_SALE S (NOLOCK)
	  JOIN #STORES ST ON S.STORE = ST.STOREID
	  JOIN SLS_SALEDETAIL SD (NOLOCK) ON S.SALEID = SD.SALE
	  JOIN PRD_PRODUCT P (NOLOCK) ON SD.PRODUCT = P.PRODUCTID
	  LEFT JOIN SLS_CANCELREASON C (NOLOCK) ON SD.SALEDETAILID = C.SALEDETAIL AND C.DELETED_FL = 'N'
	 WHERE SD.CANCEL_FL = 'Y'
	   AND SD.PRICE != 0 
	   AND S.TRANSACTION_DT = @ReconciliationDate
	   AND (@StoreId = -1 OR S.STORE = @StoreId)
	 
	 UNION ALL

	SELECT C.CANCELREASONID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           NULL STOREREC,
           S.SALEID SALEDETAIL,
           C.REASON_TXT,
           C.CASHIER_NM,
		   S.TRANSACTION_TM SALETRANSACTION_TM,
		   S.CASHREGISTER SALECASHREGISTER,
		   ' ' PRODUCTCODE_NM,
		   'Fiş İptal' PRODUCT_NM,
		   S.TOTAL_AMT PRICE,
		   S.STORE 
	  FROM SLS_SALE S (NOLOCK)
	  JOIN #STORES ST ON S.STORE = ST.STOREID
	  LEFT JOIN SLS_CANCELREASON C (NOLOCK) ON S.SALEID = C.SALEDETAIL AND C.DELETED_FL = 'N'
	 WHERE S.CANCELLED_FL = 'Y' 
	   AND S.TOTAL_AMT != 0 
	   AND S.TRANSACTION_DT = @ReconciliationDate
	   AND (@StoreId = -1 OR S.STORE = @StoreId)

	 ORDER BY S.TRANSACTION_TM

	

END;