CREATE PROCEDURE SLS_UPD_CANCELUNBALANCED_SP AS
BEGIN
    DECLARE @StartDate DATE = CAST(GETDATE()-60 AS DATE)  
    DECLARE @EndDate DATE = CAST(GETDATE()-1 AS DATE)  

	IF OBJECT_ID('tempdb.dbo.#DUZELT', 'U') IS NOT NULL DROP TABLE #DUZELT;
	WITH SALE AS (
	SELECT SALEID, SUM(TOTAL_AMT) TOTAL
	  FROM SLS_SALE S
	 WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate  
	   AND TRANSACTIONTYPE = 5
	   AND CANCELLED_FL = 'N'
	 GROUP BY SALEID),
	SALEDETAIL AS (
	SELECT SALE, SUM(PRICE) PRICE
	  FROM SLS_SALEDETAIL
	 WHERE TRANSACTION_DT BETWEEN @StartDate AND @EndDate  
	   AND CANCEL_FL = 'N'
	 GROUP BY SALE)
	SELECT *
	  INTO #DUZELT
	  FROM SALE S
	  JOIN SALEDETAIL SD ON S.SALEID = SD.SALE
	 WHERE TOTAL = -1*PRICE

	UPDATE SD
	   SET SD.PRICE = -1*SD.PRICE
	-- SELECT *
	  FROM SLS_SALEDETAIL SD
	  JOIN #DUZELT D ON SD.SALE = D.SALEID
END