CREATE PROCEDURE SLS_LST_CANCELLEDSALE_SP @StoreId INT, @StartDate DATE, @EndDate DATE AS
BEGIN
	SET @StartDate = DATEADD(DAY, -30, @EndDate);

	SELECT S.*, I.INVOICEID
	  FROM SLS_SALE S
	  LEFT JOIN ACC_INVOICE I ON S.SALEID = I.SALE AND I.DELETED_FL = 'N' AND I.STATUS_CD != 3 -- İPTAL
	 WHERE STORE = @StoreId 
	   AND TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND TRANSACTIONTYPE = 5
	   AND CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	 UNION ALL
	SELECT S.*, I.INVOICEID
	  FROM SLS_SALE S
	  JOIN SLS_SALECUSTOMER SC ON S.SALEID = SC.SALE
	  LEFT JOIN ACC_INVOICE I ON S.SALEID = I.SALE AND I.DELETED_FL = 'N' AND I.STATUS_CD != 3 -- İPTAL
	 WHERE STORE = @StoreId 
	   AND TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	 ORDER BY S.TRANSACTION_DT DESC;

END