CREATE PROCEDURE [dbo].[SLS_LST_DAILYSALETREND_SP] @StartDate DATE = NULL, @EndDate DATE = NULL, @Store INT = -1 AS
BEGIN

	WITH PACKAGES AS (
	SELECT D.DATE_DT
	     , COUNT(DISTINCT CASE WHEN P.TYPE = 3 THEN 1 END) GENERALPACKAGE_CNT
		 , COUNT(DISTINCT CASE WHEN P.TYPE IN (4,5) THEN 1 END) PRIVATEPACKAGE_CNT
	  FROM PRC_STOREPACKAGE SP
	  JOIN PRC_PACKAGE P ON SP.PACKAGE = P.PACKAGEID
	  JOIN RPT_DATE D ON D.DATE_DT BETWEEN CAST(SP.START_TM AS DATE) AND CAST(SP.END_TM AS DATE)
	 WHERE SP.PACKAGE != 1
	   AND SP.DELETED_FL = 'N'
	   AND SP.STORE = @Store
	   AND D.DATE_DT BETWEEN @StartDate AND @EndDate
	 GROUP BY SP.STORE, D.DATE_DT) 
	SELECT A.*, GENERALPACKAGE_CNT, PRIVATEPACKAGE_CNT
	  FROM (
	SELECT D.DATE_DT, ISNULL(SUM(DP.QUANTITY),0) TOTALQUANTITY, ISNULL(SUM(DP.PRICE),0) TOTALPRICE
	  FROM RPT_DATE D 
	  LEFT JOIN SLS_STOREDAILYPRODUCT_SYN DP ON DP.TRANSACTION_DT = D.DATE_DT AND DP.STORE = @Store
	 WHERE D.DATE_DT BETWEEN @StartDate AND @EndDate
	 GROUP BY D.DATE_DT) A
	  LEFT JOIN PACKAGES B ON A.DATE_DT = B.DATE_DT
	 ORDER BY A.DATE_DT

END