CREATE PROCEDURE SLS_INS_WNCDELETEDDOCS_SP @StartDate DATE, @EndDate DATE AS
BEGIN

  -- SATIR İPTALLERİ
  IF OBJECT_ID('tempdb..#WNCLINES') IS NOT NULL DROP TABLE #WNCLINES
  
  BEGIN TRANSACTION;
  
  BEGIN TRY
  
    SELECT CAST(A.BRANCH_CODE AS VARCHAR(10))+'-'+CAST(A.POS_ID AS VARCHAR(10))+'-'+CONVERT(CHAR(8),A.TRANSACTION_DATE,112)+REPLACE(A.ORJ_TRANSACTION_TIME,':','')+'-'+CAST(A.ID AS VARCHAR(10)) COLLATE Turkish_100_CI_AS TRANSACTION_TXT, 
    	   A.TRANSACTION_DATE TRANSACTION_DT, D.SUBST_CODE COLLATE Turkish_100_CI_AS  SUBST_CODE, A.BRANCH_CODE STORE, D.TRANSACTION_VALUE PRICE, D.VAT_PERCENT VAT_RT, D.QUANTITY QUANTITY_QTY, D.ID
      INTO #WNCLINES
      FROM WNC_DELETEDDOCUMENTS D
      JOIN WNC_POSTRANHEADERS A ON D.POS_ID = A.POS_ID AND D.TRANSACTION_DATE = A.TRANSACTION_DATE AND D.DOC_PTR = A.DOC_PTR
      LEFT JOIN WNC_PROCESSEDDELETEDROWS DR ON D.ID = DR.ID
     WHERE D.TRANSACTION_DATE BETWEEN @StartDate AND @EndDate
       AND DR.ID IS NULL
    
    INSERT INTO SLS_SALEDETAIL      
    (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, SALE,          
     TRANSACTION_TXT, TRANSACTION_DT, BARCODE_TXT, PRODUCT, PRODUCTCODE_NM, STORE, PRICE, VAT_RT, QUANTITY_QTY,          
     UNIT, CANCEL_FL, UNITPRICE_AMT)          
    SELECT 1045, 1, 'N', GETDATE(), 1, 1, 1, 1, S.SALEID, S.TRANSACTION_TXT, S.TRANSACTION_DT, COALESCE(SC.BARCODE_TXT, H.SUBST_CODE) BARCODE_TXT,
    	   COALESCE(SC.PRODUCTID, 326) PRODUCTID, H.SUBST_CODE,   
           S.STORE, H.PRICE, H.VAT_RT, CASE WHEN COALESCE(SC.UNIT, 1) = 1 THEN H.QUANTITY_QTY*1000 ELSE H.QUANTITY_QTY END,
    	   COALESCE(SC.UNIT, 1), 'Y', ROUND(H.PRICE/(H.QUANTITY_QTY*1.0),CASE WHEN COALESCE(SC.UNIT, 1)=1 THEN 1 ELSE 2 END)
      FROM #WNCLINES H      
      JOIN SLS_SALE S ON H.TRANSACTION_TXT = S.TRANSACTION_TXT
	  LEFT JOIN PRD_SEARCHCODE_VW SC ON H.SUBST_CODE = SC.SEARCHCODE
    
    INSERT INTO WNC_PROCESSEDDELETEDROWS
    SELECT H.* 
      FROM #WNCLINES H      
      JOIN SLS_SALE S ON H.TRANSACTION_TXT = S.TRANSACTION_TXT
    
    COMMIT TRANSACTION;
  END TRY
  
  BEGIN CATCH
  
    ROLLBACK TRANSACTION;
  
  END CATCH;

  -- SATIŞ İPTALLERİ
  IF OBJECT_ID('tempdb..#CANCELLED') IS NOT NULL DROP TABLE #CANCELLED

  BEGIN TRANSACTION;
  
  BEGIN TRY
	SELECT CAST(D.BRANCH_CODE AS VARCHAR(10))+'-'+CAST(D.POS_ID AS VARCHAR(10))+'-'+CONVERT(CHAR(8),D.TRANSACTION_DATE,112)+REPLACE(D.ORJ_TRANSACTION_TIME,':','')+'-'+CAST(D.DOC_PTR AS VARCHAR(10)) COLLATE Turkish_100_CI_AS TRANSACTION_TXT,
		   D.TRANSACTION_DATE TRANSACTION_DT, D.SUBST_CODE COLLATE Turkish_100_CI_AS  SUBST_CODE, D.BRANCH_CODE STORE, D.TRANSACTION_VALUE PRICE, D.VAT_PERCENT VAT_RT, D.QUANTITY QUANTITY_QTY, D.ID, D.POS_ID,
		   D.ORJ_TRANSACTION_TIME, D.LINE_NUMBER
	  INTO #CANCELLED
	  FROM WNC_DELETEDDOCUMENTS D
	  LEFT JOIN WNC_POSTRANHEADERS A ON D.POS_ID = A.POS_ID AND D.TRANSACTION_DATE = A.TRANSACTION_DATE AND D.DOC_PTR = A.DOC_PTR
	  LEFT JOIN WNC_PROCESSEDDELETEDROWS DR ON D.ID = DR.ID
	 WHERE DR.ID IS NULL
	   AND A.POS_ID IS NULL
	   AND D.TRANSACTION_DATE BETWEEN @StartDate AND @EndDate

    INSERT INTO SLS_SALE            
    (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN,             
    TRANSACTION_TXT, STORE, CASHIER_NM, CASHREGISTER, TRANSACTION_DT, TRANSACTION_TM, TOTALVAT_AMT, TOTAL_AMT,            
    PRODUCTDISCOUNT_AMT, SALEDISCOUNT_AMT, PRODUCT_CNT, DURATION_CNT, CANCELLED_FL, TRANSACTIONTYPE)            
    SELECT 1045, 1, 'N', GETDATE(), 1, 1, 1, 1, C.TRANSACTION_TXT, C.STORE, '00000000', C.POS_ID, C.TRANSACTION_DT,
	  	   CONVERT(DATETIME,REPLACE(CONVERT(VARCHAR(20), C.TRANSACTION_DT, 120),'00:00:00',MAX(ORJ_TRANSACTION_TIME)),120) TRANSACTION_TM,
	  	   SUM(PRICE), SUM(PRICE), 0, 0, MAX(LINE_NUMBER), 0, 'Y', 1
      FROM #CANCELLED C            
      LEFT JOIN SLS_SALE S ON C.TRANSACTION_TXT = S.TRANSACTION_TXT            
     WHERE S.TRANSACTION_TXT IS NULL 
     GROUP BY C.TRANSACTION_TXT, C.STORE, C.POS_ID, C.TRANSACTION_DT

	INSERT INTO SLS_SALEDETAIL      
    (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, SALE,          
     TRANSACTION_TXT, TRANSACTION_DT, BARCODE_TXT, PRODUCT, PRODUCTCODE_NM, STORE, PRICE, VAT_RT, QUANTITY_QTY,          
     UNIT, CANCEL_FL, UNITPRICE_AMT)          
    SELECT 1045, 1, 'N', GETDATE(), 1, 1, 1, 1, S.SALEID, S.TRANSACTION_TXT, S.TRANSACTION_DT, COALESCE(SC.BARCODE_TXT, H.SUBST_CODE) BARCODE_TXT,
    	   COALESCE(SC.PRODUCTID, 326) PRODUCTID, H.SUBST_CODE,   
           S.STORE, H.PRICE, H.VAT_RT, CASE WHEN COALESCE(SC.UNIT, 1) = 1 THEN H.QUANTITY_QTY*1000 ELSE H.QUANTITY_QTY END,
    	   COALESCE(SC.UNIT, 1), 'N', ROUND(H.PRICE/(H.QUANTITY_QTY*1.0),CASE WHEN COALESCE(SC.UNIT, 1)=1 THEN 1 ELSE 2 END)
      FROM #CANCELLED H      
      JOIN SLS_SALE S ON H.TRANSACTION_TXT = S.TRANSACTION_TXT
	  LEFT JOIN PRD_SEARCHCODE_VW SC ON H.SUBST_CODE = SC.SEARCHCODE

	INSERT INTO WNC_PROCESSEDDELETEDROWS
	(TRANSACTION_TXT, TRANSACTION_DT, BARCODE_TXT, STORE, PRICE, VAT_RT, QUANTITY_QTY, ID)
    SELECT TRANSACTION_TXT, TRANSACTION_DT, SUBST_CODE, STORE, PRICE, VAT_RT, QUANTITY_QTY, ID FROM #CANCELLED

    INSERT INTO SLS_SALEDETAIL      
    (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, SALE,          
     TRANSACTION_TXT, TRANSACTION_DT, BARCODE_TXT, PRODUCT, PRODUCTCODE_NM, STORE, PRICE, VAT_RT, QUANTITY_QTY,          
     UNIT, CANCEL_FL, UNITPRICE_AMT)
    SELECT 1045 EVENT, 1 ORGANIZATION, 'N' DELETED_FL, GETDATE() CREATE_DT, 1 CREATEUSER, 1 CREATECHANNEL, 1 CREATEBRANCH, 1 CREATESCREEN, 
	       S.SALEID, S.TRANSACTION_TXT, S.TRANSACTION_DT, COALESCE(SC.BARCODE_TXT, H.BARCODE_TXT) BARCODE_TXT,
           COALESCE(SC.PRODUCTID, 326) PRODUCTID, H.BARCODE_TXT PRODUCTCODE_NM,   
           S.STORE, H.PRICE, H.VAT_RT, CASE WHEN COALESCE(SC.UNIT, 1) = 1 THEN H.QUANTITY_QTY*1000 ELSE H.QUANTITY_QTY END QUANTITY_QTY,
           COALESCE(SC.UNIT, 1) UNIT, 'Y' CANCEL_FL, ROUND(H.PRICE/(H.QUANTITY_QTY*1.0),CASE WHEN COALESCE(SC.UNIT, 1)=1 THEN 1 ELSE 2 END) UNITPRICE_AMT
      FROM WNC_PROCESSEDDELETEDROWS H
      JOIN SLS_SALE S (NOLOCK) ON H.TRANSACTION_TXT = S.TRANSACTION_TXT
      LEFT JOIN PRD_SEARCHCODE_VW SC ON H.BARCODE_TXT = SC.SEARCHCODE
      LEFT JOIN SLS_SALEDETAIL SD WITH (NOLOCK INDEX(SLS_SALEDETAIL_X04)) ON H.TRANSACTION_TXT = SD.TRANSACTION_TXT AND H.STORE = SD.STORE 
       AND H.TRANSACTION_DT = SD.TRANSACTION_DT AND PRODUCTCODE_NM = H.BARCODE_TXT AND H.PRICE = SD.PRICE AND CANCEL_FL = 'Y'
     WHERE H.TRANSACTION_DT >= CAST(GETDATE() - 5 AS date)
       AND SD.SALEDETAILID IS NULL

	COMMIT TRANSACTION;
  END TRY
  
  BEGIN CATCH
  
    ROLLBACK TRANSACTION;
  
  END CATCH;

END