CREATE PROCEDURE [dbo].[SLS_LST_WHOLESALE_SP]          
 @Store INT = -1,
 @ProductId INT = -1,
 @StartDate DATE = NULL,
 @EndDate DATE = NULL AS
BEGIN  

  IF OBJECT_ID('tempdb.dbo.#PRODUCTAVERAGE', 'U') IS NOT NULL  DROP TABLE #PRODUCTAVERAGE
  IF OBJECT_ID('tempdb.dbo.#WHOLESALE', 'U') IS NOT NULL  DROP TABLE #WHOLESALE
      
  SELECT SD.PRODUCT, P.UNIT, AVG(SD.QUANTITY_QTY) AVGQUANTITY
    INTO #PRODUCTAVERAGE        
    FROM SLS_SALE S        
	JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE        
	JOIN PRD_PRODUCT P ON SD.PRODUCT = P.PRODUCTID        
   WHERE S.TRANSACTION_DT BETWEEN  @StartDate AND @EndDate        
	 AND S.CANCELLED_FL = 'N'        
	 AND SD.CANCEL_FL = 'N'    
	 AND (@Store = -1 OR S.STORE = @Store)
	 AND (@ProductId = -1 OR SD.PRODUCT = @ProductId)
	 AND S.TRANSACTIONTYPE!=5   
   GROUP BY SD.PRODUCT, P.UNIT        
    
    
  SELECT SD.SALE, SD.TRANSACTION_DT, SD.STORE, SD.PRODUCT,S.TRANSACTION_TXT,        
         CASE WHEN PA.UNIT = 1 THEN SD.QUANTITY_QTY / 1000.0 ELSE SD.QUANTITY_QTY END QUANTITY_QTY,        
         PU.PACKAGE_QTY, SD.PRICE,        
         CASE WHEN PA.UNIT = 1 THEN PA.AVGQUANTITY / 1000.0 ELSE PA.AVGQUANTITY END AVGQUANTITY        
    INTO #WHOLESALE        
    FROM SLS_SALE S        
    JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE        
    JOIN #PRODUCTAVERAGE PA ON SD.PRODUCT = PA.PRODUCT        
    JOIN WHS_PRODUCTSHIPMENTUNIT PU ON SD.PRODUCT = PU.PRODUCT        
   WHERE S.TRANSACTION_DT BETWEEN  @StartDate AND @EndDate        
     AND S.CANCELLED_FL = 'N'        
     AND SD.CANCEL_FL = 'N'        
     AND SD.QUANTITY_QTY > PA.AVGQUANTITY*5        
     AND CASE WHEN PA.UNIT = 1 THEN SD.QUANTITY_QTY / 1000.0 ELSE SD.QUANTITY_QTY END >= PU.PACKAGE_QTY        
     AND S.TRANSACTIONTYPE!=5
	 AND (@Store = -1 OR S.STORE = @Store)
	 AND (@ProductId = -1 OR SD.PRODUCT = @ProductId)
       
  SELECT CAST(D.DATE_DT AS date) DATE_DT, ST.STOREID, ST.STORE_NM, P.PRODUCTID, P.NAME_NM PRODUCT_NM        
       , S.QUANTITY_QTY SALEQUANTITY, S.PACKAGE_QTY, S.AVGQUANTITY AVGQUANTITY, S.PRICE SALEAMOUNT        
       , S.TRANSACTION_TXT SALE_TXT       
    FROM #WHOLESALE S        
    JOIN PRD_PRODUCT P ON S.PRODUCT = P.PRODUCTID        
    JOIN STR_STORE ST ON S.STORE = ST.STOREID        
    JOIN RPT_DATE D ON S.TRANSACTION_DT = D.DATE_DT        
   ORDER BY S.PRICE DESC
    
END;