CREATE PROCEDURE SLS_LST_DAILYTURNOVER_SP @Date DATE = NULL AS 
BEGIN

	IF @Date IS NULL
	BEGIN
		SELECT @DATE = MAX(COALESCE(DATE_DT, TRANSACTION_DT))
		  FROM SLS_SALE 
		  LEFT JOIN (SELECT DATE_DT FROM RPT_REPORTDATE WHERE ReportName = 'DEFAULT') A ON 1=1
		 WHERE TRANSACTION_DT >= GETDATE() - 10
		   AND TRANSACTION_DT < GETDATE() - 0.5;	
	END;

	WITH CARDAMT AS (	
	SELECT STORE, ISNULL(CASH_AMT,0) CASH_AMT, ISNULL(CARD_AMT,0) CARD_AMT, ISNULL(BANK_AMT,0) BANK_AMT, COMPLETE_FL
	  FROM RCL_STORE
	 WHERE RECONCILIATION_DT = @DATE),
	ZET AS (
	SELECT STORE, SUM(RECEIPTTOTAL_AMT) RECEIPTTOTAL_AMT
		 , SUM(SLPTOTAL_AMT) SLPTOTAL_AMT, SUM(REFUND_AMT) REFUND_AMT 
		 , SUM(ISNULL(RECEIPTTOTAL_AMT,0) + ISNULL(SLPTOTAL_AMT, 0) - ISNULL(REFUND_AMT,0)) ZTOTAL
		 , SUM(ISNULL(RECEIPTTOTAL_AMT,0) - ISNULL(REFUND_AMT,0)) ZTOTALWOSLP
		 , SUM(RECEIPT_CNT + REFUND_CNT + SLP_CNT) RECEIPT_CNT
	  FROM SLS_SALEZET
	 WHERE TRANSACTION_DT = @DATE
	   AND DELETED_FL = 'N'
	 GROUP BY STORE),
	SALE AS (
	SELECT STORE, SUM(CASE WHEN S.CANCELLED_FL = 'N' THEN S.TOTAL_AMT ELSE 0 END) DAILYTOTAL
		 , SUM(CASE WHEN S.CANCELLED_FL = 'N' AND S.TRANSACTIONTYPE != 2 THEN S.TOTAL_AMT ELSE 0 END) DAILYTOTALWOSLP
		 , COUNT(*) RECEIPTCOUNT
	  FROM SLS_SALE S
	 WHERE TRANSACTION_DT = @DATE
	 GROUP BY STORE)
	SELECT ROW_NUMBER() OVER (ORDER BY SELECTEDDAILYTOTAL DESC) ROWNO
		 , STOREID, STORE_NM, CASE WHEN ISNULL(COMPLETE_FL,'N') = 'Y' THEN 'OK' ELSE NULL END RCLSTATUS
		 , TRANSACTION_DT, SELECTEDDAILYTOTAL
		 , SELECTEDDAILYTOTAL - ISNULL(CARD_AMT,0) CASH_AMT
		 , CARD_AMT, SLPTOTAL_AMT, REFUND_AMT, RECEIPT_CNT
		 , SELECTEDDAILYTOTAL - ISNULL(CARD_AMT,0) + SLPTOTAL_AMT LOOMIS_AMT
		 , BANK_AMT,  SELECTEDDAILYTOTAL+SLPTOTAL_AMT TOTAL_AMT
	  FROM (
	SELECT STOREID, STORE_NM, @DATE TRANSACTION_DT
		 , CASE WHEN ISNULL(ZTOTALWOSLP,0) > ISNULL(DAILYTOTALWOSLP,0) THEN ZTOTALWOSLP ELSE ISNULL(DAILYTOTALWOSLP,0) END SELECTEDDAILYTOTAL
		 , CASE WHEN ROUND(ISNULL(ZTOTAL,0) - ISNULL(DAILYTOTAL,0),0) = 0 THEN 1 ELSE 0 END ZBALANCE
		 , B.CARD_AMT, B.BANK_AMT, Z.SLPTOTAL_AMT, Z.REFUND_AMT
		 , CASE WHEN ISNULL(ZTOTAL,0) > ISNULL(DAILYTOTAL,0) THEN RECEIPT_CNT ELSE RECEIPTCOUNT END RECEIPT_CNT
		 , ZTOTAL, ZTOTALWOSLP, DAILYTOTAL, DAILYTOTALWOSLP, COMPLETE_FL
	  FROM STR_STORE_VW ST
	  LEFT JOIN SALE S ON ST.STOREID = S.STORE
	  LEFT JOIN CARDAMT B ON ST.STOREID = B.STORE
	  LEFT JOIN ZET Z ON ST.STOREID = Z.STORE ) B
	 ORDER BY 1

END