CREATE PROCEDURE SLS_LST_REGIONTURNOVER_SP AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#TY', 'U') IS NOT NULL  DROP TABLE #TY
	IF OBJECT_ID('tempdb.dbo.#LY', 'U') IS NOT NULL  DROP TABLE #LY

	DECLARE @today DATE = CAST(GETDATE() AS DATE)
	SELECT S.STORE, SUM(S.TOTAL_AMT) CY_TURNOVER, SUM(CASE WHEN D2.YEARMONTH_NO = D.YEARMONTH_NO THEN TOTAL_AMT ELSE 0 END) CM_TURNOVER
	  INTO #TY
	  FROM SLS_SALE S
	  JOIN RPT_DATE D ON S.TRANSACTION_DT = D.DATE_DT
	  JOIN RPT_DATE D2 ON D2.DATE_DT = @today AND D2.YEAR_NO = D.YEAR_NO
	 WHERE S.CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	   AND D.DATE_DT < @today
	 GROUP BY S.STORE

	DECLARE @lastyear DATE = DATEADD(YEAR, -1, CAST(GETDATE() AS DATE))
	SELECT S.STORE, SUM(S.TOTAL_AMT) LY_TURNOVER, SUM(CASE WHEN D2.YEARMONTH_NO = D.YEARMONTH_NO THEN TOTAL_AMT ELSE 0 END) LM_TURNOVER
	  INTO #LY
	  FROM SLS_SALE S
	  JOIN RPT_DATE D ON S.TRANSACTION_DT = D.DATE_DT
	  JOIN RPT_DATE D2 ON D2.DATE_DT = @lastyear AND D2.YEAR_NO = D.YEAR_NO
	 WHERE S.CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	   AND D.DATE_DT < @lastyear
	 GROUP BY S.STORE

	SELECT *
		, (CM_TURNOVER / LM_TURNOVER) - 1 CM_GROWTH
		, (CM_LFLTURNOVER / LM_TURNOVER) - 1 CM_LFLGROWTH
		, (CY_TURNOVER / LY_TURNOVER) - 1 CY_GROWTH
		, (CY_LFLTURNOVER / LY_TURNOVER) - 1 CY_LFLGROWTH
	  FROM (
	SELECT B.BRANCH_NM, RM.MANAGER_NM
		 , SUM (CASE WHEN ISNULL(TY.CM_TURNOVER,0) > 0 THEN 1 ELSE 0 END) CM_STORECOUNT
		 , SUM (CASE WHEN ISNULL(TY.CM_TURNOVER,0) > 0 AND ISNULL(LY.LM_TURNOVER,0) > 0 THEN 1 ELSE 0 END) CM_LFLSTORECOUNT
		 , SUM (TY.CM_TURNOVER) CM_TURNOVER
		 , SUM (CASE WHEN ISNULL(LY.LM_TURNOVER,0) > 0 THEN TY.CM_TURNOVER ELSE 0 END) CM_LFLTURNOVER
		 , SUM (LY.LM_TURNOVER) LM_TURNOVER
		 -- , SUM (CASE WHEN ISNULL(TY.CY_TURNOVER,0) > 0 THEN 1 ELSE 0 END) CY_STORECOUNT
		 , SUM (TY.CY_TURNOVER) CY_TURNOVER
		 , SUM (CASE WHEN ISNULL(LY.LM_TURNOVER,0) > 0 THEN TY.CY_TURNOVER ELSE 0 END) CY_LFLTURNOVER
		 , SUM (LY.LY_TURNOVER) LY_TURNOVER
	  FROM STR_STORE ST
	  LEFT JOIN STR_REGIONMANAGERS RM ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
	  LEFT JOIN SEC_USER U ON RM.USERID = U.USERID
	  LEFT JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
	  LEFT JOIN #TY TY ON ST.STOREID = TY.STORE
	  LEFT JOIN #LY LY ON ST.STOREID = LY.STORE
	 WHERE ST.DELETED_FL = 'N'
	   AND ST.ACTIVE_FL = 'Y'
	 GROUP BY B.BRANCH_NM, RM.MANAGER_NM) A
	 ORDER BY 1

END