CREATE PROCEDURE [dbo].[SLS_LST_CANCELLEDROWREPORT_SP] @Store INT = -1,	@StartDate DATE = NULL,  @EndDate DATE = NULL WITH RECOMPILE AS      
BEGIN        

	IF @StartDate IS NULL
	BEGIN
		DECLARE @Time TIME = CAST(GETDATE() AS TIME);
		IF @Time < '09:30'
		BEGIN
			SET @StartDate = GETDATE() - 1
			SET @EndDate = GETDATE() - 1
		END      
		ELSE          
		BEGIN
			SET @StartDate = GETDATE()
			SET @EndDate = GETDATE()
		END;
	END
	ELSE IF @EndDate IS NULL
	BEGIN
		SET @EndDate = @StartDate
	END;
      
	IF @Store > 0
	BEGIN
		SELECT SD.SALEDETAILID,
			   SD.SALE,
			   S.TRANSACTION_TM,
			   SD.STORE,
			   ST.STORE_NM,
			   S.CASHREGISTER,
			   P.CODE_NM,
			   P.NAME_NM,
			   S.CASHIER_NM,
			   SD.PRICE,
			   S.TOTAL_AMT,
			   CR.CASHIER_NM CASHIERNAME_TXT,
			   CR.REASON_TXT
		  FROM SLS_SALEDETAIL SD (NOLOCK)
		  JOIN SLS_SALE S (NOLOCK) ON SD.SALE = S.SALEID
		  JOIN dbo.STR_GETUSERSTORES_FN() ST ON S.STORE = ST.STOREID
		  JOIN PRD_PRODUCT P (NOLOCK) ON SD.PRODUCT = P.PRODUCTID
		  LEFT JOIN SLS_CANCELREASON CR (NOLOCK) ON SD.SALEDETAILID = CR.SALEDETAIL
		 WHERE SD.TRANSACTION_DT >= @StartDate
		   AND SD.TRANSACTION_DT <= @EndDate
		   AND SD.CANCEL_FL = 'Y'
		   AND SD.STORE = @Store
	END
	ELSE
	BEGIN
		SELECT SD.SALEDETAILID,
			   SD.SALE,
			   S.TRANSACTION_TM,
			   SD.STORE,
			   ST.STORE_NM,
			   S.CASHREGISTER,
			   P.CODE_NM,
			   P.NAME_NM,
			   S.CASHIER_NM,
			   SD.PRICE,
			   S.TOTAL_AMT,
			   CR.CASHIER_NM CASHIERNAME_TXT,
			   CR.REASON_TXT
		  FROM SLS_SALEDETAIL SD (NOLOCK)
		  JOIN SLS_SALE S (NOLOCK) ON SD.SALE = S.SALEID
		  JOIN dbo.STR_GETUSERSTORES_FN() ST ON S.STORE = ST.STOREID
		  JOIN PRD_PRODUCT P (NOLOCK) ON SD.PRODUCT = P.PRODUCTID
		  LEFT JOIN SLS_CANCELREASON CR (NOLOCK) ON SD.SALEDETAILID = CR.SALEDETAIL
		 WHERE SD.TRANSACTION_DT >= @StartDate
		   AND SD.TRANSACTION_DT <= @EndDate
		   AND SD.CANCEL_FL = 'Y'
	END

END