CREATE PROCEDURE SLS_LST_CANCELREASON_SP @StoreRecId BIGINT AS
BEGIN

	SELECT C.CANCELREASONID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           RS.STORERECID STOREREC,
           SD.SALEDETAILID SALEDETAIL,
           C.REASON_TXT,
           C.CASHIER_NM,
		   S.TRANSACTION_TM SALETRANSACTION_TM,
		   S.CASHREGISTER SALECASHREGISTER,
		   P.CODE_NM PRODUCTCODE_NM,
		   P.NAME_NM PRODUCT_NM,
		   SD.PRICE 
	  FROM RCL_STORE RS
	  JOIN SLS_SALE S ON S.TRANSACTION_DT = RS.RECONCILIATION_DT AND RS.STORE = S.STORE
	  JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE
	  JOIN PRD_PRODUCT P ON SD.PRODUCT = P.PRODUCTID
	  LEFT JOIN SLS_CANCELREASON C ON SD.SALEDETAILID = C.SALEDETAIL
	 WHERE RS.STORERECID = @StoreRecId
	   AND SD.CANCEL_FL = 'Y'
	   AND SD.PRICE != 0 
	 
	 UNION ALL

	SELECT C.CANCELREASONID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           RS.STORERECID STOREREC,
           S.SALEID SALEDETAIL,
           C.REASON_TXT,
           C.CASHIER_NM,
		   S.TRANSACTION_TM SALETRANSACTION_TM,
		   S.CASHREGISTER SALECASHREGISTER,
		   ' ' PRODUCTCODE_NM,
		   'Fiş İptal' PRODUCT_NM,
		   S.TOTAL_AMT PRICE 
	  FROM RCL_STORE RS
	  JOIN SLS_SALE S ON S.TRANSACTION_DT = RS.RECONCILIATION_DT AND RS.STORE = S.STORE
	  LEFT JOIN SLS_CANCELREASON C ON S.SALEID = C.SALEDETAIL
	 WHERE RS.STORERECID = @StoreRecId
	   AND S.CANCELLED_FL = 'Y' 
	   AND S.TOTAL_AMT != 0 

	 ORDER BY S.TRANSACTION_TM

	

END;