CREATE PROCEDURE SLS_LST_STOCKOUTSUMMARY_SP @StartDate DATE, @EndDate DATE, @StoreCountSold INT, @CategoryId INT = -1 AS
BEGIN
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();


  WITH PRICES AS
  (SELECT PRODUCT, PRICE_AMT FROM PRC_PRODUCT WHERE PACKAGE = 1)
  SELECT S.STOREID, S.STORE_NM, COUNT(*) DAYPRODUCT_CNT, COUNT(DISTINCT S.PRODUCTID) PRODUCT_CNT, COUNT(DISTINCT TRANSACTIONDATE) DAY_CNT
	   , SUM(S.DAILYSTORE_AVG * PP.PRICE_AMT) TOTAL_AMT
	FROM SLS_STOCKOUT_SYN S (NOLOCK)
	JOIN #stores ST ON S.STOREID = ST.STOREID
	JOIN PRICES PP ON S.PRODUCTID = PP.PRODUCT
	LEFT JOIN PRD_PRODUCT P (NOLOCK) ON S.PRODUCTID = P.PRODUCTID
	LEFT JOIN PRD_SUBGROUP SG (NOLOCK) ON P.SUBGROUP = SG.SUBGROUPID
   WHERE TRANSACTIONDATE BETWEEN @StartDate AND @EndDate
	 AND STORE_CNT > @StoreCountSold
	 AND @StartDate > ST.OPENING_DT
	 AND (@CategoryId = -1 OR SG.CATEGORY = @CategoryId)
   GROUP BY S.STOREID, S.STORE_NM
   ORDER BY 3 DESC
END