CREATE PROCEDURE SLS_UPD_SALECOST_SP AS  
BEGIN  
  
    IF OBJECT_ID('tempdb..#COST') IS NOT NULL DROP TABLE #COST  
    DECLARE @startdate DATE = CAST(GETDATE() - 60 AS DATE)  
  
  
    SELECT STORE, TRANSACTION_DT, PRODUCT, SUM(SALE) SALE, SUM(ISNULL(COST, SALE)) COST, SUM(QUANTITY_QTY) QUANTITY
      INTO #COST  
      FROM (  
    SELECT SD.STORE, SD.TRANSACTION_DT, SD.PRODUCT, SD.PRICE SALEVAT, SD.VAT_RT,  
           CASE WHEN S.TRANSACTIONTYPE != 5 THEN 1.0 ELSE -1.0 END * CASE WHEN UNIT = 1 THEN SD.QUANTITY_QTY / 1000.0 ELSE SD.QUANTITY_QTY END QUANTITY_QTY, 
           SD.PRICE * 100.0 / (100.0 + SD.VAT_RT) SALE, 
           C.WEIGHTEDPURCHASE_AMT * CASE WHEN S.TRANSACTIONTYPE != 5 THEN 1.0 ELSE -1.0 END * CASE WHEN UNIT = 1 THEN SD.QUANTITY_QTY / 1000.0 ELSE SD.QUANTITY_QTY END COST  
      FROM SLS_SALEDETAIL SD (NOLOCK)  
      JOIN SLS_SALE S (NOLOCK) ON SD.SALE = S.SALEID  
      LEFT JOIN PRD_COGS C (NOLOCK) ON SD.PRODUCT = C.PRODUCT AND SD.TRANSACTION_DT BETWEEN C.START_DT AND C.END_DT  
     WHERE S.CANCELLED_FL = 'N'  
       AND SD.CANCEL_FL = 'N'  
       AND SD.TRANSACTION_DT >= @startdate ) A  
     GROUP BY STORE, TRANSACTION_DT, PRODUCT  
  
    DELETE A   
    -- SELECT A.*  
      FROM SLS_COST_SYN A  
      LEFT JOIN #COST B ON A.STORE = B.STORE AND A.TRANSACTION_DT = B.TRANSACTION_DT AND A.PRODUCT = B.PRODUCT  
     WHERE A.TRANSACTION_DT >= @startdate  
       AND B.SALE IS NULL  
  
    UPDATE A  
       SET A.COST = B.COST, A.SALE = B.SALE, A.QUANTITY = B.QUANTITY  
    -- SELECT *  
      FROM SLS_COST_SYN A  
      JOIN #COST B ON A.STORE = B.STORE AND A.TRANSACTION_DT = B.TRANSACTION_DT AND A.PRODUCT = B.PRODUCT  
     WHERE ISNULL(A.SALE,0) != ISNULL(B.SALE,0) OR ISNULL(A.COST,0) != ISNULL(B.COST,0) OR ISNULL(A.QUANTITY,0) != ISNULL(B.QUANTITY,0)
  
    INSERT INTO SLS_COST_SYN (STORE, TRANSACTION_DT, PRODUCT, SALE, COST, QUANTITY)  
    SELECT B.*  
      FROM SLS_COST_SYN A  
      RIGHT JOIN #COST B ON A.STORE = B.STORE AND A.TRANSACTION_DT = B.TRANSACTION_DT AND A.PRODUCT = B.PRODUCT  
     WHERE A.SALE IS NULL  
  
END