CREATE PROCEDURE SLS_LST_STORECANCELRATE_SP @StartDate DATE, @EndDate DATE AS      
BEGIN      
  
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;  
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();  
  
  WITH SALES AS      
  (SELECT STORE, SUM(TOTAL_AMT) TOTAL      
     FROM SLS_SALE S (NOLOCK)      
     JOIN RPT_DATE D ON S.TRANSACTION_DT = D.DATE_DT      
    WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate       
      AND CANCELLED_FL = 'N'      
    GROUP BY STORE),      
   CANCELS AS       
   (SELECT STORE, SUM(PRICE) PRICE       
      FROM SLS_CANCELLEDPRODUCTS_SYN S      
     WHERE S.OMITREASON = 0      
       AND S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate       
     GROUP BY STORE)      
  SELECT ST.STORE_NM, C.*, S.TOTAL, C.PRICE * 1000.0 / S.TOTAL CANCELRATE_PCT      
    FROM CANCELS C      
    JOIN #stores ST ON C.STORE = ST.STOREID      
    JOIN SALES S ON C.STORE = S.STORE       
   ORDER BY CANCELRATE_PCT DESC      

END;