CREATE PROCEDURE SLS_LST_REFUND_SP @StoreId INT, @ProductId INT AS
BEGIN

  DECLARE @startDate DATE = CAST(GETDATE() - 30 AS date)
  
  SELECT SD.SALEDETAILID, S.TRANSACTION_DT, S.TRANSACTION_TM, S.TRANSACTION_TXT, SD.UNIT, SD.QUANTITY_QTY, SD.PRICE, 
  	     'Tarih : '+CONVERT(VARCHAR(20), TRANSACTION_TM, 120) + ' Miktar : '+ CAST(QUANTITY_QTY AS varchar(20)) + ' Tutar : '+CAST(ABS(PRICE) AS varchar(20)) TRAN_DSC
    FROM SLS_SALE S (NOLOCK)
    JOIN SLS_SALEDETAIL SD (NOLOCK) ON S.SALEID = SD.SALE AND S.STORE = SD.STORE AND S.TRANSACTION_DT = SD.TRANSACTION_DT
	LEFT JOIN WHS_PRODUCTRETURN PR ON SD.SALEDETAILID = PR.SALEDETAIL
   WHERE S.STORE = @StoreId
     AND S.TRANSACTION_DT >= @startDate 
     AND S.TRANSACTIONTYPE = 5
     AND SD.PRODUCT = @ProductId
	 AND PR.SALEDETAIL IS NULL
   ORDER BY TRANSACTION_TM DESC

END