CREATE PROCEDURE SLS_DEL_SALEDATE_SP @StoreId INT, @Date DATE, @PosId INT = -1 AS
BEGIN
  DELETE SP
    FROM SLS_SALEPAYMENT SP
    JOIN SLS_SALE S ON SP.SALE = S.SALEID 
   WHERE S.STORE = @StoreId AND S.TRANSACTION_DT = @Date AND (@PosId = -1 OR S.CASHREGISTER = @PosId)

  DELETE SD
    FROM SLS_SALEDETAIL SD
    JOIN SLS_SALE S ON SD.SALE = S.SALEID 
   WHERE S.STORE = @StoreId AND S.TRANSACTION_DT = @Date AND (@PosId = -1 OR S.CASHREGISTER = @PosId)

  DELETE SR
    FROM SLS_SALERAW SR
    JOIN SLS_SALE S ON SR.SALE = S.SALEID 
   WHERE S.STORE = @StoreId AND S.TRANSACTION_DT = @Date AND (@PosId = -1 OR S.CASHREGISTER = @PosId)

  DELETE S
    FROM SLS_SALE S 
   WHERE S.STORE = @StoreId AND S.TRANSACTION_DT = @Date AND (@PosId = -1 OR S.CASHREGISTER = @PosId)
END
