CREATE PROCEDURE SLS_RPT_SALEVAT_SP @StartDate DATE, @EndDate DATE AS
BEGIN
	SELECT STOREID, STORE_NM, EXPENSECENTERCODE_TXT, DAY_CNT, 
		   SALENOVAT_AMT, SALE_AMT - SALENOVAT_AMT VAT_AMT, SALE_AMT,
		   REFUNDNOVAT_AMT, REFUND_AMT - REFUNDNOVAT_AMT REFUNDVAT_AMT, REFUND_AMT
	  FROM (
	SELECT ST.STOREID, ST.STORE_NM, ISNULL(EXPENSECENTERCODE_TXT, CAST(20100000 + ST.STOREID AS VARCHAR)) EXPENSECENTERCODE_TXT
		 , COUNT(DISTINCT DT.DATE_DT) DAY_CNT
		 , SUM((SALE_AMT) * 100.0 / (100.0 + P.SALEVAT_RT)) SALENOVAT_AMT
		 , SUM(SALE_AMT) SALE_AMT
		 , SUM((-1*REFUND_AMT) * 100.0 / (100.0 + P.SALEVAT_RT)) REFUNDNOVAT_AMT
		 , SUM(-1*REFUND_AMT) REFUND_AMT
	  FROM SLS_PRODUCTSUMMARY_SYN PS
	  JOIN STR_STORE ST ON PS.STORE = ST.STOREID
	  JOIN RPT_DATE DT ON PS.TRANSACTION_DT = DT.DATE_DT
	  JOIN PRD_PRODUCT P ON PS.PRODUCT = P.PRODUCTID
	  LEFT JOIN ACC_EXPENSECENTER EC ON EC.STORE = ST.STOREID AND EC.CENTERGROUP_NO = 3
	 WHERE DT.DATE_DT BETWEEN @StartDate AND @EndDate
	 GROUP BY ST.STOREID, ST.STORE_NM, EXPENSECENTERCODE_TXT) A
END