CREATE PROCEDURE [dbo].[SLS_LST_DASHBOARDSTORECOUNT_SP] AS

BEGIN

	DECLARE @StartDate DATE = CAST(GETDATE()-7 AS DATE)
	-- DECLARE @Now DATE = CAST(GETDATE() AS DATE)

	SELECT CONVERT(VARCHAR(20),TRANSACTION_DT,104) TRANSACTION_DATE, COUNT(DISTINCT STORE) STORECOUNT
	  FROM SLS_SALE (NOLOCK)
	  JOIN STR_STORE (NOLOCK) ON STORE = STOREID
	 WHERE TRANSACTION_DT > @StartDate 
	   AND (ACTIVE_FL = 'Y' OR TRANSACTION_DT BETWEEN OPENING_DT AND CLOSING_DT) 
	 GROUP BY TRANSACTION_DT
	 ORDER BY TRANSACTION_DT 

END
