CREATE PROCEDURE SLS_LST_REGIONMANAGERPERF_SP AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores

	SELECT * INTO #stores FROM dbo.STR_GETUSERSTORES_FN();

	DECLARE @currentDate DATE = dbo.STR_GETUSERCURRENTDATE_FN();

	WITH RM AS (
	SELECT DISTINCT REGIONMANAGERSID, RM.MANAGER_NM
	  FROM STR_REGIONMANAGERS RM
	  JOIN #stores ST ON ST.REGIONMANAGER = RM.REGIONMANAGERSID)
	SELECT *
	  FROM (
	SELECT MANAGER_NM, STORE_CNT
		 , DAILYSALE_AMT, LASTWEEKSALE_AMT, CASE WHEN LASTWEEKSALE_AMT != 0 THEN (DAILYSALE_AMT - LASTWEEKSALE_AMT) * 1.0 / LASTWEEKSALE_AMT ELSE 0 END DAILY_PCT
		 , WEEKLYSALE_AMT, PREVWEEKSALE_AMT, CASE WHEN PREVWEEKSALE_AMT != 0 THEN (WEEKLYSALE_AMT - PREVWEEKSALE_AMT) * 1.0 / PREVWEEKSALE_AMT ELSE 0 END WEEKLY_PCT
		 , MONTHLYSALE_AMT, PREVMONTHSALE_AMT, CASE WHEN PREVMONTHSALE_AMT != 0 THEN (MONTHLYSALE_AMT - PREVMONTHSALE_AMT) * 1.0 / PREVMONTHSALE_AMT ELSE 0 END MONTHLY_PCT
		 , ROW_NUMBER() OVER (ORDER BY DAILYSALE_AMT DESC) DAILYRANK
		 , ROW_NUMBER() OVER (ORDER BY WEEKLYSALE_AMT DESC) WEEKLYRANK
		 , ROW_NUMBER() OVER (ORDER BY MONTHLYSALE_AMT DESC) MONTHLYRANK
	  FROM (
	SELECT MANAGER_NM, COUNT(ST.STORE_NM) STORE_CNT,
		   SUM(ISNULL(DAILYSALE_AMT,0) - ISNULL(DAILYREFUND_AMT,0)) DAILYSALE_AMT, 
		   SUM(ISNULL(LASTWEEKSALE_AMT,0) - ISNULL(LASTWEEKREFUND_AMT,0)) LASTWEEKSALE_AMT, 
		   SUM(ISNULL(WEEKLYSALE_AMT,0) - ISNULL(WEEKLYREFUND_AMT,0)) WEEKLYSALE_AMT, 
		   SUM(ISNULL(PREVWEEKSALE_AMT,0) - ISNULL(PREVWEEKREFUND_AMT,0)) PREVWEEKSALE_AMT, 
		   SUM(ISNULL(MONTHLYSALE_AMT,0) - ISNULL(MONTHLYREFUND_AMT,0)) MONTHLYSALE_AMT, 
		   SUM(ISNULL(PREVMONTHSALE_AMT,0) - ISNULL(PREVMONTHREFUND_AMT,0)) PREVMONTHSALE_AMT
	  FROM SLS_SALEDASHBOARD S
	  JOIN STR_STORE ST ON S.STORE = ST.STOREID
	  JOIN STR_REGIONMANAGERS RM ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
	 WHERE ST.ACTIVE_FL = 'Y'
	   AND S.TODAY_DT = @currentDate
	 GROUP BY MANAGER_NM) A ) B
	 JOIN RM ON B.MANAGER_NM = RM.MANAGER_NM
	 ORDER BY 3 DESC

END