CREATE PROCEDURE SLS_RPT_TTYPESALES_SP @StartDate DATE, @EndDate DATE, @StoreId INT = -1, @TransactionType INT WITH RECOMPILE AS
BEGIN
	SELECT CAST(S.SALEID AS VARCHAR) SALEID, CAST(SD.SALEDETAILID AS VARCHAR) SALEDETAILID, 
		   ST.STOREID, ST.STORE_NM, S.TRANSACTION_DT, S.TOTAL_AMT, P.CODE_NM, P.NAME_NM, SD.PRICE, 
		   SD.QUANTITY_QTY, CASE WHEN P.UNIT = 1 THEN 'KG' ELSE 'ADET' END UNIT_NM, SD.VAT_RT
	  FROM SLS_SALE S
	  JOIN SLS_SALEDETAIL SD ON S.SALEID = SD.SALE
	  JOIN STR_STORE ST ON S.STORE = ST.STOREID
	  JOIN PRD_PRODUCT P ON SD.PRODUCT = P.PRODUCTID
	 WHERE SD.TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND (@StoreId = -1 OR SD.STORE = @StoreId)
	   AND SD.CANCEL_FL = 'N'
	   AND S.CANCELLED_FL = 'N'
	   AND SD.DELETED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	   AND S.TRANSACTIONTYPE = @TransactionType
END