CREATE PROCEDURE [dbo].[SLS_LST_CANCELLEDSALESREPORT_SP]
    @Store INT = -1,
	@StartDate DATE = NULL,
    @EndDate DATE = NULL AS             
BEGIN
	IF @StartDate IS NULL
	BEGIN
		DECLARE @Time TIME = CAST(GETDATE() AS TIME);
		IF @Time < '09:30'
		BEGIN
			SET @StartDate = GETDATE() - 1
			SET @EndDate = GETDATE() - 1
		END      
		ELSE          
		BEGIN
			SET @StartDate = GETDATE()
			SET @EndDate = GETDATE()
		END;
	END
    
 
	IF @Store > 0
	BEGIN
		SELECT	S.SALEID,
				S.TRANSACTION_TM,
				S.STORE,
				ST.STORE_NM,
				CR.CASHIER_NM,
				S.CASHREGISTER,
				S.TOTAL_AMT,
				CR.REASON_TXT
		  FROM	SLS_SALE S (NOLOCK)
		  JOIN	dbo.STR_GETUSERSTORES_FN() ST ON S.STORE = ST.STOREID
		  LEFT JOIN SLS_CANCELREASON CR (NOLOCK) ON S.SALEID = CR.SALEDETAIL
		 WHERE	S.TRANSACTION_DT >= @StartDate
		   AND	S.TRANSACTION_DT <= @EndDate
		   AND	S.CANCELLED_FL = 'Y'
		   AND	S.STORE = @Store
	END
	ELSE
	BEGIN    
		SELECT	S.SALEID,
				S.TRANSACTION_TM,
				S.STORE,
				ST.STORE_NM,
				CR.CASHIER_NM,
				S.CASHREGISTER,
				S.TOTAL_AMT,
				CR.REASON_TXT
		  FROM	SLS_SALE S (NOLOCK)
		  JOIN	dbo.STR_GETUSERSTORES_FN() ST ON S.STORE = ST.STOREID
		  LEFT JOIN SLS_CANCELREASON CR (NOLOCK) ON S.SALEID = CR.SALEDETAIL
		 WHERE	S.TRANSACTION_DT >= @StartDate
		   AND	S.TRANSACTION_DT <= @EndDate
		   AND	S.CANCELLED_FL = 'Y'
	END
END