CREATE PROCEDURE SLS_DEL_UNBALANCED_SP AS  
BEGIN  
  
  DECLARE @StartDate DATE = CAST(GETDATE()-15 AS DATE)  
  DECLARE @EndDate DATE = CAST(GETDATE()-1 AS DATE)  
    
  IF OBJECT_ID('tempdb.dbo.#del', 'U') IS NOT NULL DROP TABLE #del;  
  SELECT S.SALEID, S.TRANSACTION_TXT, S.TOTAL_AMT, ISNULL(SUM(SD.PRICE),0) DETAIL_AMT  
    INTO #del  
    FROM SLS_SALE S (NOLOCK)  
    LEFT JOIN SLS_SALEDETAIL SD (NOLOCK) ON S.SALEID = SD.SALE AND SD.TRANSACTION_DT = S.TRANSACTION_DT AND SD.STORE = S.STORE AND SD.CANCEL_FL = 'N'  
   WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate  
     AND S.CANCELLED_FL = 'N'  
   GROUP BY S.SALEID, S.TRANSACTION_TXT, S.TOTAL_AMT  
  HAVING S.TOTAL_AMT != ISNULL(SUM(SD.PRICE),0)  
    
  DELETE SR FROM SLS_SALERAW SR JOIN #del D ON SR.SALE = D.SALEID   
  DELETE SD FROM SLS_SALEDETAIL SD JOIN #del D ON SD.SALE = D.SALEID   
  DELETE SP FROM SLS_SALEPAYMENT SP JOIN #del D ON SP.SALE = D.SALEID   
  DELETE S FROM SLS_SALE S JOIN #del D ON S.SALEID = D.SALEID   
  
END;