CREATE PROCEDURE SLS_LST_STOCKOUTPRODUCTS_SP @StartDate DATE, @EndDate DATE, @StoreCountSold INT, @StoreId INT = -1, @CategoryId INT = -1  AS
BEGIN

  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();

  WITH PRICES AS
  (SELECT PRODUCT, PRICE_AMT FROM PRC_PRODUCT WHERE PACKAGE = 1)
  SELECT ROW_NUMBER() OVER(PARTITION BY 1 ORDER BY STORE_CNT DESC) ROWNO, S.*, S.DAILYSTORE_AVG * PP.PRICE_AMT TOTAL_AMT
    FROM SLS_STOCKOUT_SYN S (NOLOCK)
	JOIN #stores ST ON S.STOREID = ST.STOREID
	JOIN PRICES PP ON S.PRODUCTID = PP.PRODUCT
	LEFT JOIN PRD_PRODUCT P (NOLOCK) ON S.PRODUCTID = P.PRODUCTID
	LEFT JOIN PRD_SUBGROUP SG (NOLOCK) ON P.SUBGROUP = SG.SUBGROUPID
   WHERE TRANSACTIONDATE BETWEEN @StartDate AND @EndDate
     AND STORE_CNT > @StoreCountSold
	 AND (@StoreId = -1 OR S.STOREID = @StoreId)
	 AND (@CategoryId = -1 OR SG.CATEGORY = @CategoryId)
   ORDER BY STORE_CNT DESC
END