CREATE PROCEDURE [dbo].[SLS_LST_MISSINGSALESTORE_SP] AS
BEGIN

	DECLARE @StartDate DATE = CAST(GETDATE()-7 AS DATE)
	DECLARE @Now DATE = CAST(GETDATE() AS DATE)

	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;     
	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();

	SELECT STOREID, STORE_NM, TERMINAL
		 , SUM(CASE WHEN DATE_DT = @Now THEN 1 ELSE 0 END) TODAY
		 , COUNT(*) LAST7DAYS
	  FROM (
	SELECT ST.STOREID, ST.STORE_NM, ST.TERMINAL, DT.DATE_DT
	  FROM STR_STORE_VW ST
	  JOIN #STORES S ON ST.STOREID = S.STOREID
	  JOIN RPT_DATE DT ON DT.DATE_DT > @StartDate AND DT.DATE_DT <= @now
	  LEFT JOIN (SELECT DISTINCT STORE, TRANSACTION_DT FROM SLS_SALE(NOLOCK) WHERE TRANSACTION_DT > @StartDate AND TRANSACTION_DT <= @now) SALE 
	    ON ST.STOREID = SALE.STORE AND DT.DATE_DT = SALE.TRANSACTION_DT
	 WHERE SALE.STORE IS NULL
	   AND DT.DATE_DT >= ISNULL(ST.OPENING_DT,'2019-01-01')) A
	 GROUP BY STOREID, STORE_NM, TERMINAL
	 ORDER BY 5 DESC

END
