CREATE PROCEDURE [dbo].[SLS_LST_UNBALANCEDTRANSACTION_SP]
 @StartDate DATE = NULL,
 @EndDate DATE = NULL
AS
BEGIN
   IF @StartDate IS NULL
   BEGIN
     Set @StartDate = CAST(GETDATE() AS DATE)
     Set @EndDate = CAST(GETDATE() AS DATE)
   END
   ELSE IF @EndDate IS NULL
   BEGIN
     Set @EndDate = @StartDate
   END

   SELECT ST.STOREID, ST.STORE_NM, S.TRANSACTION_DT, S.SALEID, S.TRANSACTION_TXT, S.TOTAL_AMT, ISNULL(SUM(SD.PRICE),0) DETAIL_AMT
     FROM SLS_SALE S (NOLOCK)
     JOIN STR_STORE ST (NOLOCK) ON S.STORE = ST.STOREID
     LEFT JOIN SLS_SALEDETAIL SD (NOLOCK) ON S.SALEID = SD.SALE AND SD.TRANSACTION_DT = S.TRANSACTION_DT AND SD.STORE = S.STORE AND SD.CANCEL_FL = 'N'
    WHERE S.TRANSACTION_DT BETWEEN @StartDate AND @EndDate
      AND S.CANCELLED_FL = 'N'
    GROUP BY S.SALEID, S.TRANSACTION_TXT, S.TOTAL_AMT, ST.STOREID, ST.STORE_NM, S.TRANSACTION_DT 
   HAVING S.TOTAL_AMT != ISNULL(SUM(SD.PRICE),0)

END