-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [FIN_ESTATELANDLORD]
(
    /*Section="Columns"*/
    [ESTATERENT]    INT NOT NULL,
    [LANDLORD]      INT NOT NULL,
    [CREATE_DT]     DATETIME NOT NULL,
    [CREATEUSER]    INT NOT NULL,
    [CREATECHANNEL] INT NOT NULL,
    [CREATEBRANCH]  INT NOT NULL,
    [CREATESCREEN]  INT NOT NULL,
    [OWNERSHIP_RT]  NUMERIC(5,2) NULL,
    [PAYMENT_RT]    NUMERIC(5,2) NULL,
    [IBAN_TXT]      VARCHAR(50) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [FIN_ESTATELANDLORD_PK] PRIMARY KEY ([ESTATERENT],[LANDLORD]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [FIN_ESTATELANDLORD_F01] FOREIGN KEY ([ESTATERENT]) REFERENCES [FIN_ESTATERENT]([ESTATERENTID]),
    CONSTRAINT [FIN_ESTATELANDLORD_F02] FOREIGN KEY ([LANDLORD]) REFERENCES [FIN_LANDLORD]([LANDLORDID]),
    CONSTRAINT [FIN_ESTATELANDLORD_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [FIN_ESTATELANDLORD_F04] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [FIN_ESTATELANDLORD_F05] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [FIN_ESTATELANDLORD_F06] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Estate Landlord: relation table for FIN_ESTATE & FIN_LANDLORD',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'FIN_ESTATELANDLORD',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Estate Rent: Estate Rent' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'ESTATERENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Landlord: FIN_LANDLORD' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'LANDLORD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Creation date of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creation branch of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Creation screen of the user.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Ownership Rate: share rate in the ownership of the estate' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'OWNERSHIP_RT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Payment Rate: Rent payment rate' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'PAYMENT_RT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'IBAN: bank account numer (iban)' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATELANDLORD',
    @level2type=N'COLUMN',
    @level2name=N'IBAN_TXT'
GO

/*Section="End"*/
