-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [FIN_ESTATERENTPERIOD]
(
    /*Section="Columns"*/
    [ESTATERENTPERIODID]       INT NOT NULL IDENTITY,
    [ORGANIZATION]             INT NOT NULL,
    [DELETED_FL]               VARCHAR NOT NULL,
    [CREATE_DT]                DATETIME NOT NULL,
    [UPDATE_DT]                DATETIME NULL,
    [CREATEUSER]               INT NOT NULL,
    [UPDATEUSER]               INT NULL,
    [ESTATERENT]               INT NOT NULL,
    [PERIODORDER_NO]           INT NOT NULL,
    [START_DT]                 DATETIME NOT NULL,
    [END_DT]                   DATETIME NOT NULL,
    [CONTRACTRENT_AMT]         NUMERIC(22,6) NULL,
    [CONTRACTRENTCURRENCY_TXT] VARCHAR(3) NULL,
    [ADDITIONALRENT_AMT]       NUMERIC(22,6) NULL,
    [ADDRENTCURRENCY_TXT]      VARCHAR(3) NULL,
    [PLANNEDRENTRAISE_TXT]     VARCHAR(1000) NULL,
    [NEGOTIATION_DT]           DATETIME NULL,
    [COMMENT_DSC]              VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [FIN_ESTATERENTPERIOD_PK] PRIMARY KEY ([ESTATERENTPERIODID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [FIN_ESTATERENTPERIOD_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [FIN_ESTATERENTPERIOD_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [FIN_ESTATERENTPERIOD_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [FIN_ESTATERENTPERIOD_F04] FOREIGN KEY ([ESTATERENT]) REFERENCES [FIN_ESTATERENT]([ESTATERENTID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [FIN_ESTATERENTPERIOD_X01] ON [FIN_ESTATERENTPERIOD] ([ESTATERENT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Estate Rent Period: periods (years) of the rental agreement',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'FIN_ESTATERENTPERIOD',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Estate Rent Period Id: Identity column for FIN_ESTATERENTPERIOD' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'ESTATERENTPERIODID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Estate Rent: Master column (FIN_ESTATERENT)' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'ESTATERENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Period Order: Order of the period for the rental agreement' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'PERIODORDER_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Period Start Date: Period Start Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'START_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Period End Date: Period End Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'END_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Contract Rent Amount: Rent Amount for the period (written on the contract)' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'CONTRACTRENT_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Contract Rent Currency: Currency of contract rent' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'CONTRACTRENTCURRENCY_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Additional Rent Amount: Additional rent amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'ADDITIONALRENT_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Additional Rent Currency: currency for additional rent ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'ADDRENTCURRENCY_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Planned Rent Raise: Rent raise conditions determined at the beginning of the period' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'PLANNEDRENTRAISE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Negotiation Date: The notification date for the Estate Rent Raise Rate negotiations' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'NEGOTIATION_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for estate rent period.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'FIN_ESTATERENTPERIOD',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
