CREATE FUNCTION dbo.SEC_DEPARTMENTGROUP_FN() RETURNS INT AS
BEGIN
	DECLARE @value INT 
	SELECT @value = CASE WHEN RM.USERID IS NULL AND ST.STORE_NM IS NULL THEN 1 ELSE CASE WHEN RM.USERID IS NOT NULL THEN 2 ELSE 3 END END
	  FROM SEC_USER U
	  LEFT JOIN STR_REGIONMANAGERS RM ON U.USERID = RM.USERID
	  LEFT JOIN STR_STORE ST ON U.BRANCH = ST.BRANCH AND ST.ACTIVE_FL = 'Y' AND ST.PRODUCTION_FL = 'Y' AND ST.DELETED_FL = 'N'
	 WHERE U.ACTIVE_FL = 'Y'
	   AND U.USERID = dbo.SYS_GETCURRENTUSER_FN()
	RETURN @value 
END