CREATE FUNCTION dbo.STR_GETUSERCURRENTDATE_FN() RETURNS DATE AS
BEGIN
	DECLARE @branchType VARCHAR(100)
	SELECT @branchType = BT.BRANCHTYPE_NM
	 FROM ORG_BRANCH B
	 JOIN ORG_BRANCHTYPE BT ON B.BRANCHTYPE = BT.BRANCHTYPEID
	WHERE BRANCHID = dbo.SYS_GETCURRENTBRANCH_FN()

	DECLARE @returnDate DATE
	IF @branchType != 'Branch'
	BEGIN
		DECLARE @now DATETIME = GETDATE();
		DECLARE @time TIME = CAST(GETDATE() AS TIME);
		IF @time < '09:30' SET @now = @now - 1;
		SET @returnDate = CAST(@now as DATE)
	END
	ELSE
	BEGIN
		SET @returnDate = CAST(GETDATE() - 1 AS DATE)
	END
	RETURN @returnDate
END