CREATE FUNCTION [dbo].[STR_GETUSERSTORESALL_FN]() RETURNS TABLE AS
RETURN (


 WITH BranchesCTE AS
 (
  SELECT BRANCHID, BRANCH_NM, PARENT, BRANCHTYPE
    FROM ORG_BRANCH
   WHERE BRANCHID = dbo.SYS_GETCURRENTBRANCH_FN()
   UNION ALL
  SELECT A.BRANCHID, A.BRANCH_NM, A.PARENT, A.BRANCHTYPE
    FROM ORG_BRANCH A
    JOIN BranchesCTE s ON a.PARENT = s.BRANCHID
 ),  
 UserStores AS  
 (  
  SELECT ST.STOREID
    FROM STR_STORE ST
   WHERE NOT EXISTS (SELECT 1 FROM STR_USERSSTORES WHERE [USER] = dbo.SYS_GETCURRENTUSER_FN())
   UNION ALL
  SELECT STORE FROM STR_USERSSTORES WHERE [USER] = dbo.SYS_GETCURRENTUSER_FN()
 )
        
 SELECT ST.STOREID,
        ST.ORGANIZATION,
        ST.DELETED_FL,
        ST.CREATE_DT,
        ST.UPDATE_DT,
        ST.CREATEUSER,
        ST.UPDATEUSER,
        ST.STORE_NM,
        ST.BRANCH,
        ST.IPADDRESS_TXT,
        ST.ADVANCE_AMT,
        ST.OPENING_DT,
        ST.CLOSING_DT,
        ST.ACTIVE_FL,
        ST.PRODUCTION_FL,
        ST.CITY,
		CT.CITY_NM,
        ST.TOWN,
		T.TOWN_NM,
        ST.ADDRESS_TXT,
        ST.REGIONMANAGER,
		RM.MANAGER_NM,
        ST.INCONSTRUCTION_FL
   FROM BranchesCTE C
   JOIN ORG_BRANCHTYPE BT ON C.BRANCHTYPE = BT.BRANCHTYPEID
   JOIN STR_STORE ST ON C.BRANCHID = ST.BRANCH
   JOIN UserStores US ON ST.STOREID = US.STOREID
   LEFT JOIN STR_CITY CT (NOLOCK) ON ST.CITY = CT.CITYID
   LEFT JOIN STR_TOWN T (NOLOCK) ON ST.TOWN = T.TOWNID
   LEFT JOIN STR_REGIONMANAGERS RM (NOLOCK) ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
  WHERE BT.BRANCHTYPE_NM = 'Branch'
      
) 