CREATE PROCEDURE PRD_LST_PRODUCTREPORT_SP AS  
BEGIN  select P.PRODUCTID
, SEC.USER_NM CREATE_USER_NM
, SEC2.USER_NM UPDATE_USER_NM
, P.CODE_NM, P.NAME_NM
, P.PURCHASEVAT_RT
, P.SALEVAT_RT
, P.OLDCODE_NM
, P.GTIPCODE_TXT
, P.SHORTNAME_NM
, C2.COUNTRY_NM
, P.CONTENT_TXT
, P.EXPIRESIN_CNT
, P.SHELFLIFE_CNT
, P.COMMENT_DSC
, U2.UNIT_NM WEIGHTUNIT
, P.LOADORDER_TXT
, P.PARENT
, P.INITIALPRICE_AMT
, B2.BARCODE_TXT BARCODE_TXT1
, B3.BARCODE_TXT BARCODE_TXT2
, CASE PT.PROPERTYTYPE_NM WHEN 'Koku'THEN 1 ELSE 0 END  KOKU
, CASE PT.PROPERTYTYPE_NM WHEN 'DeList'THEN 1 ELSE 0 END  DELİST
, CASE PT.PROPERTYTYPE_NM WHEN 'Siparişe Kapalı'THEN 1 ELSE 0 END  SIPARISE_KAPALI
, CASE PT.PROPERTYTYPE_NM WHEN 'Toshiba Ürün Id'THEN PS.VALUE_TXT ELSE '-' END  TOSHIBAID
, CASE PT.PROPERTYTYPE_NM WHEN 'Konsinye Ürün'THEN 1 ELSE 0 END  KONSIYE_URUN
, CASE PT.PROPERTYTYPE_NM WHEN 'Uluslararası Kodu'THEN PS.VALUE_TXT ELSE '-' END  ULUSLARARASI_KODU
, CA.CATEGORY_NM
, SG.SUBGROUP_NM
, SP1.SUPERGROUP1_NM
, SP2.SUPERGROUP2_NM
, SP3.SUPERGROUP3_NM
, U.UNIT_NM
, BT.BARCODETYPE_NM
, ST.SEASONTYPE_NM
, W.WARNING_TXT
, SC.CONDITION_TXT
, C.NAME_NM CAMPAIGN_NM 
, SU.PACKAGE_QTY SHIPMENTUNIT_QTY
 from PRD_PRODUCT P 
 LEFT JOIN PRD_PROPERTY PS ON PS.PRODUCT=P.PRODUCTID 
 LEFT JOIN PRD_PROPERTYTYPE PT ON PS.PROPERTYTYPE=PT.PROPERTYTYPEID 
 LEFT JOIN SEC_USER SEC ON SEC.USERID=P.CREATEUSER 
 LEFT JOIN SEC_USER SEC2 ON SEC2.USERID=P.UPDATEUSER 
 LEFT JOIN PRD_SUBGROUP SG ON P.SUBGROUP=SG.SUBGROUPID 
 LEFT JOIN PRD_CATEGORY CA ON CA.CATEGORYID=SG.CATEGORY 
 LEFT JOIN PRD_SUPERGROUP1 SP1 ON P.SUPERGROUP1=SP1.SUPERGROUP1ID 
 LEFT JOIN PRD_SUPERGROUP2 SP2 ON P.SUPERGROUP1=SP2.SUPERGROUP2ID 
 LEFT JOIN PRD_SUPERGROUP3 SP3 ON P.SUPERGROUP1=SP3.SUPERGROUP3ID 
 LEFT JOIN PRD_UNIT U ON P.UNIT=U.UNITID   
 LEFT JOIN PRD_UNIT U2 ON P.WEIGHTUNIT=U2.UNITID   
 LEFT JOIN PRD_BARCODETYPE BT ON P.BARCODETYPE=BT.BARCODETYPEID 
 LEFT JOIN PRD_SEASONTYPE ST ON P.SEASONTYPE=ST.SEASONTYPEID 
 LEFT JOIN PRD_WARNING W ON P.WARNING=W.WARNINGID 
 LEFT JOIN PRD_STORAGECONDITION SC ON P.STORAGECONDITION=SC.STORAGECONDITIONID 
 LEFT JOIN PRD_CAMPAIGN C ON P.CAMPAIGN=C.CAMPAIGNID 
 LEFT JOIN PRD_COUNTRY C2 ON P.COUNTRY=C2.COUNTRYID 
 LEFT JOIN WHS_PRODUCTSHIPMENTUNIT SU ON SU.PRODUCT = P.PRODUCTID  
 LEFT JOIN (SELECT PRODUCT, BARCODE_TXT,ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY BARCODEID DESC) ROWNO FROM PRD_BARCODE) B2 ON B2.PRODUCT=P.PRODUCTID  AND B2.ROWNO = 1 
 LEFT JOIN (SELECT PRODUCT, BARCODE_TXT, ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY BARCODEID DESC) ROWNO FROM PRD_BARCODE) B3 ON B3.PRODUCT=P.PRODUCTID AND B3.ROWNO = 2 
 WHERE P.DELETED_FL='N' END