-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_BARCODETYPEINT]
(
    /*Section="Columns"*/
    [BARCODETYPEINTID] INT NOT NULL,
    [BARCODETYPE_NM]   VARCHAR(100) NOT NULL,
    [COMMENT_DSC]      VARCHAR(1000) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_BARCODETYPEINT_PK] PRIMARY KEY ([BARCODETYPEINTID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRD_BARCODETYPEINT_X01] ON [PRD_BARCODETYPEINT] ([BARCODETYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Barcode Type Int: Barkod tipleri',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_BARCODETYPEINT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Barcode Type ID: Identity column for PRD_BARCODETYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_BARCODETYPEINT',
    @level2type=N'COLUMN',
    @level2name=N'BARCODETYPEINTID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Barcode Type: Name of barcode.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_BARCODETYPEINT',
    @level2type=N'COLUMN',
    @level2name=N'BARCODETYPE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for barcode.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_BARCODETYPEINT',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
