-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_WARNING]
(
    /*Section="Columns"*/
    [WARNINGID]   INT NOT NULL,
    [WARNING_TXT] VARCHAR(1000) NOT NULL,
    [COMMENT_DSC] VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_WARNING_PK] PRIMARY KEY ([WARNINGID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRD_WARNING_X01] ON [PRD_WARNING] ([WARNING_TXT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Warning: Ürün uyarıları, etiket için',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_WARNING',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Warning Id: Identity column for PRD_WARNING' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_WARNING',
    @level2type=N'COLUMN',
    @level2name=N'WARNINGID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Warning Text: Ürün uyarısı' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_WARNING',
    @level2type=N'COLUMN',
    @level2name=N'WARNING_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for warning.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_WARNING',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
