-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_SUBGROUP]
(
    /*Section="Columns"*/
    [SUBGROUPID]  INT NOT NULL,
    [SUBGROUP_NM] VARCHAR(100) NOT NULL,
    [CATEGORY]    INT NOT NULL,
    [COMMENT_DSC] VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_SUBGROUP_PK] PRIMARY KEY ([SUBGROUPID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [PRD_SUBGROUP_F01] FOREIGN KEY ([CATEGORY]) REFERENCES [PRD_CATEGORY]([CATEGORYID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRD_SUBGROUP_X01] ON [PRD_SUBGROUP] ([SUBGROUP_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Subgroup: Alt grup',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_SUBGROUP',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Subgroup ID: Alt grup ID' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_SUBGROUP',
    @level2type=N'COLUMN',
    @level2name=N'SUBGROUPID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Subgroup Name: Alt grup' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_SUBGROUP',
    @level2type=N'COLUMN',
    @level2name=N'SUBGROUP_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Category: Kategori' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_SUBGROUP',
    @level2type=N'COLUMN',
    @level2name=N'CATEGORY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Açıklama' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_SUBGROUP',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
