-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_PACKAGE]
(
    /*Section="Columns"*/
    [PACKAGEID]     INT NOT NULL,
    [PACKAGE_NM]    VARCHAR(100) NOT NULL,
    [PARENTPACKAGE] INT NULL,
    [AMOUNT_AMT]    NUMERIC(22,6) NOT NULL,
    [COMMENT_DSC]   VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_PACKAGE_PK] PRIMARY KEY ([PACKAGEID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Package: Paket tanımlamalarıdır',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_PACKAGE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Id: Identity column for PRD_PACKAGE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_PACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'PACKAGEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Paketlemenin adı' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_PACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'PACKAGE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Parent Package: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_PACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'PARENTPACKAGE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Amount: Paket içeriğindeki miktar' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_PACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'AMOUNT_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Description: Açıklama' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_PACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
