-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_FIXTUREMODEL]
(
    /*Section="Columns"*/
    [FIXTUREMODELID] INT NOT NULL IDENTITY,
    [BRAND]          INT NOT NULL,
    [MODEL_NM]       VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_FIXTUREMODEL_PK] PRIMARY KEY ([FIXTUREMODELID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [PRD_FIXTUREMODEL_F01] FOREIGN KEY ([BRAND]) REFERENCES [PRD_FIXTUREBRAND]([FIXTUREBRANDID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Fixture Model: Fixture Model',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_FIXTUREMODEL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Fixture Model Id: Identity column for PRD_FIXTUREMODEL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_FIXTUREMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'FIXTUREMODELID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Brand: Brand' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_FIXTUREMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'BRAND'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Model Name: Name of fixture model.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_FIXTUREMODEL', 
    @level2type=N'COLUMN',
    @level2name=N'MODEL_NM'
GO

/*Section="End"*/
