-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_STOCKGROUPNAME]
(
    /*Section="Columns"*/
    [STOCKGROUPID]  INT NOT NULL,
    [STOCKGROUP_NM] VARCHAR(100) NOT NULL,
    [USAGETYPE_CD]  INT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_STOCKGROUPNAME_PK] PRIMARY KEY ([STOCKGROUPID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Stock Group Name: Stock Group Name',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_STOCKGROUPNAME',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Stock Group Name Id: Identity column for PRD_STOCKGROUPNAME' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_STOCKGROUPNAME',
    @level2type=N'COLUMN',
    @level2name=N'STOCKGROUPID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Stock Group Name: Name of stock group name.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_STOCKGROUPNAME',
    @level2type=N'COLUMN',
    @level2name=N'STOCKGROUP_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Usage Type: 1 : Stock Calculation 2 : Reporting' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRD_STOCKGROUPNAME',
    @level2type=N'COLUMN',
    @level2name=N'USAGETYPE_CD'
GO

/*Section="End"*/
