-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_CATEGORY]
(
    /*Section="Columns"*/
    [CATEGORYID]  INT NOT NULL,
    [CATEGORY_NM] VARCHAR(100) NOT NULL,
    [COMMENT_DSC] VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_CATEGORY_PK] PRIMARY KEY ([CATEGORYID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRD_CATEGORY_X01] ON [PRD_CATEGORY] ([CATEGORY_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Product Category: Product category',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_CATEGORY',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Category ID: Category ID' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_CATEGORY', 
    @level2type=N'COLUMN',
    @level2name=N'CATEGORYID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Category: Category' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_CATEGORY', 
    @level2type=N'COLUMN',
    @level2name=N'CATEGORY_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Açıklama' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_CATEGORY', 
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
