-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRD_PROPERTY]
(
    /*Section="Columns"*/
    [PROPERTYID]   INT NOT NULL IDENTITY,
    [PROPERTYTYPE] INT NOT NULL,
    [PRODUCT]      INT NOT NULL,
    [VALUE_TXT]    VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRD_PROPERTY_PK] PRIMARY KEY ([PROPERTYID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [PRD_PROPERTY_F01] FOREIGN KEY ([PROPERTYTYPE]) REFERENCES [PRD_PROPERTYTYPE]([PROPERTYTYPEID]),
    CONSTRAINT [PRD_PROPERTY_F02] FOREIGN KEY ([PRODUCT]) REFERENCES [PRD_PRODUCT]([PRODUCTID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [PRD_PROPERTY_X01] ON [PRD_PROPERTY] ([PRODUCT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Product Property: Ek özellikler',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRD_PROPERTY',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Property Id: Identity column for PRD_PROPERTY' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_PROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'PROPERTYID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Property Type: Özellik tipi' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_PROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'PROPERTYTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product: Ürün' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_PROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Value: Değer' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRD_PROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'VALUE_TXT'
GO

/*Section="End"*/
