CREATE FUNCTION [dbo].[INV_STOCKDATE2_FN] (@Date DATE) RETURNS TABLE AS
RETURN 
WITH LASTCOUNTINGDATE AS (
SELECT STORE, ACTUAL_DT
  FROM (  
SELECT STORE, ACTUAL_DT, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY ACTUAL_DT DESC) ROWNO
  FROM WHS_STOCKTAKINGSCHEDULE
 WHERE COUNTINGTYPE = 1
   AND STATUS = 2
   AND ACTUAL_DT <= @Date ) A 
 WHERE ROWNO = 1 )

SELECT STORE, PRODUCT, SUM(QUANTITY_QTY) STOCK
  FROM (
SELECT SD.STORE, SD.PRODUCT, SD.COUNTING_QTY QUANTITY_QTY
  FROM WHS_COUNTINGSTOCKDIFF SD
  JOIN LASTCOUNTINGDATE C ON SD.STORE = C.STORE AND SD.COUNTING_DT = C.ACTUAL_DT
 UNION ALL
SELECT INV.STORE, INV.PRODUCT, SUM(INV.QUANTITY_QTY) 
  FROM INV_STORETRANSACTIONS_VW INV
  JOIN LASTCOUNTINGDATE CD ON INV.STORE = CD.STORE 
 WHERE INV.TRANSACTION_DT > CD.ACTUAL_DT AND INV.TRANSACTION_DT <= @Date 
 GROUP BY INV.STORE, INV.PRODUCT) A
 GROUP BY STORE, PRODUCT