CREATE FUNCTION INV_STOCKDATE_FN (@Date DATE) RETURNS TABLE AS  
RETURN  
SELECT STORE, PRODUCT, SUM(STOCK) STOCK  
  FROM (  
SELECT STORE, PRODUCT, STOCK      
  FROM INV_STOCK_VW   
 UNION ALL  
SELECT STORE, PRODUCT, -1*SUM(QUANTITY_QTY) QUANTITY  
  FROM INV_STORETRANSACTIONS_VW INV  
  JOIN RPT_DATE D ON INV.TRANSACTION_DT > D.DATE_DT  
 WHERE D.DATE_DT = @Date  
 GROUP BY STORE, PRODUCT) A  
 GROUP BY STORE, PRODUCT  