CREATE VIEW BPM_ACTION_VW AS
SELECT A.ACTIONID, 
	   PD.PROCESSDEFINITION_NM [PROCESSDEFINITIONNAME], 
	   AI.ACTIVITY_NM [ACTIVITYNAME],
	   A.START_TM [ACTIONSTARTDATE],
	   PINU.USERFULL_NM [CREATEUSERNAME],
	   PINBRANCH.BRANCH_NM [CREATEBRANCHNAME],
	   ACTD.DEPARTMENT_NM [USERDEPARTMENTNAME],
	   PIN.START_DT [PROCESSINSTANCESTARTDATE],  
       PIN.UPDATE_DT [PROCESSINSTANCEUPDATEDATE],  
	   AI.START_TM [ACTIVITYINSTANCASTARTTIME],  
       A.SCREEN_REF,  
	   PIN.PROCESSDEFINITION,  
       AI.ACTIVITY_NO,  
       AI.PROCESSINSTANCE,  
       A.ACTIVITYINSTANCE,  
       PIN.INSTANCE_REF,  
       A.PRIORITY_QTY,  
       A.PERFORMER,  
       PIN.PARENT,  
	   FRM.FORMID,  
	   COALESCE(GU.MEMBERUSER, U.USERID, DU.USERID, A.[USER]) USERID
  FROM BPA_ACTION A (NOLOCK)
  JOIN BPM_PROCESSINSTANCE PIN (NOLOCK) ON A.PROCESSINSTANCE = PIN.PROCESSINSTANCEID  
  JOIN BPM_PROCESSDEFINITION PD (NOLOCK) ON PIN.PROCESSDEFINITION = PD.PROCESSDEFINITIONID
  JOIN BPM_ACTIVITYINSTANCE AI (NOLOCK) ON A.ACTIVITYINSTANCE = AI.ACTIVITYINSTANCEID  
  JOIN SEC_USER PINU (NOLOCK) ON PIN.CREATEUSER = PINU.USERID
  JOIN ORG_BRANCH PINBRANCH (NOLOCK) ON PIN.CREATEBRANCH = PINBRANCH.BRANCHID
  JOIN SEC_USER ACTU (NOLOCK) ON A.CREATEUSER = ACTU.USERID
  LEFT JOIN ORG_DEPARTMENT ACTD (NOLOCK) ON ACTU.DEPARTMENT = ACTD.DEPARTMENTID
  LEFT JOIN SEC_GROUPUSER GU ON A.[GROUP] = GU.CONTAINERGROUP
  LEFT JOIN SEC_USER U ON A.[BRANCH] = U.BRANCH
  LEFT JOIN SEC_USER DU ON A.[DEPARTMENT] = DU.DEPARTMENT
  LEFT JOIN BPA_FORM FRM (NOLOCK) ON FRM.PROCESSDEFINITION = PIN.PROCESSDEFINITION AND FRM.ACTIVITY_NO = AI.ACTIVITY_NO AND FRM.DELETED_FL = 'N'  
 WHERE A.STATUS_CD = 1
   AND A.DELETED_FL = 'N'