CREATE FUNCTION [dbo].[MIK_SALES_FN]
(	
	@StoreId INT, @Date DATE
)
RETURNS TABLE 
AS
RETURN 
(
 SELECT S.TRANSACTION_TM, SD.SALE, S.TRANSACTIONTYPE, S.COEFF        
      , CASE WHEN S.TRANSACTIONTYPE = 5 THEN 'I' ELSE 'K' END+RIGHT('000'+ISNULL(S.CASHREGISTER,''),3) CASHREGISTER, COALESCE(PC.MIKRO, P.CODE_NM) PRODUCTCODE_NM          
      , ROW_NUMBER() OVER (PARTITION BY SD.SALE ORDER BY SD.SALEDETAILID) - 1 ROWNO          
      , CASE WHEN P.UNIT = 1 THEN QUANTITY_QTY / 1000.0 ELSE QUANTITY_QTY END QUANTITY_QTY          
      , S.COEFF*PRICE PRICE        
      , S.COEFF*PRICE*VAT_RT/(100+VAT_RT) VAT_AMT          
      , CASE VAT_RT WHEN 0 THEN 1 WHEN 1 THEN 2 WHEN 8 THEN 3 WHEN 18 THEN 4 END VATGROUP_CD          
      , SALEROWNO, SD.BARCODE_TXT          
   FROM SLS_SALEDETAIL SD (NOLOCK)      
   JOIN (SELECT S.TRANSACTION_TM, S.SALEID, S.CASHREGISTER, S.TRANSACTIONTYPE, CASE WHEN S.TRANSACTIONTYPE = 5 THEN -1 ELSE 1 END COEFF, ROW_NUMBER() OVER (PARTITION BY 1 ORDER BY SALEID) SALEROWNO          
           FROM SLS_SALE S (NOLOCK)        
		   LEFT JOIN ACC_INVOICE I (NOLOCK) ON S.SALEID = I.SALE AND I.DELETED_FL = 'N'  
          WHERE S.TRANSACTION_DT = @Date          
            AND S.STORE = @StoreId          
            AND S.CANCELLED_FL = 'N'  
			AND (I.SALE IS NULL OR S.TRANSACTIONTYPE = 5)) S ON SD.SALE = S.SALEID          
   JOIN PRD_PRODUCT P (NOLOCK) ON SD.PRODUCT = P.PRODUCTID          
   LEFT JOIN MIK_PRODUCTCROSS PC (NOLOCK) ON SD.PRODUCT = PC.MAKTECH      
   -- JOIN (SELECT STORE, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY CASHREGISTERID) CRNO FROM STR_CASHREGISTER) CR ON SD.STORE = CR.STORE          
  WHERE SD.TRANSACTION_DT = @Date          
    AND SD.STORE = @StoreId          
    AND SD.CANCEL_FL = 'N'      
)
