CREATE VIEW SLS_SALEZETCRCOMPARE_VW AS
SELECT ST.STOREID, ST.STORE_NM, SALE.CASHREGISTER, T.CASHREGISTER TERMINAL, DT.DATE_DT, RECEIPT_AMT, REFUND_AMT, ZETRECEIPT_AMT, ZETREFUND_AMT  
	 , ISNULL(RECEIPT_AMT,0) - ISNULL(REFUND_AMT,0) - ISNULL(ZETRECEIPT_AMT,0) + ISNULL(ZETREFUND_AMT,0)  DIFF  
  FROM STR_STORE ST  
  JOIN STR_ACTIVETERMINALS T ON ST.STOREID = T.STORE
  JOIN RPT_DATE DT ON DT.DATE_DT BETWEEN '2018-10-01' AND CAST(GETDATE() AS DATE)  
  LEFT JOIN (SELECT STORE, TRANSACTION_DT, CASHREGISTER,  
				    SUM(CASE WHEN TRANSACTIONTYPE != 5 THEN TOTAL_AMT ELSE 0 END) RECEIPT_AMT,  
					-1*SUM(CASE WHEN TRANSACTIONTYPE = 5 THEN TOTAL_AMT ELSE 0 END) REFUND_AMT  
			   FROM SLS_SALE S (NOLOCK)  
			  WHERE CANCELLED_FL = 'N'  
			  GROUP BY STORE, TRANSACTION_DT, CASHREGISTER) SALE ON ST.STOREID = SALE.STORE AND DT.DATE_DT = SALE.TRANSACTION_DT AND T.CASHREGISTER = SALE.CASHREGISTER
  LEFT JOIN (SELECT STORE, TRANSACTION_DT, CASHREGISTER,   
					SUM(RECEIPTTOTAL_AMT + SLPTOTAL_AMT) ZETRECEIPT_AMT,  
					SUM(REFUND_AMT) ZETREFUND_AMT  
			   FROM SLS_ZET_VW    
			  GROUP BY STORE, TRANSACTION_DT, CASHREGISTER) ZET ON ST.STOREID = ZET.STORE AND DT.DATE_DT = ZET.TRANSACTION_DT AND T.CASHREGISTER = ZET.CASHREGISTER  
 WHERE ST.OPENING_DT <= DT.DATE_DT   
   AND (ST.CLOSING_DT IS NULL OR ST.CLOSING_DT >= DT.DATE_DT) 
   AND STOREID = 112 AND DATE_DT = '2019-02-01'
