CREATE VIEW SLS_ZET_VW AS
SELECT STORE, CASHREGISTER, TRANSACTION_DT, MAX(ZET_NO) ZET_NO, SUM(RECEIPT_CNT) RECEIPT_CNT,   
	   SUM(RECEIPTTOTAL_AMT) RECEIPTTOTAL_AMT, SUM(REFUND_CNT) REFUND_CNT, SUM(REFUND_AMT) REFUND_AMT,   
	   SUM(SLP_CNT) SLP_CNT, SUM(SLPTOTAL_AMT) SLPTOTAL_AMT, SUM(CASH_AMT) CASH_AMT, SUM(CARD_AMT) CARD_AMT,
	   COUNT(*) ZETCOUNT, MIN(TRANSACTION_TM) MINZET_TM, MIN(CREATE_DT) MINCREATE_TM, 
	   MAX(TRANSACTION_TM) MAXZET_TM, MAX(CREATE_DT) MAXCREATE_TM
  FROM SLS_SALEZET (NOLOCK)    
 WHERE DELETED_FL = 'N'  
 GROUP BY STORE, CASHREGISTER, TRANSACTION_DT  