CREATE VIEW SLS_MIKROCOMP_VW AS   
WITH MAKTECH AS (  
SELECT ST.STOREID, TRANSACTION_DT, SUM(CASE WHEN TRANSACTIONTYPE != 5 THEN TOTAL_AMT ELSE 0 END) TOTAL  
     , SUM(CASE WHEN TRANSACTIONTYPE = 5 THEN TOTAL_AMT ELSE 0 END) REFUND  
  FROM SLS_SALE S  
  LEFT JOIN ACC_INVOICE I (NOLOCK) ON S.SALEID = I.SALE AND I.DELETED_FL = 'N'
  JOIN STR_STORE ST ON S.STORE = ST.STOREID  
 WHERE CANCELLED_FL = 'N'  
   AND (I.SALE IS NULL OR S.TRANSACTIONTYPE = 5)
 GROUP BY ST.STOREID, TRANSACTION_DT),   
 MIKRO AS (  
SELECT STOREID, TRAN_DT, SUM(TOTAL) TOTAL, SUM(REFUND) REFUND  
  FROM (  
SELECT ST.STOREID, sth_belge_tarih TRAN_DT, SUM(sth_tutar+sth_vergi) total, 0 refund  
  FROM MIK_TRANSACTION20_SYN T  
  JOIN STR_STORE ST ON T.sth_cikis_depo_no = ST.STOREID  
 where sth_tip = 1  
   AND sth_pos_satis = 1
 GROUP BY ST.STOREID, sth_belge_tarih   
 UNION ALL  
SELECT ST.STOREID, sth_belge_tarih, 0, -1*SUM(sth_tutar+sth_vergi)  
  FROM MIK_TRANSACTION20_SYN T  
  JOIN STR_STORE ST ON T.sth_giris_depo_no = ST.STOREID  
 where sth_tip = 0  
   and sth_normal_iade = 1  
   AND sth_pos_satis = 1
 GROUP BY ST.STOREID, sth_belge_tarih) A  
 GROUP BY STOREID, TRAN_DT)   
SELECT STOREID, TRANSACTION_DT  
  , SUM(TOTAL) MAKTECHTOTAL, SUM(REFUND) MAKTECHRETURN  
  , SUM(MIKROTOTAL) MIKROTOTAL, SUM(MIKROREFUND) MIKRORETURN  
  FROM (  
SELECT *, 0 MIKROTOTAL, 0 MIKROREFUND  
  FROM MAKTECH  
 UNION ALL  
SELECT STOREID, TRAN_DT, 0, 0, TOTAL, REFUND  
  FROM MIKRO) A  
 GROUP BY STOREID, TRANSACTION_DT