CREATE VIEW SLS_SALEZETCOMPARE_VW AS
SELECT ST.STOREID, ST.STORE_NM, ST.TERMINAL, DT.DATE_DT, RECEIPT_AMT, REFUND_AMT, ZETRECEIPT_AMT, ZETREFUND_AMT
	 , ISNULL(RECEIPT_AMT,0) - ISNULL(REFUND_AMT,0) - ISNULL(ZETRECEIPT_AMT,0) + ISNULL(ZETREFUND_AMT,0)  DIFF
	 , RECEIPT_CNT, ZET_CNT
  FROM STR_STORE_VW ST
  JOIN RPT_DATE DT ON DT.DATE_DT BETWEEN '2018-01-01' AND CAST(GETDATE() AS DATE)
  LEFT JOIN (SELECT STORE, TRANSACTION_DT,
					SUM(CASE WHEN TRANSACTIONTYPE != 5 THEN TOTAL_AMT ELSE 0 END) RECEIPT_AMT,
					-1*SUM(CASE WHEN TRANSACTIONTYPE = 5 THEN TOTAL_AMT ELSE 0 END) REFUND_AMT,
					COUNT(*) RECEIPT_CNT
			   FROM SLS_SALE S (NOLOCK)  
			  WHERE CANCELLED_FL = 'N'
			  GROUP BY STORE, TRANSACTION_DT) SALE ON ST.STOREID = SALE.STORE AND DT.DATE_DT = SALE.TRANSACTION_DT
  LEFT JOIN (SELECT STORE, TRANSACTION_DT,   
					SUM(RECEIPTTOTAL_AMT + SLPTOTAL_AMT) ZETRECEIPT_AMT,  
					SUM(REFUND_AMT) ZETREFUND_AMT,  
					COUNT(*) ZET_CNT  
			   FROM SLS_ZET_VW    
			  GROUP BY STORE, TRANSACTION_DT) ZET ON ST.STOREID = ZET.STORE AND DT.DATE_DT = ZET.TRANSACTION_DT
 WHERE ST.OPENING_DT <= DT.DATE_DT 