-- bacaklar ile fişin master tablosu arasındaki uyumsuzlukları ortaya çıkarmak için
CREATE VIEW SLS_SALEDETAILBALANCE_VW AS
SELECT SALEID, S.STORE, S.TRANSACTION_DT, TOTAL_AMT, DETAILTOTAL_AMT
  FROM SLS_SALE S (NOLOCK)
  LEFT JOIN (SELECT SALE, STORE, TRANSACTION_DT, SUM(ISNULL(PRICE,0)) DETAILTOTAL_AMT FROM SLS_SALEDETAIL SD (NOLOCK) WHERE SD.CANCEL_FL = 'N' GROUP BY SALE, STORE, TRANSACTION_DT) SD 
    ON S.SALEID = SD.SALE AND S.STORE = SD.STORE AND S.TRANSACTION_DT = SD.TRANSACTION_DT
 WHERE S.CANCELLED_FL = 'N'