//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Overtech.ApiControllers.Accounting.kdsservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Kayit))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ServisHataHeader servisHataHeaderValueField;
        
        private System.Threading.SendOrPostCallback DisKullaniciKimlikDogrulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisKullaniciKimlikDogrula2OperationCompleted;
        
        private System.Threading.SendOrPostCallback BaglantiTestiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Overtech.ApiControllers.Accounting.Properties.Settings.Default.Overtech_ApiControllers_Accounting_kdsservice_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ServisHataHeader ServisHataHeaderValue {
            get {
                return this.servisHataHeaderValueField;
            }
            set {
                this.servisHataHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DisKullaniciKimlikDogrulaCompletedEventHandler DisKullaniciKimlikDogrulaCompleted;
        
        /// <remarks/>
        public event DisKullaniciKimlikDogrula2CompletedEventHandler DisKullaniciKimlikDogrula2Completed;
        
        /// <remarks/>
        public event BaglantiTestiCompletedEventHandler BaglantiTestiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServisHataHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisKullaniciKimlikDogrula", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long DisKullaniciKimlikDogrula(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, System.DateTime istemciTarihi) {
            object[] results = this.Invoke("DisKullaniciKimlikDogrula", new object[] {
                        disKullaniciKimlik,
                        islemTipi,
                        istemciTarihi});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void DisKullaniciKimlikDogrulaAsync(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, System.DateTime istemciTarihi) {
            this.DisKullaniciKimlikDogrulaAsync(disKullaniciKimlik, islemTipi, istemciTarihi, null);
        }
        
        /// <remarks/>
        public void DisKullaniciKimlikDogrulaAsync(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, System.DateTime istemciTarihi, object userState) {
            if ((this.DisKullaniciKimlikDogrulaOperationCompleted == null)) {
                this.DisKullaniciKimlikDogrulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisKullaniciKimlikDogrulaOperationCompleted);
            }
            this.InvokeAsync("DisKullaniciKimlikDogrula", new object[] {
                        disKullaniciKimlik,
                        islemTipi,
                        istemciTarihi}, this.DisKullaniciKimlikDogrulaOperationCompleted, userState);
        }
        
        private void OnDisKullaniciKimlikDogrulaOperationCompleted(object arg) {
            if ((this.DisKullaniciKimlikDogrulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisKullaniciKimlikDogrulaCompleted(this, new DisKullaniciKimlikDogrulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServisHataHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisKullaniciKimlikDogrula2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long DisKullaniciKimlikDogrula2(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, Zaman istemciZamani) {
            object[] results = this.Invoke("DisKullaniciKimlikDogrula2", new object[] {
                        disKullaniciKimlik,
                        islemTipi,
                        istemciZamani});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void DisKullaniciKimlikDogrula2Async(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, Zaman istemciZamani) {
            this.DisKullaniciKimlikDogrula2Async(disKullaniciKimlik, islemTipi, istemciZamani, null);
        }
        
        /// <remarks/>
        public void DisKullaniciKimlikDogrula2Async(DisKullaniciKimlik disKullaniciKimlik, NPSIslemTipi islemTipi, Zaman istemciZamani, object userState) {
            if ((this.DisKullaniciKimlikDogrula2OperationCompleted == null)) {
                this.DisKullaniciKimlikDogrula2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisKullaniciKimlikDogrula2OperationCompleted);
            }
            this.InvokeAsync("DisKullaniciKimlikDogrula2", new object[] {
                        disKullaniciKimlik,
                        islemTipi,
                        istemciZamani}, this.DisKullaniciKimlikDogrula2OperationCompleted, userState);
        }
        
        private void OnDisKullaniciKimlikDogrula2OperationCompleted(object arg) {
            if ((this.DisKullaniciKimlikDogrula2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisKullaniciKimlikDogrula2Completed(this, new DisKullaniciKimlikDogrula2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServisHataHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BaglantiTesti", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime BaglantiTesti() {
            object[] results = this.Invoke("BaglantiTesti", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void BaglantiTestiAsync() {
            this.BaglantiTestiAsync(null);
        }
        
        /// <remarks/>
        public void BaglantiTestiAsync(object userState) {
            if ((this.BaglantiTestiOperationCompleted == null)) {
                this.BaglantiTestiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaglantiTestiOperationCompleted);
            }
            this.InvokeAsync("BaglantiTesti", new object[0], this.BaglantiTestiOperationCompleted, userState);
        }
        
        private void OnBaglantiTestiOperationCompleted(object arg) {
            if ((this.BaglantiTestiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaglantiTestiCompleted(this, new BaglantiTestiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class ServisHataHeader : System.Web.Services.Protocols.SoapHeader {
        
        private ServisHata servisHataField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public ServisHata ServisHata {
            get {
                return this.servisHataField;
            }
            set {
                this.servisHataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServisHata {
        
        private string mesajField;
        
        private string kodField;
        
        /// <remarks/>
        public string Mesaj {
            get {
                return this.mesajField;
            }
            set {
                this.mesajField = value;
            }
        }
        
        /// <remarks/>
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Zaman {
        
        private int yilField;
        
        private int ayField;
        
        private int gunField;
        
        private int saatField;
        
        private int dakikaField;
        
        private int saniyeField;
        
        /// <remarks/>
        public int Yil {
            get {
                return this.yilField;
            }
            set {
                this.yilField = value;
            }
        }
        
        /// <remarks/>
        public int Ay {
            get {
                return this.ayField;
            }
            set {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        public int Gun {
            get {
                return this.gunField;
            }
            set {
                this.gunField = value;
            }
        }
        
        /// <remarks/>
        public int Saat {
            get {
                return this.saatField;
            }
            set {
                this.saatField = value;
            }
        }
        
        /// <remarks/>
        public int Dakika {
            get {
                return this.dakikaField;
            }
            set {
                this.dakikaField = value;
            }
        }
        
        /// <remarks/>
        public int Saniye {
            get {
                return this.saniyeField;
            }
            set {
                this.saniyeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DisKullaniciKimlik))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Kayit {
        
        private int idField;
        
        private DataRowState kayitDurumuField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public DataRowState KayitDurumu {
            get {
                return this.kayitDurumuField;
            }
            set {
                this.kayitDurumuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DataRowState {
        
        /// <remarks/>
        Detached = 1,
        
        /// <remarks/>
        Unchanged = 2,
        
        /// <remarks/>
        Added = 4,
        
        /// <remarks/>
        Deleted = 8,
        
        /// <remarks/>
        Modified = 16,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DisKullaniciKimlik : Kayit {
        
        private ProgramAdi programAdiField;
        
        private string kimlikNOField;
        
        private KimlikNOTipi kimlikNOTipiField;
        
        private string noterlikKoduField;
        
        private string noterlikKullaniciAdiField;
        
        private DisKullaniciTipi disKullaniciTipiField;
        
        private string sifreField;
        
        /// <remarks/>
        public ProgramAdi ProgramAdi {
            get {
                return this.programAdiField;
            }
            set {
                this.programAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KimlikNO {
            get {
                return this.kimlikNOField;
            }
            set {
                this.kimlikNOField = value;
            }
        }
        
        /// <remarks/>
        public KimlikNOTipi KimlikNOTipi {
            get {
                return this.kimlikNOTipiField;
            }
            set {
                this.kimlikNOTipiField = value;
            }
        }
        
        /// <remarks/>
        public string NoterlikKodu {
            get {
                return this.noterlikKoduField;
            }
            set {
                this.noterlikKoduField = value;
            }
        }
        
        /// <remarks/>
        public string NoterlikKullaniciAdi {
            get {
                return this.noterlikKullaniciAdiField;
            }
            set {
                this.noterlikKullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        public DisKullaniciTipi DisKullaniciTipi {
            get {
                return this.disKullaniciTipiField;
            }
            set {
                this.disKullaniciTipiField = value;
            }
        }
        
        /// <remarks/>
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ProgramAdi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        Vezne,
        
        /// <remarks/>
        YazimNet,
        
        /// <remarks/>
        VezneNet,
        
        /// <remarks/>
        TNBOnline,
        
        /// <remarks/>
        NBS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum KimlikNOTipi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        TCKN,
        
        /// <remarks/>
        VKN,
        
        /// <remarks/>
        MTKN,
        
        /// <remarks/>
        TCSN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DisKullaniciTipi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        NoterlikKullanicisi,
        
        /// <remarks/>
        MaliMusavir,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum NPSIslemTipi {
        
        /// <remarks/>
        Belirtilmemis,
        
        /// <remarks/>
        AracSatisi,
        
        /// <remarks/>
        DefterOnayi,
        
        /// <remarks/>
        SendikaUyelik,
        
        /// <remarks/>
        BelgeOnayi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DisKullaniciKimlikDogrulaCompletedEventHandler(object sender, DisKullaniciKimlikDogrulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisKullaniciKimlikDogrulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisKullaniciKimlikDogrulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DisKullaniciKimlikDogrula2CompletedEventHandler(object sender, DisKullaniciKimlikDogrula2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisKullaniciKimlikDogrula2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisKullaniciKimlikDogrula2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BaglantiTestiCompletedEventHandler(object sender, BaglantiTestiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaglantiTestiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaglantiTestiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591