CREATE PROCEDURE BPM_LST_HISTORYDATA_SP @ProcessInstance BIGINT AS
BEGIN
	SELECT PD.PROCESSDEFINITION_NM, P.STATUS_CD PROCESSSTATUS_CD, AI.ACTIVITY_NM, TY.ACTIVITYTYPE_NM, AI.ACTIVITY_NO, AI.STATUS_CD ACTIVITYSTATUS_CD,
		   A.STATUS_CD ACTIONSTATUS_CD, A.CHOICE_TXT, A.START_TM, A.FINISH_TM, A.PERFORMER, U.USERFULL_NM PERFORMER_NM, 
		   TS.TARGETSCOPE_NM, COALESCE(G.GROUP_NM, BR.BRANCH_NM, DP.DEPARTMENT_NM, TU.USERFULL_NM) TARGET_NM, A.USERCOMMENT_DSC
	  FROM BPM_PROCESSINSTANCE P
	  JOIN BPM_ACTIVITYINSTANCE AI ON P.PROCESSINSTANCEID = AI.PROCESSINSTANCE
	  JOIN BPM_ACTIVITYTYPE TY ON AI.ACTIVITYTYPE = TY.ACTIVITYTYPEID
	  JOIN BPM_PROCESSDEFINITION PD ON P.PROCESSDEFINITION = PD.PROCESSDEFINITIONID
	  JOIN BPA_ACTION A ON P.PROCESSINSTANCEID = A.PROCESSINSTANCE AND AI.ACTIVITYINSTANCEID = A.ACTIVITYINSTANCE
	  JOIN BPM_TARGETSCOPE TS ON A.TARGETSCOPE = TS.TARGETSCOPEID
	  LEFT JOIN SEC_USER U ON A.PERFORMER = U.USERID
	  LEFT JOIN SEC_GROUP G ON A.[GROUP] = G.GROUPID
	  LEFT JOIN ORG_BRANCH BR ON A.BRANCH = BR.BRANCHID
	  LEFT JOIN ORG_DEPARTMENT DP ON A.DEPARTMENT = DP.DEPARTMENTID
	  LEFT JOIN SEC_USER TU ON A.[USER] = TU.USERID
	 WHERE P.PROCESSINSTANCEID = @ProcessInstance
END