CREATE PROCEDURE SEC_LST_SCREENUSERS_SP @Screen INT, @Program INT = 2 AS    
BEGIN     
IF @Screen = -1    
 SELECT USERID, USER_NM, USERFULL_NM FROM SEC_USER WHERE DELETED_FL = 'N'    
ELSE    
-- TMP TABLES    
IF OBJECT_ID('tempdb.dbo.#groups', 'U') IS NOT NULL DROP TABLE #groups    
IF OBJECT_ID('tempdb.dbo.#roles', 'U') IS NOT NULL DROP TABLE #roles    
IF OBJECT_ID('tempdb.dbo.#privileges', 'U') IS NOT NULL DROP TABLE #privileges    
IF OBJECT_ID('tempdb.dbo.#screenDetails', 'U') IS NOT NULL DROP TABLE #screenDetails;    
    
-- GETTING PRIVILEGES IN THE SCREEN    
WITH PrivilegeCTE AS          
 (       
 SELECT DISTINCT SA.PRIVILEGE     
 FROM PRG_SCREENACTION SA     
 WHERE SA.SCREEN = @Screen    
 UNION ALL          
   SELECT P.PARENT PRIVILEGE    
     FROM SEC_PRIVILEGE P       
     JOIN PrivilegeCTE CT ON P.PRIVILEGEID = CT.PRIVILEGE AND P.PARENT IS NOT NULL          
 ) SELECT DISTINCT PRIVILEGE INTO #privileges FROM PrivilegeCTE    
    
    
-- GETTING ROLES FOR THOSE PRIVILEGES    
SELECT DISTINCT RP.ROLE    
INTO #roles    
FROM SEC_ROLEPRIVILEGE RP        
JOIN #privileges P ON P.PRIVILEGE = RP.PRIVILEGE;    
    
-- GETTING GROUPS WHICH HAVE THOSE ROLES    
WITH GroupCTE AS          
 (           
  SELECT GR.[GROUP]    
    FROM SEC_GROUPROLE GR           
   WHERE GR.ROLE IN (SELECT R.ROLE FROM #roles R)    
   UNION ALL          
  SELECT GG.CONTAINERGROUP            
    FROM SEC_GROUPGROUP GG      
    JOIN GroupCTE CT ON GG.MEMBERGROUP  = CT.[GROUP]           
 )     
SELECT [GROUP] INTO #groups FROM GroupCTE    
    
-- GET USER LIST WHO HAVE PRIVILEGE FOR THAT SCREEN    
SELECT DISTINCT U.USERID, U.USER_NM, U.USERFULL_NM     
FROM SEC_USER U    
JOIN SEC_GROUPUSER GU ON GU.MEMBERUSER = U.USERID    
WHERE GU.CONTAINERGROUP IN (SELECT * FROM #groups)    
    
END