CREATE PROCEDURE STR_DEL_CASHREGISTER_SP  
    @StoreCashRegisterId INT  
AS  
BEGIN  
  
  
 INSERT INTO STR_CASHREGISTERLOG   
 (CASHREGISTERID, LOG_DT, LOGUSER, LOGOPERATION_CD, LOGCHANNEL, LOGBRANCH, LOGSCREEN, CASHREGISTER_NM,   
 STORE, CASHREGISTERMODEL, PRICEFILEPATH_TXT, SALEFILEPATH1_TXT, SALEFILEPATH2_TXT, SALEFILEPATH3_TXT,  
 CURRENTPRICEVERSION, CURRENTPRICELOAD_TM, PRIVATEPRICEVERSION, PRIVATEPRICELOAD_TM, CREATEPRICEFILE_FL,  
 IPADDRESS_TXT, STATUS_FL, STATUS_TXT,  GIBDEVICENO_TXT)  
 SELECT  C.CASHREGISTERID, GETDATE(),  dbo.SYS_GETCURRENTUSER_FN(),  'DEL',  dbo.SYS_GETCURRENTCHANNEL_FN(),    
      dbo.SYS_GETCURRENTBRANCH_FN(),  dbo.SYS_GETCURRENTSCREEN_FN(),  C.CASHREGISTER_NM,  
      C.STORE, C.CASHREGISTERMODEL, C.PRICEFILEPATH_TXT, C.SALEFILEPATH1_TXT, C.SALEFILEPATH2_TXT,   
      C.SALEFILEPATH3_TXT, C.CURRENTPRICEVERSION, C.CURRENTPRICELOAD_TM, C.PRIVATEPRICEVERSION,  
      C.PRIVATEPRICELOAD_TM, C.CREATEPRICEFILE_FL, C.IPADDRESS_TXT, C.STATUS_FL, C.STATUS_TXT, C. GIBDEVICENO_TXT  
    FROM STR_CASHREGISTER C (NOLOCK)    
      WHERE C.CASHREGISTERID = @StoreCashRegisterId;    
  
    SET NOCOUNT OFF  
    -- Update the DELETED_FL to 'Y'  
    UPDATE STR_CASHREGISTER  
       SET DELETED_FL = 'Y',  
           UPDATE_DT = GETDATE()  
     WHERE CASHREGISTERID = @StoreCashRegisterId;  
  
    /*Section="Check"*/  
    -- Check the deleted/updated row count  
    IF @@ROWCOUNT = 0  
    BEGIN  
        SET NOCOUNT ON;  
        THROW 100001, 'Nothing deleted. Delete failed.', 1;  
        RETURN;  
    END;  
    SET NOCOUNT ON;  
  
/*Section="End"*/  
END;  