CREATE PROCEDURE [dbo].[STR_LST_USERFIXTURE_SP] AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;
	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();

	SELECT F.*
	  FROM STR_FIXTURE F
	  JOIN #STORES ST ON F.STORE = ST.STOREID
	 WHERE F.DELETED_FL = 'N'
END
