CREATE PROCEDURE [dbo].[STR_LST_STOREFILTER_SP]
AS
BEGIN

	SELECT -1 AS STOREID, '*TÜM MAĞAZALAR*' AS STORE_NM
	 UNION
	SELECT STOREID, STORE_NM
	  FROM dbo.STR_GETUSERSTORES_FN()
	 WHERE ACTIVE_FL = 'Y'   AND DELETED_FL = 'N'
	 ORDER BY STORE_NM

END;