CREATE PROCEDURE [dbo].[STR_SEL_WORKINGHOURSOPENRECORD_SP]
	@Date DATE = NULL,
	@StoreCode VARCHAR(50) = NULL
AS
	IF @Date IS NULL
		SET @Date = DATEADD(DAY, -1, CAST(GETDATE() AS DATE))
	SELECT * 
	  FROM STR_WORKINGHOURS
	 WHERE CAST(OPENING_TM AS DATE) = @Date
	   AND (@StoreCode IS NULL OR STORECODE_TXT = @StoreCode)
	   AND CLOSING_TM IS NULL
