CREATE PROCEDURE [dbo].[STR_LST_REMANINGPROPERTYTYPES_SP]
@Store INT
AS
BEGIN
    /*Section="Query"*/
    -- Select all 
    SELECT
           PT.PROPERTYTYPEID,
           PT.PROPERTYTYPE_NM
      FROM STR_PROPERTYTYPE PT (NOLOCK)
     WHERE PT.PROPERTYTYPEID NOT IN (SELECT PROPERTYTYPE FROM STR_PROPERTY PR (NOLOCK) WHERE PR.STORE = @Store)
	 ORDER BY PROPERTYTYPE_NM;

/*Section="End"*/
END;