CREATE PROCEDURE STR_LST_USERSTORES_SP AS
BEGIN

	DECLARE @Branch INT;
	SELECT @Branch = dbo.SYS_GETCURRENTBRANCH_FN();

	DECLARE @BranchType VARCHAR(100);
	SELECT @BranchType = BT.BRANCHTYPE_NM
      FROM ORG_BRANCH B 
      JOIN ORG_BRANCHTYPE BT ON B.BRANCHTYPE = BT.BRANCHTYPEID
     WHERE B.BRANCHID = dbo.SYS_GETCURRENTBRANCH_FN();

	DECLARE @Department VARCHAR(100);
	SELECT @Department = DEPARTMENT_NM
	  FROM SEC_USER U
	  JOIN ORG_DEPARTMENT D ON U.DEPARTMENT = D.DEPARTMENTID
	 WHERE U.USERID = dbo.SYS_GETCURRENTUSER_FN();

	WITH BranchesCTE AS
	( 
		SELECT BRANCHID, BRANCH_NM, PARENT, BRANCHTYPE
		  FROM ORG_BRANCH
		 WHERE BRANCHID = @Branch
		 UNION ALL
		SELECT A.BRANCHID, A.BRANCH_NM, A.PARENT, A.BRANCHTYPE
		  FROM ORG_BRANCH A
		  JOIN BranchesCTE s ON a.PARENT = s.BRANCHID 
	) 

	SELECT ST.STOREID,    
           ST.ORGANIZATION,    
           ST.DELETED_FL,    
           ST.CREATE_DT,    
           ST.UPDATE_DT,    
           ST.CREATEUSER,    
           ST.UPDATEUSER,    
           ST.STORE_NM,    
           ST.BRANCH,    
           ST.IPADDRESS_TXT,    
           ST.ADVANCE_AMT,    
           ST.OPENING_DT,    
           ST.CLOSING_DT,    
           ST.ACTIVE_FL,    
           ST.PRODUCTION_FL,    
           ST.CITY,    
		   CT.CITY_NM,  
           ST.TOWN,    
		   T.TOWN_NM,  
           ST.ADDRESS_TXT,    
           ST.REGIONMANAGER,    
		   RM.MANAGER_NM,  
           ST.INCONSTRUCTION_FL,
		   LASTSIP.VALUE_TXT LASTORDERENTRY_TXT,
		   @BranchType USERBRANCHTYPE_NM,
		   @Department DEPARTMENT_NM,
		   TERMINAL_CNT
	  FROM BranchesCTE C 
	  JOIN ORG_BRANCHTYPE BT ON C.BRANCHTYPE = BT.BRANCHTYPEID
	  JOIN STR_STORE ST ON C.BRANCHID = ST.BRANCH
	  LEFT JOIN STR_CITY CT (NOLOCK) ON ST.CITY = CT.CITYID  
	  LEFT JOIN STR_TOWN T (NOLOCK) ON ST.TOWN = T.TOWNID  
	  LEFT JOIN STR_REGIONMANAGERS RM (NOLOCK) ON ST.REGIONMANAGER = RM.REGIONMANAGERSID  
	  LEFT JOIN (SELECT STORE, VALUE_TXT FROM STR_PROPERTY WHERE PROPERTYTYPE = 1) LASTSIP ON ST.STOREID = LASTSIP.STORE
	  LEFT JOIN (SELECT STORE, COUNT(*) TERMINAL_CNT FROM STR_CASHREGISTER WHERE DELETED_FL = 'N' GROUP BY STORE) CR ON ST.STOREID = CR.STORE
	 WHERE BT.BRANCHTYPE_NM = 'Branch'
	   AND ST.ACTIVE_FL = 'Y'
	   AND ST.DELETED_FL = 'N'

END