CREATE PROCEDURE STR_LST_STORESCALES_SP @StoreId INT AS
BEGIN
SELECT B.SCALEBRANDID, B.BRAND_NM, B.COMMENT_DSC, MAX(S.PRICEFILEPATH_TXT) PRICEFILEPATH_TXT
  FROM STR_SCALE S
  JOIN STR_SCALEMODEL M ON S.SCALEMODEL = M.SCALEMODELID
  JOIN STR_SCALEBRAND B ON M.BRAND = B.SCALEBRANDID
 WHERE STORE = @StoreId
 GROUP BY B.SCALEBRANDID, B.BRAND_NM, B.COMMENT_DSC
END