-- Created by OverGenerator
/*Section="Main"*/
CREATE PROCEDURE [dbo].[STR_DEL_SCALE_SP]
    @StoreScalesId INT
AS
BEGIN

	  INSERT INTO STR_SCALELOG	
	  (SCALEID
		, LOG_DT
		, LOGUSER
		, LOGOPERATION_CD
		, LOGCHANNEL
		, LOGBRANCH
		, LOGSCREEN
		, SCALE_NM
		, STORE
		, SCALEMODEL
		, PRICEFILEPATH_TXT
		, CURRENTPRICEVERSION
		, CURRENTPRICELOAD_TM
		, PRIVATEPRICEVERSION
		, PRIVATEPRICELOAD_TM
		, CREATEPRICEFILE_FL
		, IPADDRESS_TXT
		, STATUS_FL
		, STATUS_TXT
		, SERIAL_TXT
		, SEALVALID_DT)
	  SELECT  S.SCALEID,	GETDATE(),  dbo.SYS_GETCURRENTUSER_FN(),  'DEL',  dbo.SYS_GETCURRENTCHANNEL_FN(),  
			  dbo.SYS_GETCURRENTBRANCH_FN(),  dbo.SYS_GETCURRENTSCREEN_FN(),  S.SCALE_NM,
			  S.STORE, S.SCALEMODEL, S.PRICEFILEPATH_TXT, S.CURRENTPRICEVERSION, S.CURRENTPRICELOAD_TM, S.PRIVATEPRICEVERSION,
			  S.PRIVATEPRICELOAD_TM, S.CREATEPRICEFILE_FL, S.IPADDRESS_TXT, S.STATUS_FL, S.STATUS_TXT, S.SERIAL_TXT, S.SEALVALID_DT
	     FROM STR_SCALE S (NOLOCK)  
        WHERE S.SCALEID = @StoreScalesId;  

    /*Section="Delete"*/
    SET NOCOUNT OFF
    -- Update the DELETED_FL to 'Y'
    UPDATE STR_SCALE
       SET DELETED_FL = 'Y',
           UPDATE_DT = GETDATE()
     WHERE SCALEID = @StoreScalesId

    /*Section="Check"*/
    -- Check the deleted/updated row count
    IF @@ROWCOUNT = 0
    BEGIN
        SET NOCOUNT ON;
        THROW 100001, 'Nothing deleted. Delete failed.', 1;
        RETURN;
    END;
    SET NOCOUNT ON;

/*Section="End"*/
END;