CREATE PROCEDURE STR_LST_CATEGORYSALES_SP WITH RECOMPILE AS
BEGIN          
          
  DECLARE @today DATE = dbo.STR_GETUSERCURRENTDATE_FN(); 
    
  IF OBJECT_ID('tempdb..#stores') IS NOT NULL DROP TABLE #stores
  SELECT STOREID, STORE_NM INTO #stores FROM dbo.STR_GETUSERSTORES_FN();
      
  SELECT SD.STORE, ST.STORE_NM
       , PF.SUBGROUP_NM CATEGORY
       , C.CATEGORY_NM PRODUCTFAMILY_NM
	   , C.COLOR_CD
	   , SUM(PRICE) NET
    FROM SLS_SALEDETAIL (NOLOCK) SD
    JOIN PRD_PRODUCT P (NOLOCK) on SD.PRODUCT = P.PRODUCTID
    JOIN #stores (NOLOCK) ST on SD.STORE = ST.STOREID
    LEFT JOIN PRD_SUBGROUP (NOLOCK) PF on P.SUBGROUP = PF.SUBGROUPID
    LEFT JOIN PRD_CATEGORY (NOLOCK) C on pf.CATEGORY = C.CATEGORYID
   WHERE SD.TRANSACTION_DT = @today
     AND SD.CANCEL_FL = 'N'
   GROUP BY SD.STORE, ST.STORE_NM
       , PF.SUBGROUP_NM
	   , C.CATEGORY_NM
	   , C.COLOR_CD
END;