CREATE PROCEDURE [dbo].[STR_LST_STORESUMMARYREPORT_SP]          
 AS          
  BEGIN    IF OBJECT_ID('tempdb.dbo.#TMPSCL', 'U') IS NOT NULL  DROP TABLE #TMPSCL;          
  SELECT C.STORE,          
   MAX(M.MODEL_NM) MODELNM,          
   SUM(CASE C.STATUS_FL WHEN 'Y' THEN 1 ELSE 0 END)  STATUSCNT,          
   COUNT(C.SCALEID) SCALECNT   INTO #TMPSCL          
   FROM STR_SCALE C JOIN STR_SCALEMODEL M  ON C.SCALEMODEL=M.SCALEMODELID          
   WHERE C.DELETED_FL ='N'   GROUP BY C.STORE    
           
   SELECT B.*,  
   B.[Son Sipariş Giriş Saati] AS LASTORDERTIME ,  
   B.[Satış Kontrol Gün Sayısı] AS CONTROLDAY_CNT    
   FROM ( SELECT S.STOREID, S.STORE_NM, S.BRANCH, S.IPADDRESS_TXT,   S.ADVANCE_AMT, S.OPENING_DT, S.CLOSING_DT, S.ACTIVE_FL,          
   S.PRODUCTION_FL, S.CITY, S.TOWN, S.ADDRESS_TXT, S.INCONSTRUCTION_FL,PP.PROPERTYTYPE_NM,P.VALUE_TXT,C.*,V.TERMINAL,W.SCHEDULE_TXT,CIT.CITY_NM,TOW.TOWN_NM           
   FROM STR_STORE S            
   JOIN #TMPSCL C ON S.STOREID=C.STORE            
   JOIN STR_STORE_VW V ON V.ACTIVE_FL='Y' AND S.STOREID=V.STOREID             
   JOIN STR_PROPERTY P ON P.STORE=S.STOREID           
   JOIN STR_PROPERTYTYPE PP ON P.PROPERTYTYPE=PP.PROPERTYTYPEID            
   JOIN WHS_SHIPMENTSCHEDULE W ON  S.STOREID=W.STORE     
   LEFT JOIN STR_CITY CIT ON CIT.CITYID=S.CITY  
   LEFT JOIN STR_TOWN TOW ON TOW.TOWNID=S.TOWN       
          
          
 WHERE S.DELETED_FL='N'   ) A            
    PIVOT  (          
    max(A.VALUE_TXT )          
    FOR A.PROPERTYTYPE_NM IN( [Son Sipariş Giriş Saati],          
                           [Satış Kontrol Gün Sayısı])) B          
 END