CREATE PROCEDURE [dbo].[STR_LST_POSMOVE_SP] AS
BEGIN
	
	DECLARE @startDate DATE = CONVERT(DATE, '20010101', 112); 
	IF OBJECT_ID('tempdb..#stores') IS NOT NULL DROP TABLE #stores
	SELECT STOREID INTO #stores FROM dbo.STR_GETUSERSTORES_FN()

    DECLARE @Organization INT;
    SELECT @Organization = dbo.SYS_GETCURRENTORGANIZATION_FN();
    IF dbo.SYS_ISSYSTEMORGANIZATION_FN() = 1
    BEGIN
      SET @Organization = null;
    END

	SELECT * 
	  FROM (
    SELECT P.POSMOVEID,
           P.POSID,
           P.ORGANIZATION,
           P.DELETED_FL,
           P.MOVE_TM,
           P.STORE,
           P.CREATE_DT,
           P.UPDATE_DT,
           P.CREATEUSER,
           P.UPDATEUSER,
		   LAG(P.STORE) OVER (PARTITION BY P.POSID ORDER BY P.MOVE_TM) LAGSTORE
      FROM STR_POSMOVE P (NOLOCK)
	  JOIN STR_POS PS (NOLOCK) ON P.POSID = PS.POSID
	  LEFT JOIN #stores ST ON PS.STORE = ST.STOREID
	  LEFT JOIN #stores ST2 ON P.STORE = ST2.STOREID
     WHERE (@Organization IS NULL OR P.ORGANIZATION = @Organization)
       AND P.DELETED_FL = 'N'
	   AND PS.MOBIL_FL = 'Y'
	   AND (ST.STOREID IS NOT NULL OR ST2.STOREID IS NOT NULL))A
	 WHERE MOVE_TM != @startDate
	 ORDER BY MOVE_TM DESC;

END