CREATE PROCEDURE [dbo].[STR_LST_USERSCALE_SP] AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;
	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();

	SELECT SC.*
	  FROM STR_SCALE SC
	  JOIN #STORES ST ON SC.STORE = ST.STOREID
END