CREATE PROCEDURE STR_INS_TERMINAL_SP @TerminalName VARCHAR(100), @StoreId INT AS
BEGIN

	DECLARE @COUNT INT = 0;
	DECLARE @TERMID INT = 0;
	SELECT @COUNT = COUNT(*) FROM DST_TERMINAL WHERE HOST_NM = @TerminalName
	IF @COUNT = 0 
	BEGIN
	  INSERT INTO DST_TERMINAL VALUES (1, 'N', getdate(), null, 1, null, @TerminalName, NULL, 1);
	  SELECT @TERMID = TERMINALID FROM DST_TERMINAL WHERE HOST_NM = @TerminalName

	  INSERT INTO DST_REPLICA VALUES (@TERMID, 2, getdate(), 1,1,1, 158, 'D:\DAEMON\Overtech.Daemons.OverStore.Store.P1', null, 30, null, null, 1);

	  INSERT INTO STR_TERMINAL (ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, TERMINAL_NO, STORE)
	  VALUES (1, 'N', GETDATE(), 1, @TERMID, @StoreId)
	END

END