CREATE PROCEDURE STR_SEL_REGIONMANAGERS_SP
    @RegionManagersId INT
AS
BEGIN

    SELECT
           R.REGIONMANAGERSID,
           R.MANAGER_NM,
           R.TELNO_TXT,
           R.EMAIL_TXT,
           R.USERID,
           R.EXPENSEACCCODE_TXT,
		   R.MIKROPROJECTCODE_TXT
      FROM STR_REGIONMANAGERS R (NOLOCK)
     WHERE R.REGIONMANAGERSID = @RegionManagersId;

END;