CREATE FUNCTION [dbo].[WHS_ORDERSUGGESTION_FN] (@StoreID INT, @RefDate DATE) RETURNS TABLE AS
RETURN

WITH STORESHIPDAYS AS (
	SELECT STORE, 1 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,1,1) = 1 
	UNION ALL
	SELECT STORE, 2 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,3,1) = 1 
	UNION ALL
	SELECT STORE, 3 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,5,1) = 1 
	UNION ALL
	SELECT STORE, 4 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,7,1) = 1 
	UNION ALL
	SELECT STORE, 5 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,9,1) = 1 
	UNION ALL
	SELECT STORE, 6 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,11,1) = 1 
	UNION ALL
	SELECT STORE, 7 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,13,1) = 1 ),

ORDERFREQ AS (
SELECT 7/COUNT(*) DAYCOUNT, MAX(DAYOFWEEK_NO) DAYOFWEEK_NO
  FROM STORESHIPDAYS 
  JOIN RPT_DATE DT ON DT.DATE_DT = @RefDate
 WHERE STORE = @StoreID),

TOCDATE AS
(SELECT TOC_DT
   FROM (
(SELECT TOC_DT, DAYCOUNT, SUM(OMITSUNDAY) OVER (ORDER BY TOC_DT DESC) SUMDAYS
   FROM (
 SELECT DISTINCT T.TOC_DT, 1 OMITSUNDAY, CASE WHEN FR.DAYOFWEEK_NO IN (1, 7) THEN DAYCOUNT + 1 ELSE DAYCOUNT END DAYCOUNT 
   FROM WHS_TOC T (NOLOCK) 
   JOIN RPT_DATE DT ON T.TOC_DT = DT.DATE_DT
   JOIN ORDERFREQ FR ON 1=1
  WHERE T.STORE = @StoreId
    AND TOC_DT <= @RefDate) A)) B
  WHERE SUMDAYS <= DAYCOUNT)

SELECT TD.DETAILPRODUCT PRODUCT, SUM(TD.ORDER_QTY)/MAX(SU.PACKAGE_QTY) ORDER_QTY, MAX(SU.PACKAGE_QTY) ORDERUNIT_QTY
  FROM WHS_TOC T 
  JOIN WHS_TOCDETAIL TD (NOLOCK) ON T.TOCID = TD.TOCID
  JOIN TOCDATE TDT ON T.TOC_DT = TDT.TOC_DT
  LEFT JOIN PRD_PROPERTY PP ON TD.DETAILPRODUCT = PP.PRODUCT AND PP.PROPERTYTYPE = 4 AND VALUE_TXT = '1'
  JOIN (SELECT PRODUCT, MAX(PACKAGE_QTY) PACKAGE_QTY FROM WHS_PRODUCTSHIPMENTUNIT WHERE SHIPMENTTYPE = 1 GROUP BY PRODUCT HAVING MAX(PACKAGE_QTY) != 0) SU ON SU.PRODUCT = TD.DETAILPRODUCT
 WHERE T.STORE = @StoreId
   AND PP.PRODUCT IS NULL
 GROUP BY TD.DETAILPRODUCT