CREATE FUNCTION [dbo].[WHS_TOCSTORECOEFF_FN] (@RefDate DATE, @StoreId INT) RETURNS NUMERIC(6,2) AS
BEGIN

	DECLARE @returnValue NUMERIC(6,2);

	WITH STORESHIPDAYS AS (
		SELECT STORE, 1 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,1,1) = 1 
		UNION ALL
		SELECT STORE, 2 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,3,1) = 1 
		UNION ALL
		SELECT STORE, 3 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,5,1) = 1 
		UNION ALL
		SELECT STORE, 4 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,7,1) = 1 
		UNION ALL
		SELECT STORE, 5 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,9,1) = 1 
		UNION ALL
		SELECT STORE, 6 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,11,1) = 1 
		UNION ALL
		SELECT STORE, 7 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,13,1) = 1 ),
 
	DAYCALC AS (
		SELECT DATE_DT, NEXT_DT, DATEDIFF(DAY, DATE_DT, NEXT_DT) DIFF
		  FROM (
		SELECT DATE_DT, LEAD(DATE_DT) OVER (ORDER BY DATE_DT) NEXT_DT, ROW_NUMBER() OVER (ORDER BY DATE_DT) ROWNO
		  FROM RPT_DATE D
		  JOIN STORESHIPDAYS SD ON D.DAYOFWEEK_NO = SD.DAYOFWEEKNO
		 WHERE DATE_DT >= @RefDate
		   AND SD.STORE = @StoreID) A
		 WHERE ROWNO = 2)
	SELECT @returnValue = (DIFF/2.0) FROM DAYCALC;

	RETURN @returnValue 

END