CREATE FUNCTION [dbo].[WHS_TOCSUGGESTION_FN] (@StoreID INT, @RefDate DATE) RETURNS TABLE AS
RETURN

 WITH STORESHIPDAYS AS (
	SELECT STORE, 1 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,1,1) = 1 
	UNION ALL
	SELECT STORE, 2 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,3,1) = 1 
	UNION ALL
	SELECT STORE, 3 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,5,1) = 1 
	UNION ALL
	SELECT STORE, 4 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,7,1) = 1 
	UNION ALL
	SELECT STORE, 5 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,9,1) = 1 
	UNION ALL
	SELECT STORE, 6 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,11,1) = 1 
	UNION ALL
	SELECT STORE, 7 DAYOFWEEKNO FROM WHS_SHIPMENTSCHEDULE WHERE SUBSTRING(SCHEDULE_TXT,13,1) = 1 ),
 
DAYCALC AS (
	SELECT DATE_DT, NEXT_DT, DATEDIFF(DAY, DATE_DT, NEXT_DT) DIFF
	  FROM (
	SELECT DATE_DT, LEAD(DATE_DT) OVER (ORDER BY DATE_DT) NEXT_DT, ROW_NUMBER() OVER (ORDER BY DATE_DT) ROWNO
	  FROM RPT_DATE D
	  JOIN STORESHIPDAYS SD ON D.DAYOFWEEK_NO = SD.DAYOFWEEKNO
	 WHERE DATE_DT >= @RefDate
	   AND SD.STORE = @StoreID) A
	 WHERE ROWNO = 2),

TOC AS
  (SELECT T.*
	 FROM WHS_TOC T (NOLOCK) 
	 JOIN DAYCALC ON 1=1
	WHERE TOC_DT BETWEEN DATEADD(DAY, -1*DIFF+1, @RefDate) AND @RefDate AND STORE = @StoreId)

	SELECT @StoreId STORE, T.PRODUCT, PG.PRODUCT_NM, DATE_DT, NEXT_DT, DIFF, PG.PRICE_AMT
		 , AVG(T.GREENLIMIT_QTY) GREENLIMIT_QTY
		 , AVG(T.YELLOWLIMIT_QTY) YELLOWLIMIT_QTY
		 , AVG(T.REDLIMIT_QTY) REDLIMIT_QTY
		 , AVG(T.STOCK_QTY) STOCK_QTY
		 , SUM(T.SALE_QTY) SALE_QTY
		 , SUM(T.INTAKE_QTY) INTAKE_QTY
		 , ISNULL(SUM(TD.ORDER_QTY),0) SUGGESTION_QTY, MAX(PG.PACKAGE_QTY) PACKAGE_QTY
	  FROM TOC T 
	  JOIN PRD_PRODUCTGROUP_VW PG ON T.PRODUCT = PG.PRODUCTID
	  LEFT JOIN WHS_TOCDETAIL TD (NOLOCK) ON T.TOCID = TD.TOCID
	  JOIN DAYCALC DC ON 1=1
	 WHERE T.STORE = @StoreId
	 GROUP BY PG.PRODUCT_NM, T.PRODUCT, DATE_DT, NEXT_DT, DIFF, PG.PRICE_AMT