CREATE FUNCTION WHS_PRODUCTRETURNSTATUS_FN() RETURNS TABLE AS 
RETURN
    SELECT 1 STATUS_CD, 'Giriş' STATUS_NM
	 UNION ALL
    SELECT 2 STATUS_CD, 'Onaylandı' STATUS_NM
	 UNION ALL
    SELECT 3 STATUS_CD, 'Sevk Edildi' STATUS_NM
	 UNION ALL
    SELECT 4 STATUS_CD, 'Kabul Edildi' STATUS_NM
	 UNION ALL
    SELECT 6 STATUS_CD, 'Reddedildi' STATUS_NM
	 UNION ALL
    SELECT 7 STATUS_CD, 'İptal' STATUS_NM