CREATE PROCEDURE PRC_LST_CURRENTPRICE_SP    
AS    
BEGIN    
    SELECT C.CURRENTPRICEID,    
           C.STORE,    
           C.PRODUCTCODE_NM,    
           C.PRODUCT_NM,    
           C.BARCODE_TXT,    
           C.PRODUCTUNIT_NO,    
           C.SALEPRICE_AMT,    
           C.SALEVAT_RT,    
           C.VERSION_TM,    
           C.GROUP_CD,    
		   ST.STORE_NM,  
		   U.UNIT_NM,  
		   CASE C.GROUP_CD   
		   WHEN 1 THEN 'KASA'  
		   WHEN 2 THEN 'TERAZİ'  
		   ELSE 'DİĞER'  
		   END GROUPCODE_NM,
		   C.PACKAGE,
		   PP.PACKAGE_NM
      FROM PRC_CURRENTPRICE C (NOLOCK)    
	  JOIN STR_STORE_VW ST (NOLOCK) ON C.STORE = ST.STOREID    
	  LEFT JOIN PRD_UNIT U (NOLOCK) ON C.PRODUCTUNIT_NO = U.UNITID  
	  LEFT JOIN PRC_PACKAGE PP ON C.PACKAGE = PP.PACKAGEID
     ORDER BY C.STORE, C.GROUP_CD, C.VERSION_TM DESC;    
END;