CREATE PROCEDURE [dbo].[PRC_UPD_SCALEVERSION_SP]   
 @StoreId INT,  
 @PrivateVersionId INT,  
 @CurrentVersionId INT AS  
BEGIN    
    
 UPDATE STR_SCALE  
 SET PRIVATEPRICEVERSION = CASE WHEN @PrivateVersionId = -1 THEN PRIVATEPRICEVERSION ELSE @PrivateVersionId END  
   , PRIVATEPRICELOAD_TM = CASE WHEN @PrivateVersionId = -1 THEN PRIVATEPRICELOAD_TM ELSE GETDATE()  END   
   , CURRENTPRICEVERSION = CASE WHEN @CurrentVersionId = -1 THEN CURRENTPRICEVERSION ELSE @CurrentVersionId END   
   , CURRENTPRICELOAD_TM = CASE WHEN @CurrentVersionId = -1 THEN CURRENTPRICELOAD_TM ELSE GETDATE() END   
  WHERE STORE = @StoreId  
  
END