CREATE PROCEDURE [dbo].[PRC_UPD_WINCORCRVERSIONS_SP] AS  
BEGIN  
    
 IF OBJECT_ID('tempdb..#STOREPACKAGES') IS NOT NULL DROP TABLE #STOREPACKAGES  
  
 DECLARE @now DATETIME = getdate();  
 SELECT *   
   INTO #STOREPACKAGES  
   FROM (  
 SELECT SP.STORE, ST.STORE_NM, SP.PACKAGE, PP.PACKAGE_NM, PV2.VERSIONID  
   , CASE WHEN SP.PACKAGE = 1 THEN CR.CURRENTPRICEVERSION ELSE CR.PRIVATEPRICEVERSION END STOREVERSION  
   , ROW_NUMBER() OVER (PARTITION BY SP.STORE ORDER BY SP.PRIORITY_NO DESC) PRIORITY_NO  
   FROM PRC_STOREPACKAGE SP  
   JOIN STR_STORE ST ON SP.STORE = ST.STOREID  
   JOIN PRC_PACKAGE PP ON SP.PACKAGE = PP.PACKAGEID  
   JOIN STR_CASHREGISTER CR ON SP.STORE = CR.STORE  
   JOIN STR_CASHREGISTERMODEL M ON CR.CASHREGISTERMODEL = M.CASHREGISTERMODELID  
   JOIN STR_CASHREGISTERBRAND B ON M.BRAND = B.CASHREGISTERBRANDID  
   LEFT JOIN (SELECT PACKAGE, MAX(PV.PACKAGEVERSIONID) VERSIONID FROM PRC_PACKAGEVERSION PV WHERE PV.ACTIVE_FL = 'Y' GROUP BY PACKAGE) PV2 ON SP.PACKAGE = PV2.PACKAGE  
  WHERE B.BRAND_NM = 'Wincor'  
    AND SP.DELETED_FL = 'N'
	AND PP.DELETED_FL = 'N'
    AND @now BETWEEN SP.START_TM AND SP.END_TM) A  
  WHERE COALESCE(VERSIONID, -1) != COALESCE(STOREVERSION, -1)  
    AND PRIORITY_NO = 1  
  
 UPDATE CR   
    SET CR.CURRENTPRICEVERSION = VERSIONID  
	  , CR.CURRENTPRICELOAD_TM = GETDATE()  
   FROM #STOREPACKAGES SP  
   JOIN STR_CASHREGISTER CR ON SP.STORE = CR.STORE  
   JOIN STR_CASHREGISTERMODEL M ON CR.CASHREGISTERMODEL = M.CASHREGISTERMODELID  
   JOIN STR_CASHREGISTERBRAND B ON M.BRAND = B.CASHREGISTERBRANDID  
  WHERE B.BRAND_NM = 'Wincor'  
    AND SP.PACKAGE = 1  
  
 UPDATE CR   
    SET CR.PRIVATEPRICEVERSION = VERSIONID  
	  , CR.PRIVATEPRICELOAD_TM = GETDATE()  
   FROM #STOREPACKAGES SP  
   JOIN STR_CASHREGISTER CR ON SP.STORE = CR.STORE  
   JOIN STR_CASHREGISTERMODEL M ON CR.CASHREGISTERMODEL = M.CASHREGISTERMODELID  
   JOIN STR_CASHREGISTERBRAND B ON M.BRAND = B.CASHREGISTERBRANDID  
  WHERE B.BRAND_NM = 'Wincor'  
    AND SP.PACKAGE != 1  
  
END