CREATE PROCEDURE PRC_RPT_PRICECHANGE_SP @StartDate DATE, @EndDate DATE, @Product INT AS
BEGIN
	
	IF OBJECT_ID('tempdb..#CAMPAIGNS') IS NOT NULL DROP TABLE #CAMPAIGNS
	IF OBJECT_ID('tempdb..#PRICECHANGES') IS NOT NULL DROP TABLE #PRICECHANGES
	IF OBJECT_ID('tempdb..#PRICES') IS NOT NULL DROP TABLE #PRICES

	SELECT *, ROW_NUMBER() OVER (PARTITION BY DATE_DT, PRODUCT ORDER BY STORE_CNT DESC) ROWNO
	  INTO #CAMPAIGNS
	  FROM (
	SELECT DT.DATE_DT, PC.PRODUCT, PC.PRICE_AMT, COUNT(DISTINCT STOREID) STORE_CNT
	  FROM PRC_PRICECHANGE_VW PC
	  JOIN PRC_STOREPACKAGE SP ON PC.PACKAGE = SP.PACKAGE
	  JOIN RPT_DATE DT ON DT.DATE_DT BETWEEN DATEADD(DAY, 1, CAST(SP.START_TM - 0.5 AS DATE)) AND CAST(SP.END_TM - 0.5 AS date) 
	  JOIN STR_STORE ST ON DT.DATE_DT BETWEEN ST.OPENING_DT AND ISNULL(ST.CLOSING_DT, '2099-12-31') AND SP.STORE = ST.STOREID
	 WHERE PC.PACKAGE != 1
	   AND DT.DATE_DT BETWEEN @StartDate AND @EndDate
	   AND (@Product = -1 OR PC.PRODUCT = @Product)
	 GROUP BY DT.DATE_DT, PC.PRODUCT, PC.PRICE_AMT) A

	SELECT DT.DATE_DT, PC.PRODUCT, PC.PRICE_AMT LISTPRICE, C1.PRICE_AMT PRICE1, C1.STORE_CNT STORE1, 
		   C2.PRICE_AMT PRICE2, C2.STORE_CNT STORE2, C3.PRICE_AMT PRICE3, C3.STORE_CNT STORE3, 
		   C4.PRICE_AMT PRICE4, C4.STORE_CNT STORE4
	  INTO #PRICES
	  FROM PRC_PRICECHANGE_VW PC
	  JOIN RPT_DATE DT ON DT.DATE_DT BETWEEN START_DT AND END_DT
	  LEFT JOIN #CAMPAIGNS C1 ON DT.DATE_DT = C1.DATE_DT AND PC.PRODUCT = C1.PRODUCT AND C1.ROWNO = 1
	  LEFT JOIN #CAMPAIGNS C2 ON DT.DATE_DT = C1.DATE_DT AND PC.PRODUCT = C1.PRODUCT AND C1.ROWNO = 2
	  LEFT JOIN #CAMPAIGNS C3 ON DT.DATE_DT = C1.DATE_DT AND PC.PRODUCT = C1.PRODUCT AND C1.ROWNO = 3
	  LEFT JOIN #CAMPAIGNS C4 ON DT.DATE_DT = C1.DATE_DT AND PC.PRODUCT = C1.PRODUCT AND C1.ROWNO = 4
	 WHERE DT.DATE_DT BETWEEN @StartDate AND @EndDate
	   AND PC.PACKAGE = 1
	   AND (@Product = -1 OR PC.PRODUCT = @Product)
	 ORDER BY 1

	SELECT *, ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY DATE_DT) ROWNO, LEAD(DATE_DT) OVER (PARTITION BY PRODUCT ORDER BY DATE_DT) LEADDATE_DT
	  INTO #PRICECHANGES
	  FROM (
	SELECT P.*, P2.DATE_DT NEWPRICE_DT, P2.LISTPRICE NEWLISTPRICE, P2.PRICE1 NEWPRICE1, P2.STORE1 NEWSTORE1,
		   P2.PRICE2 NEWPRICE2, P2.STORE2 NEWSTORE2, P2.PRICE3 NEWPRICE3, P2.STORE3 NEWSTORE3,
		   P2.PRICE4 NEWPRICE4, P2.STORE4 NEWSTORE4
	  FROM #PRICES P
	  JOIN #PRICES P2 ON P.PRODUCT = P2.PRODUCT AND P2.DATE_DT = DATEADD(DAY, 1, P.DATE_DT)
	 WHERE P.LISTPRICE != P2.LISTPRICE OR ISNULL(P.PRICE1, 0) != ISNULL(P2.PRICE1, 0)
		OR ISNULL(P.PRICE2, 0) != ISNULL(P2.PRICE2, 0)
		OR ISNULL(P.PRICE3, 0) != ISNULL(P2.PRICE3, 0)
		OR ISNULL(P.PRICE4, 0) != ISNULL(P2.PRICE4, 0)) A
 
	SELECT @StartDate START_DT, DATE_DT END_DT, P.CODE_NM, P.NAME_NM, LISTPRICE, PRICE1, STORE1, PRICE2, STORE2, PRICE3, STORE3, PRICE4, STORE4
	  FROM #PRICECHANGES PC
	  JOIN PRD_PRODUCT P ON PC.PRODUCT = P.PRODUCTID
	 WHERE ROWNO = 1
	 UNION ALL
	SELECT NEWPRICE_DT, ISNULL(LEADDATE_DT, @EndDate), P.CODE_NM, P.NAME_NM, NEWLISTPRICE, NEWPRICE1, NEWSTORE1, NEWPRICE2, NEWSTORE2, NEWPRICE3, NEWSTORE3, NEWPRICE4, NEWSTORE4
	  FROM #PRICECHANGES PC
	  JOIN PRD_PRODUCT P ON PC.PRODUCT = P.PRODUCTID
     ORDER BY 3, 1
 
END