CREATE PROCEDURE PRC_SEL_LASTPACKAGEVERSION_SP  @PackageId INT AS  
BEGIN  
    
	SELECT MAX(PACKAGEVERSIONID) MAXPACKAGEVERSION FROM PRC_PACKAGEVERSION WHERE PACKAGE = @PackageId AND DELETED_FL = 'N'
    
END;  