CREATE PROCEDURE PRC_LST_PRICELOADSTATUS_SP AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#changes', 'U') IS NOT NULL  DROP TABLE #changes;
	IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
	
	SELECT STOREID into #stores FROM dbo.STR_GETUSERSTORES_FN();
	-- SELECT STOREID into #stores FROM STR_STORE_VW;
	
	SELECT ST.STOREID, ST.STORE_NM, ST.SCALE, ST.TERMINAL, CP.GROUP_CD, MAX(VERSION_TM) - (1/(24*12.0)) CHANGE_TM
	  INTO #changes
	  FROM PRC_CURRENTPRICE CP
	  JOIN STR_STORE_VW ST ON CP.STORE = ST.STOREID
	  JOIN #stores s ON ST.STOREID = s.STOREID
	 GROUP BY ST.STOREID, ST.STORE_NM, ST.SCALE, ST.TERMINAL, CP.GROUP_CD

	SELECT *
	  FROM (
	SELECT STOREID, STORE_NM, BRAND_NM DEVICE, IPADDRESS_TXT, COUNT(*) DEVICE_CNT
		 , SUM(CASE WHEN STATUS_FL = 'Y' AND LOAD_TM >= CHANGE_TM THEN 1 ELSE 0 END)  LOADOK_CNT
		 , SUM(CASE WHEN STATUS_FL = 'N' OR LOAD_TM < CHANGE_TM THEN 1 ELSE 0 END)  LOADNOTOK_CNT
		 , MAX(LOAD_TM) LOAD_TM
	  FROM (
	SELECT c.*, B.BRAND_NM, S.IPADDRESS_TXT, S.STATUS_FL, S.STATUS_TXT, dbo.STR_EXTRACTTIMEFROMSTATUS_FN(S.STATUS_TXT, B.BRAND_NM) LOAD_TM
	  FROM STR_SCALE S
	  JOIN STR_SCALEMODEL M ON S.SCALEMODEL = M.SCALEMODELID
	  JOIN STR_SCALEBRAND B ON M.BRAND = B.SCALEBRANDID
	  JOIN #changes c ON S.STORE = c.STOREID
	 WHERE S.DELETED_FL = 'N'
	   AND c.GROUP_CD = 2) A
	 GROUP BY STOREID, STORE_NM, SCALE, IPADDRESS_TXT, BRAND_NM
	 UNION ALL
	SELECT STOREID, STORE_NM, TERMINAL, CASHREGISTERID, COUNT(*) TERMINAL_CNT
		 , SUM(CASE WHEN STATUS_FL = 'Y' AND LOAD_TM >= CHANGE_TM THEN 1 ELSE 0 END)  LOADOK_CNT
		 , SUM(CASE WHEN STATUS_FL = 'N' OR LOAD_TM < CHANGE_TM THEN 1 ELSE 0 END)  LOADNOTOK_CNT
		 , MAX(LOAD_TM) LOAD_TM
	  FROM (
	SELECT c.*, CAST(S.CASHREGISTERID AS VARCHAR(100)) CASHREGISTERID, S.STATUS_FL, S.STATUS_TXT, dbo.STR_EXTRACTTIMEFROMSTATUS_FN(S.STATUS_TXT, c.TERMINAL) LOAD_TM
	  FROM STR_CASHREGISTER S
	  JOIN #changes c ON S.STORE = c.STOREID
	 WHERE S.DELETED_FL = 'N'
	   AND c.GROUP_CD = 1
	   AND c.TERMINAL = 'Wincor') A
	 GROUP BY STOREID, STORE_NM, TERMINAL, CASHREGISTERID) B

END