CREATE PROCEDURE PRC_LST_PRICECHECKEDLABEL_SP  @StoreId  INT,  @PSIZE  VARCHAR(8) AS
BEGIN
  -- Initializing parameters
  DECLARE @StartDate DATE = DATEADD(DAY, -14, GETDATE())
		, @EndDate DATE = GETDATE()+1;

  -- Temp Tables              
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN() WHERE @StoreId <= 0 OR @StoreId IS NULL OR STOREID = @StoreId;
  -- SELECT * into #stores FROM STR_STORE WHERE @StoreId <= 0 OR @StoreId IS NULL OR STOREID = @StoreId ;

  -- Main Query
  SELECT A.PRODUCT PRODUCTID FROM (
	  SELECT C.STORE, COALESCE(PP.PRODUCTID, P.PRODUCTID) PRODUCT
		   , SUM(CASE WHEN L.LABELPRINTID IS NOT NULL AND L.LABELSIZE_TXT = @PSIZE THEN 1 ELSE 0 END) PRINTEDSIZE
	  FROM PRC_CURRENTPRICE C (NOLOCK)
	  JOIN PRD_PRODUCT P ON C.PRODUCTCODE_NM = P.CODE_NM
	  LEFT JOIN PRD_PRODUCT PP ON P.PRODUCTID = PP.PARENT
	  JOIN #stores ST ON ST.STOREID = C.STORE AND ST.DELETED_FL = 'N' AND ST.ACTIVE_FL = 'Y'
	  LEFT JOIN PRC_LABELPRINT L ON COALESCE(PP.PRODUCTID, P.PRODUCTID) = L.PRODUCT AND C.CURRENTPRICEID = L.CURRENTPRICE
	 WHERE C.GROUP_CD = 1
	   AND C.VERSION_TM BETWEEN @StartDate AND @EndDate
	 GROUP BY C.STORE, COALESCE(PP.PRODUCTID, P.PRODUCTID)
 ) A
 WHERE A.PRINTEDSIZE = 0;

END