CREATE PROCEDURE PRC_LST_PRINTEDLABELDETAILS_SP
  @Store INT = -1,
  @StartDate DATE = NULL,
  @EndDate DATE = NULL AS
BEGIN  
  -- Initializing parameters
  IF @StartDate IS NULL
  SET @StartDate = DATEADD(DAY, -14, GETDATE());
  IF @EndDate IS NULL                  
  SET @EndDate = GETDATE()+1;
                
  -- Temp Tables              
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN() WHERE @Store <= 0 OR @Store IS NULL OR STOREID = @Store;
  -- SELECT * into #stores FROM STR_STORE WHERE @Store <= 0 OR @Store IS NULL OR STOREID = @Store ;

  SELECT C.STORE
	   , COALESCE(PP.PRODUCTID, P.PRODUCTID) PRODUCT
	   , COALESCE(PP.NAME_NM, P.NAME_NM) PRODUCT_NM
	   , COALESCE(PP.CODE_NM, P.CODE_NM) PRODUCTCODE_NM
	   , MIN(C.SALEPRICE_AMT) SALEPRICE_AMT
       , SUM(CASE WHEN L.LABELPRINTID IS NOT NULL THEN 1 ELSE 0 END) PRINTED
	   , MIN(C.VERSION_TM) VERSION_TM
	   , MIN(L.CREATE_DT) PRINT_TM
  FROM PRC_CURRENTPRICE C
  JOIN PRD_PRODUCT P ON C.PRODUCTCODE_NM = P.CODE_NM
  LEFT JOIN PRD_PRODUCT PP ON P.PRODUCTID = PP.PARENT
  JOIN #stores ST ON ST.STOREID = C.STORE AND ST.DELETED_FL = 'N' AND ST.ACTIVE_FL = 'Y'
  LEFT JOIN PRC_LABELPRINT L (NOLOCK) ON COALESCE(PP.PRODUCTID, P.PRODUCTID) = L.PRODUCT AND C.CURRENTPRICEID = L.CURRENTPRICE
 WHERE C.GROUP_CD = 1
   AND C.VERSION_TM BETWEEN @StartDate AND @EndDate
 GROUP BY C.STORE, COALESCE(PP.PRODUCTID, P.PRODUCTID), COALESCE(PP.NAME_NM, P.NAME_NM), COALESCE(PP.CODE_NM, P.CODE_NM)
 HAVING SUM(CASE WHEN L.LABELPRINTID IS NOT NULL THEN 1 ELSE 0 END) = 0                      
END