CREATE PROCEDURE PRC_LST_PRICEHISTORYBYPRODUCT_SP @Product INT
AS
BEGIN
SELECT PC.*, U.USERFULL_NM FROM [PRC_PRICECHANGE_VW] PC
JOIN SEC_USER U ON U.USERID = PC.USERID
WHERE PC.PACKAGE = 1 AND PC.PRODUCT = @Product
END