CREATE PROCEDURE PRC_LST_STORECURRENTPRICE_SP @StoreId INT, @GroupCode INT AS    
BEGIN    
    SELECT C.*
      FROM PRC_CURRENTPRICE C (NOLOCK)    
	 WHERE C.STORE = @StoreId
	   AND C.GROUP_CD = @GroupCode
END;