
create  PROCEDURE [dbo].[PRC_LST_PRICEVERSIONS_SP]
	@StoreID int
AS

BEGIN

SELECT PV.PACKAGEVERSIONID PackageVersionID, 
		PV.VERSION_DT VersionDate, 
		P.PACKAGE_NM + ' - ' + CONVERT(VARCHAR,PV.VERSION_DT, 112) VersionName
  FROM PRC_PACKAGE P
  JOIN PRC_PACKAGEVERSION PV ON P.PACKAGEID = PV.PACKAGE
 WHERE PV.ACTIVE_FL = 'Y'
 ORDER BY PV.CREATE_DT DESC


END;


