CREATE VIEW PRC_ACTIVEPACKAGEPRICES_VW AS    
WITH ACTIVEVERSION AS    
(SELECT PACKAGE, MAX(PACKAGEVERSIONID) ACTIVEPACKAGEVERSIONID    
  FROM PRC_PACKAGEVERSION    
 WHERE ACTIVE_FL = 'Y'    
   AND DELETED_FL = 'N'    
 GROUP BY PACKAGE)   
SELECT PC.PRODUCTID PRICEID, PC.PACKAGE, AV.ACTIVEPACKAGEVERSIONID, PC.PRODUCT,     
	   PC.PRICE_AMT, PC.TOPPRICE_AMT, PC.PRINTTOPPRICE_FL  
  FROM ACTIVEVERSION AV 
  JOIN PRC_PRICECHANGE_VW PC
    ON PC.PACKAGE = AV.PACKAGE     
   AND AV.ACTIVEPACKAGEVERSIONID BETWEEN STARTVERSION AND ENDVERSION
