CREATE VIEW [dbo].[PRC_PRICECHANGE_VW] AS 
WITH PRICES AS (  
SELECT *, ROW_NUMBER() OVER (PARTITION BY PACKAGE, PRODUCT, PACKAGEVERSION ORDER BY LOG_DT DESC) ROWNO  
  FROM (SELECT L.PRODUCTID, L.TOPPRICE_AMT, L.PRINTTOPPRICE_FL, 
			   CAST((L.LOG_DT-0.5) AS DATE) LOG_DT, L.PACKAGEVERSION, L.LOGUSER, L.PACKAGE, L.PRODUCT, L.PRICE_AMT 
		  FROM PRC_PRODUCTLOG L
		  JOIN PRC_PRODUCT P ON L.PRODUCTID = P.PRODUCTID AND P.DELETED_FL = 'N'
		 UNION ALL  
		SELECT PRODUCTID, TOPPRICE_AMT, PRINTTOPPRICE_FL, CONVERT(DATE,'20991231', 112), PACKAGEVERSION, UPDATEUSER, PACKAGE, PRODUCT, PRICE_AMT FROM PRC_PRODUCT WHERE DELETED_FL = 'N') A )  
  
SELECT COALESCE(DATEADD(DAY, 1, MAX(LOG_DT) OVER (PARTITION BY PACKAGE, PRODUCT ORDER BY LOG_DT ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING)), CONVERT(DATE,'20000101', 112)) START_DT,  
	   A.LOG_DT END_DT,   
	   A.PACKAGEVERSION STARTVERSION,  
	   COALESCE(MAX(PACKAGEVERSION) OVER (PARTITION BY PACKAGE, PRODUCT ORDER BY LOG_DT ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING), 10000) - 1  ENDVERSION,  
	   COALESCE(MAX(LOGUSER) OVER (PARTITION BY PACKAGE, PRODUCT ORDER BY LOG_DT ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING), 1) USERID,   
	   PACKAGE, PRODUCT, PRICE_AMT, A.PRODUCTID, TOPPRICE_AMT, PRINTTOPPRICE_FL  
  FROM PRICES A  
  JOIN PRD_PRODUCT P ON A.PRODUCT = P.PRODUCTID  
 WHERE A.ROWNO = 1  
   AND P.PARENT IS NULL  
   AND P.DELETED_FL = 'N' 