CREATE VIEW PRC_SALEPRICE_VW AS
SELECT PRODUCT, PRICE_AMT, PRICE_AMT * 100.0 / (100.0 + SALEVAT_RT) PRICENOWAT_AMT
  FROM PRC_PRODUCT PR
  JOIN PRD_PRODUCT PP ON PR.PRODUCT = PP.PRODUCTID
 WHERE PACKAGE = 1 
   AND PR.DELETED_FL = 'N'
 UNION ALL
SELECT PP.PRODUCTID, PRICE_AMT, PRICE_AMT * 100.0 / (100.0 + SALEVAT_RT) PRICENOWAT_AMT 
  FROM PRC_PRODUCT PR
  JOIN PRD_PRODUCT PP ON PR.PRODUCT = PP.PARENT
 WHERE PR.PACKAGE = 1 
   AND PR.DELETED_FL = 'N'
 UNION ALL
SELECT 10000+SGN.STOCKGROUPID, MAX(SP.PRICE_AMT) PRICE_AMT, MAX(PRICE_AMT * 100.0 / (100.0 + SALEVAT_RT)) PRICENOWAT_AMT
  FROM PRD_STOCKGROUPNAME SGN 
  JOIN PRD_STOCKGROUP SG ON SGN.STOCKGROUPID = SG.STOCKGROUP
  JOIN PRC_PRODUCT SP ON SG.PRODUCTID = SP.PRODUCT AND SP.PACKAGE = 1 AND SP.DELETED_FL = 'N'
  JOIN PRD_PRODUCT PP ON SP.PRODUCT = PP.PRODUCTID
 WHERE USAGETYPE_CD = 1
 GROUP BY 10000+SGN.STOCKGROUPID