CREATE VIEW WHS_GATHERINGDETAIL_VW AS
WITH GATHERING AS (
SELECT STOREORDER, G.GATHERINGID, G.GATHERINGTYPE, GT.GATHERINGTYPE_NM, GD.STOREORDERDETAIL, GD.PALLET_NO, G.GATHERINGUSER, U1.USERFULL_NM GATHERINGUSER_NM
	 , G.GATHERINGSTATUS, GS.GATHERINGSTATUS_NM, G.GATHERINGSTART_TM, G.GATHERINGEND_TM, GD.GATHERED_QTY, GD.GATHERING_TM
	 , GP.CONTROLUSER, U2.USERFULL_NM CONTROLUSER_NM, GP.GATHERINGPALLETSTATUS, GPS.STATUS_NM PALLETSTATUS_NM, GD.CONTROL_QTY, GD.CONTROL_TM
	 , GP.CONTROLSTART_TM, GP.CONTROLEND_TM
  FROM WHS_GATHERING G (NOLOCK)
  JOIN WHS_GATHERINGDETAIL GD (NOLOCK) ON G.GATHERINGID = GD.GATHERING AND GD.DELETED_FL = 'N'
  JOIN WHS_GATHERINGTYPE GT (NOLOCK) ON G.GATHERINGTYPE = GT.GATHERINGTYPEID
  JOIN WHS_GATHERINGSTATUS GS (NOLOCK) ON G.GATHERINGSTATUS = GS.GATHERINGSTATUSID
  LEFT JOIN SEC_USER U1 (NOLOCK) ON G.GATHERINGUSER = U1.USERID
  LEFT JOIN WHS_GATHERINGPALLET2_VW GP (NOLOCK) ON G.GATHERINGID = GP.GATHERING AND GD.PALLET_NO = GP.PALLET_NO -- AND GP.DELETED_FL = 'N'
  LEFT JOIN WHS_GATHERINGPALLETSTATUS GPS (NOLOCK) ON GP.GATHERINGPALLETSTATUS = GPS.GATHERINGPALLETSTATUSID
  LEFT JOIN SEC_USER U2 (NOLOCK) ON GP.CONTROLUSER = U2.USERID
 WHERE G.DELETED_FL = 'N')
SELECT SOD.STOREORDER, SO.STATUS, SOD.STOREORDERDETAILID, G.GATHERINGID, G.GATHERINGTYPE, G.GATHERINGTYPE_NM, G.GATHERINGSTATUS, G.GATHERINGSTATUS_NM, G.GATHERINGSTART_TM, G.GATHERINGEND_TM
     , G.PALLET_NO, G.GATHERINGPALLETSTATUS, G.PALLETSTATUS_NM, G.CONTROLUSER, G.CONTROLUSER_NM, G.CONTROLSTART_TM, G.CONTROLEND_TM, SOD.PRODUCT
	 , P.CODE_NM PRODUCTCODE_NM, P.NAME_NM PRODUCT_NM, SP.PRICE_AMT, COALESCE(SOD.SHIPPED_QTY, SOD.REVISED_QTY, SOD.ORDER_QTY) ORDER_QTY
	 , G.GATHERED_QTY, G.CONTROL_QTY, G.GATHERING_TM, G.CONTROL_TM, G.GATHERINGUSER, G.GATHERINGUSER_NM 
	 , CASE ISNULL(GATHERINGSTATUS, 1) 
	   WHEN 1 THEN 10 -- Toplama Bekliyor
	   WHEN 2 THEN 20 -- Toplanıyor
	   WHEN 9 THEN 
			  CASE ISNULL(GATHERINGPALLETSTATUS, 1) 
			  WHEN 1 THEN 30 -- Kontrol Bekliyor
			  WHEN 2 THEN 40 -- Kontrol Ediliyor
			  WHEN 9 THEN 50 -- Kontrol Tamamlandı
			  ELSE 60 -- Tasnif dışı
			  END
	   ELSE 70 -- Tasnif dışı
	   END PROCESSSTATUS
  FROM WHS_STOREORDER SO (NOLOCK)
  JOIN WHS_STOREORDERDETAIL SOD (NOLOCK) ON SO.STOREORDERID = SOD.STOREORDER
  JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
  LEFT JOIN PRC_SALEPRICE_VW SP ON P.PRODUCTID = SP.PRODUCT
  LEFT JOIN GATHERING G ON SO.STOREORDERID = G.STOREORDER AND SOD.STOREORDERDETAILID = G.STOREORDERDETAIL
 WHERE COALESCE(SOD.SHIPPED_QTY, SOD.REVISED_QTY, SOD.ORDER_QTY) > 0
    OR G.CONTROL_QTY > 0