CREATE VIEW WHS_GATHERINGPALLET2_VW AS 
SELECT *
  FROM (
SELECT *, ROW_NUMBER() OVER (PARTITION BY GATHERING, PALLET_NO ORDER BY GATHERINGPALLETSTATUS DESC) ROWNO
  FROM WHS_GATHERINGPALLET
 WHERE DELETED_FL = 'N') A
 WHERE ROWNO = 1