CREATE VIEW [dbo].[WHS_ORDERSTATUSHISTORY_VW] AS 
SELECT STOREORDER
	 , MIN(CASE WHEN STATUS = 1 AND HISTORY_TM=MINHISTORY_TM THEN USERFULL_NM END) FIRSTENTRYUSER 
	 , MIN(CASE WHEN STATUS = 1 AND HISTORY_TM=MINHISTORY_TM THEN HISTORY_TM END) FIRSTENTRYTIME
	 , MIN(CASE WHEN STATUS = 2 AND HISTORY_TM=MAXHISTORY_TM THEN USERFULL_NM END) LASTAPPROVEUSER 
	 , MIN(CASE WHEN STATUS = 2 AND HISTORY_TM=MAXHISTORY_TM THEN HISTORY_TM END) LASTAPPROVETIME
	 , MIN(CASE WHEN STATUS = 3 AND HISTORY_TM=MAXHISTORY_TM THEN USERFULL_NM END) CONTROLUSER 
	 , MIN(CASE WHEN STATUS = 3 AND HISTORY_TM=MAXHISTORY_TM THEN HISTORY_TM END) CONTROLTIME
	 , MIN(CASE WHEN STATUS = 4 AND HISTORY_TM=MAXHISTORY_TM THEN USERFULL_NM END) DISPATCHUSER 
	 , MIN(CASE WHEN STATUS = 4 AND HISTORY_TM=MAXHISTORY_TM THEN HISTORY_TM END) DISPATCHTIME
  FROM (
SELECT STOREORDER, U.USERFULL_NM, STATUS, HISTORY_TM
	 , MIN(HISTORY_TM) OVER (PARTITION BY STOREORDER, STATUS ORDER BY HISTORY_TM DESC) MINHISTORY_TM
	 , MAX(HISTORY_TM) OVER (PARTITION BY STOREORDER, STATUS ORDER BY HISTORY_TM DESC) MAXHISTORY_TM
  FROM WHS_STOREORDERHISTORY H
  JOIN SEC_USER U ON H.CREATEUSER = U.USERID) A
 GROUP BY STOREORDER
