CREATE VIEW [dbo].[WHS_GATHERSUMMARY_VW] AS
	SELECT SOD.STOREORDER, G.GATHERINGUSER, G.GATHERINGTYPE, CAST(GD.GATHERING_TM AS DATE) GATHER_DT, DATEPART(HOUR, GATHERING_TM) GATHERHOUR, 
		   SUM(ISNULL(GATHERED_QTY, 0) * ORDERUNIT_QTY * WEIGHT_AMT / 1000.0) GATHERINGWEIGHT_QTY,
		   SUM(ISNULL(GATHERED_QTY, 0) * ORDERUNIT_QTY * SP.PRICE_AMT) GATHERPRICE_AMT,
		   SUM(ISNULL(GATHERED_QTY, 0)) GATHERPACKAGE_QTY,
		   COUNT(DISTINCT GD.PALLET_NO) GATHERPALLET_CNT,
		   COUNT(DISTINCT SOD.PRODUCT) GATHERPRODUCT_CNT
	  FROM WHS_GATHERINGDETAIL GD
	  JOIN WHS_GATHERING G ON GD.GATHERING = G.GATHERINGID
	  JOIN WHS_STOREORDERDETAIL SOD ON GD.STOREORDERDETAIL = SOD.STOREORDERDETAILID
	  JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
	  LEFT JOIN PRC_SALEPRICE_VW SP ON P.PRODUCTID = SP.PRODUCT
	 WHERE GD.DELETED_FL = 'N'
	 GROUP BY SOD.STOREORDER, G.GATHERINGUSER, G.GATHERINGTYPE, CAST(GD.GATHERING_TM AS DATE), DATEPART(HOUR, GATHERING_TM)
