CREATE VIEW WHS_STOCKTAKINGRESULT_VW AS    
WITH COUNTINGDATES AS     
(SELECT STORE, STOCKTAKINGSCHEDULEID, ACTUAL_DT, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY ACTUAL_DT DESC) ROWNO    
   FROM WHS_STOCKTAKINGSCHEDULE    
  WHERE COUNTINGTYPE = 1    
    AND STATUS = 2
	AND DELETED_FL = 'N')     
SELECT CD.STORE, COALESCE(PP.PRODUCTID, P.PRODUCTID) PRODUCT, CD.ACTUAL_DT DATE_DT, SUM(COUNTINGVALUE_AMT) COUNTINGVALUE_AMT    
  FROM WHS_STOCKTAKING ST    
  JOIN PRD_PRODUCT P ON ST.PRODUCT = P.PRODUCTID  
  LEFT JOIN PRD_PRODUCT PP ON P.PARENT = PP.PRODUCTID  
  JOIN COUNTINGDATES CD ON ST.STOCKTAKINGSCHEDULE  = CD.STOCKTAKINGSCHEDULEID    
 WHERE CD.ROWNO = 1    
   AND ST.DELETED_FL = 'N'    
 GROUP BY CD.STORE, COALESCE(PP.PRODUCTID, P.PRODUCTID), CD.ACTUAL_DT