CREATE VIEW [dbo].[WHS_GATHERINGPALLET_VW] AS  
SELECT G.STOREORDER, G.GATHERINGID, GP.PALLET_NO, GP.GATHERINGPALLETSTATUS, GPS.STATUS_NM, GP.CONTROLUSER, U2.USERFULL_NM CONTROLUSER_NM  
	 , GP.CONTROLSTART_TM, GP.CONTROLEND_TM  
	 , SUM(GD.GATHERED_QTY * SOD.ORDERUNIT_QTY * SP.PRICE_AMT) GATHERINGPRICE_AMT  
	 , SUM(GD.CONTROL_QTY * SOD.ORDERUNIT_QTY * SP.PRICE_AMT) CONTROLPRICE_AMT  
	 , COUNT(DISTINCT SOD.PRODUCT) CONTROLLEDPRODUCT_CNT  
  FROM WHS_GATHERING G  
  JOIN WHS_GATHERINGPALLET2_VW GP ON G.GATHERINGID = GP.GATHERING AND GP.DELETED_FL = 'N' 
  JOIN WHS_GATHERINGPALLETSTATUS GPS ON GP.GATHERINGPALLETSTATUS = GPS.GATHERINGPALLETSTATUSID  
  JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING AND GP.PALLET_NO = GD.PALLET_NO AND GD.DELETED_FL = 'N'
  JOIN WHS_STOREORDERDETAIL SOD ON GD.STOREORDERDETAIL = SOD.STOREORDERDETAILID  
  JOIN PRC_SALEPRICE_VW SP ON SOD.PRODUCT = SP.PRODUCT  
  LEFT JOIN SEC_USER U2 ON GP.CONTROLUSER = U2.USERID  
 WHERE ISNULL(GD.CONTROL_QTY, 0) > 0   
   AND G.DELETED_FL = 'N'
 GROUP BY G.STOREORDER, G.GATHERINGID, GP.PALLET_NO, GP.GATHERINGPALLETSTATUS, GPS.STATUS_NM, GP.CONTROLUSER, U2.USERFULL_NM, GP.CONTROLSTART_TM, GP.CONTROLEND_TM