CREATE VIEW [dbo].[WHS_GATHERINGDURATION_VW] AS
SELECT STOREORDER, GATHERINGTYPE, GATHERINGUSER, PALLET_NO, GATHER_DT,
	   SUM(CASE WHEN DURATION < 300 THEN DURATION ELSE 0 END) DURATION,
	   SUM(WEIGHT_AMT) TOTALWEIGHT
  FROM (
SELECT SOD.STOREORDER, G.GATHERINGTYPE, G.GATHERINGUSER, 
	   GD.PALLET_NO, CAST(GD.GATHERING_TM AS DATE) GATHER_DT, GD.GATHERING_TM, 
	   LAG(GD.GATHERING_TM) OVER (PARTITION BY SOD.STOREORDER, GATHERINGTYPE, PALLET_NO ORDER BY GATHERING_TM) LAGGATHERING_TM,
	   DATEDIFF(SECOND, LAG(GD.GATHERING_TM) OVER (PARTITION BY SOD.STOREORDER, GATHERINGTYPE, PALLET_NO ORDER BY GATHERING_TM), GD.GATHERING_TM) DURATION, 
	   GD.GATHERED_QTY * SOD.ORDERUNIT_QTY * P.WEIGHT_AMT / 1000.0 WEIGHT_AMT
  FROM WHS_GATHERING G
  JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING
  JOIN WHS_STOREORDERDETAIL SOD ON GD.STOREORDERDETAIL = SOD.STOREORDERDETAILID
  JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
 WHERE G.GATHERINGSTATUS = 9
   AND G.DELETED_FL = 'N'
   AND GD.DELETED_FL = 'N') A
 GROUP BY STOREORDER, GATHERINGTYPE, GATHERINGUSER, PALLET_NO, GATHER_DT
