-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRC_PRICECHANGE]
(
    /*Section="Columns"*/
    [PRICECHANGEID]  BIGINT NOT NULL IDENTITY,
    [ORGANIZATION]   INT NOT NULL,
    [CREATE_DT]      DATETIME NOT NULL,
    [UPDATE_DT]      DATETIME NULL,
    [STORE]          INT NOT NULL,
    [PRODUCTCODE_NM] VARCHAR(100) NOT NULL,
    [PRODUCTNAME_NM] VARCHAR(100) NOT NULL,
    [OPERATION_TXT]  VARCHAR(3) NOT NULL,
    [OLDPRICE_AMT]   NUMERIC(22,6) NULL,
    [NEWPRICE_AMT]   NUMERIC(22,6) NULL,
    [STATUS_CD]      INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRC_PRICECHANGE_PK] PRIMARY KEY ([PRICECHANGEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [PRC_PRICECHANGE_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [PRC_PRICECHANGE_F02] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [PRC_PRICECHANGE_X01] ON [PRC_PRICECHANGE] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Price Change History: Price Change History',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRC_PRICECHANGE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Price Change History Id: Identity column for PRC_PRICECHANGE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'PRICECHANGEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Code Name: Product Code Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTCODE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Name: Product Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTNAME_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Operation Code: Operation Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'OPERATION_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Old Price Amount: Old Price Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'OLDPRICE_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'New Price Amount: New Price Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'NEWPRICE_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Code: Status Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'PRC_PRICECHANGE', 
    @level2type=N'COLUMN',
    @level2name=N'STATUS_CD'
GO

/*Section="End"*/
