-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRC_PROMOTIONTYPE]
(
    /*Section="Columns"*/
    [PROMOTIONTYPEID]  INT NOT NULL IDENTITY,
    [PROMOTIONTYPE_NM] VARCHAR(100) NOT NULL,
    [COMMENT_DSC]      VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRC_PROMOTIONTYPE_PK] PRIMARY KEY ([PROMOTIONTYPEID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRC_PROMOTIONTYPE_X01] ON [PRC_PROMOTIONTYPE] ([PROMOTIONTYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Promotion Type: Promosyon yöntemleri (insert, afiş, radyo) ve ileride eklenecek diğer özellikler',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRC_PROMOTIONTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Promotion Type Id: Identity column for PRC_PROMOTIONTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PROMOTIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'PROMOTIONTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Promotion Name: Name of promotion  type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PROMOTIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'PROMOTIONTYPE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Description: Comment for package promotion  type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PROMOTIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
