-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRC_STOREPACKAGE]
(
    /*Section="Columns"*/
    [STOREPACKAGEID] INT NOT NULL IDENTITY,
    [ORGANIZATION]   INT NOT NULL,
    [DELETED_FL]     VARCHAR NOT NULL,
    [CREATE_DT]      DATETIME NOT NULL,
    [UPDATE_DT]      DATETIME NULL,
    [CREATEUSER]     INT NOT NULL,
    [UPDATEUSER]     INT NULL,
    [STORE]          INT NOT NULL,
    [PACKAGE]        INT NOT NULL,
    [PRIORITY_NO]    INT NOT NULL,
    [ISCURRENT_FL]   VARCHAR(1) NULL,
    [CURRENTVERSION] INT NULL,
    [START_TM]       DATETIME NOT NULL,
    [END_TM]         DATETIME NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRC_STOREPACKAGE_PK] PRIMARY KEY ([STOREPACKAGEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [PRC_STOREPACKAGE_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [PRC_STOREPACKAGE_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [PRC_STOREPACKAGE_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [PRC_STOREPACKAGE_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [PRC_STOREPACKAGE_F05] FOREIGN KEY ([PACKAGE]) REFERENCES [PRC_PACKAGE]([PACKAGEID]),
    CONSTRAINT [PRC_STOREPACKAGE_F06] FOREIGN KEY ([CURRENTVERSION]) REFERENCES [PRC_PACKAGEVERSION]([PACKAGEVERSIONID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [PRC_STOREPACKAGE_X01] ON [PRC_STOREPACKAGE] ([STORE])
GO

CREATE INDEX [PRC_STOREPACKAGE_X02] ON [PRC_STOREPACKAGE] ([PACKAGE])
GO

CREATE INDEX [PRC_STOREPACKAGE_X03] ON [PRC_STOREPACKAGE] ([CURRENTVERSION])
GO

CREATE UNIQUE INDEX [PRC_STOREPACKAGE_X04] ON [PRC_STOREPACKAGE] ([STORE], [PACKAGE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Package: Store Package',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRC_STOREPACKAGE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Package Id: Identity column for PRC_STOREPACKAGE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'STOREPACKAGEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package: Package' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'PACKAGE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Priority Number: Priority Number' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'PRIORITY_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Is Current Flag: Is Current Flag' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'ISCURRENT_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Current Version: Current Version' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'CURRENTVERSION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Start Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'START_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'End Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_STOREPACKAGE',
    @level2type=N'COLUMN',
    @level2name=N'END_TM'
GO

/*Section="End"*/
