-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [PRC_PACKAGETYPE]
(
    /*Section="Columns"*/
    [PACKAGETYPEID]  INT NOT NULL IDENTITY,
    [PACKAGETYPE_NM] VARCHAR(100) NOT NULL,
    [COMMENT_DSC]    VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [PRC_PACKAGETYPE_PK] PRIMARY KEY ([PACKAGETYPEID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [PRC_PACKAGETYPE_X01] ON [PRC_PACKAGETYPE] ([PACKAGETYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Package Type: Package Type',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'PRC_PACKAGETYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Type Id: Identity column for PRC_PACKAGETYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PACKAGETYPE',
    @level2type=N'COLUMN',
    @level2name=N'PACKAGETYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Type Name: Name of package type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PACKAGETYPE',
    @level2type=N'COLUMN',
    @level2name=N'PACKAGETYPE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for package type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'PRC_PACKAGETYPE',
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
