CREATE VIEW PRD_STOCKGROUP_VW AS 
SELECT SG.STOCKGROUP, SGN.STOCKGROUP_NM, SG.PRODUCTID, P.CODE_NM PRODUCTCODE_NM, P.NAME_NM PRODUCT_NM, SGN.USAGETYPE_CD
  FROM PRD_STOCKGROUP SG
  JOIN PRD_STOCKGROUPNAME SGN ON SG.STOCKGROUP = SGN.STOCKGROUPID
  JOIN PRD_PRODUCT P ON SG.PRODUCTID = P.PRODUCTID