CREATE VIEW PRD_STOCKGROUPPURCHASE_VW AS
WITH PURCHASES AS (
SELECT P.PRODUCTID, P.NAME_NM PRODUCT_NM, SG.STOCKGROUP_NM, SUM(QUANTITY_QTY) QUANTITY
  FROM INV_STOCKTRANSACTIONS_SYN S
  JOIN INV_WAREHOUSE_SYN W ON S.WAREHOUSE = W.WAREHOUSEID
  JOIN PRD_PRODUCT P ON S.PRODUCT = P.PRODUCTID
  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
 WHERE W.WAREHOUSETYPE = 2
   AND TRANSACTION_DT >= GETDATE()-90
   AND TRANSACTIONTYPE = 9
   AND S.WAREHOUSE NOT IN (1002, 1004)
 GROUP BY P.PRODUCTID, P.NAME_NM, SG.STOCKGROUP_NM)
SELECT P.PRODUCTID, P.NAME_NM, 10000+SG.STOCKGROUP GROUPPRODUCTID, SG.STOCKGROUP_NM, ISNULL(QUANTITY,0) QUANTITY
	 , SUM(ISNULL(QUANTITY,0)) OVER (PARTITION BY SG.STOCKGROUP) GROUPTOTALQUANTITY
  FROM PRD_STOCKGROUP_VW SG
  JOIN PRD_PRODUCT P ON SG.PRODUCTID = P.PRODUCTID
  LEFT JOIN PURCHASES A ON SG.PRODUCTID = A.PRODUCTID
 WHERE SG.USAGETYPE_CD = 1