CREATE PROCEDURE INV_UPD_CURRENTSTOCK_SP AS  
BEGIN  
  IF OBJECT_ID('tempdb.dbo.#currentstock', 'U') IS NOT NULL  DROP TABLE #currentstock;  
  SELECT * INTO #currentstock FROM INV_CURRENTSTOCK_VW  
    
  INSERT INTO INV_CURRENTSTOCK   
  SELECT tmp.*  
    FROM #currentstock tmp   
	LEFT JOIN INV_CURRENTSTOCK CS ON CS.STORE = tmp.STORE AND CS.PRODUCT = tmp.PRODUCT  
   WHERE CS.STORE IS NULL  
  
  UPDATE CS  
     SET CS.STOCK = tmp.STOCK  
       , CS.AVGDAILYSALE = tmp.AVGDAILYSALE  
       , CS.STOCKGROUP_NM = tmp.STOCKGROUP_NM  
	   , CS.MAXDAILYSALE = tmp.MAXDAILYSALE
    FROM INV_CURRENTSTOCK CS  
	JOIN #currentstock tmp ON CS.STORE = tmp.STORE AND CS.PRODUCT = tmp.PRODUCT  
   WHERE CS.STOCK != tmp.STOCK OR CS.AVGDAILYSALE != tmp.AVGDAILYSALE OR CS.STOCKGROUP_NM != tmp.STOCKGROUP_NM OR CS.MAXDAILYSALE != tmp.MAXDAILYSALE 
  
  DELETE CS   
    FROM #currentstock tmp   
   RIGHT JOIN INV_CURRENTSTOCK CS ON CS.STORE = tmp.STORE AND CS.PRODUCT = tmp.PRODUCT  
   WHERE tmp.STORE IS NULL  
END