CREATE PROCEDURE INV_LST_WHPRODUCTSTOCK_SP @ProductId INT, @StartDate DATE, @EndDate DATE AS    
BEGIN     
  DECLARE @TODAY DATE = CAST(GETDATE() AS DATE)

  SELECT PRODUCT, STOCK INTO #CURRENTSTOCK 
    FROM INV_WAREHOUSESTOCK_VW
   WHERE WAREHOUSE = 1001 
     AND @TODAY BETWEEN START_DT AND END_DT
	 AND PRODUCT = @ProductId

  SELECT DT.DATE_DT, SUM(ISNULL(STOCK,0)) OVER (ORDER BY DATE_DT DESC ROWS UNBOUNDED PRECEDING) STOCK 
    FROM RPT_DATE DT
	LEFT JOIN (
  SELECT @TODAY TRANSACTION_DT, PRODUCT, STOCK
    FROM #CURRENTSTOCK 
   UNION ALL
  SELECT DATEADD(DAY, -1, TRANSACTION_DT), PRODUCT, -1*SUM(QUANTITY_QTY) QUANTITY
    FROM INV_STOCKTRANSACTIONS_SYN
   WHERE WAREHOUSE = 1001
     AND TRANSACTION_DT >= @StartDate
	 AND TRANSACTION_DT <= @TODAY
	 AND PRODUCT = @ProductId
   GROUP BY TRANSACTION_DT, PRODUCT) A ON DT.DATE_DT = A.TRANSACTION_DT
   WHERE DT.DATE_DT BETWEEN @StartDate AND @TODAY
   ORDER BY DT.DATE_DT      
END 