CREATE PROCEDURE INV_RPT_MIKROEXTRE_SP @WarehouseId INT, @ProductId INT = -1 AS
BEGIN

	SELECT TRANSACTION_DT, TRANSACTIONTYPE, DOCUMENTTYPE, TRANSACTIONKIND, PRODUCTCODE_NM, PRODUCT_NM, QUANTITY, 
		   SUM(QUANTITY) OVER (PARTITION BY PRODUCTCODE_NM ORDER BY PRODUCTCODE_NM, TRANSACTION_DT, TRANSACTIONTYPEID, DOCUMENTTYPE, TRANSACTIONKIND) STOCK
	  FROM (
	SELECT CAST(sth_tarih AS date) TRANSACTION_DT, HT.TIPID TRANSACTIONTYPEID, HT.TIP_ACK TRANSACTIONTYPE, 
		   ET.EVRAK_ACK DOCUMENTTYPE, CS.CINS_ACK TRANSACTIONKIND,
		   P.CODE_NM PRODUCTCODE_NM, P.NAME_NM PRODUCT_NM, 
		   SUM(CASE WHEN sth_tip in (0,2) and sth_giris_depo_no = @WarehouseId THEN sth_miktar ELSE -1*sth_miktar END) QUANTITY
	  FROM MIK_TRANSACTION20_SYN TR (NOLOCK)
	  JOIN PRD_PRODUCT P (NOLOCK) ON TR.sth_stok_kod COLLATE Turkish_100_CI_AS = P.CODE_NM AND DELETED_FL = 'N'
	  LEFT JOIN MIK_HAREKETTIP_SYN HT (NOLOCK) ON TR.sth_tip = HT.TIPID
	  LEFT JOIN MIK_CINS_SYN CS (NOLOCK) ON TR.sth_cins = CS.CINSID
	  LEFT JOIN MIK_EVRAKTIP_SYN ET (NOLOCK) ON TR.sth_evraktip = ET.TIPID
	 WHERE (sth_giris_depo_no = @WarehouseId OR sth_cikis_depo_no = @WarehouseId)
	   AND (@ProductId = -1 OR P.PRODUCTID = @ProductId)
	   AND TR.sth_cins != 9
	 GROUP BY CAST(sth_tarih AS date), HT.TIPID, HT.TIP_ACK, ET.EVRAK_ACK, CS.CINS_ACK, P.CODE_NM, P.NAME_NM ) A
	 ORDER BY PRODUCTCODE_NM, TRANSACTION_DT, TRANSACTIONTYPEID, DOCUMENTTYPE, TRANSACTIONKIND

END