CREATE PROCEDURE INV_LST_STOCKOUTDAY_SP @StoreID INT, @DayCount INT, @Date DATE AS
BEGIN
	WITH INITIALSTOCK AS (
	SELECT COALESCE(10000+SG.STOCKGROUP, P.PRODUCTID) PRODUCTID,
		   COALESCE(SG.STOCKGROUP_NM, P.NAME_NM) PRODUCT_NM, SUM(INV.STOCK) STOCK
	  FROM dbo.INV_STOCKDATE_FN(@Date) INV  
	  JOIN STR_STORE ST ON INV.STORE = ST.STOREID  
	  JOIN PRD_PRODUCT_VW P ON INV.PRODUCT = P.PRODUCTID  
	  LEFT JOIN PRD_PROPERTY PP ON P.PRODUCTID = PP.PRODUCT AND PP.PROPERTYTYPE = 6
	  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
	 WHERE P.CATEGORY_NM != 'Sarf Malzemeleri'
	   AND ST.STOREID = @StoreID
	   AND P.ACTIVE_FL = 'Y'
	   AND PP.PRODUCT IS NULL
	 GROUP BY COALESCE(10000+SG.STOCKGROUP, P.PRODUCTID), COALESCE(SG.STOCKGROUP_NM, P.NAME_NM)),
 
	SALES AS (
	SELECT COALESCE(SG.STOCKGROUP+10000, S.PRODUCT) PRODUCT, COALESCE(SG.STOCKGROUP_NM, P.NAME_NM) PRODUCT_NM, 
		   SUM(CASE WHEN S.TRANSACTION_DT = @Date THEN S.QUANTITY ELSE 0 END) DAYSALE,
		   SUM(S.QUANTITY) SALE
	  FROM SLS_STOREDAILYPRODUCT_SYN S
	  JOIN PRD_PRODUCT_VW P ON S.PRODUCT = P.PRODUCTID
	  LEFT JOIN PRD_PROPERTY PP ON P.PRODUCTID = PP.PRODUCT AND PP.PROPERTYTYPE = 6
	  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
	 WHERE STORE = @StoreID
	   AND P.CATEGORY_NM != 'Sarf Malzemeleri'
	   AND PP.PRODUCT IS NULL
	   AND P.ACTIVE_FL = 'Y'
	   AND S.TRANSACTION_DT BETWEEN CAST (GETDATE()-@DayCount AS DATE) AND CAST (GETDATE()-1 AS DATE)
	 GROUP BY COALESCE(SG.STOCKGROUP+10000, S.PRODUCT), COALESCE(SG.STOCKGROUP_NM, P.NAME_NM)), 

	DAILYSTOCK AS (SELECT ST.PRODUCTID, ST.PRODUCT_NM, STOCK DAYSTOCK FROM INITIALSTOCK ST) 

	SELECT B.*, (B.AVGSALE-B.SALE)*PR.PRICE STOCKOUT
	  FROM (
	SELECT PRODUCTID, PRODUCT_NM, SUM(DAYSTOCK) DAYSTOCK, SUM(DAYSALE) SALE, SUM(SALE)/ (@DayCount*1.0) AVGSALE
	  FROM (
	SELECT *, 0 DAYSALE, 0 SALE
	  FROM DAILYSTOCK DS 
	 UNION ALL
	SELECT PRODUCT, PRODUCT_NM, 0 DAYSTOCK, DAYSALE, SALE
	  FROM SALES) A
	 GROUP BY PRODUCTID, PRODUCT_NM) B 
	 JOIN (SELECT COALESCE(10000+SG.STOCKGROUP, PRODUCT) PRODUCT, MIN(PRICE_AMT) PRICE
			  FROM PRC_PRODUCT P
			  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCT = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
			 WHERE PACKAGE = 1 
			 GROUP BY COALESCE(10000+SG.STOCKGROUP, PRODUCT)) PR ON B.PRODUCTID = PR.PRODUCT
	 WHERE B.DAYSTOCK < B.AVGSALE
	   AND B.SALE < (B.AVGSALE/2)
	 ORDER BY (B.AVGSALE-B.SALE)*PR.PRICE DESC
END
