CREATE PROCEDURE INV_LST_STORESTOCK_SP @StoreId INT AS
BEGIN
	SELECT CS.PRODUCT, CS.STOCKGROUP_NM, CS.STOCK, CS.AVGDAILYSALE, PR.PRICE, CS.AVGDAILYSALE*PR.PRICE AVGDAILYTOTAL, CATEGORY_NM
	  FROM INV_CURRENTSTOCK CS
	  JOIN (SELECT COALESCE(10000+SG.STOCKGROUP, PRODUCT) PRODUCT, MIN(PRICE_AMT) PRICE, MAX(PV.CATEGORY_NM) CATEGORY_NM
			  FROM PRC_PRODUCT P
			  JOIN PRD_PRODUCT_VW PV ON P.PRODUCT = PV.PRODUCTID
			  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCT = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
			 WHERE PACKAGE = 1 
			 GROUP BY COALESCE(10000+SG.STOCKGROUP, PRODUCT)) PR ON CS.PRODUCT = PR.PRODUCT
	 WHERE STORE = @StoreId
	ORDER BY CS.AVGDAILYSALE*PR.PRICE DESC
END