CREATE PROCEDURE INV_LST_CURRENTSTOCK_SP @Store INT, @Product INT, @Select INT=1 AS 
BEGIN
IF @Select=1 
BEGIN
 SELECT STORE
  ,STORE_NM
  ,PRODUCT
  ,STOCKGROUP_NM
  ,STOCK
  ,AVGDAILYSALE
  ,MAXDAILYSALE 
 FROM INV_CURRENTSTOCK 
 WHERE (STORE=@Store OR @Store=-1) 
 AND (@Product=-1 OR PRODUCT=@Product)
END
ELSE IF @Select=0
BEGIN
 SELECT 
   'STORE' STORE
  ,'STORE_NM' STORE_NM
  ,PRODUCT
  ,STOCKGROUP_NM
  ,SUM(STOCK)
  ,'AVGDAILYSALE' AVGDAILYSALE
  ,'MAXDAILYSALE' MAXDAILYSALE
 FROM INV_CURRENTSTOCK 
 WHERE (STORE=@Store OR @Store=-1) 
 AND (@Product=-1 OR PRODUCT=@Product)
 GROUP BY PRODUCT,STOCKGROUP_NM
END
END

