CREATE PROCEDURE INV_LST_STOCKSATCRITICALLEVEL_SP @StoreID INT AS  
BEGIN  
 SELECT *, CASE WHEN STOCK < AVGDAILYSALE THEN 1 ELSE 0 END CRITICALLEVEL  
   FROM INV_CURRENTSTOCK   
   WHERE STORE = @StoreID        
   AND STOCK < AVGDAILYSALE*2  
END