CREATE PROCEDURE INV_LST_DAILYSTOCKOUT_SP @StoreId INT, @DayCount INT AS
BEGIN
	SELECT *
	  INTO #stockout
	  FROM dbo.INV_STOCKOUT_FN (@StoreId, @DayCount)

	SELECT TRANSACTION_DT, SUM((AVGSALE-SALE)*PRICE) STOCKOUT
	  FROM #stockout S
	  JOIN (SELECT COALESCE(10000+SG.STOCKGROUP, PRODUCT) PRODUCT, MIN(PRICE_AMT) PRICE
			  FROM PRC_PRODUCT P
		  	  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
			 WHERE PACKAGE = 1 
			 GROUP BY COALESCE(10000+SG.STOCKGROUP, PRODUCT)) PR ON S.PRODUCTID = PR.PRODUCT
	 GROUP BY TRANSACTION_DT
	 ORDER BY 1
END