CREATE PROCEDURE INV_LST_STOCK_SP @StoreId INT = -1 AS  
BEGIN  
  IF @StoreId = -1   
  BEGIN  
    SELECT ST.STOREID, ST.STORE_NM, P.PRODUCTID, P.CATEGORY_NM, P.NAME_NM PRODUCT_NM, INV.COUNTING_DT, INV.COUNTINGVALUE_AMT, INV.STOCK  
      FROM INV_STOCK_VW INV  
	  JOIN STR_STORE ST ON INV.STORE = ST.STOREID  
	  JOIN PRD_PRODUCT_VW P ON INV.PRODUCT = P.PRODUCTID  
	 WHERE P.CATEGORY_NM != 'Sarf Malzemeleri'
  END  
  ELSE IF @StoreId != 999 
  BEGIN  
    SELECT ST.STOREID, ST.STORE_NM, P.PRODUCTID, P.CATEGORY_NM, P.NAME_NM PRODUCT_NM, INV.COUNTING_DT, INV.COUNTINGVALUE_AMT, INV.STOCK  
      FROM INV_STOCK_VW INV  
	  JOIN STR_STORE ST ON INV.STORE = ST.STOREID  
	  JOIN PRD_PRODUCT_VW P ON INV.PRODUCT = P.PRODUCTID  
     WHERE STORE = @StoreId  
	   AND P.CATEGORY_NM != 'Sarf Malzemeleri'
  END 
  ELSE 
  BEGIN
    SELECT 999 STOREID, 'MERKEZ DEPO' STORE_NM, P.PRODUCTID, P.CATEGORY_NM, P.NAME_NM PRODUCT_NM, NULL COUNTING_DT, 0 COUNTINGVALUE_AMT, INV.STOCK  
      FROM INV_WAREHOUSESTOCK_VW INV  
	  JOIN PRD_PRODUCT_VW P ON INV.PRODUCT = P.PRODUCTID  
     WHERE WAREHOUSE = 1001
	   AND CAST(GETDATE() AS DATE) BETWEEN START_DT AND END_DT
	   AND P.CATEGORY_NM != 'Sarf Malzemeleri'
  END
END  