CREATE PROCEDURE INV_LST_WAREHOUSESTOCK_SP @Date DATE AS
BEGIN
   
 DECLARE @StartDate DATE = DATEADD(DAY, -30, @Date)
  
 IF OBJECT_ID('tempdb..#sale') IS NOT NULL DROP TABLE #sale
  
 SELECT PRODUCT, SUM(-1*QUANTITY_QTY)/31 sale
   into #sale  
   FROM INV_STOCKTRANSACTIONS_SYN  
  WHERE WAREHOUSE = 1001  
    AND TRANSACTION_DT BETWEEN @StartDate AND @Date  
    AND TRANSACTIONTYPE = 2  
  GROUP BY PRODUCT  
  
 SELECT P.PRODUCTID, P.CATEGORY_NM, P.CODE_NM, P.NAME_NM, WS.STOCK
	  , ISNULL(S.sale,0) AVGDAILYSALE_QTY  
	  , ISNULL(S.sale,0)*ISNULL(PR.PRICE_AMT,1) AVGDAILYSALE_AMT
	  , CASE WHEN ISNULL(S.sale,0) != 0 THEN WS.STOCK / ISNULL(S.sale,0) ELSE 1000 END STOCKTURNOVER
   FROM INV_WAREHOUSESTOCK_VW WS  
   JOIN PRD_PRODUCT_VW P ON WS.PRODUCT = P.PRODUCTID  
   LEFT JOIN PRD_PRODUCT PP ON P.PARENT = PP.PRODUCTID
   LEFT JOIN #sale S ON WS.PRODUCT = S.PRODUCT  
   LEFT JOIN (SELECT PRODUCT, PRICE_AMT FROM PRC_PRODUCT WHERE PACKAGE = 1 AND DELETED_FL = 'N') PR ON COALESCE(PP.PRODUCTID, P.PRODUCTID) = PR.PRODUCT
  WHERE WAREHOUSE = 1001  
    AND @Date BETWEEN START_DT AND END_DT
  ORDER BY 8

END