-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [OSM_SCREENPROPERTY]
(
    /*Section="Columns"*/
    [SCREENPROPERTYID] INT NOT NULL IDENTITY,
    [SCREEN]           INT NOT NULL,
    [PROPERTY_NM]      VARCHAR(100) NOT NULL,
    [VALUE_TXT]        VARCHAR(1000) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [OSM_SCREENPROPERTY_PK] PRIMARY KEY ([SCREENPROPERTYID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [OSM_SCREENPROPERTY_F01] FOREIGN KEY ([SCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [OSM_SCREENPROPERTY_X01] ON [OSM_SCREENPROPERTY] ([SCREEN])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'OverStore Screen Property: OverStore Screen Property',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'OSM_SCREENPROPERTY',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'OverStore Screen Property Id: Identity column for OSM_SCREENPROPERTY' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_SCREENPROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'SCREENPROPERTYID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Screen: Screen' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_SCREENPROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'SCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Property Name: Name of overstore screen property.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_SCREENPROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'PROPERTY_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Property Value: Property Value' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_SCREENPROPERTY', 
    @level2type=N'COLUMN',
    @level2name=N'VALUE_TXT'
GO

/*Section="End"*/
