-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [OSM_TASKDOCUMENT]
(
    /*Section="Columns"*/
    [TASK]          BIGINT NOT NULL,
    [DOCUMENT]      BIGINT NOT NULL,
    [CREATE_DT]     DATETIME NOT NULL,
    [CREATEUSER]    INT NOT NULL,
    [CREATECHANNEL] INT NOT NULL,
    [CREATEBRANCH]  INT NOT NULL,
    [CREATESCREEN]  INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [OSM_TASKDOCUMENT_PK] PRIMARY KEY ([TASK],[DOCUMENT]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [OSM_TASKDOCUMENT_F01] FOREIGN KEY ([TASK]) REFERENCES [OSM_TASK]([TASKID]),
    CONSTRAINT [OSM_TASKDOCUMENT_F02] FOREIGN KEY ([DOCUMENT]) REFERENCES [DOC_DOCUMENT]([DOCUMENTID]),
    CONSTRAINT [OSM_TASKDOCUMENT_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [OSM_TASKDOCUMENT_F04] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [OSM_TASKDOCUMENT_F05] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [OSM_TASKDOCUMENT_F06] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Task Document: relation table for OSM_TASK and DOC_DOCUMENT',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'OSM_TASKDOCUMENT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'OverStore Task: OSM_TASK' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'TASK'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Document: DOC_DOCUMENT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'DOCUMENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Creation date of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creation branch of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Creation screen of the user.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'OSM_TASKDOCUMENT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

/*Section="End"*/
