-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [OSM_TASK]
(
    /*Section="Columns"*/
    [TASKID]              BIGINT NOT NULL IDENTITY,
    [EVENT]               INT NOT NULL,
    [ORGANIZATION]        INT NOT NULL,
    [DELETED_FL]          VARCHAR NOT NULL,
    [CREATE_DT]           DATETIME NOT NULL,
    [UPDATE_DT]           DATETIME NULL,
    [CREATEUSER]          INT NOT NULL,
    [UPDATEUSER]          INT NULL,
    [CREATECHANNEL]       INT NOT NULL,
    [CREATEBRANCH]        INT NOT NULL,
    [CREATESCREEN]        INT NOT NULL,
    [STATUS]              INT NOT NULL,
    [TYPE]                INT NOT NULL,
    [CONTENT_TXT]         VARCHAR(1000) NULL,
    [DEADLINE_TM]         DATETIME NULL,
    [RESPONSIBLETYPE_CD]  INT NOT NULL,
    [RESPONSIBLEUSER]     INT NULL,
    [RESPONSIBLEGROUP]    INT NULL,
    [RESPONSIBLEBRANCH]   INT NULL,
    [PROCESSINSTANCE_LNO] BIGINT NULL,
    [FORWARDABLE_FL]      VARCHAR(1) NOT NULL,
    [FOLDER]              BIGINT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [OSM_TASK_PK] PRIMARY KEY ([TASKID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [OSM_TASK_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [OSM_TASK_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [OSM_TASK_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [OSM_TASK_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [OSM_TASK_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [OSM_TASK_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [OSM_TASK_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [OSM_TASK_F08] FOREIGN KEY ([STATUS]) REFERENCES [OSM_TASKSTATUS]([TASKSTATUSID]),
    CONSTRAINT [OSM_TASK_F09] FOREIGN KEY ([TYPE]) REFERENCES [OSM_TASKTYPE]([TASKTYPEID]),
    CONSTRAINT [OSM_TASK_F10] FOREIGN KEY ([RESPONSIBLEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [OSM_TASK_F11] FOREIGN KEY ([RESPONSIBLEGROUP]) REFERENCES [SEC_GROUP]([GROUPID]),
    CONSTRAINT [OSM_TASK_F12] FOREIGN KEY ([RESPONSIBLEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [OSM_TASK_F13] FOREIGN KEY ([FOLDER]) REFERENCES [DOC_FOLDER]([FOLDERID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [OSM_TASK_X01] ON [OSM_TASK] ([RESPONSIBLEUSER])
GO

CREATE INDEX [OSM_TASK_X02] ON [OSM_TASK] ([RESPONSIBLEGROUP])
GO

CREATE INDEX [OSM_TASK_X03] ON [OSM_TASK] ([RESPONSIBLEBRANCH])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'OverStoreTask: task',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'OSM_TASK',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'OverStoreTask Id: Identity column for OSM_TASK' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'TASKID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status: OSM_TASKSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'STATUS'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Type: OSM_TASKTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'TYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Content: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'CONTENT_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deadline: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'DEADLINE_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Responsible Type: 1_USER, 2_GROUP, 3_BRANCH' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'RESPONSIBLETYPE_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Responsible User: if RESPONSIBLETYPE_CD == 1' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'RESPONSIBLEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Responsible Group: if RESPONSIBLETYPE_CD == 2' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'RESPONSIBLEGROUP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Responsible Branch: if RESPONSIBLETYPE_CD == 3' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'RESPONSIBLEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Process Instance: BPM_PROCESSINSTANCE (not FK)' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'PROCESSINSTANCE_LNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Forwardable Flag: whether the process responsible can forward the process to another party or not' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'FORWARDABLE_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Folder: FOLDER ID' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'OSM_TASK',
    @level2type=N'COLUMN',
    @level2name=N'FOLDER'
GO

/*Section="End"*/
