CREATE PROCEDURE [dbo].[WHS_UPD_SHIPMENTQTYFROMGATHERING_SP]
	@Gathering BIGINT
AS
	UPDATE OD
	   SET OD.SHIPPED_QTY = GD.CONTROL_QTY
	  FROM WHS_GATHERINGDETAIL GD 
	  JOIN WHS_STOREORDERDETAIL OD ON GD.STOREORDERDETAIL = OD.STOREORDERDETAILID
	 WHERE GD.GATHERING = @Gathering

