CREATE PROCEDURE WHS_LST_RETORDSTATUSHIST_SP @ReturnOrderId INT AS
BEGIN
  SELECT B.BRANCH_NM, U.USERFULL_NM, O.CREATE_DT, 'Giriş' OPCODE, 'Mağaza Giriş' STATUS_NM, '' COMMENT_TXT
    FROM WHS_RETURNORDER O 
    JOIN SEC_USER U ON O.CREATEUSER = U.USERID
    JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
   WHERE RETURNORDERID = @ReturnOrderId
   UNION ALL
  SELECT B.BRANCH_NM, U.USERFULL_NM, H.CREATE_DT, CASE OPERATION_CD WHEN 1 THEN 'Onay' ELSE 'Ret' END OPCODE, S.STATUS_NM, COMMENT_TXT
    FROM WHS_ORDERSTATUSHISTORY H
    JOIN SEC_USER U ON H.CREATEUSER = U.USERID
    JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
    JOIN WHS_RETURNSTATUS S ON H.STATUS = S.RETURNSTATUSID
   WHERE RETURNORDER = @ReturnOrderId
   ORDER BY 3
END