CREATE PROCEDURE WHS_LST_GATHERINGDETAIL_SP
    @GatheringId BIGINT = null
AS
BEGIN
    DECLARE @Organization INT;
    SELECT @Organization = dbo.SYS_GETCURRENTORGANIZATION_FN();
    IF dbo.SYS_ISSYSTEMORGANIZATION_FN() = 1
    BEGIN
      SET @Organization = null;
    END

    DECLARE @dummyDAY DATE = CONVERT(DATE, '20010101', 112)
    SELECT G.GATHERINGDETAILID,
           G.EVENT,
           G.ORGANIZATION,
           G.DELETED_FL,
           G.CREATE_DT,
           G.UPDATE_DT,
           G.CREATEUSER,
           G.UPDATEUSER,
           G.CREATECHANNEL,
           G.CREATEBRANCH,
           G.CREATESCREEN,
           G.STOREORDERDETAIL,
           G.GATHERING_TM,
           G.GATHERING,
           G.GATHERED_QTY,
		   G.PALLET_NO,
		   G.CONTROL_QTY,
           G.CONTROL_TM,
		   P.NAME_NM PRODUCTNAME,
		   P.CODE_NM PRODUCTCODE,
		   OD.ORDERUNIT_QTY,
		   COALESCE(OD.SHIPPED_QTY, OD.REVISED_QTY, OD.ORDER_QTY) ORDER_QTY,
		   U.UNIT_NM
      FROM WHS_GATHERINGDETAIL G (NOLOCK)
      JOIN WHS_GATHERING GG (NOLOCK) ON G.GATHERING = GG.GATHERINGID
	  JOIN WHS_STOREORDERDETAIL OD ON OD.STOREORDERDETAILID = G.STOREORDERDETAIL AND OD.DELETED_FL = 'N'
	  JOIN PRD_PRODUCT P ON OD.PRODUCT = P.PRODUCTID 
	  JOIN PRD_UNIT U ON P.UNIT = U.UNITID
     WHERE (@GatheringId IS null OR G.GATHERING = @GatheringId)
	   AND (@Organization IS NULL OR G.ORGANIZATION = @Organization)
       AND G.DELETED_FL = 'N'
	   AND (COALESCE(OD.SHIPPED_QTY, OD.REVISED_QTY, OD.ORDER_QTY) > 0 OR OD.EVENT = 1059)
     ORDER BY CASE WHEN GG.GATHERINGSTATUS = 9 THEN PALLET_NO ELSE 1 END, 
              CASE WHEN GG.GATHERINGSTATUS = 9 THEN GATHERING_TM ELSE @dummyDAY END DESC, 
              LOADORDER_TXT;

END