CREATE PROCEDURE WHS_RPT_PRODUCTRETURNSUMMARY_SP @StartDate DATE, @EndDate DATE, @ProductId INT, @StatusCode INT, @StoreDetail INT AS
BEGIN
	SELECT P.CODE_NM, P.NAME_NM, 
		   CASE WHEN @StoreDetail = 1 THEN 'Tüm Mağazalar' ELSE ST.STORE_NM END STORE_NM, 
		   PRS.STATUS_NM, SUM(ISNULL(PR.INTAKE_AMT, PR.RETURNQUANTITY_AMT)) RETURN_QTY,
		   SUM(ISNULL(PR.INTAKE_AMT, PR.RETURNQUANTITY_AMT)*SP.PRICE_AMT) RETURN_AMT
	  FROM WHS_PRODUCTRETURN PR
	  JOIN PRD_PRODUCT P ON PR.PRODUCT = P.PRODUCTID
	  JOIN STR_STORE ST ON PR.STORE = ST.STOREID
	  JOIN DBO.WHS_PRODUCTRETURNSTATUS_FN() PRS ON PR.STATUS_CD = PRS.STATUS_CD
	  LEFT JOIN PRC_SALEPRICE_VW SP ON P.PRODUCTID = SP.PRODUCT
	 WHERE PR.DELETED_FL = 'N'
	   AND (@StatusCode = -1 OR PR.STATUS_CD = @StatusCode)
	   AND RETURN_DT BETWEEN @StartDate AND @EndDate
	   AND (@ProductId = -1 OR PR.PRODUCT = @ProductId)
	 GROUP BY P.CODE_NM, P.NAME_NM, CASE WHEN @StoreDetail = 1 THEN 'Tüm Mağazalar' ELSE ST.STORE_NM END, PRS.STATUS_NM
END