CREATE PROCEDURE [dbo].[WHS_RPT_DRILLCOUNTPERFCALC_SP] @today DATE = NULL AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;     
	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();

	IF (@today IS NULL) SET @today = CAST(GETDATE() - 0.8 AS DATE)

	SELECT STORE, MAX(ACTUAL_DT) LASTCOUNTING_DT
	  INTO #STOREDATE
	  FROM WHS_STOCKTAKINGSCHEDULE
	 WHERE COUNTINGTYPE = 1
	   AND STATUS = 2
	   AND ACTUAL_DT < @today
	 GROUP BY STORE

	SELECT STORE, COUNT(*) NOTCOUNTEDPRODUCT_CNT
	  INTO #NOTCOUNTEDPRODUCTS
	  FROM (
	SELECT S.STORE, ST.PRODUCT, CAST(SS.PLANNED_DT AS DATE) COUNTING_DT, SUM(CASE WHEN ST.UPDATE_DT IS NOT NULL THEN COUNTINGVALUE_AMT END) COUNT_AMT
	  FROM WHS_STOCKTAKINGSCHEDULE SS
	  JOIN WHS_STOCKTAKING ST ON SS.STOCKTAKINGSCHEDULEID = ST.STOCKTAKINGSCHEDULE
	  JOIN #STOREDATE S ON SS.STORE = S.STORE
	  JOIN PRD_PRODUCT P ON ST.PRODUCT = P.PRODUCTID
	 WHERE SS.COUNTINGTYPE = 2
	   AND SS.PLANNED_DT > S.LASTCOUNTING_DT
	   AND SS.STATUS = 2
	 GROUP BY S.STORE, ST.PRODUCT, CAST(SS.PLANNED_DT AS DATE)) A
	 WHERE COUNT_AMT IS NULL
	 GROUP BY STORE;

	SELECT B2.BRANCH_NM, RM.MANAGER_NM, D.*
		 , ROW_NUMBER() OVER (ORDER BY ABS(ISNULL(SUCCESSKPI,100))) MONTHKPIRANK
		 , NCP.NOTCOUNTEDPRODUCT_CNT
		 , DATEDIFF(DAY, D.LASTCOUNTING_DT, GETDATE()) DAYSPASSED
		 , CASE WHEN ABS(SUCCESSKPI)*100 > 1 AND RISKRATIO > 7  THEN 'E'+CAST(RISKRATIO AS VARCHAR)
				WHEN ABS(SUCCESSKPI)*100 > 1 AND RISKRATIO > 3  THEN 'D'+CAST(RISKRATIO AS VARCHAR)
				WHEN ABS(SUCCESSKPI)*100 > 1 AND RISKRATIO <= 3 THEN 'C'+CAST(RISKRATIO AS VARCHAR)
				WHEN ABS(SUCCESSKPI)*100 < 1 AND RISKRATIO > 3  THEN 'B'+CAST(RISKRATIO AS VARCHAR)
				WHEN ABS(SUCCESSKPI)*100 < 1 AND RISKRATIO <= 3 THEN 'A'+CAST(RISKRATIO AS VARCHAR)
		   END GRADE
	  FROM (
	SELECT DC.STORE, STORE_NM, SD.LASTCOUNTING_DT
		 , SUM(CASE WHEN STOCK < 0 THEN 1 ELSE 0 END) MINUSSTOCKCOUNT
		 , SUM(CASE WHEN DIFF_AMT > 0 THEN DIFF_AMT ELSE 0 END) STOCKSURPLUS_AMT
		 , SUM(CASE WHEN DIFF_AMT < 0 THEN -1*DIFF_AMT ELSE 0 END) STOCKDEFICIT_AMT
		 , COUNT(*) PRODUCT_CNT
		 , SUM(DIFF_AMT) / SUM(SALE_AMT) SUCCESSKPI
		 , CAST(ROUND(ABS(SUM(DIFF_AMT)) / 2400.0,0) AS INT) RISKRATIO
	  FROM WHS_DRILLCOUNTSUMMARY DC
	  JOIN #STOREDATE SD ON DC.STORE = SD.STORE AND DC.COUNTING_DT > SD.LASTCOUNTING_DT
	 WHERE DC.COUNTING_DT <= @today
	 GROUP BY DC.STORE, STORE_NM, SD.LASTCOUNTING_DT) D 
	  JOIN #STORES ST ON D.STORE = ST.STOREID
	  LEFT JOIN #NOTCOUNTEDPRODUCTS NCP ON ST.STOREID = NCP.STORE
	  LEFT JOIN STR_REGIONMANAGERS RM ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
	  LEFT JOIN ORG_BRANCH B ON ST.BRANCH = B.BRANCHID
	  LEFT JOIN ORG_BRANCH B2 ON B.PARENT = B2.BRANCHID
	 ORDER BY 10 

END