CREATE PROCEDURE [dbo].[WHS_LST_STOCKTAKINGPRODUCTS_SP]
	@StoreId INT,
	@CountingDate DATE,
	@Zone INT
AS
BEGIN

	SELECT P.*, P.NAME_NM+' - '+P.CODE_NM+' - '+COALESCE(C.CATEGORY_NM,'')+' - '+COALESCE(BARCODE_TXT,'') SEARCHSTRING
	  FROM PRD_PRODUCT P
	  LEFT JOIN PRD_SUBGROUP SG ON P.SUBGROUP = SG.SUBGROUPID
	  LEFT JOIN PRD_CATEGORY C ON SG.CATEGORY = C.CATEGORYID
	  LEFT JOIN (SELECT PRODUCT, MAX(BARCODE_TXT) BARCODE_TXT FROM PRD_BARCODE GROUP BY PRODUCT) B ON P.PRODUCTID = B.PRODUCT
	  LEFT JOIN (SELECT * FROM WHS_STOCKTAKING WHERE STORE = @StoreId AND COUNTING_DT = @CountingDate AND ZONE = @Zone) CN ON P.PRODUCTID = CN.PRODUCT
	 WHERE P.SUPERGROUP3 NOT IN (1,3)
	   AND P.DELETED_FL = 'N'
	   AND CN.PRODUCT IS NULL

END
