-- Created by OverGenerator
/*Section="Main"*/
CREATE PROCEDURE WHS_LST_GATHERING_SP
	@StoreOrderId BIGINT = NULL,
	@GatheringStatus INT = NULL,
	@OnlyIncompleteFlag VARCHAR(1) = 'N',
	@GatheringType INT = NULL,
	@User INT = NULL
AS
BEGIN
    /*Section="Organization"*/
    -- Get the caller organization from session context
    DECLARE @Organization INT;
    SELECT @Organization = dbo.SYS_GETCURRENTORGANIZATION_FN();
    IF dbo.SYS_ISSYSTEMORGANIZATION_FN() = 1
    BEGIN
      -- Current organization is system. This is a batch or system process.
      SET @Organization = null;
    END;  
    /*Section="Query"*/  
    -- Select all  
    WITH GATHERINGQUANTITIES AS (
		SELECT G.GATHERINGID,
			   SUM(COALESCE(OD.SHIPPED_QTY, OD.REVISED_QTY, OD.ORDER_QTY) * OD.ORDERUNIT_QTY * (CASE WHEN P.UNIT = 1 THEN 1 ELSE P.WEIGHT_AMT / 1000 END) ) ORDERTOTALKG,
			   COUNT(DISTINCT OD.PRODUCT) PRODUCTCOUNT,
			   SUM(OD.ORDER_QTY) PACKAGECOUNT
		  FROM WHS_GATHERING G
		  JOIN WHS_STOREORDER O ON G.STOREORDER = O.STOREORDERID
		  JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING
		  JOIN WHS_STOREORDERDETAIL OD ON GD.STOREORDERDETAIL = OD.STOREORDERDETAILID
		  JOIN PRD_PRODUCT P ON Od.PRODUCT = P.PRODUCTID
		 WHERE ((@StoreOrderId IS NULL AND O.STATUS BETWEEN 3 AND 4) OR O.STOREORDERID = @StoreOrderId)
		   AND G.DELETED_FL = 'N' 
		 GROUP BY G.GATHERINGID
	)

    SELECT
           G.GATHERINGID,
           G.EVENT,
           G.ORGANIZATION,
           G.DELETED_FL,
           G.CREATE_DT,
           G.UPDATE_DT,
           G.CREATEUSER,
           G.UPDATEUSER,
           G.CREATECHANNEL,
           G.CREATEBRANCH,
           G.CREATESCREEN,
           G.STOREORDER,
           G.GATHERINGUSER,
           G.GATHERINGSTART_TM,
           G.GATHERINGEND_TM,
           G.GATHERINGSTATUS,
           G.GATHERINGTYPE,
           G.PRIORITY_NO,
		   ST.STORE_NM STORENAME,
		   O.ORDER_DT, 
		   O.SHIPMENT_DT, 
		   O.ORDERCODE_NM, 
		   GT.GATHERINGTYPE_NM, 
		   U.USERFULL_NM GATHERINGUSER_NM,
		   GQ.ORDERTOTALKG,
		   GQ.PRODUCTCOUNT,
		   GQ.PACKAGECOUNT
      FROM WHS_GATHERING G (NOLOCK)
	  JOIN GATHERINGQUANTITIES GQ ON G.GATHERINGID = GQ.GATHERINGID
	  JOIN WHS_STOREORDER O (NOLOCK) ON O.STOREORDERID = G.STOREORDER
	  JOIN STR_STORE ST (NOLOCK) ON ST.STOREID = O.STORE
	  JOIN WHS_GATHERINGTYPE GT ON G.GATHERINGTYPE = GT.GATHERINGTYPEID
	  LEFT JOIN SEC_USER U (NOLOCK) ON G.GATHERINGUSER = U.USERID
     WHERE (@Organization IS NULL OR G.ORGANIZATION = @Organization)
	   AND (@StoreOrderId IS NULL OR G.STOREORDER = @StoreOrderId)
	   AND (@GatheringStatus IS NULL OR G.GATHERINGSTATUS = @GatheringStatus)
	   AND (G.GATHERINGSTATUS IN (1, 2) OR (@OnlyIncompleteFlag = 'N' AND G.GATHERINGSTATUS = 9))
	   AND (@GatheringType IS NULL OR G.GATHERINGTYPE = @GatheringType)
	   AND (@User IS NULL OR (G.GATHERINGUSER = @User AND G.PRIORITY_NO != -1))
	   AND O.STATUS = 3
       AND G.DELETED_FL = 'N'
     ORDER BY G.PRIORITY_NO DESC, ISNULL(G.UPDATE_DT, G.CREATE_DT) DESC, G.GATHERINGID;
	 

/*Section="End"*/
END;
