CREATE PROCEDURE WHS_LST_ORDERSALEPRODUCTDET_SP 
	@StoreId INT = -1,
	@StartDate DATE,
	@EndDate DATE AS
BEGIN

	WITH PRICE AS (
	SELECT PRODUCT, PRICE_AMT
	  FROM PRC_PRODUCT
	 WHERE PACKAGE = 1),
	ORDERS AS (
	SELECT COALESCE(P2.PRODUCTID, P.PRODUCTID) PRODUCTID
		 , COALESCE(P2.CATEGORY_NM, P.CATEGORY_NM) CATEGORY_NM
		 , COALESCE(P2.NAME_NM, P.NAME_NM) PRODUCT_NM
		 , COALESCE(P2.CODE_NM, P.CODE_NM) CODE_NM
		 , COALESCE(P2.BARCODE_TXT, P.BARCODE_TXT) BARCODE_TXT
		 , SUM(OD.SHIPPED_QTY*OD.ORDERUNIT_QTY) ORDER_QTY
		 , SUM(OD.SHIPPED_QTY*OD.ORDERUNIT_QTY*ISNULL(PR.PRICE_AMT,0)) ORDER_AMT
	  FROM WHS_STOREORDER O
	  JOIN WHS_STOREORDERDETAIL OD ON O.STOREORDERID = OD.STOREORDER
	  JOIN PRD_PRODUCT_VW P ON OD.PRODUCT = P.PRODUCTID
	  LEFT JOIN PRD_PRODUCT_VW P2 ON P.PARENT = P2.PRODUCTID
	  LEFT JOIN PRICE PR ON COALESCE(P2.PRODUCTID, P.PRODUCTID) = PR.PRODUCT
	 WHERE CAST(ORDER_DT AS DATE) BETWEEN @StartDate AND @EndDate
	   AND (@StoreId = -1 OR O.STORE = @StoreId)
	   AND O.STATUS >= 4
	 GROUP BY COALESCE(P2.PRODUCTID, P.PRODUCTID), COALESCE(P2.CATEGORY_NM, P.CATEGORY_NM), 
	 COALESCE(P2.NAME_NM, P.NAME_NM), COALESCE(P2.CODE_NM, P.CODE_NM), COALESCE(P2.BARCODE_TXT, P.BARCODE_TXT)), 
	SALES AS (
	SELECT COALESCE(P2.PRODUCTID, P.PRODUCTID) PRODUCTID
		 , COALESCE(P2.CATEGORY_NM, P.CATEGORY_NM) CATEGORY_NM
		 , COALESCE(P2.NAME_NM, P.NAME_NM) PRODUCT_NM
		 , COALESCE(P2.CODE_NM, P.CODE_NM) CODE_NM
		 , COALESCE(P2.BARCODE_TXT, P.BARCODE_TXT) BARCODE_TXT
		 , SUM(QUANTITY) SALE_QTY, SUM(PRICE) SALE_AMT
	  FROM SLS_STOREDAILYPRODUCT_SYN
	  JOIN PRD_PRODUCT_VW P ON PRODUCT = P.PRODUCTID
	  LEFT JOIN PRD_PRODUCT_VW P2 ON P.PARENT = P2.PRODUCTID
	 WHERE TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND (@StoreId = -1 OR STORE = @StoreId)
	 GROUP BY COALESCE(P2.PRODUCTID, P.PRODUCTID), COALESCE(P2.CATEGORY_NM, P.CATEGORY_NM), 
	 COALESCE(P2.NAME_NM, P.NAME_NM), COALESCE(P2.CODE_NM, P.CODE_NM), COALESCE(P2.BARCODE_TXT, P.BARCODE_TXT) ) 
	SELECT COALESCE(A.PRODUCTID, B.PRODUCTID) PRODUCTID
		 , COALESCE(A.PRODUCT_NM, B.PRODUCT_NM) PRODUCT_NM
		 , COALESCE(A.CODE_NM, B.CODE_NM) CODE_NM
		 , COALESCE(A.BARCODE_TXT, B.BARCODE_TXT) BARCODE_TXT
		 , COALESCE(A.CATEGORY_NM, B.CATEGORY_NM) CATEGORY_NM
		 , A.ORDER_QTY, A.ORDER_AMT, B.SALE_QTY, B.SALE_AMT
		 , (A.ORDER_AMT - B.SALE_AMT) / B.SALE_AMT DIFF 
		 , B.SALE_AMT / SUM(B.SALE_AMT) OVER (PARTITION BY 1) SALE_PCT
		 , B.SALE_AMT / SUM(B.SALE_AMT) OVER (PARTITION BY COALESCE(A.CATEGORY_NM, B.CATEGORY_NM) ) SALECATEGORY_PCT
	  FROM ORDERS A
	  FULL OUTER JOIN SALES B ON A.PRODUCTID = B.PRODUCTID;

END;