CREATE PROCEDURE WHS_LST_NOORDERSTORES_SP AS
BEGIN
	DECLARE @nextWorkingDay DATE, @dayofweek_no INT
	SELECT @nextWorkingDay = MIN(DATE_DT)
	  FROM RPT_DATE
	 WHERE DATE_DT > CAST(GETDATE() AS DATE)
	   AND DAYOFWEEK_NO != 7
	SELECT @dayofweek_no = DAYOFWEEK_NO  
	  FROM RPT_DATE
	 WHERE DATE_DT = @nextWorkingDay
	SELECT ST.*
	  FROM WHS_SHIPMENTSCHEDULE SS
	  JOIN STR_STORE ST ON SS.STORE = ST.STOREID
	  LEFT JOIN WHS_STOREORDER SO ON SS.STORE = SO.STORE AND SO.SHIPMENT_DT = @nextWorkingDay AND SO.STATUS >= 2
	 WHERE SUBSTRING(SCHEDULE_TXT,(@dayofweek_no - 1)*2+1,1) = 1
	   AND ST.ACTIVE_FL = 'Y'
	   AND SO.STOREORDERID IS NULL
END