CREATE PROCEDURE WHS_LST_ORDERGATHERING_SP @StoreOrderId BIGINT AS
BEGIN
	SELECT G.PRODUCTCODE_NM
		 , G.PRODUCT_NM
		 , G.ORDER_QTY * OD.ORDERUNIT_QTY ORDER_QTY
		 , G.PALLET_NO
		 , G.GATHERINGUSER_NM
		 , G.GATHERING_TM
		 , G.GATHERED_QTY * OD.ORDERUNIT_QTY GATHERED_QTY
		 , G.GATHERINGSTATUS
		 , G.CONTROLUSER_NM
		 , G.CONTROL_TM
		 , G.CONTROL_QTY * OD.ORDERUNIT_QTY CONTROL_QTY
		 , G.GATHERINGPALLETSTATUS
		 , G.PROCESSSTATUS
		 , U.UNIT_NM UNITNAME
		 , B.BARCODE_TXT
		 , OD.SHIPPED_QTY * OD.ORDERUNIT_QTY SHIPPED_QTY
		 , G.STATUS
	  FROM WHS_GATHERINGDETAIL_VW G 
	  JOIN PRD_PRODUCT P ON P.CODE_NM = G.PRODUCTCODE_NM
	  JOIN PRD_UNIT U ON U.UNITID = P.UNIT
	  LEFT JOIN (SELECT PRODUCT, MAX(BARCODE_TXT) BARCODE_TXT FROM PRD_BARCODE GROUP BY PRODUCT) B ON B.PRODUCT = P.PRODUCTID
	  JOIN WHS_STOREORDERDETAIL OD ON G.STOREORDERDETAILID = OD.STOREORDERDETAILID
	 WHERE G.STOREORDER = @StoreOrderId
	 ORDER BY G.PALLET_NO, GATHERING_TM DESC, LOADORDER_TXT
END