CREATE PROCEDURE WHS_INS_TOCDETAIL_SP @TocId INT, @ProductId INT, @Sales NUMERIC(10,3), @SourceCode INT AS
BEGIN
  SET NOCOUNT OFF
  INSERT INTO WHS_TOCDETAIL
  (TOCID, DETAILPRODUCT, PACKAGE_QTY, ORDER_QTY, SOURCE_CD)
  SELECT @TocId, PRODUCTID, U.PACKAGE_QTY
	   , CEILING((@Sales * S.QUANTITY / S.GROUPTOTALQUANTITY)/U.PACKAGE_QTY)*U.PACKAGE_QTY ORDER_QTY
	   , @SourceCode 
    FROM PRD_STOCKGROUPPURCHASE_VW S
	JOIN (SELECT PRODUCT, CASE WHEN PACKAGE_QTY = 0 THEN 1 ELSE PACKAGE_QTY END PACKAGE_QTY FROM WHS_PRODUCTSHIPMENTUNIT WHERE SHIPMENTTYPE = 1) U ON S.PRODUCTID = U.PRODUCT
   WHERE GROUPPRODUCTID = @ProductId
     AND S.QUANTITY > 0

  IF @@ROWCOUNT = 0
  BEGIN
    INSERT INTO WHS_TOCDETAIL
	(TOCID, DETAILPRODUCT, PACKAGE_QTY, ORDER_QTY, SOURCE_CD)
	SELECT @TocId, PRODUCT, U.PACKAGE_QTY, CEILING(@Sales / U.PACKAGE_QTY)*U.PACKAGE_QTY ORDER_QTY, @SourceCode
	  FROM (SELECT PRODUCT, CASE WHEN PACKAGE_QTY = 0 THEN 1 ELSE PACKAGE_QTY END PACKAGE_QTY FROM WHS_PRODUCTSHIPMENTUNIT WHERE SHIPMENTTYPE = 1) U
	 WHERE PRODUCT = @ProductId
  END
  SET NOCOUNT ON
END