CREATE PROCEDURE WHS_LST_TOCPROGRESS_SP @StoreId INT, @StartDate DATE, @EndDate DATE AS
BEGIN
	SELECT TOCID, TOC_DT, STORE, STORE_NM, PRODUCT, PRODUCT_NM, GREENLIMIT_QTY, YELLOWLIMIT_QTY, REDLIMIT_QTY, REDREMNANT_QTY, BUFFER_QTY, STOCK_QTY, 
		   SALE_QTY, INTAKE_QTY, ORDER_QTY, PERIOD_NO
	  FROM (
	SELECT T.TOCID, T.TOC_DT, T.STORE, ST.STORE_NM, T.PRODUCT, COALESCE(SGN.STOCKGROUP_NM, P.NAME_NM) PRODUCT_NM,
		   T.GREENLIMIT_QTY, T.YELLOWLIMIT_QTY, T.REDLIMIT_QTY, T.REDREMNANT_QTY, T.BUFFER_QTY, T.STOCK_QTY, 
		   T.SALE_QTY, T.INTAKE_QTY, ISNULL(TD.ORDER_QTY,0) ORDER_QTY, T.PERIOD_NO, MAX(GREENLIMIT_QTY) OVER (PARTITION BY T.PRODUCT) MAXGREENLIMIT
	  FROM WHS_TOC T
	  JOIN STR_STORE ST ON T.STORE = ST.STOREID
	  LEFT JOIN PRD_PRODUCT P ON T.PRODUCT = P.PRODUCTID
	  LEFT JOIN PRD_STOCKGROUPNAME SGN ON T.PRODUCT = 10000+SGN.STOCKGROUPID
	  LEFT JOIN (SELECT TOCID, SUM(ORDER_QTY) ORDER_QTY FROM WHS_TOCDETAIL GROUP BY TOCID) TD ON T.TOCID = TD.TOCID
	 WHERE T.STORE = @StoreId 
	   AND T.TOC_DT BETWEEN @StartDate AND @EndDate) A
	 ORDER BY MAXGREENLIMIT DESC, TOC_DT
END