CREATE PROCEDURE WHS_RPT_MATERIALORDER_SP @StartDate DATE, @EndDate DATE AS
BEGIN
	SELECT MO.MATERIALORDERID, MO.ORDER_NM, MO.CREATE_DT, MO.ORDER_DT, ST.STOREID, ST.STORE_NM, MO.ORDERSTATUS_CD, M.MATERIALID, 
		   M.MATERIAL_NM+CASE WHEN MI.INFOSHORT_NM IS NULL THEN '' ELSE '-'+MI.INFOSHORT_NM END MATERIAL_NM, MOS.STATUS_NM, 
		   SHIPMENTORDERDATE.HISTORY_TM SHIPMENTORDER_TM, DATEDIFF(DAY, MO.CREATE_DT, SHIPMENTORDERDATE.HISTORY_TM) SHIPMENTORDERDATEDIFF,
		   SHIPPEDDATE.HISTORY_TM SHIPPED_TM, DATEDIFF(DAY, SHIPMENTORDERDATE.HISTORY_TM, SHIPPEDDATE.HISTORY_TM) SHIPPEDDATEDIFF,
		   ACCEPTDATE.HISTORY_TM ACCEPT_TM, DATEDIFF(DAY, SHIPPEDDATE.HISTORY_TM, ACCEPTDATE.HISTORY_TM) ACCEPTDATEDIFF
	  FROM WHS_MATERIALORDER MO
	  JOIN DBO.[WHS_MATERIALORDERSTATUS_FN]() MOS ON MO.ORDERSTATUS_CD = MOS.STATUS_CD
	  JOIN STR_STORE ST ON MO.STORE = ST.STOREID
	  JOIN WHS_MATERIAL	M ON MO.MATERIAL = M.MATERIALID
	  LEFT JOIN WHS_MATERIALINFO MI ON M.MATERIALID = MI.MATERIAL AND MO.MATERIALINFO = MI.MATERIALINFOID
	  LEFT JOIN (SELECT MATERIALORDER, MAX(HISTORY_TM) HISTORY_TM FROM WHS_MATERIALORDERSTATUSHIST WHERE STATUS_CD = 3 GROUP BY MATERIALORDER) SHIPMENTORDERDATE ON SHIPMENTORDERDATE.MATERIALORDER = MO.MATERIALORDERID
	  LEFT JOIN (SELECT MATERIALORDER, MAX(HISTORY_TM) HISTORY_TM FROM WHS_MATERIALORDERSTATUSHIST WHERE STATUS_CD = 4 GROUP BY MATERIALORDER) SHIPPEDDATE  ON SHIPPEDDATE.MATERIALORDER = MO.MATERIALORDERID
	  LEFT JOIN (SELECT MATERIALORDER, MAX(HISTORY_TM) HISTORY_TM FROM WHS_MATERIALORDERSTATUSHIST WHERE STATUS_CD = 5 GROUP BY MATERIALORDER) ACCEPTDATE  ON ACCEPTDATE.MATERIALORDER = MO.MATERIALORDERID
	 WHERE ORDER_DT BETWEEN @StartDate AND @EndDate
	   AND MO.DELETED_FL = 'N'
	 ORDER BY CREATE_DT
END