CREATE PROCEDURE WHS_LST_DRILLCOUNT_SP @StartDate DATE, @EndDate DATE, @ProductId INT = -1, @StoreId INT = -1, @RegionManagerId INT = -1 AS   
BEGIN  
    SELECT AA.COUNTING_DT, CATEGORY_NM, SUBGROUP_NM,  
           AA.CODE_NM, AA.PRODUCTNAME, AA.STORE_NM,   
           ISNULL(RM.MANAGER_NM, '-') REGIONMANAGERNAME, AA.COUNTINGVALUE_AMT,   
           DC.STOCK, DC.DIFF_AMT, DC.SALE_AMT, DC.LASTCOUNTING_DT,  
           CASE WHEN DC.SALE_AMT > 0 THEN DC.DIFF_AMT / DC.SALE_AMT ELSE 0 END SUCCESSKPI  
      FROM (  
            SELECT A.STOCKTAKINGSCHEDULEID, COALESCE(10000 + SGW.STOCKGROUP, ISNULL(PP.PRODUCTID, P.PRODUCTID)) PRODUCT, CAST(PLANNED_DT AS DATE) COUNTING_DT,   
                   C.CATEGORY_NM, SG.SUBGROUP_NM,  
                   ISNULL(PP.CODE_NM, P.CODE_NM) CODE_NM, ISNULL(PP.NAME_NM, P.NAME_NM) PRODUCTNAME,  
                   ST.STORE_NM, ST.REGIONMANAGER, SUM(B.COUNTINGVALUE_AMT) COUNTINGVALUE_AMT  
              FROM WHS_STOCKTAKINGSCHEDULE A  
              JOIN WHS_STOCKTAKING B ON A.STOCKTAKINGSCHEDULEID = B.STOCKTAKINGSCHEDULE  
              JOIN PRD_PRODUCT P ON B.PRODUCT = P.PRODUCTID  
              JOIN STR_STOREWHINC_VW ST ON A.STORE = ST.STOREID  
              LEFT JOIN PRD_PRODUCT PP ON P.PARENT = PP.PRODUCTID  
              LEFT JOIN PRD_SUBGROUP SG ON P.SUBGROUP = SG.SUBGROUPID  
              LEFT JOIN PRD_CATEGORY C ON SG.CATEGORY = C.CATEGORYID  
              LEFT JOIN PRD_STOCKGROUP_VW SGW ON P.PRODUCTID = SGW.PRODUCTID AND SGW.USAGETYPE_CD = 1
             WHERE PLANNED_DT BETWEEN @StartDate AND @EndDate  
               AND COUNTINGTYPE = 2  
               AND B.UPDATE_DT IS NOT NULL  
               AND (@StoreId = -1 OR A.STORE = @StoreId)  
               AND (@ProductId = -1 OR B.PRODUCT = @ProductId)      
			   AND (@RegionManagerId = -1 OR ST.REGIONMANAGER = @RegionManagerId)
             GROUP BY A.STOCKTAKINGSCHEDULEID, COALESCE(10000 + SGW.STOCKGROUP, ISNULL(PP.PRODUCTID, P.PRODUCTID)), CAST(PLANNED_DT AS DATE),  
                      C.CATEGORY_NM, SG.SUBGROUP_NM,  
                      ISNULL(PP.CODE_NM, P.CODE_NM), ISNULL(PP.NAME_NM, P.NAME_NM), ST.STORE_NM, ST.REGIONMANAGER) AA  
      LEFT JOIN WHS_DRILLCOUNTSUMMARY DC ON AA.STOCKTAKINGSCHEDULEID = DC.SCHEDULEID AND AA.PRODUCT = DC.PRODUCT  
      LEFT JOIN STR_REGIONMANAGERS RM ON AA.REGIONMANAGER = RM.REGIONMANAGERSID  
END