ALTER PROCEDURE WHS_LST_COUNTEDSTORES_SP AS
BEGIN
  SELECT DISTINCT ST.*
    FROM WHS_STOCKTAKINGSCHEDULE S
    JOIN STR_STORE ST ON S.STORE = ST.STOREID
   WHERE S.COUNTINGTYPE = 1
     AND S.STATUS = 2
	 AND S.DELETED_FL = 'N'
   UNION ALL
  SELECT TOP 1 999, ORGANIZATION, DELETED_FL, CREATE_DT, UPDATE_DT, CREATEUSER, UPDATEUSER, 'MERKEZ DEPO'
	   , BRANCH, IPADDRESS_TXT, ADVANCE_AMT, OPENING_DT, CLOSING_DT, ACTIVE_FL, PRODUCTION_FL, CITY
	   , TOWN, ADDRESS_TXT, REGIONMANAGER, INCONSTRUCTION_FL
    FROM STR_STORE
   WHERE DELETED_FL = 'N'
     AND ACTIVE_FL = 'Y'
END