CREATE PROCEDURE [dbo].[WHS_UPD_GATHERSUMMARY_SP] AS
BEGIN

	IF OBJECT_ID('tempdb.dbo.#SUMMARYTABLE', 'U') IS NOT NULL DROP TABLE #SUMMARYTABLE;
	SELECT *
	  INTO #SUMMARYTABLE
	  FROM WHS_GATHERSUMMARY_VW
	 WHERE GATHER_DT >= CAST(GETDATE() - 3 AS DATE)

	INSERT INTO WHS_GATHERSUMMARY_SYN
	SELECT A.*
	  FROM #SUMMARYTABLE A
	  LEFT JOIN WHS_GATHERSUMMARY_SYN B ON A.STOREORDER = B.STOREORDER AND A.GATHERINGUSER = B.GATHERINGUSER AND A.GATHERINGTYPE = B.GATHERINGTYPE AND A.GATHER_DT = B.GATHER_DT AND A.GATHERHOUR = B.GATHERHOUR
	 WHERE B.STOREORDER IS NULL

	DELETE B
	  FROM #SUMMARYTABLE A
	 RIGHT JOIN WHS_GATHERSUMMARY_SYN B ON A.STOREORDER = B.STOREORDER AND A.GATHERINGUSER = B.GATHERINGUSER AND A.GATHERINGTYPE = B.GATHERINGTYPE AND A.GATHER_DT = B.GATHER_DT AND A.GATHERHOUR = B.GATHERHOUR
	 WHERE A.STOREORDER IS NULL
	   AND B.GATHER_DT >= CAST(GETDATE() - 3 AS DATE)

	UPDATE B  
	   SET B.GATHERINGWEIGHT_QTY = A.GATHERINGWEIGHT_QTY
		 , B.GATHERPACKAGE_QTY = A.GATHERPACKAGE_QTY
		 , B.GATHERPALLET_CNT = A.GATHERPALLET_CNT
		 , B.GATHERPRICE_AMT = A.GATHERPRICE_AMT
		 , B.GATHERPRODUCT_CNT = A.GATHERPRODUCT_CNT
		 , B.CONTROLERR_CNT = A.CONTROLERR_CNT
		 , B.CONTROLDIFF_CNT = A.CONTROLDIFF_CNT
	   FROM #SUMMARYTABLE A  
	   JOIN WHS_GATHERSUMMARY_SYN B ON A.STOREORDER = B.STOREORDER AND A.GATHERINGUSER = B.GATHERINGUSER AND A.GATHERINGTYPE = B.GATHERINGTYPE AND A.GATHER_DT = B.GATHER_DT AND A.GATHERHOUR = B.GATHERHOUR
	  WHERE B.GATHERINGWEIGHT_QTY != A.GATHERINGWEIGHT_QTY	
		 OR B.GATHERPACKAGE_QTY != A.GATHERPACKAGE_QTY
		 OR B.GATHERPALLET_CNT != A.GATHERPALLET_CNT
		 OR B.GATHERPRICE_AMT != A.GATHERPRICE_AMT
		 OR B.GATHERPRODUCT_CNT != A.GATHERPRODUCT_CNT
		 OR B.CONTROLERR_CNT != A.CONTROLERR_CNT
		 OR B.CONTROLDIFF_CNT != A.CONTROLDIFF_CNT

END