CREATE PROCEDURE WHS_LST_INTAKESTATUS_SP
AS
BEGIN
    DECLARE @StartDate DATE, @EndDate DATE
	Set @EndDate = CAST(GETDATE() AS DATE)
	SET @StartDate = DATEADD(MM, -3, @EndDate)
	
	IF OBJECT_ID('tempdb.dbo.#mikroA', 'U') IS NOT NULL  DROP TABLE #mikroA;
	IF OBJECT_ID('tempdb.dbo.#storeOrderIds', 'U') IS NOT NULL  DROP TABLE #storeOrderIds;
	IF OBJECT_ID('tempdb.dbo.#historyStatus5', 'U') IS NOT NULL  DROP TABLE #historyStatus5;  

	SELECT A.STOREORDER
	  INTO #storeOrderIds 
	  FROM (SELECT DISTINCT STOREORDER 
	          FROM WHS_STOREORDERDETAIL (NOLOCK) 
	         WHERE STOREORDERDETAILID IN (SELECT DISTINCT STOREORDERDETAIL FROM WHS_INTAKESTATUS (NOLOCK))) A;

    SELECT sth_giris_depo_no STORE
         , sth_evrakno_sira STOREORDER
	     , P.PRODUCTID PRODUCT
	     , SUM(sth_miktar) QUANTITY
	     , MAX(sth_tarih) SHIPMENT_DT
      INTO #mikroA
	  FROM MIK_TRANSACTION_VW MQ
	  JOIN PRD_PRODUCT P ON MQ.sth_stok_kod COLLATE Turkish_100_CI_AS = P.CODE_NM
	  JOIN #storeOrderIds OID ON MQ.sth_evrakno_sira = OID.STOREORDER
     WHERE sth_evraktip = 2 AND sth_evrakno_seri = 'OMS'
	   AND sth_tarih BETWEEN @StartDate AND @EndDate
     GROUP BY sth_giris_depo_no, sth_evrakno_sira, P.PRODUCTID

	SELECT A.* 
      INTO #historyStatus5
      FROM (SELECT STOREORDER, HISTORY_TM, ROW_NUMBER() OVER (PARTITION BY STOREORDER ORDER BY OH.HISTORY_TM DESC) ROWNO
		      FROM WHS_STOREORDERHISTORY OH 
             WHERE OH.[STATUS] = 5 
	           AND OH.STOREORDER IN (SELECT STOREORDER FROM #storeOrderIds)
			   AND OH.DELETED_FL = 'N') A
	WHERE A.ROWNO = 1

    SELECT
           I.INTAKESTATUSID,
           I.EVENT,
           I.ORGANIZATION,
           I.DELETED_FL,
           I.CREATE_DT,
           I.UPDATE_DT,
           I.CREATEUSER,
           I.UPDATEUSER,
           I.CREATECHANNEL,
           I.CREATEBRANCH,
           I.CREATESCREEN,
           I.STOREORDERDETAIL,
           I.INTAKESTATUSTYPE,
           I.DESCRIPTION_DSC,
           I.MIKROTRANSFER_FL,
           I.MIKROTRANSFER_TM,
           I.QUANTITYDIF_QTY,
		   CASE WHEN QUANTITYDIF_QTY < 0 THEN 'MD' ELSE 'DM' END DIFFTYPE_TXT,
		   P.NAME_NM PRODUCT_NM,
		   CASE P.UNIT WHEN 1 THEN 'Kg' WHEN 2 THEN 'Adet' END UNIT_NM,
		   ST.STORE_NM,
		   O.ORDER_DT,
		   ISNULL(M.SHIPMENT_DT, O.SHIPMENT_DT) MIKROSHIPMENT_DT,
		   OH.HISTORY_TM INTAKE_DT,
		   -- OD.SHIPPED_QTY * OD.ORDERUNIT_QTY SHIPPED_QTY,
		   ISNULL(M.QUANTITY, 0) SHIPPED_QTY,
		   OD.INTAKE_QTY * OD.ORDERUNIT_QTY INTAKE_QTY,
		   O.STOREORDERID STOREORDER
      FROM WHS_INTAKESTATUS I (NOLOCK)
	  JOIN WHS_STOREORDERDETAIL OD (NOLOCK) ON I.STOREORDERDETAIL = OD.STOREORDERDETAILID
	  JOIN WHS_STOREORDER O (NOLOCK) ON OD.STOREORDER = O.STOREORDERID
	  JOIN #historyStatus5 OH ON OH.STOREORDER = OD.STOREORDER
	  JOIN PRD_PRODUCT P ON OD.PRODUCT = P.PRODUCTID
	  JOIN STR_STORE ST ON O.STORE = ST.STOREID
	  LEFT JOIN #mikroA M ON M.STOREORDER = OD.STOREORDER AND M.PRODUCT = OD.PRODUCT AND M.STORE = ST.STOREID
     WHERE I.DELETED_FL = 'N'
     ORDER BY I.INTAKESTATUSID;

/*Section="End"*/
END;