CREATE PROCEDURE WHS_LST_COUNTINGREPORT_SP
 @StoreId INT = -1,    
 @CountingDate DATE,    
 @EntryStatus INT = 0 -- 0: tümü, 1: giriş yapılanlar, 2: giriş yapılmayanlar  
AS    
BEGIN 

	DECLARE @IFEXIST INT
	SELECT @IFEXIST = COUNT(*) FROM WHS_STOCKTAKING (NOLOCK) WHERE STORE = @StoreId AND COUNTING_DT = @CountingDate;

	WITH COUNTINGTABLE AS    
		(SELECT * FROM WHS_STOCKTAKING (NOLOCK)
			WHERE COUNTING_DT = @CountingDate AND STORE = @StoreId)    
	
	SELECT P.CATEGORY_NM, P.CODE_NM, P.NAME_NM PRODUCT_NM,     
		SUM(CASE WHEN ZONE = 1 THEN COUNTINGVALUE_AMT END) WAREHOUSE_AMT,    
		SUM(CASE WHEN ZONE = 2 THEN COUNTINGVALUE_AMT END) STAND_AMT,    
		SUM(CASE WHEN ZONE = 3 THEN COUNTINGVALUE_AMT END) ADDITIONALSTAND_AMT,  
		MAX(P.UNIT_NM) UNIT_NM 
	FROM PRD_PRODUCT_VW P    
	LEFT JOIN COUNTINGTABLE TK ON TK.PRODUCT = P.PRODUCTID    
	WHERE @IFEXIST > 0
	GROUP BY P.CATEGORY_NM, P.CODE_NM, P.NAME_NM    
	HAVING (@EntryStatus = 0 OR (@EntryStatus = 1 AND SUM(COALESCE(COUNTINGVALUE_AMT,0)) > 0) OR (@EntryStatus = 2 AND SUM(COALESCE(COUNTINGVALUE_AMT,0)) = 0));    
END 