CREATE PROCEDURE WHS_RPT_PRODUCTRETURN_SP @StartDate DATE, @EndDate DATE, @ProductId INT = -1, @StoreId INT = -1 AS
BEGIN
	SELECT ST.STORE_NM, C.CATEGORY_NM, P.CODE_NM, P.NAME_NM, RETURN_DT, RETURNQUANTITY_AMT
		 , CASE WHEN P.UNIT = 1 THEN 'KG' ELSE 'ADET' END UNIT
		 , CASE STATUS_CD  
		   WHEN 1 THEN 'Giriş'  
		   WHEN 2 THEN 'Onaylandı'  
		   WHEN 3 THEN 'Sevk Edildi'  
		   WHEN 4 THEN 'Kabul Edildi'  
		   WHEN 6 THEN 'Reddedildi'  
		   WHEN 7 THEN 'İptal'  
		   ELSE 'Tanımsız'  
		   END STATUS_TXT
		 , RD.DESTINATION_NM, INTAKE_AMT, WAYBILL_DT, WAYBILL_TXT
		 , CASE WHEN CUSTOMERRETURN_FL = 'Y' THEN 'Müşteri İade' ELSE 'Mağaza İade' END RETURNTYPE_TXT
		 , S.TRANSACTION_DT REFUND_DT, S.TRANSACTION_TXT RECEIPT_TXT
		 , CAST(S.SALEID AS VARCHAR) RECEIPTID, CAST(SD.SALEDETAILID AS VARCHAR) RECEIPTLINEID
		 , CASE WHEN REUSABLE_FL = 'Y' THEN 'Tekrar Kullanılabilir' ELSE 'Tekrar Kullanılamaz' END REUSAGE_TXT
		 , SUPPLIER_TXT, MANUFACTURING_DT, EXPIRE_DT, RETURNREASON_TXT
	  FROM WHS_PRODUCTRETURN PR
	  JOIN PRD_PRODUCT P ON PR.PRODUCT = P.PRODUCTID
	  JOIN PRD_SUBGROUP SG ON P.SUBGROUP = SG.SUBGROUPID
	  JOIN PRD_CATEGORY C ON C.CATEGORYID = SG.CATEGORY
	  JOIN STR_STORE ST ON PR.STORE = ST.STOREID
	  LEFT JOIN WHS_RETURNDESTINATION RD ON PR.RETURNDESTINATION = RD.RETURNDESTINATIONID
	  LEFT JOIN SLS_SALEDETAIL SD ON PR.SALEDETAIL = SD.SALEDETAILID
	  LEFT JOIN SLS_SALE S ON SD.SALE = S.SALEID
	 WHERE PR.DELETED_FL = 'N'
	   AND PR.RETURN_DT BETWEEN @StartDate AND @EndDate
	   AND (@ProductId = -1 OR PR.PRODUCT = @ProductId)
	   AND (@StoreId = -1 OR PR.STORE = @StoreId)
     ORDER BY RETURN_DT
END
