CREATE PROCEDURE WHS_UPD_ALIGNORDERGATHERING_SP AS
BEGIN
	DECLARE @StartDate DATE = CAST(GETDATE()-7 AS DATE)
	INSERT INTO WHS_GATHERING
	(EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, 
	 STOREORDER, GATHERINGSTATUS, GATHERINGTYPE, PRIORITY_NO)
	SELECT SO.EVENT, SO.ORGANIZATION, 'N', GETDATE(), SO.CREATEUSER, SO.CREATECHANNEL, SO.CREATEBRANCH, SO.CREATESCREEN,
		   SO.STOREORDERID, 1, GT.GATHERINGTYPE, 0
	  FROM WHS_STOREORDER SO
	  JOIN (SELECT 1 GATHERINGTYPE UNION ALL SELECT 2) GT ON 1=1
	  LEFT JOIN WHS_GATHERING G ON SO.STOREORDERID = G.STOREORDER
	 WHERE SO.STATUS IN (3,4)
	   AND SHIPMENT_DT >= @StartDate
	   AND G.GATHERINGID IS NULL

	INSERT INTO WHS_GATHERINGDETAIL 
	(EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, 
	 STOREORDERDETAIL, GATHERING, PALLET_NO)
	SELECT SOD.EVENT, SOD.ORGANIZATION, 'N', GETDATE(), SOD.CREATEUSER, SOD.CREATECHANNEL, SOD.CREATEBRANCH, SOD.CREATESCREEN,
		   SOD.STOREORDERDETAILID, G.GATHERINGID, 1 
	  FROM WHS_STOREORDER SO
	  JOIN WHS_STOREORDERDETAIL SOD ON SO.STOREORDERID = SOD.STOREORDER
	  JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
	  JOIN WHS_GATHERING G ON SO.STOREORDERID = G.STOREORDER AND GATHERINGTYPE = 1
	  LEFT JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING AND SOD.STOREORDERDETAILID = GD.STOREORDERDETAIL
	 WHERE SHIPMENT_DT >= @StartDate
	   AND SO.STATUS IN (3,4)
	   AND P.LOADORDER_TXT LIKE 'A%'
	   AND SOD.SHIPPED_QTY > 0
	   AND GD.GATHERINGDETAILID IS NULL

	INSERT INTO WHS_GATHERINGDETAIL 
	(EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, 
	 STOREORDERDETAIL, GATHERING, PALLET_NO)
	SELECT SOD.EVENT, SOD.ORGANIZATION, 'N', GETDATE(), SOD.CREATEUSER, SOD.CREATECHANNEL, SOD.CREATEBRANCH, SOD.CREATESCREEN,
		   SOD.STOREORDERDETAILID, G.GATHERINGID, 1 
	  FROM WHS_STOREORDER SO
	  JOIN WHS_STOREORDERDETAIL SOD ON SO.STOREORDERID = SOD.STOREORDER
	  JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
	  JOIN WHS_GATHERING G ON SO.STOREORDERID = G.STOREORDER AND GATHERINGTYPE = 2
	  LEFT JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING AND SOD.STOREORDERDETAILID = GD.STOREORDERDETAIL
	 WHERE SHIPMENT_DT >= @StartDate
	   AND SO.STATUS IN (3,4)
	   AND NOT(P.LOADORDER_TXT LIKE 'A%')
	   AND SOD.SHIPPED_QTY > 0
	   AND GD.GATHERINGDETAILID IS NULL
END