CREATE PROCEDURE [dbo].[WHS_SEL_GATHERINGSTATS_SP] @User INT = -1
AS

IF @User = -1 OR @User IS NULL
	SELECT SUM(CASE WHEN G.GATHERINGSTATUS = 1 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END) WAITINGLIGHT_CNT, 
		   SUM(CASE WHEN G.GATHERINGSTATUS = 1 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END) WAITINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 2 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END)  PROCESSINGLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 2 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END)  PROCESSINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 3 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END)  ONHOLDLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 3 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END)  ONHOLDHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 9 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END) WAITINGFORCONTROLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 9 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END) WAITINGFORCONTROLHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 12 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END)  CONTROLLINGLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 12 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END)  CONTROLLINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 13 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END)  ONHOLDCONTROLLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 13 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END)  ONHOLDCONTROLHEAVY_CNT
		   -- SUM(CASE WHEN G.GATHERINGSTATUS = 19 AND G.GATHERINGTYPE = 2 AND CAST(G.GATHERINGEND_TM AS DATE) = GETDATE() THEN 1 ELSE 0 END)  COMPLETEDTODAYLIGHT_CNT,
		   -- SUM(CASE WHEN G.GATHERINGSTATUS = 19 AND G.GATHERINGTYPE = 1 AND CAST(G.GATHERINGEND_TM AS DATE) = GETDATE() THEN 1 ELSE 0 END)  COMPLETEDTODAYHEAVY_CNT
	  FROM WHS_GATHERING G
	  JOIN WHS_STOREORDER O ON G.STOREORDER = O.STOREORDERID AND O.STATUS = 3
	 WHERE G.DELETED_FL = 'N'

ELSE
	SELECT SUM(CASE WHEN G.GATHERINGSTATUS = 1 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END) WAITINGLIGHT_CNT, 
		   SUM(CASE WHEN G.GATHERINGSTATUS = 1 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END) WAITINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 2 AND G.GATHERINGTYPE = 2 AND U.USERID = @User THEN 1 ELSE 0 END)  PROCESSINGLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 2 AND G.GATHERINGTYPE = 1 AND U.USERID = @User THEN 1 ELSE 0 END)  PROCESSINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 3 AND G.GATHERINGTYPE = 2 AND U.USERID = @User THEN 1 ELSE 0 END)  ONHOLDLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 3 AND G.GATHERINGTYPE = 1 AND U.USERID = @User THEN 1 ELSE 0 END)  ONHOLDHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 9 AND G.GATHERINGTYPE = 2 THEN 1 ELSE 0 END) WAITINGFORCONTROLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 9 AND G.GATHERINGTYPE = 1 THEN 1 ELSE 0 END) WAITINGFORCONTROLHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 12 AND G.GATHERINGTYPE = 2 AND U.USERID = @User THEN 1 ELSE 0 END)  CONTROLLINGLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 12 AND G.GATHERINGTYPE = 1 AND U.USERID = @User THEN 1 ELSE 0 END)  CONTROLLINGHEAVY_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 13 AND G.GATHERINGTYPE = 2 AND U.USERID = @User THEN 1 ELSE 0 END)  ONHOLDCONTROLLIGHT_CNT,
		   SUM(CASE WHEN G.GATHERINGSTATUS = 13 AND G.GATHERINGTYPE = 1 AND U.USERID = @User THEN 1 ELSE 0 END)  ONHOLDCONTROLHEAVY_CNT
		   -- SUM(CASE WHEN G.GATHERINGSTATUS = 19 AND G.GATHERINGTYPE = 2 AND U.USERID = @UserId AND CAST(G.GATHERINGEND_TM AS DATE) = GETDATE() THEN 1 ELSE 0 END)  COMPLETEDTODAYLIGHT_CNT,
		   -- SUM(CASE WHEN G.GATHERINGSTATUS = 19 AND G.GATHERINGTYPE = 1 AND U.USERID = @UserId AND CAST(G.GATHERINGEND_TM AS DATE) = GETDATE() THEN 1 ELSE 0 END)  COMPLETEDTODAYHEAVY_CNT
	  FROM WHS_GATHERING G
	  JOIN WHS_STOREORDER O ON G.STOREORDER = O.STOREORDERID AND O.STATUS = 3
	  LEFT JOIN SEC_USER U ON ISNULL(G.CONTROLLERUSER, G.GATHERINGUSER) = U.USERID
	 WHERE G.DELETED_FL = 'N'