CREATE PROCEDURE WHS_LST_PRODUCT_SP AS
BEGIN

	-- Shipped in last 48 hours
	IF OBJECT_ID('tempdb..#onwayProducts') IS NOT NULL DROP TABLE #onwayProducts
	IF OBJECT_ID('tempdb..#stores') IS NOT NULL DROP TABLE #stores

	select STOREID into #stores from dbo.STR_GETUSERSTORES_FN();

	DECLARE @storeCount INT, @storeId INT;
	SELECT @storeCount = COUNT(*) FROM #stores;
	SET @storeId = -1;
	IF @storeCount = 1 
	BEGIN
	  SELECT TOP 1 @storeId = STOREID from #stores;
	END

	DECLARE @twodaysago DATE
	SET @twodaysago = CAST(DATEADD(DAY, -2, GETDATE()) AS DATE)
	SELECT D.PRODUCT, SUM(D.SHIPPED_QTY) ONWAY_QTY
	  INTO #onwayProducts
	  FROM WHS_STOREORDERDETAIL D
	  JOIN WHS_STOREORDER M ON D.STOREORDER = M.STOREORDERID
	 WHERE M.STATUS = 4
	   AND M.SHIPMENT_DT >= @twodaysago
	   AND M.STORE = @storeId
	 GROUP BY D.PRODUCT;

	SELECT P.PRODUCTID, P.CODE_NM, SCALECODE_NM, C.CATEGORY_NM, SG.SUBGROUP_NM, P.NAME_NM, 
		   S.PACKAGE_QTY,  PT.PACKAGETYPE_NM, 
		   CASE P.UNIT WHEN 1 THEN 'KG' ELSE 'AD' END UNIT_NM, P.LOADORDER_TXT LOCATION_TXT, ONWAY_QTY, PR.PRICE_AMT,
		   P.NAME_NM+' - '+P.CODE_NM+' - '+C.CATEGORY_NM+' - '+COALESCE(SCALECODE_NM,'') SEARCHSTRING
	  FROM PRD_PRODUCT P
	  JOIN WHS_PRODUCTSHIPMENTUNIT S ON P.PRODUCTID = S.PRODUCT AND S.SHIPMENTTYPE = 1
	  JOIN WHS_PACKAGETYPE PT ON S.PACKAGETYPE = PT.PACKAGETYPEID
	  LEFT JOIN PRC_ACTIVEPACKAGEPRICES_VW PR ON P.PRODUCTID = PR.PRODUCT AND PR.PACKAGE = 1
	  LEFT JOIN PRD_SUBGROUP SG ON P.SUBGROUP = SG.SUBGROUPID
	  LEFT JOIN PRD_CATEGORY C ON SG.CATEGORY = C.CATEGORYID
	  LEFT JOIN #onwayProducts OW ON P.PRODUCTID = OW.PRODUCT
	  LEFT JOIN (SELECT PRODUCT, MAX(SUBSTRING(BARCODE_TXT,4,10)) SCALECODE_NM 
				   FROM PRD_BARCODE WHERE BARCODE_TXT LIKE '290%' AND BARCODETYPE = 1 
				  GROUP BY PRODUCT) B ON P.PRODUCTID = B.PRODUCT
	 WHERE PACKAGE_QTY != 0

END
