CREATE PROCEDURE WHS_LST_TOPSALEDAYGROUP_SP 
	@StoreId INT, 
	@ProductId INT, 
	@StartDate DATE,
	@EndDate DATE AS
BEGIN
  SELECT YESTERDAY, TRANSACTION_DT, TOMORROW, LAGQUANTITY, QUANTITY, LEADQUANTITY, LAGQUANTITY + QUANTITY + LEADQUANTITY TOTAL
    FROM (
  SELECT *
       , ISNULL(LAG(QUANTITY) OVER (ORDER BY TRANSACTION_DT),0) LAGQUANTITY
	   , ISNULL(LEAD(QUANTITY) OVER (ORDER BY TRANSACTION_DT),0) LEADQUANTITY
	   , LAG(TRANSACTION_DT) OVER (ORDER BY TRANSACTION_DT) LAGDATE
	   , LEAD(TRANSACTION_DT) OVER (ORDER BY TRANSACTION_DT) LEADDATE
	   , DATEADD(DAY,-1,TRANSACTION_DT) YESTERDAY
	   , DATEADD(DAY,1,TRANSACTION_DT) TOMORROW
    FROM SLS_STOREDAILYPRODUCT_SYN
   WHERE STORE = @StoreId
     AND PRODUCT = @ProductId
     AND TRANSACTION_DT BETWEEN @StartDate AND @EndDate) A
   WHERE YESTERDAY = LAGDATE  
     AND TOMORROW = LEADDATE
   ORDER BY LAGQUANTITY + QUANTITY + LEADQUANTITY DESC
END