CREATE PROCEDURE [dbo].[WHS_LST_ACTIVECONTROLPALLET_SP] AS
BEGIN
	SELECT GP.*, ST.STORE_NM, SO.ORDER_DT, SO.SHIPMENT_DT, SO.ORDERCODE_NM, GT.GATHERINGTYPEID, GT.GATHERINGTYPE_NM, U.USERFULL_NM CONTROLUSER_NM
	  FROM WHS_GATHERING G (NOLOCK)
	  JOIN WHS_GATHERINGPALLET GP (NOLOCK) ON G.GATHERINGID = GP.GATHERING
	  JOIN WHS_STOREORDER SO (NOLOCK) ON G.STOREORDER = SO.STOREORDERID
	  JOIN STR_STORE ST (NOLOCK) ON SO.STORE = ST.STOREID
	  JOIN WHS_GATHERINGTYPE GT (NOLOCK) ON G.GATHERINGTYPE = GT.GATHERINGTYPEID
	  LEFT JOIN SEC_USER U (NOLOCK) ON GP.CONTROLUSER = U.USERID
	 WHERE SO.STATUS = 3
END