CREATE PROCEDURE WHS_LST_STOCKGROUPPARAMETER_SP AS
BEGIN
	SELECT DISTINCT COALESCE(10000+STGN.STOCKGROUPID, P.PRODUCTID) GROUPID, ISNULL(STGN.STOCKGROUP_NM, P.NAME_NM) STOCKGROUP_NM
	  FROM PRD_PRODUCT P 
	  LEFT JOIN PRD_STOCKGROUP STG ON P.PRODUCTID = STG.PRODUCTID
	  LEFT JOIN PRD_STOCKGROUPNAME STGN ON STG.STOCKGROUP = STGN.STOCKGROUPID
	 WHERE P.DELETED_FL = 'N'
END