CREATE PROCEDURE WHS_LST_SCHEDULES_SP AS
BEGIN
  IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;     
  SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();
  SELECT *
       , ST.STORE_NM + '-' + convert(varchar, SC.PLANNED_DT, 103) + '-' + CT.COUNTINGTYPE_NM SCHEDULEFULL_NM
    FROM WHS_STOCKTAKINGSCHEDULE SC
	JOIN #STORES ST ON SC.STORE = ST.STOREID
	JOIN WHS_COUNTINGTYPE (NOLOCK) CT ON SC.COUNTINGTYPE = CT.COUNTINGTYPEID
   WHERE STATUS = 1
     AND SC.COUNTINGTYPE = 1
     AND SC.DELETED_FL = 'N'
END