CREATE PROCEDURE WHS_LST_CONSIGNMENTPURCHASEREPORT_SP @StartDate DATE, @EndDate DATE, @Product INT = -1
AS
BEGIN
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();

  SELECT ST.STORE_NM,
		 COUNT(DISTINCT CG.PRODUCT) PRODUCT_CN,
		 COUNT(CG.CONSIGNMENTGOODPURCHASEID) QUANTITY_CN,
		 SUM(CG.QUANTITY_QTY) QUANTITY_QTY
    FROM WHS_CONSIGNMENTGOODPURCHASE (NOLOCK) CG
	JOIN #stores ST ON ST.STOREID = CG.STORE
   WHERE CG.CREATE_DT BETWEEN @StartDate AND @EndDate
     AND (@Product IS NULL OR @Product = -1 OR @Product = CG.PRODUCT)
GROUP BY CG.STORE, ST.STORE_NM

END;