CREATE PROCEDURE WHS_UPD_COUNTINGSTOCK_SP AS
BEGIN

  DELETE A
  -- SELECT A.*
    FROM WHS_COUNTINGSTOCK A
	LEFT JOIN WHS_COUNTINGSTOCK_VW B ON A.STORE = B.STORE AND A.DATE_DT = B.DATE_DT AND A.PRODUCT = B.PRODUCT AND B.DATE_DT >= GETDATE() - 60
   WHERE A.DATE_DT >= GETDATE() - 60
     AND B.STORE IS NULL

  UPDATE A
     SET A.PREVCOUNTING = B.PREVCOUNTING, A.STOCK = B.STOCK, A.NEWCOUNTING = B.NEWCOUNTING
	FROM WHS_COUNTINGSTOCK A
	JOIN WHS_COUNTINGSTOCK_VW B ON A.STORE = B.STORE AND A.DATE_DT = B.DATE_DT AND A.PRODUCT = B.PRODUCT AND B.DATE_DT >= GETDATE() - 60
   WHERE A.DATE_DT >= GETDATE() - 60
     AND (A.PREVCOUNTING != B.PREVCOUNTING OR A.STOCK != B.STOCK OR A.NEWCOUNTING != B.NEWCOUNTING)

  INSERT INTO WHS_COUNTINGSTOCK
  SELECT A.*
	FROM WHS_COUNTINGSTOCK_VW A
	LEFT JOIN WHS_COUNTINGSTOCK B ON A.STORE = B.STORE AND A.DATE_DT = B.DATE_DT AND A.PRODUCT = B.PRODUCT
   WHERE A.DATE_DT >= GETDATE() - 60
     AND B.STORE IS NULL

END