CREATE PROCEDURE WHS_LST_CONSIGNMENTGOODPURCHASE_SP
AS
BEGIN

	IF OBJECT_ID('tempdb..#stores') IS NOT NULL DROP TABLE #stores
	SELECT STOREID INTO #stores FROM dbo.STR_GETUSERSTORES_FN();

    SELECT
           C.CONSIGNMENTGOODPURCHASEID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           C.STORE,
           C.PRODUCT,
           C.SUPPLIER,
           ABS(C.QUANTITY_QTY) QUANTITY_QTY,
		   U.UNIT_NM UNITNAME,
		   CASE WHEN C.QUANTITY_QTY >= 0 THEN 'Alım' ELSE 'İade' END TRANSACTIONTYPE
      FROM WHS_CONSIGNMENTGOODPURCHASE C (NOLOCK)
	  JOIN PRD_PRODUCT P ON P.PRODUCTID = C.PRODUCT
	  JOIN PRD_UNIT U ON U.UNITID = P.UNIT
     WHERE C.STORE IN (SELECT STOREID FROM #stores)
       AND C.DELETED_FL = 'N'
  ORDER BY CONSIGNMENTGOODPURCHASEID;

END;
