CREATE PROCEDURE WHS_LST_STORESCHEDULES_SP @StoreId INT AS
BEGIN
  SELECT *
       , ST.STORE_NM + '-' + convert(varchar, SC.PLANNED_DT, 103) + '-' + CT.COUNTINGTYPE_NM SCHEDULEFULL_NM
    FROM WHS_STOCKTAKINGSCHEDULE SC
	JOIN STR_STORE ST ON SC.STORE = ST.STOREID
	JOIN WHS_COUNTINGTYPE (NOLOCK) CT ON SC.COUNTINGTYPE = CT.COUNTINGTYPEID
   WHERE STATUS = 1
     AND SC.DELETED_FL = 'N'
	 AND ST.STOREID = @StoreId
END