CREATE PROCEDURE WHS_LST_STOCKDIFFLIST_SP AS
BEGIN
	SELECT STOCKTAKINGSCHEDULEID, STORE_NM+' - '+CONVERT(VARCHAR,ACTUAL_DT,104) COUNTING_NM
	  FROM (
	SELECT STOCKTAKINGSCHEDULEID, STORE, ST.STORE_NM, ACTUAL_DT
		 , LAG(ACTUAL_DT) OVER (PARTITION BY STORE ORDER BY ACTUAL_DT) LAGACTUAL_DT
		 , LAG(STOCKTAKINGSCHEDULEID) OVER (PARTITION BY STORE ORDER BY ACTUAL_DT) LAGSTOCKTAKINGSCHEDULEID
	  FROM WHS_STOCKTAKINGSCHEDULE SS
	  JOIN STR_STORE ST ON SS.STORE = ST.STOREID
	 WHERE COUNTINGTYPE = 1
	   AND SS.DELETED_FL = 'N'
	   AND STATUS = 2) A
	 WHERE LAGACTUAL_DT IS NOT NULL
	 ORDER BY ACTUAL_DT DESC
END