CREATE PROCEDURE WHS_LST_DBOARDHOURGATHERING_SP AS
BEGIN
	
	DECLARE @startDate DATE = CONVERT(DATE, '20200210', 112)
	DECLARE @today DATE = CAST(GETDATE() AS DATE)

	DECLARE @yesterday DATE  
	SELECT @yesterday = MAX(DATE_DT)  
	  FROM RPT_DATE  
	 WHERE DATE_DT <= CAST(GETDATE() - 1 AS DATE)  
	   AND DAYOFWEEK_NO != 7;  
	
	IF OBJECT_ID('tempdb.dbo.#RESULT', 'U') IS NOT NULL DROP TABLE #RESULT;

	SELECT * INTO #RESULT 
	  FROM (
	SELECT @yesterday GATHER_DT, GATHERINGTYPE, GATHERHOUR, SUM(GATHERINGWEIGHT_QTY) / COUNT(DISTINCT GATHER_DT) GATHERINGWEIGHT
	  FROM WHS_GATHERSUMMARY_SYN
	 WHERE GATHER_DT >= @startDate
	   AND GATHER_DT < @today
     GROUP BY GATHERINGTYPE, GATHERHOUR
	 UNION ALL
	SELECT @today GATHER_DT, GATHERINGTYPE, GATHERHOUR, SUM(GATHERINGWEIGHT_QTY) / COUNT(DISTINCT GATHER_DT)
	  FROM WHS_GATHERSUMMARY_VW
	 WHERE GATHER_DT = @today
     GROUP BY GATHERINGTYPE, GATHERHOUR ) A;
	 
	WITH HOURS AS (
	SELECT DISTINCT GATHERHOUR
	  FROM #RESULT
	 WHERE GATHERHOUR <= DATEPART(HOUR, GETDATE()) + 1),  
	DAYS AS (
	SELECT DISTINCT GATHERINGTYPE, GATHER_DT
	  FROM #RESULT)
	SELECT D.GATHERINGTYPE, D.GATHER_DT, H.GATHERHOUR, ISNULL(G.GATHERINGWEIGHT, 0) GATHERINGWEIGHT
	  FROM DAYS D
	  JOIN HOURS H ON 1 = 1
	  LEFT JOIN #RESULT G ON D.GATHERINGTYPE = G.GATHERINGTYPE AND D.GATHER_DT = G.GATHER_DT AND H.GATHERHOUR = G.GATHERHOUR
	 ORDER BY 1, 2, 3
END