CREATE PROCEDURE [dbo].[WHS_LST_ACTIVECONTROLPALLET_SP] AS
BEGIN
	SELECT GP.*, ST.STORE_NM, SO.ORDER_DT, SO.SHIPMENT_DT, SO.ORDERCODE_NM, GT.GATHERINGTYPE_NM, GT.GATHERINGTYPEID
	  FROM WHS_GATHERING G
	  JOIN WHS_GATHERINGPALLET GP ON G.GATHERINGID = GP.GATHERING AND GP.DELETED_FL = 'N'
	  JOIN WHS_STOREORDER SO ON G.STOREORDER = SO.STOREORDERID
	  JOIN STR_STORE ST ON SO.STORE = ST.STOREID
	  JOIN WHS_GATHERINGTYPE GT ON G.GATHERINGTYPE = GT.GATHERINGTYPEID
	 WHERE SO.STATUS = 3
	   AND G.DELETED_FL = 'N'  
END