CREATE PROCEDURE WHS_LST_PRODUCTRETURNREASON_SP @ProductReturnId INT AS
BEGIN
    SELECT
           P.PRODUCTRETURNREASONID,
           P.EVENT,
           P.ORGANIZATION,
           P.DELETED_FL,
           P.CREATE_DT,
           P.UPDATE_DT,
           P.CREATEUSER,
           P.UPDATEUSER,
           P.CREATECHANNEL,
           P.CREATEBRANCH,
           P.CREATESCREEN,
           P.PRODUCTRETURN,
           P.RETURNREASON,
		   ISNULL(RR2.REASON_NM,'') + CASE WHEN RR2.REASON_NM IS NOT NULL THEN '->' ELSE '' END + RR.REASON_NM REASON_NM
      FROM WHS_PRODUCTRETURNREASON P (NOLOCK)
	  JOIN WHS_RETURNREASON RR (NOLOCK) ON P.RETURNREASON = RR.RETURNREASONID
	  LEFT JOIN WHS_RETURNREASON RR2 (NOLOCK) ON RR.PARENT = RR2.RETURNREASONID
     WHERE DELETED_FL = 'N'
	   AND PRODUCTRETURN = @ProductReturnId
END;
