CREATE PROCEDURE WHS_LST_TRANSFERPRODUCT_SP
AS
BEGIN

	IF OBJECT_ID('tempdb..#stores') IS NOT NULL DROP TABLE #stores       
	select STOREID into #stores from dbo.STR_GETUSERSTORES_FN();            

    DECLARE @Organization INT;
    SELECT @Organization = dbo.SYS_GETCURRENTORGANIZATION_FN();
    IF dbo.SYS_ISSYSTEMORGANIZATION_FN() = 1
    BEGIN
      SET @Organization = null;
    END;

	WITH ACTIONCOMMENTS AS (
		SELECT USERCOMMENT_DSC, PROCESSINSTANCE 
		FROM (SELECT USERCOMMENT_DSC, PROCESSINSTANCE, ROW_NUMBER() OVER(PARTITION BY PROCESSINSTANCE ORDER BY ACTIONID DESC) ROWNO
				FROM BPA_ACTION 
			   WHERE CHOICE_TXT IS NOT NULL  
				 AND PROCESSINSTANCE IN (SELECT PROCESSINSTANCE_LNO FROM WHS_TRANSFERPRODUCT) ) B
		WHERE B.ROWNO = 1 )
    SELECT T.TRANSFERPRODUCTID,
           T.EVENT,
           T.ORGANIZATION,
           T.DELETED_FL,
           T.CREATE_DT,
           T.UPDATE_DT,
           T.CREATEUSER,
           T.UPDATEUSER,
           T.CREATECHANNEL,
           T.CREATEBRANCH,
           T.CREATESCREEN,
           T.SOURCESTORE,
           T.DESTINATIONSTORE,
           T.PROCESSINSTANCE_LNO,
           T.TRANSFERSTATUS,
		   T.WAYBILL_TXT,
           T.RETURNDESTINATION,
		   A.USERCOMMENT_DSC PREVIOUSCOMMENT_DSC,
		   CASE I.STATUS_CD WHEN 3 THEN 'IDLE' WHEN 4 THEN 'COMPLETED' WHEN 5 THEN 'CANCELLED' WHEN 6 THEN 'FAILED' ELSE 'OTHER' END PROCESSSTATUS_DSC
      FROM WHS_TRANSFERPRODUCT T (NOLOCK)
	  JOIN #stores ST ON T.SOURCESTORE = ST.STOREID
	  LEFT JOIN BPM_PROCESSINSTANCE I ON T.PROCESSINSTANCE_LNO = I.PROCESSINSTANCEID
	  LEFT JOIN ACTIONCOMMENTS A ON A.PROCESSINSTANCE = T.PROCESSINSTANCE_LNO
     WHERE (@Organization IS NULL OR T.ORGANIZATION = @Organization)
       AND T.DELETED_FL = 'N'
	   AND ISNULL(I.STATUS_CD,1) != 5
     ORDER BY TRANSFERPRODUCTID DESC;

END;
