CREATE PROCEDURE WHS_LST_RETURNORDER_SP AS
BEGIN
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  SELECT * into #stores FROM dbo.STR_GETUSERSTORES_FN();
  SELECT R.RETURNORDERID,
         R.EVENT,
         R.ORGANIZATION,
         R.DELETED_FL,
         R.CREATE_DT,
         R.UPDATE_DT,
         R.CREATEUSER,
         R.UPDATEUSER,
         R.CREATECHANNEL,
         R.CREATEBRANCH,
         R.CREATESCREEN,
         R.STORE,
         R.STATUS,
		 R.PROCESSINSTANCE_LNO
    FROM WHS_RETURNORDER R (NOLOCK)
	JOIN #stores ST ON R.STORE = ST.STOREID
   WHERE R.DELETED_FL = 'N'
     AND R.STATUS NOT IN (6, 7)
   ORDER BY R.CREATE_DT DESC

END;
