CREATE PROCEDURE [dbo].[WHS_INS_INTAKESTATUSBATCH_SP] @Store INT = -1, @StartDate DATE = NULL, @EndDate DATE = NULL, @Product INT = -1 AS
BEGIN

IF @EndDate IS NULL
	BEGIN
	Set @EndDate = CAST(GETDATE() AS DATE)
	END
IF @StartDate IS NULL
	BEGIN
	Set @StartDate = DATEADD(MM, -1, @EndDate)
	END

IF OBJECT_ID('tempdb.dbo.#DifferencesTable', 'U') IS NOT NULL  DROP TABLE #DifferencesTable;
CREATE TABLE #DifferencesTable (
   STOREORDER INT,
   STORE INT,
   STORE_NM VARCHAR(50),
   SHIPMENTDT_PLANNED DATE,
   SHIPMENTDT_ACTUAL DATE,
   INTAKE_TM DATETIME,
   SHIPMENTDT_MIKRO DATE,
   CODE_NM VARCHAR(20),
   NAME_NM VARCHAR(50),
   CATEGORY_NM VARCHAR(50),
   UNIT_NM VARCHAR(10),
   UNIT_SALE_PRICE INT,
   ORDERUNIT_QTY NUMERIC(10,2), 
   SHIPPED_QTY NUMERIC(10,2),
   MIKRO_QTY NUMERIC(10,2), 
   INTAKE_QTY NUMERIC(10,2),
   QUANTITY_DIFFERENCE NUMERIC(12,4),
   SHIPPEDUSER VARCHAR(50),
   INTAKEUSER VARCHAR(50),
   DECISION VARCHAR(50))


INSERT INTO #DifferencesTable
EXEC WHS_LST_STOREORDERDIFFREPORT_SP @Store, @StartDate, @EndDate, @Product

DELETE A
-- SELECT A.*, B.PRODUCT, B.STOREORDER
  FROM WHS_INTAKESTATUS A  
  JOIN WHS_STOREORDERDETAIL B ON A.STOREORDERDETAIL = B.STOREORDERDETAILID  
  JOIN PRD_PRODUCT P ON B.PRODUCT = P.PRODUCTID  
  JOIN (SELECT DISTINCT sth_evrakno_sira FROM MIK_TRANSACTION20_SYN WHERE sth_evrakno_seri = 'OMS' AND sth_tarih BETWEEN @StartDate AND @EndDate) T ON B.STOREORDER = T.sth_evrakno_sira 
  -- JOIN (SELECT DISTINCT STOREORDER FROM #DifferencesTable) D ON B.STOREORDER = D.STOREORDER  
  LEFT JOIN #DifferencesTable D2 ON B.STOREORDER = D2.STOREORDER AND P.CODE_NM COLLATE Turkish_CI_AS= D2.CODE_NM  
 WHERE MIKROTRANSFER_FL = 'N'  
   AND D2.STOREORDER IS NULL  
   AND A.DELETED_FL = 'N'
   AND B.DELETED_FL = 'N'

INSERT INTO WHS_INTAKESTATUS 
SELECT OD.[EVENT]
	 , OD.ORGANIZATION
	 , 'N'
	 , GETDATE()
	 , NULL
     , dbo.SYS_GETCURRENTUSER_FN()
     , NULL
     , dbo.SYS_GETCURRENTCHANNEL_FN()
     , dbo.SYS_GETCURRENTBRANCH_FN()
     , dbo.SYS_GETCURRENTSCREEN_FN()
	 , OD.STOREORDERDETAILID STOREORDERDETAIL
	 , 3
	 , NULL
	 , 'N'
	 , NULL
	 , DT.QUANTITY_DIFFERENCE
  FROM #DifferencesTable DT
  JOIN PRD_PRODUCT P ON P.CODE_NM COLLATE Turkish_CI_AS = DT.CODE_NM
  JOIN WHS_STOREORDERDETAIL (NOLOCK) OD ON OD.STOREORDER = DT.STOREORDER AND OD.PRODUCT = P.PRODUCTID
  LEFT JOIN WHS_INTAKESTATUS NS ON NS.STOREORDERDETAIL = OD.STOREORDERDETAILID
 WHERE NS.STOREORDERDETAIL IS NULL 

UPDATE NS SET NS.QUANTITYDIF_QTY = DT.QUANTITY_DIFFERENCE
-- SELECT DT.*, NS.*
  FROM #DifferencesTable DT
  JOIN PRD_PRODUCT P ON P.CODE_NM COLLATE Turkish_CI_AS = DT.CODE_NM
  JOIN WHS_STOREORDERDETAIL (NOLOCK) OD ON OD.STOREORDER = DT.STOREORDER AND OD.PRODUCT = P.PRODUCTID
  JOIN WHS_INTAKESTATUS NS ON NS.STOREORDERDETAIL = OD.STOREORDERDETAILID
 WHERE DT.QUANTITY_DIFFERENCE != NS.QUANTITYDIF_QTY AND NS.MIKROTRANSFER_FL = 'N'

END