CREATE PROCEDURE WHS_SEL_STOREORDER_SP @StoreOrderId BIGINT AS
BEGIN
	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;     
	SELECT * INTO #STORES FROM dbo.STR_GETUSERSTORES_FN();

    WITH AUTHLEVEL AS (
		SELECT USERID, USER_NM, CASE WHEN AdminRole=1 THEN 4 WHEN ManagerRole = 1 THEN 3 WHEN ITRole = 1 THEN 2 WHEN RegionRole = 1 THEN 1 ELSE 0 END AUTHLEVEL_CD
		  FROM (
		SELECT U.USERID, U.USER_NM
			 , SUM(CASE WHEN G.GROUP_NM = 'System Administrators' THEN 1 ELSE 0 END) AdminRole
			 , SUM(CASE WHEN G.GROUP_NM = 'Genel Müdür' THEN 1 ELSE 0 END) ManagerRole
			 , SUM(CASE WHEN G.GROUP_NM = 'Bilgi Sistemleri Kullanıcıları' THEN 1 ELSE 0 END) ITRole
			 , SUM(CASE WHEN G.GROUP_NM = 'Bölge Sorumluları' THEN 1 ELSE 0 END) RegionRole
		  FROM SEC_USER U (NOLOCK)
		  JOIN SEC_GROUPUSER GU (NOLOCK) ON U.USERID = GU.MEMBERUSER
		  JOIN SEC_GROUP G (NOLOCK) ON GU.CONTAINERGROUP = G.GROUPID
		 WHERE U.DELETED_FL = 'N'
		 GROUP BY U.USERID, U.USER_NM) A ) 
    SELECT S.STOREORDERID,
           S.EVENT,
           S.ORGANIZATION,
           S.DELETED_FL,
           S.CREATE_DT,
           S.UPDATE_DT,
           S.CREATEUSER,
           S.UPDATEUSER,
           S.CREATECHANNEL,
           S.CREATEBRANCH,
           S.CREATESCREEN,
           S.STORE,
           S.ORDERCODE_NM,
           S.STATUS,
           CAST(S.ORDER_DT AS DATE) ORDER_DT,
           CAST(S.SHIPMENT_DT AS DATE) SHIPMENT_DT,
		   CASE WHEN S.STATUS = 1 THEN 'Y' ELSE 'N' END APPROVEENABLED_FL,
		   'Y' EDITDETAILSENABLED_FL,
		   CASE WHEN S.STATUS = 2 THEN 'Y' ELSE 'N' END PRINTENABLED_FL,
		   CASE WHEN S.STATUS = 3 THEN 'Y' ELSE 'N' END SHIPMENTENABLED_FL,
		   ST.STORE_NM,
		   H.FIRSTENTRYUSER,
		   H.FIRSTENTRYTIME,
		   H.LASTAPPROVEUSER,
		   H.LASTAPPROVETIME,
		   H.CONTROLUSER,
		   H.CONTROLTIME,
		   H.DISPATCHUSER,
		   H.DISPATCHTIME,
		   ISNULL(AL.AUTHLEVEL_CD, 0) AUTHLEVEL_CD
      FROM WHS_STOREORDER S (NOLOCK)
	  LEFT JOIN AUTHLEVEL AL ON S.CREATEUSER = AL.USERID
	  JOIN #stores ST ON S.STORE = ST.STOREID
	  LEFT JOIN WHS_ORDERSTATUSHISTORY_VW H (NOLOCK) ON S.STOREORDERID = H.STOREORDER
     WHERE S.STOREORDERID = @StoreOrderId;
END;
