CREATE PROCEDURE WHS_BAT_TOC_SP AS
BEGIN
	
	DECLARE @storeId INT

	DECLARE @today DATE = CAST(GETDATE()-0.25 AS DATE)
	
	DECLARE store_cursor CURSOR FOR SELECT STOREID FROM STR_STORE_VW WHERE STOREID NOT IN (SELECT STORE FROM WHS_TOCSTORE)
	
	OPEN store_cursor
	FETCH NEXT FROM store_cursor INTO @storeId

	WHILE @@FETCH_STATUS = 0    
	BEGIN

		BEGIN TRY  
			BEGIN TRANSACTION
			EXEC WHS_UPD_STORETOC_SP @storeId
			INSERT INTO WHS_TOCRUNLOG VALUES (@storeId, @today, GETDATE(), 'OK')
			COMMIT TRANSACTION
		END TRY  

		BEGIN CATCH  
			ROLLBACK TRANSACTION
			INSERT INTO WHS_TOCRUNLOG VALUES (@storeId, @today, GETDATE(), ERROR_MESSAGE())
		END CATCH  

		FETCH NEXT FROM store_cursor INTO @storeId
  
	END 

	CLOSE store_cursor;  
	DEALLOCATE store_cursor;  
END