CREATE PROCEDURE WHS_INS_GATHERINGFROMORDER_SP @StoreOrderId BIGINT AS
BEGIN
 
  IF OBJECT_ID('tempdb.dbo.#GATHERING', 'U') IS NOT NULL  DROP TABLE #GATHERING;

  SELECT SO.STOREORDERID, CASE WHEN LEFT(ISNULL(P.LOADORDER_TXT,'B'),1) = 'A' THEN 1 ELSE 2 END GATHERINGTYPEID, SOD.STOREORDERDETAILID
    INTO #GATHERING
    FROM WHS_STOREORDER SO
	JOIN WHS_STOREORDERDETAIL SOD ON SO.STOREORDERID = SOD.STOREORDER
	JOIN PRD_PRODUCT P ON SOD.PRODUCT = P.PRODUCTID
   WHERE SO.STOREORDERID = @StoreOrderId
     AND COALESCE(SOD.REVISED_QTY, SOD.ORDER_QTY, 0) > 0
  /*
  DELETE GD
    FROM WHS_GATHERING G
	JOIN WHS_GATHERINGDETAIL GD ON G.GATHERINGID = GD.GATHERING
	LEFT JOIN (SELECT DISTINCT STOREORDERID, GATHERINGTYPEID FROM #GATHERING) GG ON G.STOREORDER = GG.STOREORDERID AND G.GATHERINGTYPE = GG.GATHERINGTYPEID
   WHERE G.STOREORDER = @StoreOrderId
     AND GG.STOREORDERID IS NULL

  DELETE G
    FROM WHS_GATHERING G
	LEFT JOIN (SELECT DISTINCT STOREORDERID, GATHERINGTYPEID FROM #GATHERING) GG ON G.STOREORDER = GG.STOREORDERID AND G.GATHERINGTYPE = GG.GATHERINGTYPEID
   WHERE G.STOREORDER = @StoreOrderId
     AND GG.STOREORDERID IS NULL */ 

  INSERT INTO WHS_GATHERING 
  (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, STOREORDER, GATHERINGSTATUS, GATHERINGTYPE)
  SELECT 1, ISNULL(dbo.SYS_GETCURRENTORGANIZATION_FN(), 1), 'N', GETDATE(), 
		 ISNULL(dbo.SYS_GETCURRENTUSER_FN(), 1), ISNULL(dbo.SYS_GETCURRENTCHANNEL_FN(), 1), ISNULL(dbo.SYS_GETCURRENTBRANCH_FN(), 5),
		 ISNULL(dbo.SYS_GETCURRENTSCREEN_FN(), 1), GG.STOREORDERID, 1, GG.GATHERINGTYPEID
    FROM WHS_GATHERING G
	RIGHT JOIN (SELECT DISTINCT STOREORDERID, GATHERINGTYPEID FROM #GATHERING) GG ON G.STOREORDER = GG.STOREORDERID AND G.GATHERINGTYPE = GG.GATHERINGTYPEID
   WHERE GG.STOREORDERID = @StoreOrderId
     AND G.STOREORDER IS NULL

  /*
  DELETE GD
  -- SELECT *
    FROM WHS_GATHERINGDETAIL GD
	JOIN WHS_GATHERING G ON GD.GATHERING = G.GATHERINGID
	LEFT JOIN #GATHERING GG ON G.STOREORDER = GG.STOREORDERID AND G.GATHERINGTYPE = GG.GATHERINGTYPEID AND GD.STOREORDERDETAIL = GG.STOREORDERDETAILID
   WHERE G.STOREORDER = @StoreOrderId
     AND GG.STOREORDERDETAILID IS NULL */
   
  INSERT INTO WHS_GATHERINGDETAIL   
  (EVENT, ORGANIZATION, DELETED_FL, CREATE_DT, CREATEUSER, CREATECHANNEL, CREATEBRANCH, CREATESCREEN, STOREORDERDETAIL, GATHERING, PALLET_NO)
  SELECT 1, ISNULL(dbo.SYS_GETCURRENTORGANIZATION_FN(), 1), 'N', GETDATE(), 
		 ISNULL(dbo.SYS_GETCURRENTUSER_FN(), 1), ISNULL(dbo.SYS_GETCURRENTCHANNEL_FN(), 1), ISNULL(dbo.SYS_GETCURRENTBRANCH_FN(), 5),
		 ISNULL(dbo.SYS_GETCURRENTSCREEN_FN(), 1), GG.STOREORDERDETAILID, G.GATHERINGID, 1
    FROM #GATHERING GG 
	JOIN WHS_GATHERING G ON G.STOREORDER = GG.STOREORDERID AND G.GATHERINGTYPE = GG.GATHERINGTYPEID 
	LEFT JOIN WHS_GATHERINGDETAIL GD ON GD.GATHERING = G.GATHERINGID AND GD.STOREORDERDETAIL = GG.STOREORDERDETAILID
   WHERE G.STOREORDER = @StoreOrderId
     AND GD.STOREORDERDETAIL IS NULL

END