CREATE PROCEDURE WHS_LST_PRODUCTRETURNHISTORY_SP @Id int = 0 AS

DECLARE @ProcessInstance INT;
SELECT @ProcessInstance = PROCESSINSTANCE_LNO FROM WHS_PRODUCTRETURN WHERE PRODUCTRETURNID = @Id

SELECT A.CREATE_DT
	 , A.START_TM
	 , A.FINISH_TM
	 , A.PERFORMER
	 , A.STATUS_CD ACTIONSTATUS_CD
	 , P.STATUS_CD PROCESSSTATUS_CD
	 , A.CHOICE_TXT
	 , A.USERCOMMENT_DSC
  FROM BPA_ACTION A
  JOIN BPM_PROCESSINSTANCE P ON P.PROCESSINSTANCEID = A.PROCESSINSTANCE
 WHERE A.PROCESSINSTANCE = @ProcessInstance
   AND A.DELETED_FL = 'N' 
   AND P.DELETED_FL = 'N'