CREATE TABLE [RCL_EXPENSELOG]
(
    [EXPENSEID] BIGINT NOT NULL,
    [LOG_DT] DATETIME NOT NULL,
    [LOGUSER] INT NOT NULL,
    [LOGOPERATION_CD] VARCHAR(3) NOT NULL,
    [LOGCHANNEL] INT NOT NULL,
    [LOGBRANCH] INT NOT NULL,
    [LOGSCREEN] INT NOT NULL,
    [EXPENSETYPE]   INT NOT NULL,
    [STORE]         INT NULL,
    [EXPENSE_DT]    DATETIME NOT NULL,
    [EXPENSE_AMT]   NUMERIC(22,6) NOT NULL,
    [RECEIPTNO_TXT] VARCHAR(100) NULL,
    [OPEN_FL]       VARCHAR(1) NOT NULL,
    [PAYOFF_DT]     DATETIME NULL,
    [EXPENSE_DSC]   VARCHAR(1000) NULL,
    [VAT_RT]        NUMERIC(4,2) NOT NULL,
);
GO