-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [RCL_EXPENSETYPE]
(
    /*Section="Columns"*/
    [EXPENSETYPEID]   INT NOT NULL IDENTITY,
    [EXPENSETYPE_NM]  VARCHAR(100) NOT NULL,
    [ACCOUNTCODE_TXT] VARCHAR(50) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [RCL_EXPENSETYPE_PK] PRIMARY KEY ([EXPENSETYPEID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [RCL_EXPENSETYPE_X01] ON [RCL_EXPENSETYPE] ([EXPENSETYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Expense Type: Expense Type',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'RCL_EXPENSETYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Type Id: Identity column for RCL_EXPENSETYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSETYPE', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSETYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Type Name: Name of expense type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSETYPE', 
    @level2type=N'COLUMN',
    @level2name=N'EXPENSETYPE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Account Code: Account Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSETYPE', 
    @level2type=N'COLUMN',
    @level2name=N'ACCOUNTCODE_TXT'
GO

/*Section="End"*/
