-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [RCL_EXPENSE]
(
    /*Section="Columns"*/
    [EXPENSEID]     BIGINT NOT NULL IDENTITY,
    [EVENT]         INT NOT NULL,
    [ORGANIZATION]  INT NOT NULL,
    [DELETED_FL]    VARCHAR NOT NULL,
    [CREATE_DT]     DATETIME NOT NULL,
    [UPDATE_DT]     DATETIME NULL,
    [CREATEUSER]    INT NOT NULL,
    [UPDATEUSER]    INT NULL,
    [CREATECHANNEL] INT NOT NULL,
    [CREATEBRANCH]  INT NOT NULL,
    [CREATESCREEN]  INT NOT NULL,
    [EXPENSETYPE]   INT NOT NULL,
    [STORE]         INT NULL,
    [EXPENSE_DT]    DATETIME NOT NULL,
    [EXPENSE_AMT]   NUMERIC(22,6) NOT NULL,
    [RECEIPTNO_TXT] VARCHAR(100) NULL,
    [OPEN_FL]       VARCHAR(1) NOT NULL,
    [PAYOFF_DT]     DATETIME NULL,
    [EXPENSE_DSC]   VARCHAR(1000) NULL,
    [VAT_RT]        NUMERIC(4,2) NOT NULL,
    [MIKRO_CD]      INT NULL,
    [MIKRO_TM]      DATETIME NULL,
    [STATUS_CD]     INT NULL,
    [STATUS_TXT]    VARCHAR(1000) NULL,
    [MIKROUSER]     INT NULL,
    [HASRECEIPT_FL] VARCHAR(1) NOT NULL,
    [REGIONMANAGER] INT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [RCL_EXPENSE_PK] PRIMARY KEY ([EXPENSEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [RCL_EXPENSE_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [RCL_EXPENSE_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [RCL_EXPENSE_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [RCL_EXPENSE_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [RCL_EXPENSE_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [RCL_EXPENSE_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [RCL_EXPENSE_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [RCL_EXPENSE_F08] FOREIGN KEY ([EXPENSETYPE]) REFERENCES [RCL_EXPENSETYPE]([EXPENSETYPEID]),
    CONSTRAINT [RCL_EXPENSE_F09] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [RCL_EXPENSE_F10] FOREIGN KEY ([MIKROUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [RCL_EXPENSE_F11] FOREIGN KEY ([REGIONMANAGER]) REFERENCES [STR_REGIONMANAGERS]([REGIONMANAGERSID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [RCL_EXPENSE_X01] ON [RCL_EXPENSE] ([STORE])
GO

CREATE INDEX [RCL_EXPENSE_X02] ON [RCL_EXPENSE] ([MIKROUSER])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Expense: Store and regional manager expenses',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'RCL_EXPENSE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Id: Identity column for RCL_EXPENSE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Type: Expense Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSETYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Date: Expense Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Amount: Expense Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSE_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'ReceiptNo: ReceiptNo' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'RECEIPTNO_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Open Flag: Open Flag' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'OPEN_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'PayOff Date: PayOff Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'PAYOFF_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Expense Description: Comment for expense.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'EXPENSE_DSC'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'VAT Rate: VAT Rate' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'VAT_RT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Transaction Code: Mikro Transaction Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'MIKRO_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro Time: Mikro Time' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'MIKRO_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Code: Status Code 1: Transferred to Mikro 2: Invalid Expense' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Text: Explanation of why an invalid expense' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Mikro User: Mikro User' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'MIKROUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'HasReceipt: with or without receipt' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'HASRECEIPT_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Region Manager: Region Manager' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'RCL_EXPENSE',
    @level2type=N'COLUMN',
    @level2name=N'REGIONMANAGER'
GO

/*Section="End"*/
