-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [GAM_GAMELEVEL]
(
    /*Section="Columns"*/
    [GAMELEVELID]           INT NOT NULL IDENTITY,
    [GAME]                  INT NOT NULL,
    [LEVEL_NM]              VARCHAR(100) NOT NULL,
    [QUESTION_CNT]          INT NOT NULL,
    [MINDIFFLEVEL_CD]       INT NOT NULL,
    [MAXDIFFLEVEL_CD]       INT NOT NULL,
    [DURATION_CNT]          INT NOT NULL,
    [ERRTOLERANCE_CNT]      INT NULL,
    [POINTOFRIGHTANSWER_NO] INT NOT NULL,
    [LEVEL_CD]              INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [GAM_GAMELEVEL_PK] PRIMARY KEY ([GAMELEVELID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [GAM_GAMELEVEL_F01] FOREIGN KEY ([GAME]) REFERENCES [GAM_GAME]([GAMEID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Game Level: Game Level',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'GAM_GAMELEVEL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Game Level Id: Identity column for GAM_GAMELEVEL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'GAMELEVELID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Game: Game' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'GAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Level Name: Name of game level.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'LEVEL_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Question Count: Question Count' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'QUESTION_CNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Min Difficulty Level: Min Difficulty Level' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'MINDIFFLEVEL_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Max Difficulty Level: Max Difficulty Level' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'MAXDIFFLEVEL_CD'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Duration: Duration' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'DURATION_CNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Level Error Tolerance: Level Error Tolerance' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'ERRTOLERANCE_CNT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Point of Right Answer: Point of Right Answer' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'POINTOFRIGHTANSWER_NO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Level Code: Level Code' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'GAM_GAMELEVEL', 
    @level2type=N'COLUMN',
    @level2name=N'LEVEL_CD'
GO

/*Section="End"*/
