-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [SLS_SALEPAYMENT]
(
    /*Section="Columns"*/
    [SALEPAYMENTID]   BIGINT NOT NULL IDENTITY,
    [EVENT]           INT NOT NULL,
    [ORGANIZATION]    INT NOT NULL,
    [DELETED_FL]      VARCHAR NOT NULL,
    [CREATE_DT]       DATETIME NOT NULL,
    [UPDATE_DT]       DATETIME NULL,
    [CREATEUSER]      INT NOT NULL,
    [UPDATEUSER]      INT NULL,
    [CREATECHANNEL]   INT NOT NULL,
    [CREATEBRANCH]    INT NOT NULL,
    [CREATESCREEN]    INT NOT NULL,
    [SALE]            BIGINT NOT NULL,
    [TRANSACTION_TXT] VARCHAR(100) NOT NULL,
    [TRANSACTION_DT]  DATETIME NOT NULL,
    [STORE]           INT NOT NULL,
    [PAYMENTTYPE_TXT] VARCHAR(10) NOT NULL,
    [PAID_AMT]        NUMERIC(22,6) NOT NULL,
    [REFUND_AMT]      NUMERIC(22,6) NOT NULL,
    [POSBANKTYPE]     INT NULL,
    [POSTRXTYPE]      INT NULL,
    [ACCNO_TXT]       VARCHAR(100) NULL,
    [DEBITCARD_FL]    VARCHAR(1) NULL,
    [CARD_AMT]        NUMERIC(22,6) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [SLS_SALEPAYMENT_PK] PRIMARY KEY ([SALEPAYMENTID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [SLS_SALEPAYMENT_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [SLS_SALEPAYMENT_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [SLS_SALEPAYMENT_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SLS_SALEPAYMENT_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SLS_SALEPAYMENT_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [SLS_SALEPAYMENT_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [SLS_SALEPAYMENT_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [SLS_SALEPAYMENT_F08] FOREIGN KEY ([SALE]) REFERENCES [SLS_SALE]([SALEID]),
    CONSTRAINT [SLS_SALEPAYMENT_F09] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [SLS_SALEPAYMENT_X01] ON [SLS_SALEPAYMENT] ([SALE])
GO

CREATE INDEX [SLS_SALEPAYMENT_X02] ON [SLS_SALEPAYMENT] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Sale Payment: Sale Payment',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'SLS_SALEPAYMENT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale Payment Id: Identity column for SLS_SALEPAYMENT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'SALEPAYMENTID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale ID: Sale ID' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'SALE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Transaction ID: Transaction Unique Text Key' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'TRANSACTION_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Transaction Date: Transaction Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'TRANSACTION_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Payment Type: Payment Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'PAYMENTTYPE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Paid Amount: Paid Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'PAID_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Refund Amount: Refund Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'REFUND_AMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Pos Bank Type: Pos Bank Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'POSBANKTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Pos Trx Type: Pos Trx Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'POSTRXTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'CreditCardNo: CreditCardNo' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'ACCNO_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Is Debit Card: Is Debit Card' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'DEBITCARD_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Credit Card Amount: Credit Card Amount' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SLS_SALEPAYMENT',
    @level2type=N'COLUMN',
    @level2name=N'CARD_AMT'
GO

/*Section="End"*/
