-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [SLS_CANCELREASON]
(
    /*Section="Columns"*/
    [CANCELREASONID] BIGINT NOT NULL IDENTITY,
    [EVENT]          INT NOT NULL,
    [ORGANIZATION]   INT NOT NULL,
    [DELETED_FL]     VARCHAR NOT NULL,
    [CREATE_DT]      DATETIME NOT NULL,
    [UPDATE_DT]      DATETIME NULL,
    [CREATEUSER]     INT NOT NULL,
    [UPDATEUSER]     INT NULL,
    [CREATECHANNEL]  INT NOT NULL,
    [CREATEBRANCH]   INT NOT NULL,
    [CREATESCREEN]   INT NOT NULL,
    [STOREREC]       BIGINT NOT NULL,
    [SALEDETAIL]     BIGINT NOT NULL,
    [REASON_TXT]     VARCHAR(1000) NOT NULL,
    [CASHIER_NM]     VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [SLS_CANCELREASON_PK] PRIMARY KEY ([CANCELREASONID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [SLS_CANCELREASON_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [SLS_CANCELREASON_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [SLS_CANCELREASON_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SLS_CANCELREASON_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SLS_CANCELREASON_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [SLS_CANCELREASON_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [SLS_CANCELREASON_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [SLS_CANCELREASON_F08] FOREIGN KEY ([STOREREC]) REFERENCES [RCL_STORE]([STORERECID]),
);
GO

/*Section="Indexes"*/

CREATE INDEX [SLS_CANCELREASON_X01] ON [SLS_CANCELREASON] ([STOREREC])
GO

CREATE UNIQUE INDEX [SLS_CANCELREASON_X02] ON [SLS_CANCELREASON] ([SALEDETAIL])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Cancel Reason: Cancel Reason',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'SLS_CANCELREASON',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Cancel Reason Id: Identity column for SLS_CANCELREASON' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CANCELREASONID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Reconciliation: Store Reconciliation' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'STOREREC'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Sale Detail: Sale Detail' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'SALEDETAIL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Reason Text: Reason Text' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'REASON_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Cashier Name: Name of cashier' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'SLS_CANCELREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CASHIER_NM'
GO

/*Section="End"*/
