CREATE PROCEDURE RCL_LST_PAIDEXPENSES_SP @StoreId INT, @Date DATE AS
BEGIN
  WITH USERS AS (
  SELECT U.USERID, ST.STORE_NM
    FROM SEC_USER U
    JOIN STR_STORE ST ON U.BRANCH = ST.BRANCH
   WHERE ST.ACTIVE_FL = 'Y') 
  SELECT DISTINCT E.*
    FROM RCL_EXPENSE E
	JOIN USERS U ON E.CREATEUSER = U.USERID
   WHERE STORE = @StoreId 
     AND PAYOFF_DT = @Date
	 -- AND CAST(PAYOFF_DT AS DATE) != CAST(EXPENSE_DT AS DATE)
	 AND OPEN_FL = 'N'
END
