CREATE PROCEDURE [dbo].[RCL_LST_EXPENSEREPORT_SP] @StartDate DATE, @EndDate DATE, @StoreList VARCHAR(MAX), @ExpenseTypeList VARCHAR(MAX), @ManagerList VARCHAR(MAX) AS    
BEGIN    
  
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL DROP TABLE #stores;      
  IF OBJECT_ID('tempdb.dbo.#expensetypes', 'U') IS NOT NULL DROP TABLE #expensetypes;      
  IF OBJECT_ID('tempdb.dbo.#managers', 'U') IS NOT NULL DROP TABLE #managers;      
  
  SELECT *     
    INTO #stores     
    FROM STR_STORE    
   WHERE @StoreList IS NULL OR LEN(@StoreList) = 0 OR STOREID IN (SELECT [Value] FROM [dbo].[SYS_SPLITTOINTEGERS_FN] (@StoreList,','))    
    
  SELECT *    
    INTO #expensetypes    
    FROM RCL_EXPENSETYPE    
   WHERE @ExpenseTypeList IS NULL OR LEN(@ExpenseTypeList) = 0 OR EXPENSETYPEID IN (SELECT [Value] FROM [dbo].[SYS_SPLITTOINTEGERS_FN] (@ExpenseTypeList,','))    
    
  SELECT *    
    INTO #managers    
    FROM STR_REGIONMANAGERS    
   WHERE @ManagerList IS NULL OR LEN(@ManagerList) = 0 OR REGIONMANAGERSID IN (SELECT [Value] FROM [dbo].[SYS_SPLITTOINTEGERS_FN] (@ManagerList,','))    
  
  SELECT *, ROW_NUMBER() OVER (ORDER BY EXPENSE_AMT DESC) ROWNO    
    FROM (    
  SELECT RM.MANAGER_NM, RM.USERID, S.STORE_NM, S.STOREID, ET.EXPENSETYPE_NM, ET.EXPENSETYPEID, SUM(E.EXPENSE_AMT) EXPENSE_AMT    
    FROM RCL_EXPENSE E    
    JOIN #stores S ON E.STORE = S.STOREID   
    JOIN STR_REGIONMANAGERS RM ON RM.REGIONMANAGERSID = S.REGIONMANAGER    
    JOIN RCL_EXPENSETYPE ET ON E.EXPENSETYPE = ET.EXPENSETYPEID     
    JOIN #managers M ON RM.REGIONMANAGERSID = M.REGIONMANAGERSID    
    JOIN #expensetypes ETT ON ET.EXPENSETYPEID = ETT.EXPENSETYPEID
   WHERE CAST(E.EXPENSE_DT AS DATE) BETWEEN @StartDate AND @EndDate
     AND E.DELETED_FL = 'N'   
   GROUP BY RM.MANAGER_NM, RM.USERID, S.STORE_NM, S.STOREID, ET.EXPENSETYPE_NM, ET.EXPENSETYPEID) A
     
END  