CREATE PROCEDURE RCL_DEL_STORE_SP
    @StoreReconciliationId BIGINT
AS
BEGIN

	INSERT INTO RCL_STORELOG
    (
        STORERECID, LOG_DT, LOGUSER, LOGOPERATION_CD, LOGCHANNEL, LOGBRANCH, LOGSCREEN, STORE, RECONCILIATION_DT
	  , ZET_AMT, DEFINEDADVANCE_AMT, EXPENSE_AMT, CASH_AMT, CARD_AMT, RECOVERED_AMT, ADJUSTMENT_AMT, NETOFF_AMT
	  , BANK_AMT, CURRENTADVANCE_AMT, EXPENSERETURN_AMT, DIFFREASONCODES_TXT, DIFFREASON_TXT, LASTSTEP_NO, COMPLETE_FL
	  , ADJUSTMENT_DSC, DEFICITCYCLE_CNT
	)
    SELECT
        S.STORERECID,
        GETDATE(),
        dbo.SYS_GETCURRENTUSER_FN(),
        'UPD',
        dbo.SYS_GETCURRENTCHANNEL_FN(),
        dbo.SYS_GETCURRENTBRANCH_FN(),
        dbo.SYS_GETCURRENTSCREEN_FN(),
        STORE, RECONCILIATION_DT, ZET_AMT, DEFINEDADVANCE_AMT, EXPENSE_AMT, CASH_AMT, CARD_AMT, 
		RECOVERED_AMT, ADJUSTMENT_AMT, NETOFF_AMT, BANK_AMT, CURRENTADVANCE_AMT, EXPENSERETURN_AMT, 
		DIFFREASONCODES_TXT, DIFFREASON_TXT, LASTSTEP_NO, COMPLETE_FL, ADJUSTMENT_DSC, DEFICITCYCLE_CNT
      FROM
        RCL_STORE S (NOLOCK)
     WHERE
        S.STORERECID = @StoreReconciliationId;

    SET NOCOUNT OFF
    UPDATE RCL_STORE
       SET COMPLETE_FL = 'N',
		   LASTSTEP_NO = 1,
           UPDATE_DT = GETDATE(),
		   UPDATEUSER = dbo.SYS_GETCURRENTUSER_FN()
     WHERE STORERECID = @StoreReconciliationId;

    IF @@ROWCOUNT = 0
    BEGIN
        SET NOCOUNT ON;
        THROW 100001, 'Nothing deleted. Delete failed.', 1;
        RETURN;
    END;
    SET NOCOUNT ON;
END;
