CREATE PROCEDURE RCL_LST_LOG_SP @StoreRecID BIGINT AS
BEGIN
	SELECT LOG_DT, USERFULL_NM LOGUSER_NM, 
		CASE LASTSTEP_NO 
		WHEN 1 THEN 'Tarih Seçim' WHEN 2 THEN 'Kasa Farkları Gösterim' WHEN 3 THEN 'Nakit Giriş'
		WHEN 4 THEN 'Masraf ve Düzeltme Gösterim' WHEN 5 THEN 'Kredi Kart Giriş'
		WHEN 6 THEN 'Fark Neden Giriş' WHEN 7 THEN 'Banka Teslimat Gösterim' WHEN 8 THEN 'İşlem Tamamlandı' END STEP_TXT
	  FROM (
	SELECT L.LOG_DT, U.USERFULL_NM, L.LASTSTEP_NO, L.COMPLETE_FL
	  FROM RCL_STORELOG L (NOLOCK)
	  JOIN SEC_USER U ON L.LOGUSER = U.USERID
	  JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
	 WHERE STORERECID = @StoreRecID
	 UNION ALL
	SELECT DATEADD(SECOND, 1, R.UPDATE_DT), U.USERFULL_NM, R.LASTSTEP_NO, R.COMPLETE_FL
	  FROM RCL_STORE R (NOLOCK)
	  JOIN SEC_USER U ON R.UPDATEUSER = U.USERID
	  JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
	 WHERE STORERECID = @StoreRecID) a
	 ORDER BY 1, 3 DESC
END