CREATE PROCEDURE RCL_LST_STORECONTROL_SP @StoreId INT, @StartDate DATE, @EndDate DATE AS
BEGIN
  -- DECLARE @StoreId INT = 11
  -- DECLARE @StartDate DATE = '2019-08-01'
  -- DECLARE @EndDate DATE = '2019-08-31'

  IF OBJECT_ID('tempdb.dbo.#sales', 'U') IS NOT NULL  DROP TABLE #sales;
  IF OBJECT_ID('tempdb.dbo.#rec', 'U') IS NOT NULL  DROP TABLE #rec;
  IF OBJECT_ID('tempdb.dbo.#loomis', 'U') IS NOT NULL  DROP TABLE #loomis;
  IF OBJECT_ID('tempdb.dbo.#kk', 'U') IS NOT NULL  DROP TABLE #kk;
  IF OBJECT_ID('tempdb.dbo.#stores', 'U') IS NOT NULL  DROP TABLE #stores;
  IF OBJECT_ID('tempdb.dbo.#tmpstores', 'U') IS NOT NULL  DROP TABLE #tmpstores;
  IF OBJECT_ID('tempdb.dbo.#result', 'U') IS NOT NULL  DROP TABLE #result;

  SELECT * INTO #tmpstores FROM STR_STORE; 
  -- SELECT * INTO #tmpstores FROM dbo.STR_GETUSERSTORES_FN();

  SELECT ROW_NUMBER() OVER (PARTITION BY D.DATE_DT ORDER BY ST.STOREID) ROWNO, ST.STOREID, ST.STORE_NM, D.DATE_DT, CR.TERMINAL
    INTO #stores
    FROM #tmpstores ST
    JOIN RPT_DATE D ON D.DATE_DT BETWEEN @StartDate AND @EndDate 
	JOIN STR_CASHREGISTER_VW CR ON ST.STOREID = CR.STORE
   WHERE D.DATE_DT BETWEEN ST.OPENING_DT AND ISNULL(ST.CLOSING_DT, CONVERT(DATE, '20991231', 112))
     AND ST.DELETED_FL = 'N'
   ORDER BY 4 DESC, 1 DESC;

  WITH INVOICES AS (
	SELECT STORE, TRANSACTION_DT, SUM(ABS(S.TOTAL_AMT)) TOTAL_AMT
	  FROM ACC_INVOICE I
	  JOIN SLS_SALE S ON I.SALE = S.SALEID
	 WHERE S.TRANSACTION_DT >= GETDATE() - 60
	   AND S.CANCELLED_FL = 'N'
	   AND S.DELETED_FL = 'N'
	   AND I.DELETED_FL = 'N'
	   AND S.TRANSACTIONTYPE = 5
	 GROUP BY STORE, TRANSACTION_DT)	
  SELECT Z.*, ISNULL(I.TOTAL_AMT, 0) INVOICETOTAL
    INTO #sales
    FROM SLS_SALEZETCOMPARE_VW Z
	LEFT JOIN INVOICES I ON Z.STOREID = I.STORE AND z.DATE_DT = I.TRANSACTION_DT
   WHERE Z.DATE_DT BETWEEN @StartDate AND @EndDate 
     AND (@StoreId = -1 OR Z.STOREID = @StoreId)
  
  SELECT *
    INTO #rec
    FROM (
  SELECT STORE, TRANSACTION_DT, TOBANK_AMT, CARDTOTAL_AMT, 0 ADJUSTMENT_AMT
    FROM (
  select STORE, TRANSACTION_DT, TOBANK_AMT, CARDTOTAL_AMT, ROW_NUMBER() OVER (PARTITION BY STORE, TRANSACTION_DT ORDER BY CREATE_DT DESC) ROWNO
    from RCL_RECONCILIATION R
   WHERE R.TRANSACTION_DT BETWEEN @StartDate AND @EndDate 
     AND DELETED_FL = 'N') A
   WHERE ROWNO = 1
   UNION ALL
  SELECT STORE, RECONCILIATION_DT, BANK_AMT, CARD_AMT, ADJUSTMENT_AMT
    FROM RCL_STORE
   WHERE RECONCILIATION_DT BETWEEN @StartDate AND @EndDate 
     AND DELETED_FL = 'N'
     AND COMPLETE_FL = 'Y') AA
  
  select cha_kod, cha_tarihi, sum(cha_meblag) cha_meblag, 
		 case when cast(right(cha_kod,3) as int) = 105 then 55 
			  else cast(right(cha_kod,3) as int) 
		 end magaza, count(*) adet
    into #loomis
    from MIK_CURRENTTRANSACTION_VW (NOLOCK) T
   WHERE T.cha_belge_tarih BETWEEN @StartDate AND @EndDate 
     and cha_evrakno_seri IN ('ML', 'MML')
     and cha_kod != '100.01.999'
   group by cha_kod, cha_tarihi
  
  select cha_tarihi, sum(cha_meblag) cha_meblag, cast(right(cha_kod,3) as int) magaza, count(*) adet
    into #kk
    from MIK_CURRENTTRANSACTION_VW (NOLOCK) T
   WHERE T.cha_tarihi BETWEEN @StartDate AND @EndDate 
     and cha_evrakno_seri LIKE '%POS'
     and cha_kod like '100%'
   group by cha_tarihi, cast(right(cha_kod,3) as int)
  
  -- drop table #result
  SELECT S.STOREID, S.STORE_NM, S.TERMINAL, S.DATE_DT, Z.RECEIPT_AMT, Z.REFUND_AMT, Z.ZETRECEIPT_AMT, Z.ZETREFUND_AMT, Z.DIFF ZDIFF, Z.INVOICETOTAL
	   , R.TOBANK_AMT, L.cha_meblag LOOMIS_AMT, L.cha_meblag - R.TOBANK_AMT LOOMISDIFF
       , R.CARDTOTAL_AMT, ISNULL(R.ADJUSTMENT_AMT, 0) ADJUSTMENT_AMT, K.cha_meblag MIKROKK_AMT, K.cha_meblag - R.CARDTOTAL_AMT CARDDIFF
       , CASE WHEN ABS(DIFF) < 0.1 THEN 1 ELSE 0 END SALESTATUS
       , CASE WHEN TOBANK_AMT IS NOT NULL THEN 1 ELSE 0 END RECSTATUS
       , CASE WHEN L.cha_meblag IS NOT NULL THEN 1 ELSE 0 END LOOMISSTATUS
       , CASE WHEN K.cha_meblag IS NOT NULL THEN 1 ELSE 0 END KKSTATUS
    INTO #result
    FROM #stores S
	LEFT JOIN #sales Z ON S.STOREID = Z.STOREID AND S.DATE_DT = Z.DATE_DT
    LEFT JOIN #rec R ON S.STOREID = R.STORE AND S.DATE_DT = R.TRANSACTION_DT   
    LEFT JOIN #loomis L ON S.STOREID = L.magaza AND S.DATE_DT = L.cha_tarihi  
    LEFT JOIN #kk K ON S.STOREID = K.magaza AND S.DATE_DT = K.cha_tarihi  
   WHERE (@StoreId = -1 OR S.STOREID = @StoreId)  
   ORDER BY ABS(L.cha_meblag - R.TOBANK_AMT) DESC;

  SELECT *
	  , SUM(DIFF) OVER (PARTITION BY STORE_NM ORDER BY DATE_DT ROWS UNBOUNDED PRECEDING) CUMDIFF
	  , SUM(DIFF2) OVER (PARTITION BY STORE_NM ORDER BY DATE_DT ROWS UNBOUNDED PRECEDING) CUMDIFF2
    FROM (
  SELECT STORE_NM, DATE_DT, ADJUSTMENT_AMT, ISNULL(ZETRECEIPT_AMT + INVOICETOTAL - ZETREFUND_AMT,0)-ISNULL(CARDTOTAL_AMT,0) MINCASH, ISNULL(LOOMIS_AMT,0) LOOMIS
  	 , ISNULL(LOOMIS_AMT,0) - (ISNULL(ZETRECEIPT_AMT + INVOICETOTAL - ZETREFUND_AMT,0) - ISNULL(CARDTOTAL_AMT,0)) DIFF
  	 , ISNULL(ZETRECEIPT_AMT + INVOICETOTAL - ZETREFUND_AMT,0) ZTOTAL
  	 , ISNULL(CARDTOTAL_AMT, 0) CARDTOTAL
	 , ISNULL(MIKROKK_AMT, 0) MIKROCARDTOTAL 
	 , ISNULL(ZETRECEIPT_AMT + INVOICETOTAL - ZETREFUND_AMT,0)-ISNULL(MIKROKK_AMT,0) MINCASH2
	 , ISNULL(LOOMIS_AMT,0) - (ISNULL(ZETRECEIPT_AMT + INVOICETOTAL - ZETREFUND_AMT,0)-ISNULL(MIKROKK_AMT,0)) DIFF2
    FROM #result) A
   ORDER BY STORE_NM, DATE_DT
END