CREATE PROCEDURE RCL_LST_CASHDIST_SP @StoreRecId INT AS
BEGIN

    SELECT C.CASHDISTID,
           C.EVENT,
           C.ORGANIZATION,
           C.DELETED_FL,
           C.CREATE_DT,
           C.UPDATE_DT,
           C.CREATEUSER,
           C.UPDATEUSER,
           C.CREATECHANNEL,
           C.CREATEBRANCH,
           C.CREATESCREEN,
           C.STOREREC,
           C.BANKNOTE,
           C.QUANTITY_QTY,
           C.GROUP_CD,
		   B.BANKNOTE_AMT,
		   B.COIN_FL,
		   B.BANKNOTE_AMT * C.QUANTITY_QTY AMOUNT_AMT
      FROM RCL_CASHDIST C (NOLOCK)
	  JOIN RCL_BANKNOTE B (NOLOCK) ON C.BANKNOTE = B.BANKNOTEID
     WHERE DELETED_FL = 'N'
	   AND C.STOREREC = @StoreRecId
     ORDER BY CASHDISTID;

END;