CREATE PROCEDURE RCL_LST_EXPENSE_SP @StartDate DATE = NULL, @EndDate DATE = NULL AS
BEGIN
	IF OBJECT_ID('tempdb.dbo.#STORES', 'U') IS NOT NULL DROP TABLE #STORES;     
	SELECT * INTO #STORES FROM dbo.[STR_GETUSERSTORESALL_FN]();

	DECLARE @branchType VARCHAR(100)
	SELECT @branchType = BT.BRANCHTYPE_NM
	  FROM ORG_BRANCH B
	  JOIN ORG_BRANCHTYPE BT ON B.BRANCHTYPE = BT.BRANCHTYPEID
	 WHERE BRANCHID = dbo.SYS_GETCURRENTBRANCH_FN()

    SELECT
           E.EXPENSEID,
           E.EVENT,
           E.ORGANIZATION,
           E.DELETED_FL,
           E.CREATE_DT,
           E.UPDATE_DT,
           E.CREATEUSER,
           E.UPDATEUSER,
           E.CREATECHANNEL,
           E.CREATEBRANCH,
           E.CREATESCREEN,
           E.EXPENSETYPE,
           E.STORE,
           E.EXPENSE_DT,
           E.EXPENSE_AMT,
           E.RECEIPTNO_TXT,
           E.OPEN_FL,
           E.PAYOFF_DT,
           E.EXPENSE_DSC,
           E.VAT_RT,
           E.MIKRO_CD,
           E.MIKRO_TM,
           E.STATUS_CD,
           E.STATUS_TXT,
           E.MIKROUSER,
           E.REGIONMANAGER,
		   S.STORE_NM,
		   E.HASRECEIPT_FL,
		   U.USERFULL_NM CREATEUSER_NM,
		   U2.USERFULL_NM UPDATEUSER_NM,
		   ET.EXPENSETYPE_NM,
		   SRM.MANAGER_NM REGIONMANAGER_NM
      FROM RCL_EXPENSE E (NOLOCK)
	  LEFT JOIN #STORES S ON E.STORE = S.STOREID
	  LEFT JOIN STR_REGIONMANAGERS RM ON E.REGIONMANAGER = RM.REGIONMANAGERSID
	  JOIN SEC_USER U ON U.USERID = E.CREATEUSER
	  LEFT JOIN SEC_USER U2 ON U2.USERID = E.UPDATEUSER
	  LEFT JOIN RCL_EXPENSETYPE ET ON E.EXPENSETYPE = ET.EXPENSETYPEID
	  LEFT JOIN STR_REGIONMANAGERS SRM ON E.REGIONMANAGER = SRM.REGIONMANAGERSID
     WHERE E.DELETED_FL = 'N'
	   AND ((@branchType = 'Branch' AND S.STOREID IS NOT NULL)
			OR 
		    (@branchType = 'Region' AND (S.STOREID IS NOT NULL OR SRM.REGIONMANAGERSID IS NOT NULL))
			OR 
			(@branchType = 'Central Office'))
	   AND (@StartDate IS NULL OR E.PAYOFF_DT IS NULL OR CAST(E.PAYOFF_DT AS DATE) >= @StartDate)
	   AND (@EndDate IS NULL OR E.PAYOFF_DT IS NULL OR CAST(E.PAYOFF_DT AS DATE) <= @EndDate)

     ORDER BY EXPENSEID;
END