CREATE PROCEDURE [dbo].[RCL_LST_POSENDDAY_SP]
	@StoreId INT = -1,
	@StartDate DATE = NULL,
	@EndDate DATE = NULL
AS
BEGIN
SELECT S.RECONCILIATION_DT TARIH, S.STORE MAGAZAKODU, ST.STORE_NM MAGAZAADI
       , SUM(CASE WHEN CARDGROUP_CD = 1 THEN CARDZET_AMT ELSE 0 END) KASA_POS_1
       , SUM(CASE WHEN CARDGROUP_CD = 2 THEN CARDZET_AMT ELSE 0 END) KASA_POS_2
       , SUM(CASE WHEN CARDGROUP_CD = 3 THEN CARDZET_AMT ELSE 0 END) MOBIL_POS_1
       , SUM(CASE WHEN CARDGROUP_CD = 4 THEN CARDZET_AMT ELSE 0 END) MOBIL_POS_2
  FROM RCL_STORE S
  JOIN RCL_CARDDIST CD ON S.STORERECID = CD.STOREREC
  JOIN STR_STORE ST ON S.STORE = ST.STOREID
WHERE S.RECONCILIATION_DT BETWEEN @StartDate AND @EndDate
  AND (@StoreId = -1 OR S.STORE = @StoreId)
GROUP BY S.RECONCILIATION_DT, S.STORE, ST.STORE_NM
ORDER BY 1 DESC, 2
END;
