CREATE PROCEDURE [dbo].[SLS_LST_MIKROTRANSFERDATA_SP]  @StartDate DATE, @EndDate DATE, @CheckDate INT AS    
BEGIN    
 WITH ZET AS  
(SELECT STORE, TRANSACTION_DT, SUM(RECEIPTTOTAL_AMT + SLPTOTAL_AMT) ZETTOTAL, -1*SUM(REFUND_AMT) ZETRETURN  
  FROM SLS_ZET_VW  
GROUP BY STORE, TRANSACTION_DT)  
SELECT ST.STOREID, ST.STORE_NM, ST.TERMINAL, CAST(C.TRANSACTION_DT AS date) TRANSACTION_DT  
        , MAKTECHTOTAL, MAKTECHRETURN, MIKROTOTAL, MIKRORETURN  
       , Z.ZETTOTAL, Z.ZETRETURN  
       , (ABS(ROUND(MAKTECHTOTAL,2) - ROUND(MIKROTOTAL,2)) + ABS(ROUND(MAKTECHRETURN,2) - ROUND(MIKRORETURN,2))) DIFF  
  FROM SLS_MIKROCOMP_VW C  
  JOIN STR_STORE_VW ST ON C.STOREID = ST.STOREID  
  LEFT JOIN ZET Z ON C.STOREID = Z.STORE AND C.TRANSACTION_DT = Z.TRANSACTION_DT  
WHERE C.TRANSACTION_DT BETWEEN @StartDate AND @EndDate  
   AND ( (ABS(ROUND(MAKTECHTOTAL,2) - ROUND(MIKROTOTAL,2)) + ABS(ROUND(MAKTECHRETURN,2) - ROUND(MIKRORETURN,2)))>0.5 OR @CheckDate = 1)  
ORDER BY DIFF DESC  
END