/*Section="Main"*/
CREATE PROCEDURE ANN_LST_SUGGESTION_SP @SuggestionAdmin NVARCHAR(1) = 'N'
AS
BEGIN
    /*Section="Query"*/
    -- Select all
	WITH PREVCOMM AS (
		SELECT S.SUGGESTIONID, A.PROCESSINSTANCE, ISNULL(A.USERCOMMENT_DSC, ' ') USERCOMMENT_DSC, I.ACTIVITY_NM, S.STATUS
		     , ROW_NUMBER() OVER (PARTITION BY S.SUGGESTIONID ORDER BY A.CREATE_DT DESC) ROWNO
		  FROM BPA_ACTION A
          JOIN ANN_SUGGESTION S ON A.PROCESSINSTANCE = S.PROCESSINSTANCE_LNO
          JOIN BPM_ACTIVITYINSTANCE I ON A.ACTIVITYINSTANCE = I.ACTIVITYINSTANCEID
         WHERE I.ACTIVITY_NM = 'Değerlendirme Adımı'
           AND S.STATUS IN (4,5)
	)
    SELECT
           S.SUGGESTIONID,
           S.EVENT,
           S.ORGANIZATION,
           S.DELETED_FL,
           S.CREATE_DT,
           S.UPDATE_DT,
           S.CREATEUSER,
           S.UPDATEUSER,
           S.CREATECHANNEL,
           S.CREATEBRANCH,
           S.CREATESCREEN,
           S.SUGGESTION_TXT,
           S.PROCESSINSTANCE_LNO,
		   B.BRANCH_NM,
           S.[STATUS],
           S.[TYPE],
           S.INNOVATIVENESS_RT,
           S.FEASIBILITY_RT,
           S.ADDEDVALUE_RT,
		   P.USERCOMMENT_DSC PREVIOUSACTIONCOMMENT_DSC
      FROM ANN_SUGGESTION S (NOLOCK)
      JOIN SEC_USER U ON U.USERID = S.CREATEUSER
   	  JOIN ORG_BRANCH B ON B.BRANCHID = U.BRANCH
	  LEFT JOIN PREVCOMM P ON S.SUGGESTIONID = P.SUGGESTIONID AND P.ROWNO = 1
     WHERE S.DELETED_FL = 'N'
       AND (@SuggestionAdmin = 'Y' OR dbo.SYS_GETCURRENTUSER_FN() = S.CREATEUSER)  
     ORDER BY S.CREATE_DT DESC;

/*Section="End"*/
END;
