CREATE PROCEDURE ANN_LST_NTFUSERSTATUS_SP @NotificationId BIGINT AS
BEGIN
  SELECT PB.BRANCH_NM REGION_NM, B.BRANCH_NM, 
		 RM.MANAGER_NM REGIONMANAGER_NM,
  	     CASE B.BRANCHTYPE WHEN 4 THEN 'Şube' WHEN 6 THEN 'Bölge' ELSE 'Merkez' END BRANCHTYPE_NM,
  	     U.USERFULL_NM, 
  	     CASE WHEN PIN.STATUS_CD = 4 THEN 'Okundu' ELSE 'Okunmadı' END STATUS_TXT, 
  	     PIN.START_DT, PIN.FINISH_DT
    FROM ANN_NOTIFICATIONUSER NU
    JOIN BPM_PROCESSINSTANCE PIN ON NU.PROCESSINSTANCE_LNO = PIN.PROCESSINSTANCEID
    JOIN SEC_USER U ON NU.[USER] = U.USERID
    JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
    LEFT JOIN ORG_BRANCH PB ON B.PARENT = PB.BRANCHID
	LEFT JOIN STR_STORE ST ON B.BRANCHID = ST.BRANCH AND ST.ACTIVE_FL = 'Y'
	LEFT JOIN STR_REGIONMANAGERS RM ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
   WHERE NOTIFICATION = @NotificationId
END