CREATE VIEW INV_CURRENTSTOCK_VW AS  
WITH STOCK AS (  
	SELECT ST.STOREID, ST.STORE_NM, COALESCE(10000+SG.STOCKGROUP, P.PRODUCTID) PRODUCTID,  
		   COALESCE(SG.STOCKGROUP_NM, P.NAME_NM) PRODUCT_NM, SUM(INV.STOCK) STOCK  
	  FROM INV_STOCK_VW INV    
	  JOIN STR_STORE ST ON INV.STORE = ST.STOREID    
	  JOIN PRD_PRODUCT_VW P ON INV.PRODUCT = P.PRODUCTID    
	  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
	 WHERE P.CATEGORY_NM != 'Sarf Malzemeleri'  
	   AND P.ACTIVE_FL = 'Y'  
	 GROUP BY ST.STOREID, ST.STORE_NM, COALESCE(10000+SG.STOCKGROUP, P.PRODUCTID), COALESCE(SG.STOCKGROUP_NM, P.NAME_NM)),   

COUNTINGDATES AS (
    SELECT STORE, DATE_DT       
      FROM (SELECT STORE, ACTUAL_DT DATE_DT, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY ACTUAL_DT DESC) ROWNO      
              FROM WHS_STOCKTAKINGSCHEDULE      
       	     WHERE COUNTINGTYPE = 1      
   		 	   AND DELETED_FL = 'N'    
   			   AND STATUS = 2) A      
     WHERE ROWNO = 1),  

AVGS AS (  
	SELECT S.STORE, S.PRODUCT, AVG(QUANTITY) QUANTITY, MAX(QUANTITY) MAXQUANTITY  
	  FROM SLS_STOREDAILYPRODUCT_SYN S  
	  JOIN PRD_PRODUCT_VW P ON S.PRODUCT = P.PRODUCTID    
	  JOIN COUNTINGDATES CD ON S.STORE = CD.STORE  
	 WHERE TRANSACTION_DT >= GETDATE() - 28   
	   AND P.CATEGORY_NM != 'Sarf Malzemeleri'  
	   AND P.ACTIVE_FL = 'Y'  
	 GROUP BY S.STORE, S.PRODUCT )   

SELECT STORE, STORE_NM, PRODUCT, STOCKGROUP_NM, SUM(STOCK) STOCK, SUM(QUANTITY) AVGDAILYSALE, SUM(MAXQUANTITY) MAXDAILYSALE  
  FROM (  
SELECT A.STORE, ST.STORE_NM, COALESCE(10000+SG.STOCKGROUP, A.PRODUCT) PRODUCT, 
	   COALESCE(SG.STOCKGROUP_NM, P.NAME_NM) STOCKGROUP_NM, 0 STOCK, SUM(QUANTITY) QUANTITY,  
	   SUM(MAXQUANTITY) MAXQUANTITY
  FROM AVGS A  
  JOIN STR_STORE ST ON A.STORE = ST.STOREID  
  JOIN PRD_PRODUCT_VW P ON A.PRODUCT = P.PRODUCTID    
  LEFT JOIN PRD_STOCKGROUP_VW SG ON P.PRODUCTID = SG.PRODUCTID AND SG.USAGETYPE_CD = 1
 GROUP BY A.STORE, ST.STORE_NM, COALESCE(10000+SG.STOCKGROUP, A.PRODUCT), COALESCE(SG.STOCKGROUP_NM, P.NAME_NM)  
 UNION ALL  
SELECT *, 0, 0 FROM STOCK) AA  
 GROUP BY STORE, STORE_NM, PRODUCT, STOCKGROUP_NM