CREATE VIEW [dbo].[INV_WAREHOUSESTOCK_VW] AS
WITH LASTCOUNTING AS (
SELECT sym_depono, MAX(sym_tarihi) sym_tarihi
  FROM MIK_SAYIM_SYN C
  JOIN INV_WAREHOUSE_SYN W ON C.sym_depono = W.WAREHOUSEID  
 WHERE W.WAREHOUSETYPE = 2
 GROUP BY sym_depono), 
 COUNTINGRESULT AS (
SELECT C.sym_depono WAREHOUSE, CAST(c.sym_tarihi AS date) TRAN_DT, P.PRODUCTID PRODUCT, sym_miktar1 STOCK
  FROM MIK_SAYIM_SYN C 
  JOIN LASTCOUNTING L ON C.sym_depono = L.sym_depono AND C.sym_tarihi = L.sym_tarihi
  JOIN PRD_PRODUCT P ON C.sym_stokkodu COLLATE Turkish_100_CI_AS = P.CODE_NM),
 STOCKTRAN AS (
SELECT ST.WAREHOUSE, CAST(ST.TRANSACTION_DT AS date) TRAN_DT, ST.PRODUCT, SUM(ST.QUANTITY_QTY) QUANTITY
  FROM INV_STOCKTRANSACTIONS_SYN ST
  JOIN PRD_PRODUCT P ON ST.PRODUCT = P.PRODUCTID
  JOIN LASTCOUNTING L ON ST.WAREHOUSE = L.sym_depono
 WHERE ST.TRANSACTION_DT > L.sym_tarihi
 GROUP BY ST.WAREHOUSE, ST.TRANSACTION_DT, ST.PRODUCT)
-- SELECT * FROM COUNTINGRESULT WHERE PRODUCT = 3
SELECT WAREHOUSE, TRAN_DT START_DT, 
	   DATEADD(DAY,-1,ISNULL(LEAD(TRAN_DT) OVER (PARTITION BY WAREHOUSE, PRODUCT ORDER BY TRAN_DT),CONVERT(DATE,'20991231',112))) END_DT,
	   PRODUCT, SUM(STOCK) OVER (PARTITION BY WAREHOUSE, PRODUCT ORDER BY TRAN_DT ROWS UNBOUNDED PRECEDING) STOCK
  FROM (
SELECT *
  FROM COUNTINGRESULT 
 UNION ALL
SELECT *
  FROM STOCKTRAN) A