-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ANN_NOTIFICATIONTYPE]
(
    /*Section="Columns"*/
    [NOTIFICATIONTYPEID]  INT NOT NULL,
    [NOTIFICATIONTYPE_NM] VARCHAR(100) NOT NULL,
    [DESCRIPTION_DSC]     VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ANN_NOTIFICATIONTYPE_PK] PRIMARY KEY ([NOTIFICATIONTYPEID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [ANN_NOTIFICATIONTYPE_X01] ON [ANN_NOTIFICATIONTYPE] ([NOTIFICATIONTYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Notification Type: Types of notifications',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ANN_NOTIFICATIONTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Notification Type Id: Identity column for ANN_NOTIFICATIONTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'NOTIFICATIONTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Notification Type Name: Name of notification type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'NOTIFICATIONTYPE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Description: Comment for notification type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONTYPE',
    @level2type=N'COLUMN',
    @level2name=N'DESCRIPTION_DSC'
GO

/*Section="End"*/
