-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ANN_NOTIFICATIONGROUPUSER]
(
    /*Section="Columns"*/
    [NOTIFICATIONGROUP] INT NOT NULL,
    [USER]              INT NOT NULL,
    [CREATE_DT]         DATETIME NOT NULL,
    [CREATEUSER]        INT NOT NULL,
    [CREATECHANNEL]     INT NOT NULL,
    [CREATEBRANCH]      INT NOT NULL,
    [CREATESCREEN]      INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_PK] PRIMARY KEY ([NOTIFICATIONGROUP],[USER]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F01] FOREIGN KEY ([NOTIFICATIONGROUP]) REFERENCES [ANN_NOTIFICATIONGROUP]([NOTIFICATIONGROUPID]),
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F02] FOREIGN KEY ([USER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F04] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F05] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [ANN_NOTIFICATIONGROUPUSER_F06] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Notification Group User: notificataionGroup & user relation table',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ANN_NOTIFICATIONGROUPUSER',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Notification Group: Group Id ' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'NOTIFICATIONGROUP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'User: user id from SEC_USER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'USER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Creation date of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creation branch of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Creation screen of the user.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONGROUPUSER', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

/*Section="End"*/
