-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [ANN_NOTIFICATIONSTATUS]
(
    /*Section="Columns"*/
    [NOTIFICATIONSTATUSID]  INT NOT NULL,
    [NOTIFICATIONSTATUS_NM] VARCHAR(100) NOT NULL,
    [DESCRIPTION_DSC]       VARCHAR(1000) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [ANN_NOTIFICATIONSTATUS_PK] PRIMARY KEY ([NOTIFICATIONSTATUSID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [ANN_NOTIFICATIONSTATUS_X01] ON [ANN_NOTIFICATIONSTATUS] ([NOTIFICATIONSTATUS_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Notification Status: Status of notifications',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'ANN_NOTIFICATIONSTATUS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Notification Status Id: Identity column for ANN_NOTIFICATIONSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'NOTIFICATIONSTATUSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Notification Status Name: Name of notification status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'NOTIFICATIONSTATUS_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Description: Comment for notification status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'ANN_NOTIFICATIONSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'DESCRIPTION_DSC'
GO

/*Section="End"*/
