CREATE PROCEDURE MIK_LST_WHTRANSACTIONS_SP @WarehouseId INT, @StartDate DATE, @EndDate DATE AS
BEGIN
	SELECT P.CODE_NM PRODUCT_CD, P.NAME_NM PRODUCT_NM, T.TRANSACTION_DT, E.EVRAK_ACK DOCUMENTTYPE
		 , MT.sth_evrakno_seri + CASE WHEN LEN(TRIM(MT.sth_evrakno_seri)) > 0 THEN '-' ELSE '' END + CAST(MT.sth_evrakno_sira AS VARCHAR(100)) DOCUMENT_NO
		 , CASE WHEN QUANTITY_QTY > 0 THEN W1.WAREHOUSE_NM ELSE W.WAREHOUSE_NM END INTAKEWH
		 , CASE WHEN QUANTITY_QTY < 0 THEN W1.WAREHOUSE_NM ELSE W.WAREHOUSE_NM END DEPARTWH
		 , QUANTITY_QTY, CASE WHEN P.UNIT = 1 THEN 'KG' ELSE 'ADET' END UNIT
	  FROM INV_STOCKTRANSACTIONS_SYN T
	  JOIN PRD_PRODUCT P ON T.PRODUCT = P.PRODUCTID
	  JOIN INV_WAREHOUSE_SYN W1 ON T.WAREHOUSE = W1.WAREHOUSEID
	  LEFT JOIN INV_WAREHOUSE_SYN W ON T.COUNTERWAREHOUSE = W.WAREHOUSEID
	  JOIN MIK_TRANSACTION_SYN MT ON T.MIKROGUID = MT.sth_Guid
	  LEFT JOIN MIK_EVRAKTIP_SYN E ON MT.sth_evraktip = E.TIPID
	 WHERE TRANSACTION_DT BETWEEN @StartDate AND @EndDate
	   AND WAREHOUSE = @WarehouseId
	 ORDER BY 3, 1
END