-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [SUP_DATAUPLOAD]
(
    /*Section="Columns"*/
    [DATAUPLOADID]  INT NOT NULL IDENTITY,
    [ORGANIZATION]  INT NOT NULL,
    [EVENT]         INT NOT NULL,
    [DELETED_FL]    VARCHAR NOT NULL,
    [CREATE_DT]     DATETIME NOT NULL,
    [UPDATE_DT]     DATETIME NULL,
    [CREATEUSER]    INT NOT NULL,
    [UPDATEUSER]    INT NULL,
    [CREATECHANNEL] INT NOT NULL,
    [CREATEBRANCH]  INT NOT NULL,
    [CREATESCREEN]  INT NOT NULL,
    [TYPE]          INT NOT NULL,
    [STATUS]        INT NOT NULL,
    [DOCUMENT]      BIGINT NOT NULL,
    [UPLOAD_DT]     DATETIME NOT NULL,
    [PROCESS_DT]    DATETIME NULL,
    [SOURCE_REF]    VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [SUP_DATAUPLOAD_PK] PRIMARY KEY ([DATAUPLOADID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [SUP_DATAUPLOAD_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [SUP_DATAUPLOAD_F02] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [SUP_DATAUPLOAD_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SUP_DATAUPLOAD_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [SUP_DATAUPLOAD_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [SUP_DATAUPLOAD_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [SUP_DATAUPLOAD_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [SUP_DATAUPLOAD_F08] FOREIGN KEY ([TYPE]) REFERENCES [SUP_UPLOADTYPE]([UPLOADTYPEID]),
    CONSTRAINT [SUP_DATAUPLOAD_F09] FOREIGN KEY ([STATUS]) REFERENCES [SUP_STATUS]([STATUSID]),
    CONSTRAINT [SUP_DATAUPLOAD_F10] FOREIGN KEY ([DOCUMENT]) REFERENCES [DOC_DOCUMENT]([DOCUMENTID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [SUP_DATAUPLOAD_X01] ON [SUP_DATAUPLOAD] ([DOCUMENT])
GO

CREATE NONCLUSTERED INDEX [SUP_DATAUPLOAD_X02] ON [dbo].[SUP_DATAUPLOAD]
(
	[STATUS] ASC
) WHERE STATUS IN (1)
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Data Upload: Upload işlemlerini saklar.',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'SUP_DATAUPLOAD',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Data Upload Id: Identity column for SUP_DATAUPLOAD' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'DATAUPLOADID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Upload Type: Upload  Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'TYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status: Status' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'STATUS'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Document: Document id on document management system.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'DOCUMENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Upload Date: Upload tarihi.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'UPLOAD_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Process Date: İşlem tarihi' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'PROCESS_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Source Ref: Kaynak referansı.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'SUP_DATAUPLOAD',
    @level2type=N'COLUMN',
    @level2name=N'SOURCE_REF'
GO

/*Section="End"*/
