CREATE VIEW [dbo].[STR_WINCORPRICE_VW] AS 
WITH LASTPRICE AS (
SELECT STORE, MAX(PV.UPDATE_DT) VERSION_TM
  FROM PRC_STOREPACKAGE SP
  JOIN PRC_PACKAGEVERSION PV ON SP.PACKAGE = PV.PACKAGE
 GROUP BY STORE) 
SELECT A.*
	 , CASE WHEN LEFT(A.TERMINAL1_TM,10) = CONVERT(VARCHAR(20), COALESCE(LP.VERSION_TM, GETDATE()), 104) AND A.TERMINAL1_FL = 'Y' THEN 1 ELSE 0 END + 
	   CASE WHEN LEFT(A.TERMINAL2_TM,10) = CONVERT(VARCHAR(20), COALESCE(LP.VERSION_TM, GETDATE()), 104) AND A.TERMINAL2_FL = 'Y' THEN 1 ELSE 0 END STATUS	
  FROM (
SELECT ST.STOREID, ST.STORE_NM, ST.TERMINAL
	 , MAX(CASE WHEN CR.CRNO = 1 THEN STATUS_FL END) TERMINAL1_FL
	 , LEFT(MAX(CASE WHEN CR.CRNO = 1 THEN STATUS_TXT END),16) TERMINAL1_TM
	 , MAX(CASE WHEN CR.CRNO = 2 THEN STATUS_FL END) TERMINAL2_FL
	 , LEFT(MAX(CASE WHEN CR.CRNO = 2 THEN STATUS_TXT END),16) TERMINAL2_TM
  FROM [STR_STORE_VW] ST
  LEFT JOIN (SELECT STORE, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY CASHREGISTERID) CRNO, STATUS_FL, STATUS_TXT, UPDATE_DT 
			   FROM STR_CASHREGISTER 
			  WHERE DELETED_FL = 'N') CR ON ST.STOREID = CR.STORE
 WHERE ST.TERMINAL = 'Wincor'
 GROUP BY ST.STOREID, ST.STORE_NM, ST.TERMINAL) A
 LEFT JOIN LASTPRICE LP ON A.STOREID = LP.STORE
