CREATE VIEW [dbo].[STR_STORE_VW] AS 
SELECT S.STOREID, S.STORE_NM, ACTIVE_FL, PRODUCTION_FL, S.OPENING_DT, B2.BRANCH_NM REGION_NM
	 , MAX(B.BRAND_NM) TERMINAL, MAX(SB.BRAND_NM) SCALE
	 , MAX(COALESCE(SALEFILEPATH1_TXT, 
					CASE WHEN B.BRAND_NM = 'NCR' THEN 'D:\ROOT\Database\ConLgAll.dat'
						 WHEN B.BRAND_NM = 'Toshiba' THEN 'C:\Genius\Office\Data Files\GeniusPOS.mdb'
					END)) SALEFILEPATH1_TXT
	 , MAX(COALESCE(SALEFILEPATH2_TXT,
					CASE WHEN B.BRAND_NM = 'NCR' THEN 'D:\ROOT\Database\Log\'
						 WHEN B.BRAND_NM = 'Toshiba' THEN 'C:\Genius\Office\Genius.mdw'
					END)) SALEFILEPATH2_TXT  
	 , MAX(SALEFILEPATH3_TXT) SALEFILEPATH3_TXT
	 , COUNT(DISTINCT CR.CASHREGISTERID) TERMCOUNT
  FROM STR_STORE S  
  LEFT JOIN STR_CASHREGISTER CR ON S.STOREID = CR.STORE AND CR.DELETED_FL = 'N' 
  LEFT JOIN STR_CASHREGISTERMODEL M ON CR.CASHREGISTERMODEL = M.CASHREGISTERMODELID  
  LEFT JOIN STR_CASHREGISTERBRAND B ON M.BRAND = B.CASHREGISTERBRANDID  
  LEFT JOIN STR_SCALE SC ON S.STOREID = SC.STORE AND SC.DELETED_FL = 'N'
  LEFT JOIN STR_SCALEMODEL SM ON SC.SCALEMODEL = SM.SCALEMODELID
  LEFT JOIN STR_SCALEBRAND SB ON SM.BRAND = SB.SCALEBRANDID
  LEFT JOIN ORG_BRANCH B1 ON S.BRANCH = B1.BRANCHID
  LEFT JOIN ORG_BRANCH B2 ON B1.PARENT = B2.BRANCHID
 WHERE S.ACTIVE_FL = 'Y'  
 GROUP BY S.STOREID, S.STORE_NM, ACTIVE_FL, PRODUCTION_FL, S.OPENING_DT, B2.BRANCH_NM 