CREATE VIEW [dbo].[STR_SCALEPRICE_VW] AS
WITH LASTPRICE AS (
SELECT STORE, MAX(PV.UPDATE_DT) VERSION_TM
  FROM PRC_STOREPACKAGE SP
  JOIN PRC_PACKAGEVERSION PV ON SP.PACKAGE = PV.PACKAGE
 GROUP BY STORE) 
SELECT A.STOREID, A.STORE_NM, A.SCALE, A.IP1_TXT, A.SCALE1_FL, A.SCALE1_TXT, A.SCALE1_TM, A.IP2_TXT, A.SCALE2_FL, A.SCALE2_TXT, A.SCALE2_TM
	 , A.IP3_TXT, A.SCALE3_FL, A.SCALE3_TXT, A.SCALE3_TM, A.IP4_TXT, A.SCALE4_FL, A.SCALE4_TXT, A.SCALE4_TM
	 , CASE WHEN CAST(A.SCALE1_TM AS DATE) >= CAST(COALESCE(LP.VERSION_TM, GETDATE()) AS DATE) AND A.SCALE1_FL = 'Y' THEN 1 ELSE 0 END + 
	   CASE WHEN CAST(A.SCALE2_TM AS DATE) >= CAST(COALESCE(LP.VERSION_TM, GETDATE()) AS DATE) AND A.SCALE2_FL = 'Y' THEN 1 ELSE 0 END + 
	   CASE WHEN CAST(A.SCALE3_TM AS DATE) >= CAST(COALESCE(LP.VERSION_TM, GETDATE()) AS DATE) AND A.SCALE3_FL = 'Y' THEN 1 ELSE 0 END + 
	   CASE WHEN CAST(A.SCALE4_TM AS DATE) >= CAST(COALESCE(LP.VERSION_TM, GETDATE()) AS DATE) AND A.SCALE4_FL = 'Y' THEN 1 ELSE 0 END STATUS
  FROM (
SELECT ST.STOREID, ST.STORE_NM, ST.SCALE
	 , MAX(CASE WHEN SC.SCALENO = 1 THEN STATUS_FL END) SCALE1_FL
	 , MAX(CASE WHEN SC.SCALENO = 1 THEN STATUS_TXT END) SCALE1_TXT
	 , MAX(CASE WHEN SC.SCALENO = 1 THEN IPADDRESS_TXT END) IP1_TXT
	 , MAX(CASE WHEN SC.SCALENO = 1 THEN UPDATE_DT END) SCALE1_TM
	 , MAX(CASE WHEN SC.SCALENO = 2 THEN STATUS_FL END) SCALE2_FL
	 , MAX(CASE WHEN SC.SCALENO = 2 THEN STATUS_TXT END) SCALE2_TXT
	 , MAX(CASE WHEN SC.SCALENO = 2 THEN IPADDRESS_TXT END) IP2_TXT
	 , MAX(CASE WHEN SC.SCALENO = 2 THEN UPDATE_DT END) SCALE2_TM
	 , MAX(CASE WHEN SC.SCALENO = 3 THEN STATUS_FL END) SCALE3_FL
	 , MAX(CASE WHEN SC.SCALENO = 3 THEN STATUS_TXT END) SCALE3_TXT
	 , MAX(CASE WHEN SC.SCALENO = 3 THEN IPADDRESS_TXT END) IP3_TXT
	 , MAX(CASE WHEN SC.SCALENO = 3 THEN UPDATE_DT END) SCALE3_TM
	 , MAX(CASE WHEN SC.SCALENO = 4 THEN STATUS_FL END) SCALE4_FL
	 , MAX(CASE WHEN SC.SCALENO = 4 THEN STATUS_TXT END) SCALE4_TXT
	 , MAX(CASE WHEN SC.SCALENO = 4 THEN IPADDRESS_TXT END) IP4_TXT
	 , MAX(CASE WHEN SC.SCALENO = 4 THEN UPDATE_DT END) SCALE4_TM
  FROM [STR_STORE_VW] ST
  LEFT JOIN (SELECT STORE, ROW_NUMBER() OVER (PARTITION BY STORE ORDER BY SCALEID) SCALENO, STATUS_FL, STATUS_TXT, UPDATE_DT, IPADDRESS_TXT 
			   FROM STR_SCALE 
			  WHERE DELETED_FL = 'N') SC ON ST.STOREID = SC.STORE
 GROUP BY ST.STOREID, ST.STORE_NM, ST.SCALE) A
 LEFT JOIN LASTPRICE LP ON A.STOREID = LP.STORE