CREATE VIEW [dbo].[STR_STOREREGION_VW] AS

SELECT STOREID, MAX(B.BRANCH_NM) REGION_NM, MAX(RM.MANAGER_NM) REGIONMANAGER_NM
  FROM STR_STORE ST
  JOIN STR_REGIONMANAGERS RM ON ST.REGIONMANAGER = RM.REGIONMANAGERSID
  JOIN SEC_USER U ON RM.USERID = U.USERID
  JOIN ORG_BRANCH B ON U.BRANCH = B.BRANCHID
 GROUP BY STOREID