CREATE VIEW STR_STOREWHINC_VW AS
SELECT STOREID, ORGANIZATION, DELETED_FL, CREATE_DT, UPDATE_DT, CREATEUSER, UPDATEUSER, STORE_NM, BRANCH, IPADDRESS_TXT, ADVANCE_AMT, OPENING_DT
	 , CLOSING_DT, ACTIVE_FL, PRODUCTION_FL, CITY, TOWN, ADDRESS_TXT, REGIONMANAGER, INCONSTRUCTION_FL 
  FROM STR_STORE
 UNION ALL
SELECT 999, 1, 'N', GETDATE(), NULL, 1, 1, 'MERKEZ DEPO', 999, NULL, NULL, NULL, NULL, 'Y', 'Y', NULL, NULL, NULL, NULL, NULL
