CREATE PROCEDURE [dbo].[SUP_LST_STOREMISSINGDAYS_SP] @StoreId INT AS  
BEGIN  
  
 DECLARE @today DATE = CAST(GETDATE() AS DATE);  
 DECLARE @yesterday DATE = CAST(GETDATE() - 1 AS DATE);  
 
 DECLARE @histday INT 
 SELECT @histday = CAST(VALUE_TXT AS INT) - 1 FROM STR_PROPERTY WHERE PROPERTYTYPE = 9 AND STORE = @StoreId

 DECLARE @startingday DATE = CAST(GETDATE()-@histday AS DATE); 

 SELECT DISTINCT ST.STOREID, ST.STORE_NM, DATE_DT, ST.TERMINAL  
	  , ST.SALEFILEPATH1_TXT, ST.SALEFILEPATH2_TXT  
	  , ST.SALEFILEPATH3_TXT  
   FROM SLS_SALEZETCRCOMPARE_VW Z  
   JOIN STR_STORE_VW ST ON Z.STOREID = ST.STOREID  
  WHERE Z.STOREID = @StoreId AND DATE_DT BETWEEN @startingday AND @yesterday  
    AND DIFF != 0  
  UNION ALL  
 SELECT ST.STOREID, ST.STORE_NM, @today DATE_DT, ST.TERMINAL  
      , ST.SALEFILEPATH1_TXT, ST.SALEFILEPATH2_TXT  
	  , ST.SALEFILEPATH3_TXT  
   FROM STR_STORE_VW ST  
  WHERE STOREID = @StoreId  
  UNION ALL
 SELECT ST.STOREID, ST.STORE_NM, DT.DATE_DT, ST.TERMINAL  
      , ST.SALEFILEPATH1_TXT, ST.SALEFILEPATH2_TXT  
 	 , ST.SALEFILEPATH3_TXT  
   FROM RPT_DATE DT
   JOIN STR_STORE_VW ST ON ST.STOREID = @StoreId
   LEFT JOIN (SELECT DISTINCT TRANSACTION_DT FROM SLS_SALE WHERE STORE = @StoreId AND CANCELLED_FL = 'N' ) SALE ON DT.DATE_DT = SALE.TRANSACTION_DT
  WHERE DT.DATE_DT BETWEEN @startingday AND @yesterday  
    AND SALE.TRANSACTION_DT IS NULL  

END;