-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_CONSTRAINTEXCEPTION]
(
    /*Section="Columns"*/
    [CONSTRAINTEXCEPTIONID] INT NOT NULL IDENTITY,
    [STORE]                 INT NOT NULL,
    [STARTDATE_DT]          DATETIME NOT NULL,
    [ENDDATE_DT]            DATETIME NOT NULL,
    [CATEGORY]              INT NULL,
    [SUBGROUP]              INT NULL,
    [PRODUCT]               INT NULL,
    [COEFFICIENT_RT]        NUMERIC(4,2) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_CONSTRAINTEXCEPTION_PK] PRIMARY KEY ([CONSTRAINTEXCEPTIONID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_CONSTRAINTEXCEPTION_F01] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [WHS_CONSTRAINTEXCEPTION_F02] FOREIGN KEY ([CATEGORY]) REFERENCES [PRD_CATEGORY]([CATEGORYID]),
    CONSTRAINT [WHS_CONSTRAINTEXCEPTION_F03] FOREIGN KEY ([SUBGROUP]) REFERENCES [PRD_SUBGROUP]([SUBGROUPID]),
    CONSTRAINT [WHS_CONSTRAINTEXCEPTION_F04] FOREIGN KEY ([PRODUCT]) REFERENCES [PRD_PRODUCT]([PRODUCTID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_CONSTRAINTEXCEPTION_X01] ON [WHS_CONSTRAINTEXCEPTION] ([STORE])
GO

CREATE INDEX [WHS_CONSTRAINTEXCEPTION_X02] ON [WHS_CONSTRAINTEXCEPTION] ([PRODUCT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Constraint Exception: Coefficient table for contraint theory system',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_CONSTRAINTEXCEPTION',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Constraint Exception Id: Identity column for WHS_CONSTRAINTEXCEPTION' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'CONSTRAINTEXCEPTIONID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Start Date: Start Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'STARTDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'End Date: End Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'ENDDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Category: Category' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'CATEGORY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'SubGroup: SubGroup' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'SUBGROUP'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product: Product' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Coefficient: Coefficient' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSTRAINTEXCEPTION', 
    @level2type=N'COLUMN',
    @level2name=N'COEFFICIENT_RT'
GO

/*Section="End"*/
