-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_PRODUCTIONCONTENT]
(
    /*Section="Columns"*/
    [PRODUCTIONCONTENTID] INT NOT NULL IDENTITY,
    [PRODUCTION]          INT NOT NULL,
    [PRODUCT]             INT NOT NULL,
    [SHARE_RT]            NUMERIC(4,2) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_PRODUCTIONCONTENT_PK] PRIMARY KEY ([PRODUCTIONCONTENTID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_PRODUCTIONCONTENT_F01] FOREIGN KEY ([PRODUCTION]) REFERENCES [WHS_PRODUCTION]([PRODUCTIONID]),
    CONSTRAINT [WHS_PRODUCTIONCONTENT_F02] FOREIGN KEY ([PRODUCT]) REFERENCES [PRD_PRODUCT]([PRODUCTID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_PRODUCTIONCONTENT_X01] ON [WHS_PRODUCTIONCONTENT] ([PRODUCT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Production Content: Production Content',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_PRODUCTIONCONTENT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Production Content Id: Identity column for WHS_PRODUCTIONCONTENT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTIONCONTENT', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTIONCONTENTID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Production: Production' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTIONCONTENT', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product: Product' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTIONCONTENT', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Share Rate: Share Rate' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTIONCONTENT', 
    @level2type=N'COLUMN',
    @level2name=N'SHARE_RT'
GO

/*Section="End"*/
