-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_GATHERINGSTATUS]
(
    /*Section="Columns"*/
    [GATHERINGSTATUSID]  INT NOT NULL,
    [GATHERINGSTATUS_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_GATHERINGSTATUS_PK] PRIMARY KEY ([GATHERINGSTATUSID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [WHS_GATHERINGSTATUS_X01] ON [WHS_GATHERINGSTATUS] ([GATHERINGSTATUS_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Gathering Status: Status of StoreORderGathering',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_GATHERINGSTATUS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Status Id: Identity column for WHS_GATHERINGSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGSTATUSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Name: Name of gathering status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGSTATUS_NM'
GO

/*Section="End"*/
