-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_STOCKTAKINGSCHEDULE]
(
    /*Section="Columns"*/
    [STOCKTAKINGSCHEDULEID] BIGINT NOT NULL IDENTITY,
    [EVENT]                 INT NOT NULL,
    [ORGANIZATION]          INT NOT NULL,
    [DELETED_FL]            VARCHAR NOT NULL,
    [CREATE_DT]             DATETIME NOT NULL,
    [UPDATE_DT]             DATETIME NULL,
    [CREATEUSER]            INT NOT NULL,
    [UPDATEUSER]            INT NULL,
    [CREATECHANNEL]         INT NOT NULL,
    [CREATEBRANCH]          INT NOT NULL,
    [CREATESCREEN]          INT NOT NULL,
    [SCHEDULE_NM]           VARCHAR(100) NOT NULL,
    [STORE]                 INT NOT NULL,
    [COUNTINGTYPE]          INT NOT NULL,
    [PLANNED_DT]            DATETIME NOT NULL,
    [ACTUAL_DT]             DATETIME NULL,
    [STATUS]                INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_PK] PRIMARY KEY ([STOCKTAKINGSCHEDULEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F08] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F09] FOREIGN KEY ([COUNTINGTYPE]) REFERENCES [WHS_COUNTINGTYPE]([COUNTINGTYPEID]),
    CONSTRAINT [WHS_STOCKTAKINGSCHEDULE_F10] FOREIGN KEY ([STATUS]) REFERENCES [WHS_COUNTINGSTATUS]([COUNTINGSTATUSID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_STOCKTAKINGSCHEDULE_X01] ON [WHS_STOCKTAKINGSCHEDULE] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'StockTaking Schedule: StockTaking Schedule',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_STOCKTAKINGSCHEDULE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'StockTaking Schedule Id: Identity column for WHS_STOCKTAKINGSCHEDULE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'STOCKTAKINGSCHEDULEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Schedule Name: Name of stocktaking schedule.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'SCHEDULE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Counting Type: Counting Type Name' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'COUNTINGTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Planned Date: Planned Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'PLANNED_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Actual Date: Actual Date' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'ACTUAL_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Counting Status: Counting Status' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOCKTAKINGSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'STATUS'
GO

/*Section="End"*/
