-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_STOREORDERSTATUS]
(
    /*Section="Columns"*/
    [STOREORDERSTATUSID] INT NOT NULL,
    [STATUS_NM]          VARCHAR(100) NOT NULL,
    [COMMENT_DSC]        VARCHAR(100) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_STOREORDERSTATUS_PK] PRIMARY KEY ([STOREORDERSTATUSID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Store Order Status: Store Order Status',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_STOREORDERSTATUS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Order Status Id: Identity column for WHS_STOREORDERSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOREORDERSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'STOREORDERSTATUSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Name: Name of store order status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOREORDERSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'STATUS_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for store order status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_STOREORDERSTATUS', 
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
