-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_SUPPLIERTYPE]
(
    /*Section="Columns"*/
    [SUPPLIERTYPEID]  INT NOT NULL,
    [SUPPLIERTYPE_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_SUPPLIERTYPE_PK] PRIMARY KEY ([SUPPLIERTYPEID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [WHS_SUPPLIERTYPE_X01] ON [WHS_SUPPLIERTYPE] ([SUPPLIERTYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Supplier Type: Tedarikçi Tipi',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_SUPPLIERTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Supplier Type Id: Identity column for WHS_SUPPLIERTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SUPPLIERTYPE', 
    @level2type=N'COLUMN',
    @level2name=N'SUPPLIERTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Supplier Type Name: Name of supplier type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SUPPLIERTYPE', 
    @level2type=N'COLUMN',
    @level2name=N'SUPPLIERTYPE_NM'
GO

/*Section="End"*/
