CREATE TABLE [dbo].[WHS_MATERIALORDERSTATUSHIST]
(
	ORDERSTATUSHISTORYID BIGINT NOT NULL IDENTITY,
	MATERIALORDER BIGINT NOT NULL,
	CREATEUSER INT NOT NULL,
	STATUS_CD INT NOT NULL,
	HISTORY_TM DATETIME NOT NULL,
	CONSTRAINT [WHS_MATERIALORDERSTATUSHIST_PK] PRIMARY KEY (ORDERSTATUSHISTORYID),
	CONSTRAINT [WHS_MATERIALORDERSTATUSHIST_F01] FOREIGN KEY (MATERIALORDER) REFERENCES [WHS_MATERIALORDER](MATERIALORDERID)
)

GO

CREATE INDEX [WHS_MATERIALORDERSTATUSHIST_X01] ON [WHS_MATERIALORDERSTATUSHIST] ([MATERIALORDER])
GO
