CREATE TABLE WHS_STOCKTAKINGLOG
(
    [STOCKTAKINGID]       BIGINT NOT NULL,
	[LOG_DT] DATETIME NOT NULL,
    [LOGUSER] INT NOT NULL,
    [LOGOPERATION_CD] VARCHAR(3) NOT NULL,
    [LOGCHANNEL] INT NOT NULL,
    [LOGBRANCH] INT NOT NULL,
    [LOGSCREEN] INT NOT NULL,
    [STORE]               INT NOT NULL,
    [COUNTING_DT]         DATETIME NOT NULL,
    [PRODUCT]             INT NOT NULL,
    [COUNTINGVALUE_AMT]   NUMERIC(10,3) NOT NULL,
    [ZONE]                INT NOT NULL,
    [STOCKTAKINGSCHEDULE] BIGINT NOT NULL
)