-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_RETURNREASONDETAIL]
(
    /*Section="Columns"*/
    [RETURNREASONDETAILID] INT NOT NULL IDENTITY,
    [RETURNREASON]         INT NOT NULL,
    [DETAIL_NM]            VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_RETURNREASONDETAIL_PK] PRIMARY KEY ([RETURNREASONDETAILID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_RETURNREASONDETAIL_F01] FOREIGN KEY ([RETURNREASON]) REFERENCES [WHS_RETURNREASON]([RETURNREASONID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Return Reason Detail: Return Reason Detail',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_RETURNREASONDETAIL',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Return Reason Detail Id: Identity column for WHS_RETURNREASONDETAIL' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_RETURNREASONDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'RETURNREASONDETAILID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Return Reason: Return Reason' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_RETURNREASONDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'RETURNREASON'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Reason Detail Name: Name of return reason detail.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_RETURNREASONDETAIL', 
    @level2type=N'COLUMN',
    @level2name=N'DETAIL_NM'
GO

/*Section="End"*/
