CREATE TABLE [dbo].[WHS_DRILLCOUNTSUMMARY](
	[SCHEDULEID] [bigint] NOT NULL,
	[COUNTING_DT] [date] NULL,
	[STORE] [int] NOT NULL,
	[PRODUCT] [int] NOT NULL,
	[PRODUCTCODE_NM] [varchar](100) NOT NULL,
	[PRODUCT_NM] [varchar](100) NOT NULL,
	[MINCOUNTING_TM] [datetime] NULL,
	[MAXCOUNTING_TM] [datetime] NULL,
	[SONDAJSTOK] [numeric](38, 3) NULL,
	[LASTCOUNTING_DT] [date] NULL,
	[STOCK] [float] NULL,
	[WHOLECOUNTING_DT] [date] NULL,
	[DIFF_AMT] [float] NULL,
	[STORE_NM] [varchar](100) NOT NULL,
	[PRICE_AMT] [numeric](22, 6) NULL,
	[SALE_QTY] [numeric](38, 7) NULL,
	[SALE_AMT] [numeric](38, 6) NULL
) ON [PRIMARY]
GO


CREATE UNIQUE NONCLUSTERED INDEX [WHS_DRILLCOUNTSUMMARY_X01] ON [dbo].[WHS_DRILLCOUNTSUMMARY]
(
	[SCHEDULEID] ASC,
	[PRODUCT] ASC
)
GO