-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_INTAKESTATUSTYPE]
(
    /*Section="Columns"*/
    [INTAKESTATUSTYPEID]  INT NOT NULL,
    [INTAKESTATUSTYPE_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_INTAKESTATUSTYPE_PK] PRIMARY KEY ([INTAKESTATUSTYPEID])
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Intake Status Type: Status types',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_INTAKESTATUSTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Intake Status Type Id: Identity column for WHS_INTAKESTATUSTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_INTAKESTATUSTYPE',
    @level2type=N'COLUMN',
    @level2name=N'INTAKESTATUSTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Intake Status Type Name: Name of intake status type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_INTAKESTATUSTYPE',
    @level2type=N'COLUMN',
    @level2name=N'INTAKESTATUSTYPE_NM'
GO

/*Section="End"*/
