CREATE TABLE WHS_TOC (
  TOCID INT NOT NULL IDENTITY
, STORE INT NOT NULL
, PRODUCT INT NOT NULL
, TOC_DT DATE NOT NULL
, GREENLIMIT_QTY NUMERIC(10,3)
, YELLOWLIMIT_QTY NUMERIC(10,3)
, REDLIMIT_QTY NUMERIC(10,3)
, REDREMNANT_QTY NUMERIC(10,3)
, BUFFER_QTY NUMERIC(10,3)
, STOCK_QTY NUMERIC(10,3)
, SALE_QTY NUMERIC(10,3)
, INTAKE_QTY NUMERIC(10,3)
, PERIOD_NO INT NOT NULL
, [DETAIL_TXT] VARCHAR(1000) NULL, 
    CONSTRAINT [WHS_TOC_PK] PRIMARY KEY (TOCID))
GO

CREATE UNIQUE INDEX WHS_TOC_X01 ON WHS_TOC(TOC_DT, STORE, PRODUCT)
GO

CREATE INDEX WHS_TOC_X02 ON WHS_TOC(STORE, TOC_DT) INCLUDE(PRODUCT)
GO

CREATE INDEX WHS_TOC_X03 ON WHS_TOC(STORE, PRODUCT, PERIOD_NO, BUFFER_QTY) INCLUDE (TOCID, REDREMNANT_QTY)
GO