CREATE TABLE WHS_TOCDETAIL (
  TOCDETAILID INT NOT NULL IDENTITY
, TOCID INT NOT NULL
, DETAILPRODUCT INT NOT NULL
, PACKAGE_QTY NUMERIC(10,3) 
, ORDER_QTY NUMERIC(10,3) NOT NULL
, SOURCE_CD INT)
GO
CREATE INDEX WHS_TOCDETAIL_X01 ON WHS_TOCDETAIL(TOCID) INCLUDE(ORDER_QTY)
GO