-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_SHIPMENTSCHEDULE]
(
    /*Section="Columns"*/
    [SHIPMENTSCHEDULEID]  INT NOT NULL IDENTITY,
    [ORGANIZATION]        INT NOT NULL,
    [DELETED_FL]          VARCHAR NOT NULL,
    [CREATE_DT]           DATETIME NOT NULL,
    [UPDATE_DT]           DATETIME NULL,
    [CREATEUSER]          INT NOT NULL,
    [UPDATEUSER]          INT NULL,
    [SHIPMENTSCHEDULE_NM] VARCHAR(100) NOT NULL,
    [STORE]               INT NOT NULL,
    [SCHEDULE_TXT]        VARCHAR(1000) NOT NULL,
    [COMMENT_DSC]         VARCHAR(200) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_SHIPMENTSCHEDULE_PK] PRIMARY KEY ([SHIPMENTSCHEDULEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_SHIPMENTSCHEDULE_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_SHIPMENTSCHEDULE_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_SHIPMENTSCHEDULE_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_SHIPMENTSCHEDULE_F04] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_SHIPMENTSCHEDULE_X01] ON [WHS_SHIPMENTSCHEDULE] ([STORE])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Shipment Schedule: Shipment Schedule',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_SHIPMENTSCHEDULE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Shipment Schedule Id: Identity column for WHS_SHIPMENTSCHEDULE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'SHIPMENTSCHEDULEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Shipment Schedule Name: Name of shipment schedule.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'SHIPMENTSCHEDULE_NM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: Store' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Schedule Detail: Schedule Detail' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'SCHEDULE_TXT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Comment: Comment for shipment schedule.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_SHIPMENTSCHEDULE', 
    @level2type=N'COLUMN',
    @level2name=N'COMMENT_DSC'
GO

/*Section="End"*/
