-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_MATERIALCATEGORY]
(
    /*Section="Columns"*/
    [MATERIALCATEGORYID] INT NOT NULL IDENTITY,
    [CATEGORY_NM]        VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_MATERIALCATEGORY_PK] PRIMARY KEY ([MATERIALCATEGORYID]) 
);
GO

/*Section="Indexes"*/

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Material Category: Material Category',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_MATERIALCATEGORY',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Material Category Id: Identity column for WHS_MATERIALCATEGORY' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_MATERIALCATEGORY', 
    @level2type=N'COLUMN',
    @level2name=N'MATERIALCATEGORYID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Category Name: Name of material category.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_MATERIALCATEGORY', 
    @level2type=N'COLUMN',
    @level2name=N'CATEGORY_NM'
GO

/*Section="End"*/
