CREATE TABLE [dbo].[WHS_COUNTINGSTOCKDIFF](
	[STOCKTAKINGSCHEDULEID] [bigint] NOT NULL,
	[LAGSTOCKTAKINGSCHEDULEID] [bigint] NULL,
	[LAGACTUAL_DT] [datetime] NULL,
	[STORE] [int] NULL,
	[PRODUCT] [int] NULL,
	[COUNTING_DT] [datetime] NULL,
	[STOCK] [numeric](38, 3) NULL,
	[COUNTING_QTY] [numeric](38, 3) NULL,
	[SALE_QTY] [numeric](38, 7) NULL,
	[SALE_AMT] [numeric](38, 6) NULL
) ON [PRIMARY]
GO

CREATE UNIQUE INDEX WHS_COUNTINGSTOCKDIFF_IX01 ON WHS_COUNTINGSTOCKDIFF (STORE, PRODUCT, COUNTING_DT) INCLUDE (STOCK, COUNTING_QTY, SALE_QTY)
GO