-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_GATHERINGPALLETPHOTO]
(
    /*Section="Columns"*/
    [GATHERINGPALLETPHOTOID] BIGINT NOT NULL IDENTITY,
    [EVENT]                  INT NOT NULL,
    [ORGANIZATION]           INT NOT NULL,
    [DELETED_FL]             VARCHAR NOT NULL,
    [CREATE_DT]              DATETIME NOT NULL,
    [UPDATE_DT]              DATETIME NULL,
    [CREATEUSER]             INT NOT NULL,
    [UPDATEUSER]             INT NULL,
    [CREATECHANNEL]          INT NOT NULL,
    [CREATEBRANCH]           INT NOT NULL,
    [CREATESCREEN]           INT NOT NULL,
    [GATHERINGPALLET]        INT NOT NULL,
    [PHOTO]                  BIGINT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_PK] PRIMARY KEY ([GATHERINGPALLETPHOTOID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F08] FOREIGN KEY ([GATHERINGPALLET]) REFERENCES [WHS_GATHERINGPALLET]([GATHERINGPALLETID]),
    CONSTRAINT [WHS_GATHERINGPALLETPHOTO_F09] FOREIGN KEY ([PHOTO]) REFERENCES [DOC_DOCUMENT]([DOCUMENTID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_GATHERINGPALLETPHOTO_X01] ON [WHS_GATHERINGPALLETPHOTO] ([GATHERINGPALLET])
GO

CREATE INDEX [WHS_GATHERINGPALLETPHOTO_X02] ON [WHS_GATHERINGPALLETPHOTO] ([PHOTO])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Gathering Pallet Photo: GatheringPallet & Document tables',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_GATHERINGPALLETPHOTO',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Pallet Photo Id: Identity column for WHS_GATHERINGPALLETPHOTO' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGPALLETPHOTOID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Pallet: GAtheringPallet fk' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGPALLET'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Photo: Document FK' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETPHOTO', 
    @level2type=N'COLUMN',
    @level2name=N'PHOTO'
GO

/*Section="End"*/
