-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_GATHERINGPALLETSTATUS]
(
    /*Section="Columns"*/
    [GATHERINGPALLETSTATUSID] INT NOT NULL,
    [STATUS_NM]               VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_GATHERINGPALLETSTATUS_PK] PRIMARY KEY ([GATHERINGPALLETSTATUSID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [WHS_GATHERINGPALLETSTATUS_X01] ON [WHS_GATHERINGPALLETSTATUS] ([STATUS_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Gathering Pallet Status: status for pallets',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_GATHERINGPALLETSTATUS',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Status Id: Unique identifier for {table}.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETSTATUS',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGPALLETSTATUSID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Name: Name of gathering pallet status.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGPALLETSTATUS',
    @level2type=N'COLUMN',
    @level2name=N'STATUS_NM'
GO

/*Section="End"*/
