-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_GATHERING]
(
    /*Section="Columns"*/
    [GATHERINGID]       BIGINT NOT NULL IDENTITY,
    [EVENT]             INT NOT NULL,
    [ORGANIZATION]      INT NOT NULL,
    [DELETED_FL]        VARCHAR NOT NULL,
    [CREATE_DT]         DATETIME NOT NULL,
    [UPDATE_DT]         DATETIME NULL,
    [CREATEUSER]        INT NOT NULL,
    [UPDATEUSER]        INT NULL,
    [CREATECHANNEL]     INT NOT NULL,
    [CREATEBRANCH]      INT NOT NULL,
    [CREATESCREEN]      INT NOT NULL,
    [STOREORDER]        BIGINT NOT NULL,
    [GATHERINGUSER]     INT NULL,
    [GATHERINGSTART_TM] DATETIME NULL,
    [GATHERINGEND_TM]   DATETIME NULL,
    [GATHERINGSTATUS]   INT NOT NULL,
    [GATHERINGTYPE]     INT NOT NULL,
    [PRIORITY_NO]       INT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_GATHERING_PK] PRIMARY KEY ([GATHERINGID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_GATHERING_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [WHS_GATHERING_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_GATHERING_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_GATHERING_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_GATHERING_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [WHS_GATHERING_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [WHS_GATHERING_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [WHS_GATHERING_F08] FOREIGN KEY ([STOREORDER]) REFERENCES [WHS_STOREORDER]([STOREORDERID]),
    CONSTRAINT [WHS_GATHERING_F09] FOREIGN KEY ([GATHERINGUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_GATHERING_F10] FOREIGN KEY ([GATHERINGSTATUS]) REFERENCES [WHS_GATHERINGSTATUS]([GATHERINGSTATUSID]),
    CONSTRAINT [WHS_GATHERING_F11] FOREIGN KEY ([GATHERINGTYPE]) REFERENCES [WHS_GATHERINGTYPE]([GATHERINGTYPEID])
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_GATHERING_X01] ON [WHS_GATHERING] ([STOREORDER])
GO

CREATE INDEX [WHS_GATHERING_X02] ON [WHS_GATHERING] ([GATHERINGUSER])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Gathering: Store Order Gathering',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_GATHERING',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Id: Identity column for WHS_GATHERING' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store Order: StoreOrderId from WHS_STOREORDER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'STOREORDER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering User: UserId of gathering user from SEC_USER' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Start Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGSTART_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering End Time: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGEND_TM'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Status: StatusId of WHS_GATHERINGSTATUS' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGSTATUS'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Type: gatheringType' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Priority: N/A' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERING',
    @level2type=N'COLUMN',
    @level2name=N'PRIORITY_NO'
GO

/*Section="End"*/
