-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_PRODUCTRETURNREASON]
(
    /*Section="Columns"*/
    [PRODUCTRETURNREASONID] BIGINT NOT NULL IDENTITY,
    [EVENT]                 INT NOT NULL,
    [ORGANIZATION]          INT NOT NULL,
    [DELETED_FL]            VARCHAR NOT NULL,
    [CREATE_DT]             DATETIME NOT NULL,
    [UPDATE_DT]             DATETIME NULL,
    [CREATEUSER]            INT NOT NULL,
    [UPDATEUSER]            INT NULL,
    [CREATECHANNEL]         INT NOT NULL,
    [CREATEBRANCH]          INT NOT NULL,
    [CREATESCREEN]          INT NOT NULL,
    [PRODUCTRETURN]         BIGINT NOT NULL,
    [RETURNREASON]          INT NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_PRODUCTRETURNREASON_PK] PRIMARY KEY ([PRODUCTRETURNREASONID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F08] FOREIGN KEY ([PRODUCTRETURN]) REFERENCES [WHS_PRODUCTRETURN]([PRODUCTRETURNID]),
    CONSTRAINT [WHS_PRODUCTRETURNREASON_F09] FOREIGN KEY ([RETURNREASON]) REFERENCES [WHS_RETURNREASON]([RETURNREASONID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_PRODUCTRETURNREASON_X01] ON [WHS_PRODUCTRETURNREASON] ([PRODUCTRETURN])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Product Return Reason: Product Return Reason',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_PRODUCTRETURNREASON',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Return Reason Id: Identity column for WHS_PRODUCTRETURNREASON' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTRETURNREASONID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Return: Product Return' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTRETURN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Return Reason: Return Reason' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTRETURNREASON', 
    @level2type=N'COLUMN',
    @level2name=N'RETURNREASON'
GO

/*Section="End"*/
