-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_PRODUCTSHIPMENTUNIT]
(
    /*Section="Columns"*/
    [PRODUCTSHIPMENTUNITID] INT NOT NULL IDENTITY,
    [ORGANIZATION]          INT NOT NULL,
    [DELETED_FL]            VARCHAR NOT NULL,
    [CREATE_DT]             DATETIME NOT NULL,
    [UPDATE_DT]             DATETIME NULL,
    [CREATEUSER]            INT NOT NULL,
    [UPDATEUSER]            INT NULL,
    [PRODUCT]               INT NOT NULL,
    [SHIPMENTTYPE]          INT NOT NULL,
    [PACKAGE_QTY]           NUMERIC(10,2) NOT NULL,
    [PACKAGETYPE]           INT NOT NULL,
    [LOCATION_TXT]          VARCHAR(100) NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_PK] PRIMARY KEY ([PRODUCTSHIPMENTUNITID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F01] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F02] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F03] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F04] FOREIGN KEY ([PRODUCT]) REFERENCES [PRD_PRODUCT]([PRODUCTID]),
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F05] FOREIGN KEY ([SHIPMENTTYPE]) REFERENCES [WHS_SHIPMENTTYPE]([SHIPMENTTYPEID]),
    CONSTRAINT [WHS_PRODUCTSHIPMENTUNIT_F06] FOREIGN KEY ([PACKAGETYPE]) REFERENCES [WHS_PACKAGETYPE]([PACKAGETYPEID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_PRODUCTSHIPMENTUNIT_X02] ON [WHS_PRODUCTSHIPMENTUNIT] ([PRODUCT])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Product Shipment Unit: Product Shipment Unit',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_PRODUCTSHIPMENTUNIT',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product Shipment Unit Id: Identity column for WHS_PRODUCTSHIPMENTUNIT' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCTSHIPMENTUNITID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product: Product' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Shipment Type: Shipment Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'SHIPMENTTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Quantity: Package Quantity' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'PACKAGE_QTY'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Type: Package Type' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'PACKAGETYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Warehouse Location: Warehouse Location' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PRODUCTSHIPMENTUNIT', 
    @level2type=N'COLUMN',
    @level2name=N'LOCATION_TXT'
GO

/*Section="End"*/
