-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_PACKAGETYPE]
(
    /*Section="Columns"*/
    [PACKAGETYPEID]  INT NOT NULL IDENTITY,
    [PACKAGETYPE_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_PACKAGETYPE_PK] PRIMARY KEY ([PACKAGETYPEID]) 
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [WHS_PACKAGETYPE_X01] ON [WHS_PACKAGETYPE] ([PACKAGETYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Shipment Package Type: Shipment Package Type',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_PACKAGETYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Shipment Package Type Id: Identity column for WHS_PACKAGETYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PACKAGETYPE', 
    @level2type=N'COLUMN',
    @level2name=N'PACKAGETYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Package Type Name: Name of shipment package type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_PACKAGETYPE', 
    @level2type=N'COLUMN',
    @level2name=N'PACKAGETYPE_NM'
GO

/*Section="End"*/
