-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_GATHERINGTYPE]
(
    /*Section="Columns"*/
    [GATHERINGTYPEID]  INT NOT NULL,
    [GATHERINGTYPE_NM] VARCHAR(100) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_GATHERINGTYPE_PK] PRIMARY KEY ([GATHERINGTYPEID])
);
GO

/*Section="Indexes"*/

CREATE UNIQUE INDEX [WHS_GATHERINGTYPE_X01] ON [WHS_GATHERINGTYPE] ([GATHERINGTYPE_NM])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Gathering Type: Gathering Type',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_GATHERINGTYPE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Type Id: Identity column for WHS_GATHERINGTYPE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGTYPE',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGTYPEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Gathering Type Name: Name of gathering type.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo',
    @level1type=N'TABLE',
    @level1name=N'WHS_GATHERINGTYPE',
    @level2type=N'COLUMN',
    @level2name=N'GATHERINGTYPE_NM'
GO

/*Section="End"*/
