-- Generated by OverGenerator
/*Section="Main"*/
CREATE TABLE [WHS_CONSIGNMENTGOODPURCHASE]
(
    /*Section="Columns"*/
    [CONSIGNMENTGOODPURCHASEID] BIGINT NOT NULL IDENTITY,
    [EVENT]                     INT NOT NULL,
    [ORGANIZATION]              INT NOT NULL,
    [DELETED_FL]                VARCHAR NOT NULL,
    [CREATE_DT]                 DATETIME NOT NULL,
    [UPDATE_DT]                 DATETIME NULL,
    [CREATEUSER]                INT NOT NULL,
    [UPDATEUSER]                INT NULL,
    [CREATECHANNEL]             INT NOT NULL,
    [CREATEBRANCH]              INT NOT NULL,
    [CREATESCREEN]              INT NOT NULL,
    [STORE]                     INT NOT NULL,
    [PRODUCT]                   INT NOT NULL,
    [SUPPLIER]                  INT NOT NULL,
    [QUANTITY_QTY]              NUMERIC(9,2) NOT NULL,
    /*Section="PrimaryKey"*/
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_PK] PRIMARY KEY ([CONSIGNMENTGOODPURCHASEID]),
    /*Section="ForeignKeys"*/
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F01] FOREIGN KEY ([EVENT]) REFERENCES [PRM_EVENT]([EVENTID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F02] FOREIGN KEY ([ORGANIZATION]) REFERENCES [ORG_ORGANIZATION]([ORGANIZATIONID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F03] FOREIGN KEY ([CREATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F04] FOREIGN KEY ([UPDATEUSER]) REFERENCES [SEC_USER]([USERID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F05] FOREIGN KEY ([CREATECHANNEL]) REFERENCES [SYS_CHANNEL]([CHANNELID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F06] FOREIGN KEY ([CREATEBRANCH]) REFERENCES [ORG_BRANCH]([BRANCHID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F07] FOREIGN KEY ([CREATESCREEN]) REFERENCES [PRG_SCREEN]([SCREENID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F08] FOREIGN KEY ([STORE]) REFERENCES [STR_STORE]([STOREID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F09] FOREIGN KEY ([PRODUCT]) REFERENCES [PRD_PRODUCT]([PRODUCTID]),
    CONSTRAINT [WHS_CONSIGNMENTGOODPURCHASE_F10] FOREIGN KEY ([SUPPLIER]) REFERENCES [WHS_SUPPLIER]([SUPPLIERID]) 
);
GO

/*Section="Indexes"*/

CREATE INDEX [WHS_CONSIGNMENTGOODPURCHASE_X01] ON [WHS_CONSIGNMENTGOODPURCHASE] ([STORE])
GO

CREATE INDEX [WHS_CONSIGNMENTGOODPURCHASE_X02] ON [WHS_CONSIGNMENTGOODPURCHASE] ([PRODUCT])
GO

CREATE INDEX [WHS_CONSIGNMENTGOODPURCHASE_X03] ON [WHS_CONSIGNMENTGOODPURCHASE] ([SUPPLIER])
GO

/*Section="TableComment"*/
-- Add table comment
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Consignment Good Purchase: Konsinye ürün alımları',
    @level0type = N'SCHEMA',
    @level0name = N'dbo',
    @level1type = N'TABLE',
    @level1name = N'WHS_CONSIGNMENTGOODPURCHASE',
    @level2type = NULL,
    @level2name = NULL
GO

/*Section="ColumnComments"*/
-- Add column comments

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Consignment Good Purchase Id: Identity column for WHS_CONSIGNMENTGOODPURCHASE' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CONSIGNMENTGOODPURCHASEID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Event: Event for the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'EVENT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Organization: Organization of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'ORGANIZATION'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Deleted: Deletion flag.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'DELETED_FL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Date: Record insert date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update Date: Record update date.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATE_DT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create User: Creator user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Update User: Updater user id of the record.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'UPDATEUSER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Channel: Creation channel of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATECHANNEL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Branch: Creator branch of the transaction.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATEBRANCH'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Create Screen: Screen id of the transaction performed.' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'CREATESCREEN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Store: StoreId' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'STORE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Product: productId' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'PRODUCT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Supplier: supplierId' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'SUPPLIER'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description',
    @value=N'Quantity: Quantity' ,
    @level0type=N'SCHEMA',
    @level0name=N'dbo', 
    @level1type=N'TABLE',
    @level1name=N'WHS_CONSIGNMENTGOODPURCHASE', 
    @level2type=N'COLUMN',
    @level2name=N'QUANTITY_QTY'
GO

/*Section="End"*/
