CREATE PROCEDURE TOC_BAT_FIXBUFFERVALUES_SP @StoreId INT, @StartDate DATE = '2018-01-01', @EndDate DATE = NULL AS      
BEGIN      
  
  -- DECLARE @StartDate DATE = CAST(GETDATE() - 31 AS DATE)       
  -- DECLARE @EndDate DATE = NULL  
  -- DECLARE @StoreID INT = 100  
  IF OBJECT_ID('tempdb.dbo.#saleavg', 'U') IS NOT NULL  DROP TABLE #saleavg;      
  IF OBJECT_ID('tempdb.dbo.#UPDATE', 'U') IS NOT NULL  DROP TABLE #UPDATE;      
      
  SELECT PRODUCT, MAX(LAG2QUANTITY + LAGQUANTITY + QUANTITY + LEADQUANTITY + LEAD2QUANTITY) BUFFER_QTY, AVG(LAG2QUANTITY + LAGQUANTITY + QUANTITY + LEADQUANTITY + LEAD2QUANTITY)*1.2 BUFFER2_QTY          
    INTO #saleavg      
    FROM (        
  SELECT *        
	   , ISNULL(LAG(QUANTITY,2) OVER (PARTITION BY PRODUCT ORDER BY TRANSACTION_DT),0) LAG2QUANTITY     
       , ISNULL(LAG(QUANTITY) OVER (PARTITION BY PRODUCT ORDER BY TRANSACTION_DT),0) LAGQUANTITY        
       , ISNULL(LEAD(QUANTITY) OVER (PARTITION BY PRODUCT ORDER BY TRANSACTION_DT),0) LEADQUANTITY        
	   , ISNULL(LEAD(QUANTITY,2) OVER (PARTITION BY PRODUCT ORDER BY TRANSACTION_DT),0) LEAD2QUANTITY        
   FROM (      
  SELECT COALESCE(SG.STOCKGROUP+10000, S.PRODUCT) PRODUCT, D.DATE_DT TRANSACTION_DT, SUM(ISNULL(S.QUANTITY,0)) QUANTITY      
    FROM PRD_PRODUCT_VW P  
	JOIN RPT_DATE D ON D.DATE_DT BETWEEN @StartDate AND ISNULL(@EndDate, CAST(GETDATE() AS DATE))  
	LEFT JOIN SLS_STOREDAILYPRODUCT_SYN S ON S.PRODUCT = P.PRODUCTID AND D.DATE_DT = S.TRANSACTION_DT  
    LEFT JOIN PRD_PROPERTY PP ON P.PRODUCTID = PP.PRODUCT AND PP.PROPERTYTYPE = 6      
    LEFT JOIN PRD_STOCKGROUP_VW SG ON S.PRODUCT = SG.PRODUCTID AND USAGETYPE_CD = 1  
   WHERE STORE = @StoreId      
     AND P.CATEGORY_NM != 'Sarf Malzemeleri'      
     AND PP.PRODUCT IS NULL      
     AND P.ACTIVE_FL = 'Y'      
	 AND P.SUPERGROUP3 != 3  
   GROUP BY COALESCE(SG.STOCKGROUP+10000, S.PRODUCT), D.DATE_DT) A  ) B      
   GROUP BY PRODUCT;      
      
  WITH TOC AS      
  (SELECT *, ROW_NUMBER() OVER (PARTITION BY PRODUCT ORDER BY TOC_DT DESC) ROWNO FROM WHS_TOC WHERE STORE = @StoreId)      
  SELECT A.PRODUCT, P.NAME_NM, B.GREENLIMIT_QTY, A.BUFFER2_QTY,       
   B.TOCID BTOCID, B.REDREMNANT_QTY BRED, B.TOC_DT, B.STORE       
    INTO #UPDATE      
    FROM #saleavg A      
    LEFT JOIN PRD_PRODUCT P ON A.PRODUCT = P.PRODUCTID      
    LEFT JOIN TOC B ON A.PRODUCT = B.PRODUCT AND B.ROWNO = 1      
   WHERE B.GREENLIMIT_QTY > A.BUFFER2_QTY * 5 OR B.GREENLIMIT_QTY IS NULL OR B.GREENLIMIT_QTY * 1.5 < A.BUFFER2_QTY      
  
      
  UPDATE B      
     SET B.GREENLIMIT_QTY = U.BUFFER2_QTY      
       , B.YELLOWLIMIT_QTY = U.BUFFER2_QTY * 0.8      
       , B.REDLIMIT_QTY = U.BUFFER2_QTY * 0.6      
       , B.REDREMNANT_QTY = 0      
  -- SELECT B.*      
    FROM #UPDATE U      
    JOIN WHS_TOC B ON U.STORE = B.STORE AND U.PRODUCT = B.PRODUCT      
   WHERE B.TOC_DT >= DATEADD(DAY, -7, U.TOC_DT)      
      
END